
<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/AttendanceManagement/by-hr/index.js'));
?>

<style type="text/css">
#map {
    width: 90%;
}
html, body {
    height: 100%;
    margin: 0;
    padding: 0;
}
</style>

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBE0Yegor3f8CZ1ZEEhFAwgI3M0RCh2-T4&amp"></script>

<script>
    window.onerror = function(message, url, lineNumber) { return true; };

    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.picUrl = '<?= $this->basePath('img/nobody_m.original.jpg'); ?>';
    document.pullAttendanceWS = '<?php echo $this->url('attendancebyhr', ['action' => 'pullAttendance']); ?>';
    document.bulkAttendanceWS = '<?php echo $this->url('attendancebyhr', ['action' => 'bulkAttendanceWS']); ?>';
    document.pullInOutTimeLink = '<?php echo $this->url('attendancebyhr', ['action' => 'pullInOutTime']); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
</script>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<form method="post" action="<?= $this->url('showlocation', ['action' => 'showMap']); ?>">
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase">Select Employee and Date</span>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Employee</label>
                <select class="form-control" name="employee" id="employeeId">
                </select>
            </div> 
            <div class="col-sm-2">
                <div class="form-group">
                    <label>From Date(AD)</label>
                    <input type="text" id="fromDate" name="fromDate" class="form-control" placeholder="From Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>From Date(BS)</label>
                    <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>To Date(AD)</label>
                    <input type="text" id="toDate" name="toDate"  class="form-control" placeholder="From Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>To Date(BS)</label>
                    <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>View Level</label>
                    <select onchange="changeView();" id="viewLevel">
                        <option value="1">World</option>
                        <option value="5">Landmass/continent</option>
                        <option value="10">City</option>
                        <option value="15">Streets</option>
                        <option value="20">Buildings</option>
                        <option selected="selected" value="9">Fit All Locations</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-2">
                <button id="search" class="btn btn-default btn-sm pull-right" class="form-control">
                    Show Location
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div>
</div>
</form>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <?php echo "<h3>".json_decode($employee)->FULL_NAME."&nbsp;<b style='font-size: 50%;'>(Note: Some locations may be overlapped or unavailable. Place cursor on the marker to see details.)</b></h3>"; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-0">
            
        </div>
    </div>
</div>

<div id ="map" style="height: 500px"></div>
<script language="javascript" type="text/javascript">

var map;
var marker;
var markerLocation;
var bounds = new google.maps.LatLngBounds();

function changeView(){
    var e = document.getElementById("viewLevel");
    var viewLevel = e.options[e.selectedIndex].value;
    viewLevel = parseInt(viewLevel);
    initializeMap(viewLevel);
}

function initializeMap(view) {
    var latlng = new google.maps.LatLng(<?php echo $locData1[0]; ?>);

    var myOptions =
    {
        zoom: view,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        disableDefaultUI: true
    };
    map = new google.maps.Map(document.getElementById("map"), myOptions);

    //marking checkin locations
    <?php for($i = 0; $i < count($locData1); $i++){ ?>
        markerLocation = new google.maps.LatLng(<?php echo $locData1[$i]; ?>);
        marker = new google.maps.Marker({
            map: map,
            position: markerLocation,
            title: "Checked In on: <?php echo $timeData1[$i]; ?>",
            icon: "<?=$this->basePath();?>/leaflet-color-markers-master/img/marker-icon-2x-green.png"
        });
        bounds.extend(marker.getPosition());
        marker.setMap(map);
    <?php } ?>

    //marking checkout locations
    <?php for($i = 0; $i < count($locData2); $i++){ ?>
        markerLocation = new google.maps.LatLng(<?php echo $locData2[$i]; ?>);
        marker = new google.maps.Marker({
            map: map,
            position: markerLocation,
            title: "Checked Out on: <?php echo $timeData2[$i]; ?>",
            icon: "<?=$this->basePath();?>/leaflet-color-markers-master/img/marker-icon-2x-red.png"
        });
        bounds.extend(marker.getPosition());
        marker.setMap(map);
    <?php } ?>

    if(view != 1 && view != 5 && view != 10 && view != 15 && view != 20){
        map.fitBounds(bounds);
    }
}

window.onload = initializeMap(9);

</script>



