<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advance-request-self')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/advance/advance-request-self/add.js'));
?>


<?php
$form->setAttribute('role', 'form');

$advanceId = $form->get('advanceId');
$requestedAmount = $form->get('requestedAmount');
$dateOfadvance = $form->get('dateOfadvance');
$reason = $form->get('reason');
$recommendedBy = $form->get('recommendedBy');
$recommendedRemarks = $form->get('recommendedRemarks');
$approvedBy = $form->get('approvedBy');
$approvedRemarks = $form->get('approvedRemarks');
$deductionType = $form->get('deductionType');
$deductionRate = $form->get('deductionRate');
$deductionIn = $form->get('deductionIn');



$submit = $form->get('submit');
$submit->setAttribute('value', 'Apply Advance');
$submit->setAttribute('id', 'request');
//
$form->setAttribute('action', $this->url('advance-request-self', ['action' => 'add']));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.advanceList = '<?=json_encode($advance);?>';
</script>


<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    Apply For Advance
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group">
                    <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
                </div>

                <div class="row">

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($advanceId); ?>
                            <?php print $this->formElement($advanceId); ?>
                            <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($requestedAmount); ?>
                            <?php print $this->formElement($requestedAmount); ?>
                            <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($dateOfadvance); ?>
                            <?php print $this->formElement($dateOfadvance); ?>
                            <?php print $this->formElementErrors()->render($dateOfadvance, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($reason); ?>
                            <?php print $this->formElement($reason); ?>
                            <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($recommendedBy); ?>
                            <?php print $this->formElement($recommendedBy); ?>
                            <?php print $this->formElementErrors()->render($recommendedBy, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($recommendedRemarks); ?>
                            <?php print $this->formElement($recommendedRemarks); ?>
                            <?php print $this->formElementErrors()->render($recommendedRemarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($approvedBy); ?>
                            <?php print $this->formElement($approvedBy); ?>
                            <?php print $this->formElementErrors()->render($approvedBy, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($approvedRemarks); ?>
                            <?php print $this->formElement($approvedRemarks); ?>
                            <?php print $this->formElementErrors()->render($approvedRemarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($deductionType); ?>
                            <?php print $this->formElement($deductionType); ?>
                            <?php print $this->formElementErrors()->render($deductionType, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($deductionRate); ?>
                            <?php print $this->formElement($deductionRate); ?>
                            <?php print $this->formElementErrors()->render($deductionRate, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($deductionIn); ?>
                            <?php print $this->formElement($deductionIn); ?>
                            <?php print $this->formElementErrors()->render($deductionIn, ['class' => 'help-block']); ?>
                        </div>
                    </div>


                </div>


                <?php print $this->formSubmit($submit); ?>

            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>
