<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/codemirror-5.19.0/lib/codemirror.css'))
        ->appendStylesheet($this->basePath('css/multi-select.dist.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/codemirror-5.19.0/lib/codemirror.js'));
$this->headScript()->appendFile($this->basePath('js/Payroll/Rules/form-wizard.js'));
$this->headScript()->appendFile($this->basePath('js/search.js'));
?>

<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.getRuleEmployeeWS = '<?php echo $this->url("rules", ["action" => "getRuleEmployee"]); ?>';
    document.putRuleEmployeeWS = '<?php echo $this->url("rules", ["action" => "putRuleEmployee"]); ?>';

    document.monthlyValues =<?= json_encode($monthlyValues) ?>;
    document.flatValues =<?= json_encode($flatValues) ?>;
    document.variables =<?= json_encode($variables) ?>;
    document.systemRules =<?= json_encode($systemRules) ?>;
    document.ruleId =<?= json_encode($id) ?>;

    document.ruleTableName = '<?= Payroll\Model\Rules::TABLE_NAME ?>';
    document.ruleTableUniqueColName1 = '<?= Payroll\Model\Rules::PAY_CODE ?>';
    document.ruleTableUniqueColName2 = '<?= Payroll\Model\Rules::PRIORITY_INDEX ?>';
    document.ruleTablePKColName = '<?= Payroll\Model\Rules::PAY_ID ?>';

    document.rulesIndexUrl = '<?= $this->url("rules", ["action" => "index"]) ?>';
    document.fiscalYears =<?= json_encode($fiscalYears) ?>;
    document.pullReferencedRules = '<?= $this->url("rules", ["action" => "pullReferencedRules"]) ?>';
    document.genders =<?= json_encode($genders) ?>;
    document.serviceTypes =<?= json_encode($serviceTypes) ?>;
    document.searchValues =<?php echo json_encode($searchValues); ?>;
</script>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\rules')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="portlet light bordered" id="form_wizard_1">
    <div class="portlet-title">
        <div class="caption">
            <i class=" icon-layers f-green"></i>
            <span class="caption-subject f-green bold uppercase">
                Form Wizard -
                <span class="step-title"> Step 1 of 4 </span>
            </span>
        </div>
        <div class="actions">
            <a class="btn btn-circle btn-icon-only btn-default" href="javascript:;">
                <i class="icon-cloud-upload"></i>
            </a>
            <a class="btn btn-circle btn-icon-only btn-default" href="javascript:;">
                <i class="icon-wrench"></i>
            </a>
            <a class="btn btn-circle btn-icon-only btn-default" href="javascript:;">
                <i class="icon-trash"></i>
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <div class="form-wizard">
            <ul class="nav nav-pills nav-justified steps">
                <li>
                    <a href="#tab1" data-toggle="tab" class="step">
                        <span class="number"> 1 </span>
                        <span class="desc">
                            <i class="fa fa-check"></i> Rule Setup </span>
                    </a>
                </li>
                <li>
                    <a href="#tab2" data-toggle="tab" class="step">
                        <span class="number"> 2 </span>
                        <span class="desc">
                            <i class="fa fa-check"></i> Rule Detail Setup </span>
                    </a>
                </li>
                <li>
                    <a href="#tab3" data-toggle="tab" class="step active">
                        <span class="number"> 3 </span>
                        <span class="desc">
                            <i class="fa fa-check"></i> Assign Rule </span>
                    </a>
                </li>

            </ul>
            <div id="bar" class="progress progress-striped" role="progressbar">
                <div class="progress-bar progress-bar-success"></div>
            </div>
            <div class="tab-content">
                <div class="alert alert-danger display-none">
                    <button class="close" data-dismiss="alert"></button>
                    You have some form errors. Please check below.
                </div>
                <div class="alert alert-success display-none">
                    <button class="close" data-dismiss="alert"></button>
                    Your form validation is successful!
                </div>
                <div class="tab-pane active" id="tab1">
                    <h4 class="block">Provide your account details</h4>
                    <form method="POST" name="Rules" action="/neo/neo-hris-metronic/public/payroll/rules/add"
                          id="Rules">
                        <div class="row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label for="payEdesc">Pay EDesc</label>
                                    <textarea name="payEdesc"
                                              required="required"
                                              id="payEdesc"
                                              class="form-control"></textarea></div>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group ">
                                    <label for="payLdesc">Pay LDesc</label>
                                    <textarea name="payLdesc"
                                              required="required"
                                              id="payLdesc"
                                              class="form-control"></textarea></div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label for="payTypeFlag">Pay Type</label>
                                    <div class="md-radio-inline">
                                        <div class="md-radio">
                                            <input
                                                checked="checked"
                                                type="radio"
                                                value="A"
                                                name="payTypeFlag"
                                                id="payTypeFlag+Addition"
                                                class="md-radiobtn">
                                            <label
                                                for="payTypeFlag+Addition">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Addition
                                            </label>
                                        </div>
                                        <div class="md-radio">
                                            <input
                                                type="radio"
                                                value="D"
                                                name="payTypeFlag"
                                                id="payTypeFlag+Deduction"
                                                class="md-radiobtn">
                                            <label
                                                for="payTypeFlag+Deduction">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Deduction
                                            </label></div>
                                    </div>
                                </div>

                            </div>
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group ">
                                    <label for="priorityIndex">Priority Index</label>
                                    <input type="number"
                                           name="priorityIndex"
                                           id="priorityIndex"
                                           class="form-control"
                                           value="">
                                    <span class="errorMsg"></span>
                                </div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group ">
                                    <label for="remarks">Remarks</label>
                                    <textarea
                                        ng-model="rule.remarks"
                                        name="remarks"
                                        id="remarks"
                                        class="form-control"></textarea>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="tab-pane" id="tab2">


                    <div class="row">

                        <div class="col-sm-12">
                            <textarea id="rule"></textarea>
                            <!--<button id="check" class="margin-top-10 pull-right btn btn-danger">Check</button>-->
                            <div class="checkbox margin-top-10 pull-right">
                                <label><input type="checkbox" id="isMonthly" value="">Monthly</label>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-12 ">
                            <div class="row">
                                <div class="col-sm-2">
                                    <div class="ms-container" >
                                        <div class="ms-selectable">
                                            <div class="ms-header">Monthly Values</div>
                                            <ul class="ms-list" id="monthlyValueList">
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="ms-container" >
                                        <div class="ms-selectable">
                                            <div class="ms-header">Flat Values</div>
                                            <ul class="ms-list" id="flatValueList">
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="ms-container" >
                                        <div class="ms-selectable">
                                            <div class="ms-header">Variables</div>
                                            <ul class="ms-list" id="variables">
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="ms-container" >
                                        <div class="ms-selectable">
                                            <div class="ms-header">System Rules</div>
                                            <ul class="ms-list" id="systemRules">
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="ms-container" >
                                        <div class="ms-selectable">
                                            <div class="ms-header">Referencing Rules</div>
                                            <ul class="ms-list" id="referencingRules">
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div>
                                        <select class="form-control" id="years">
                                        </select>
                                    </div> 
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <button id="pickMonth" class="btn btn-success">
                                                <span class="fa fa-youtube">
                                                </span>
                                            </button>

                                        </div>
                                        <div class="col-sm-8">
                                            <select class="form-control" id="months">
                                                <option value="">Select Month</option>
                                            </select>
                                        </div>
                                    </div>
                                    <!--                                            <div id="days">
                                    
                                                                                </div>-->
                                    <div>
                                        <select class="form-control" id="gender">
                                            <option value="">Select Gender</option>
                                        </select>
                                    </div>
                                    <div>
                                        <select class="form-control" id="serviceType">
                                            <option value="">Select Emp type</option>
                                        </select>
                                    </div>

                                </div>
                            </div>


                        </div>
                    </div>

                </div>
                <div class="tab-pane" id="tab3">
                    <div class="portlet light bg-inverse">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="icon-paper-plane font-green-haze"></i>
                                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-sm-2">
                                    <select class="form-control" name="company" id="companyId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="branchId" id="branchId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="department" id="departmentId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="designation" id="designationId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="position" id="positionId">
                                    </select>
                                </div>
                            </div>
                            <div class="row margin-top-10">
                                <div class="col-sm-2">
                                    <select class="form-control" name="serviceType" id="serviceTypeId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="employeeType" id="employeeTypeId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="employee" id="employeeId">
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <button id="reset" class="btn default btn-sm pull-right">
                                        Reset
                                        <i class="fa fa-refresh"></i>
                                    </button>
                                    <button id="searchBtn" class="btn btn-default btn-sm pull-right">
                                        Search
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="scroller"  style="min-height:300px;height: 400px;" id="loadingDiv">
                        <table id="employeeTable" class="table table-striped table-bordered table-hover no-footer custometbletwo">
                            <thead>
                                <tr>
                                    <th>
                                        Employee
                                    </th>
                                    <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                                        <div class="th-inner ">
                                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                <input class="" type="checkbox" id="checkAll"/>
                                                <span></span>
                                            </label>
                                        </div>
                                        <div class="fht-cell" style="width: 46px;"></div>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-12">
                    <a href="javascript:;" class="btn default green button-previous pull-left">
                        <i class="fa fa-angle-left"></i> Back </a>
                    <a href="javascript:;" class="btn btn-outline green button-next pull-right"> Continue
                        <i class="fa fa-angle-right"></i>
                    </a>
                    <a href="javascript:;" class="btn green button-submit pull-right">
                        Submit
                        <i class="fa fa-check"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>