<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/setup/training/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'training-form');

$trainingCode = $form->get('trainingCode');
$trainingName = $form->get('trainingName');
$remarks = $form->get('remarks');
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$duration = $form->get('duration');
$instructorName = $form->get('instructorName');
$trainingType = $form->get('trainingType');
$trainingType->setValueOptions($trainingTypeList);
$instituteName = $form->get('instituteId');
$instituteName->setValueOptions($instituteNameList);

$companyId = $form->get('companyId');
$companyId->setValueOptions($companies);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('training', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu =<?php
$menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuTraining"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\training')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($trainingCode); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($trainingCode); ?>
                            <?php print $this->formElementErrors()->render($trainingCode, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($trainingName); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($trainingName); ?>
                            <input type="hidden" id="trainingID" value="<?php echo $id; ?>"/>
                            <?php print $this->formElementErrors()->render($trainingName, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($trainingType); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($trainingType); ?>
                            <?php print $this->formElementErrors()->render($trainingType, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($startDate); ?>
                                    <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($startDate); ?>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                               class="form-control" value="">
                                    </div>
                                </div>     
                            </div> 
                        </div> 

                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($endDate); ?>
                                    <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($endDate) ?>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div> 

                    </div>
                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($duration); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($duration); ?>
                            <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>
                        </div> 
                    </div>
                </div>


                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($instituteName); ?>
                            <?php print $this->formElement($instituteName); ?>
                            <?php print $this->formElementErrors()->render($instituteName, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($instructorName); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($instructorName); ?>
                            <?php print $this->formElementErrors()->render($instructorName, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($companyId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($companyId); ?>
                            <?php print $this->formElementErrors()->render($companyId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
