<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/setup/training/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages) ?>;
        document.editLink ='<?= $this->url("training", ["action" => "edit"]); ?>';
        document.deleteLink ='<?= $this->url("training", ["action" => "delete"]) ?>';
    </script>
<?php } ?>

<script>
    document.menu =<?php
$menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuTraining"]];
echo json_encode($menu);
?>;
    document.deleteURL = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.trainings =<?php echo json_encode($list); ?>
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\Training')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('training', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="trainingTable">
    </div>
	</div>
<!--    
       
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (TRAINING_NAME == null) ? '-' : TRAINING_NAME #
        </td>
        <td>    
        #: (COMPANY_NAME == null) ? '-' : COMPANY_NAME #
        </td>
        <td>    
        #: (START_DATE == null) ? '-' : START_DATE #
        </td>
        <td>    
        #: (END_DATE == null) ? '-' : END_DATE #
        </td>
        <td>    
        #: (DURATION == null) ? '-' : DURATION #
        </td>
        <td>    
        #: (INSTITUTE_NAME == null) ? '-' : INSTITUTE_NAME #
        </td>
        <td>
        <a class="btn-edit"
        href="`+ document.editLink +`/#:TRAINING_ID#" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="btn-delete confirmation"
        href="/#:TRAINING_ID#" id="bs_#:TRAINING_ID #" style="height:17px;"> 
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>-->
</div>