<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/spin.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/ladda.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/jobHistorySearch.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()
        ->appendFile($this->basePath('js/setup/recommend-approve/comBranchDeptDesignSearch.js'))
        ->appendFile($this->basePath('js/appraisal/assign/appraisalAssignController.js'));
?>

<script>
    document.url = '<?= $this->url("appraisalAssign", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.employeeList =<?php echo json_encode($employeeList); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\AppraisalAssign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="" ng-app="hris" ng-controller="appraisalAssignController">
    <div id="hris-page-content">
        <div class="row margin-top-20">
            <div class="col-sm-4">
                <?php print $this->formElement($appraisals); ?>
            </div>
        </div>
        <div class="portlet light bg-inverse margin-top-10">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-paper-plane font-green-haze"></i>
                    <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                </div>
                <div class="tools">
                    <a href="" class="collapse" data-original-title="" title=""> </a>
                    <a href="" class="fullscreen" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-2">
                        <label>Company</label>
                        <select class="form-control" name="company" id="companyId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Branch</label>
                        <select class="form-control" name="branchId" id="branchId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Department</label>
                        <select class="form-control" name="department" id="departmentId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Designation</label>
                        <select class="form-control" name="designation" id="designationId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Position</label>
                        <select class="form-control" name="position" id="positionId">
                        </select>
                    </div>
                </div>
                <div class="row margin-top-10">
                    <div class="col-sm-2">
                        <label>Service Type</label>
                        <select class="form-control" name="serviceType" id="serviceTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee</label>
                        <select class="form-control" name="employee" id="employeeId">
                        </select>
                    </div>
                    <div class="col-sm-4 col-lg-offset-4">
                        <label height="45"></label>
                        <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                        <button ng-click="view()" id="viewEmployees" class="btn btn-default btn-sm pull-right">
                            Search
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="margin-top-20 scrollbar-vertical" id="loadingTable">
            <table class="table table-striped table-bordered table-hover no-footer customTable">
                <thead>
                    <tr>
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Appraisal Name
                        </th>
                        <th>
                            Appraiser Assigned
                        </th>
                        <th>
                            Alt. Appraiser Assigned
                        </th>
                        <th>
                            Reviewer Assigned
                        </th>
                        <th>
                            Alt. Reviewer Assigned
                        </th>
                        <th>
                            Super Reviewer Assigned
                        </th>
                        <th>
                            Current Stage
                        </th>
                        <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="employee in employeeList">
                        <td>
                            <span ng-bind="employee.FIRST_NAME"></span>
                            <span ng-bind="employee.MIDDLE_NAME"></span>
                            <span ng-bind="employee.LAST_NAME"></span>
                        </td>
                        <td>                       
                            <span ng-bind="employee.APPRAISAL_EDESC"></span>
                        </td>
                        <td>
                            <span ng-bind="employee.APPRAISER_NAME"></span>
                        </td>
                        <td>
                            <span ng-bind="employee.ALT_APPRAISER_NAME"></span>
                        </td>
                        <td>                       
                            <span ng-bind="employee.REVIEWER_NAME"></span>
                        </td>
                        <td>                       
                            <span ng-bind="employee.ALT_REVIEWER_NAME"></span>
                        </td>
                        <td>                       
                            <span ng-bind="employee.SUPER_REVIEWER_NAME"></span>
                        </td>
                        <td>                       
                            <span ng-bind="employee.CURRENT_STAGE_NAME"></span>
                        </td>
                        <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" ng-model="employee.checked" type="checkbox"
                                           ng-change="checkUnit(item.checked)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row margin-top-20 position-relative" ng-show="assignShowHide">  
            <div class="col-sm-3">
                <label for="appraiserId" style="width:100%">Appraiser</label>             
                <div class="row">
                    <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                        <select name="appraiserId" id="appraiserId" class="form-control" ng-options="appraiser.name for appraiser in appraiserOptions track by appraiser.id" ng-model="appraiserSelected">
                        </select>   
                    </div>
                    <div class="col-md-3 rlPadding appraiserWrap" style="padding:0px 0px !important;">
                        <a class="btn-edit" href="javascript::" ng-click="open(3)" style="height:22px; padding: 0px 7px !important;">
                            <i class="fa fa-search" style="height:17px;"></i>
                        </a>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="appraiserAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="appraiserAssign"/>
                            <span></span>
                        </label>
                    </div>  
                </div>
                <label for="altAppraiserId" style="width:100%; margin-top:2%;">Alternate Appraiser</label>
                <div class="row">
                    <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                        <select name="altAppraiserId" id="altAppraiserId" class="form-control" ng-options="altAppraiser.name for altAppraiser in altAppraiserOptions track by altAppraiser.id" ng-model="altAppraiserSelected">
                        </select>   
                    </div>
                    <div class="col-md-3 rlPadding appraiserWrap" style="padding:0px 0px !important;">
                        <a class="btn-edit" href="javascript::" ng-click="open('A3')" style="height:22px; padding: 0px 7px !important;">
                            <i class="fa fa-search" style="height:17px;"></i>
                        </a>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="altAppraiserAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="altAppraiserAssign"/>
                            <span></span>
                        </label>
                    </div>  
                </div>
            </div> 
            <div class="col-sm-3">
                <label for="reviewerId" style="width:100%">Reviewer</label>
                <div class="row">
                    <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                        <select name="reviwerId" required="required" id="reviewerId" class="form-control" ng-options="reviewer.name for reviewer in reviewerOptions track by reviewer.id" ng-model="reviewerSelected">
                        </select>   
                    </div>
                    <div class="col-md-3 rlPadding reviewerWrap" style="padding:0px 0px !important;">
                        <a class="btn-edit" href="javascript::" ng-click="open(2)" style="height:22px; padding: 0px 7px !important;">
                            <i class="fa fa-search" style="height:17px;"></i>
                        </a>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="reviewerAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="reviewerAssign"/>
                            <span></span>
                        </label>
                    </div>  
                </div>
                <label for="altReviewerId" style="width:100%; margin-top:2%;">Alternate Reviewer</label>
                <div class="row">
                    <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                        <select name="altReviewerId" required="required" id="altReviewerId" class="form-control" ng-options="altReviewer.name for altReviewer in altReviewerOptions track by altReviewer.id" ng-model="altReviewerSelected">
                        </select>   
                    </div>
                    <div class="col-md-3 rlPadding reviewerWrap" style="padding:0px 0px !important;">
                        <a class="btn-edit" href="javascript::" ng-click="open('A2')" style="height:22px; padding: 0px 7px !important;">
                            <i class="fa fa-search" style="height:17px;"></i>
                        </a>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="altReviewerAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="altReviewerAssign"/>
                            <span></span>
                        </label>
                    </div>  
                </div>
            </div>
            <div class="col-sm-3">
                <label for="superReviewerId" style="width:100%;">Super Reviewer</label>
                <div class="row">
                    <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                        <select name="superReviewerId" required="required" id="superReviewerId" class="form-control" ng-options="superReviewer.name for superReviewer in superReviewerOptions track by superReviewer.id" ng-model="superReviewerSelected">
                        </select>   
                    </div>
                    <div class="col-md-3 rlPadding reviewerWrap" style="padding:0px 0px !important;">
                        <a class="btn-edit" href="javascript::" ng-click="open('S2')" style="height:22px; padding: 0px 7px !important;">
                            <i class="fa fa-search" style="height:17px;"></i>
                        </a>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="superReviewerAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="superReviewerAssign"/>
                            <span></span>
                        </label>
                    </div>  
                </div>
                <label for="stageId" style="width:100%; margin-top:2%;">Current Stage</label>
                <div class="row">
                    <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                        <select name="stageId" required="required" id="stageId" class="form-control" >
                            <?php foreach($stages as $key=>$value){ ?>
                            <option value="<?= $key; ?>"><?= $value; ?></option>
                            <?php } ?>
                        </select>   
                    </div>
                    <div class="col-md-3 rlPadding reviewerWrap" style="padding:0px 0px !important;">
                        <a class="btn-edit" href="javascript::" ng-click="open('STG')" style="height:22px; padding: 0px 7px !important;">
                            <i class="fa fa-search" style="height:17px;"></i>
                        </a>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="stageAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="stageAssign"/>
                            <span></span>
                        </label>
                    </div>  
                </div>
            </div>
            <div class="col-sm-2 " id="assignBtnWrap" ng-show="showHideAssignBtn">
                <label height="45"></label>
                <button id="assignBtn" ng-click="assign()" class="btn btn-default form-control i-search mt-ladda-btn ladda-button mt-progress-demo">
                    Assign
                    <i class="fa fa-edit"></i>
                </button>
            </div>
        </div>

        <script type="text/ng-template" id="myModalContent.html">
            <div class="modal-header"> 
            <button type="button" class="close" ng-click="cancel()" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span> 
            </button> 
            <h4 class="modal-title">Filter For <span ng-bind="role"></span> </h4> 
            </div>
            <div class="modal-body"> 
            <div class="row">
            <div class="col-sm-4">
                <label for="branchId">Company</label>
                <select class="form-control" name="company" id="recomCompanyId">
                </select>
            </div>
            <div class="col-sm-4">
                <label for="branchId">Branch</label>
                <select class="form-control" name="branchId" id="recomBranchId">
                </select>
            </div>
            <div class="col-sm-4">
                <label for="branchId">Department</label>
                <select class="form-control" name="department" id="recomDepartmentId">
                </select>
            </div>
            </div>
            <div class="row" style="margin-top:10px;">
            <div class="col-sm-4">
                <label for="branchId">Designation</label>
                <select class="form-control" name="designation" id="recomDesignationId">
                </select>
            </div>
            <div class="col-sm-4">
                <label for="branchId">Employee</label>
                <select class="form-control" name="employee" id="recomEmployeeId">
                </select>
            </div>
            </div>
            <div class="row">                   
            <div class="col-sm-3">
            <label height="45"></label>
            <button ng-click="filterForRole()" id="filterForRole" class="btn btn-default form-control i-search">
            Search
            <i class="fa fa-search"></i>
            </button>
            </div>

            </div>
            </div> 
        </script>
    </div>

</div>