<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'department-form');

$departmentCode = $form->get('departmentCode');
$departmentName = $form->get('departmentName');

$remarks = $form->get('remarks');
$parentDepartment = $form->get('parentDepartment');

$parentDepartment->setValueOptions(array_merge(["0" => "none"], $departments));

$countryId = $form->get('countryId');
$countryId->setValueOptions($countries);
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('department', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuDepartment"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Department')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php print $this->formLabel($departmentCode); ?>
                    <?php print $this->formElement($departmentCode); ?>
                    <?php print $this->formElementErrors()->render($departmentCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($departmentName); ?>
                    <?php print $this->formElement($departmentName); ?>
                    <?php print $this->formElementErrors()->render($departmentName, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($countryId); ?>
                    <?php print $this->formElement($countryId); ?>
                    <?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($parentDepartment); ?>
                    <?php print $this->formElement($parentDepartment); ?>
                    <?php print $this->formElementErrors()->render($parentDepartment, ['class' => 'help-block']); ?>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>