<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'department-form');

$departmentCode = $form->get('departmentCode');
$departmentName = $form->get('departmentName');
$remarks = $form->get('remarks');

$parentDepartment = $form->get('parentDepartment');
$parentDepartment->setValueOptions(array_merge(["0"=>"none"],$departments));


$countryId = $form->get('countryId');
$countryId->setValueOptions($countries);
$submit = $form->get('submit');
$submit->setAttribute('value','UPDATE');

$form->setAttribute('action', $this->url('department', ['action' => 'edit','id'=>$id]));

if ($this->messages) {
	print '<ul class="help-block bg-danger" style="background:#f3e250;">';
	foreach ($this->messages as $message) {
		print '<li>' . $message . '</li>';
	}
	print '</ul>';
}
$form->prepare();
?>
	<script>
		document.menu=<?php $menu = ["id" => "menuSetup","subMenu"=>["id"=>"subMenuDepartment"]];echo json_encode($menu);?>;
	</script>

	<div class="row">
		<div class="col-sm-8 bg-light-color padding-30" >
			<div class="row panel-title-head" style="margin-bottom: 2%">
				<div class="col-xs-9 col-sm-9 col-md-9">
					<div class="panel-heading padding-5">
						<h4>Edit Department</h4>
					</div>
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 pull-right">
					<div class="pull-right m-b-10">
						<a href="<?= $this->url("department",["action","index"])?>" style="margin-left:16%;">
							<button class="btn btn-default btn-cons"><i class="fa fa-arrow-left"></i>
								<span>Back </span></button>
						</a>
					</div>
				</div>
			</div>
			<div class="panel-body padding-0" >
				<?php
					print $this->form()->openTag($form);
				?>
				<div class="form-group form-group-default">
					<?php print $this->formLabel($departmentCode); ?>
					<?php print $this->formElement($departmentCode); ?>
					<?php print $this->formElementErrors()->render($departmentCode, ['class' => 'help-block']); ?>
				</div>
				<div class="form-group form-group-default  ">
					<?php print $this->formLabel($departmentName); ?>
					<?php print $this->formElement($departmentName); ?>
					<?php print $this->formElementErrors()->render($departmentName, ['class' => 'help-block']); ?>
				</div>
				<div class="form-group form-group-default form-group-default-select2">
					<?php print $this->formLabel($countryId); ?>
					<?php print $this->formElement($countryId); ?>
					<?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block']); ?>
				</div>
				<div class="form-group form-group-default  ">
					<?php print $this->formLabel($remarks); ?>
					<?php print $this->formElement($remarks); ?>
					<?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
				</div>
				<div class="form-group form-group-default  form-group-default-select2">
					<?php print $this->formLabel($parentDepartment); ?>
					<?php print $this->formElement($parentDepartment); ?>
					<?php print $this->formElementErrors()->render($parentDepartment, ['class' => 'help-block']); ?>
				</div>

			</div>
			<?php
			print $this->formSubmit($submit);
			print $this->form()->closeTag();

			?>
		</div>
		<div class="col-sm-2">

		</div>
	</div>
