
<a href="<?php echo $this->url('department',["action"=>"add"]) ?>">Add New</a>


<table role="grid" class="table table-hover dataTable no-footer" id="employeelist">

    <thead>
    <tr role="row">
        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1" rowspan="1"
            aria-controls="basicTable" tabindex="0" class="sorting_desc" style="width: 218px;">Department Code
        </th>
        <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="basicTable"
            tabindex="0" class="sorting" style="width: 219px;">Department Name
        </th>
        <th aria-label="Last Update: activate to sort column ascending" colspan="1" rowspan="1"
            aria-controls="basicTable" tabindex="0" class="sorting" style="width: 155px;">
            Action
        </th>
    </tr>
    </thead>
    <tbody>

<?php  foreach($departments as $department):?>
    <tr role="row">
        <td class="v-align-middle sorting_1">
            <p>
                <?php print $this->escapeHtml($department->departmentCode) ?>
            </p>
        </td>
        <td class="v-align-middle sorting_1">
            <p>
                <?php print $this->escapeHtml($department->departmentName) ?>
            </p>
        </td>
        <td class="v-align-middle sorting_1">
            <a href="<?= $this->url("department",["action"=>"edit","id"=>$department->departmentCode]) ?>">Edit</a>|
            <a href="<?= $this->url("department",["action"=>"delete","id"=>$department->departmentCode]); ?>">Delete</a>
        </td>
    </tr>

<?php endforeach;?>

    </tbody>
</table>
