<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('plugins/datatables/media/js/jquery.dataTables.min.js'))
    ->appendFile($this->basePath('plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js'))
    ->appendFile($this->basePath('js/datatables.js'));
?>

<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuDepartment"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Department')->breadcrumbs()->setMinDepth(0) ?>
</div>

<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-user"></i>Table
        </div>
        <div class="actions">
            <a href="<?= $this->url('department', ['action' => 'add']) ?>" class="btn btn-default btn-sm">
                <i class="fa fa-pencil"></i> Add </a>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-bordered bg-master-lighter table-striped small-table" id="tableWithSearch">
            <thead>
            <tr role="row">
                <th>
                    Department Code
                </th>
                <th>Department Name
                </th>
                <th>
                    Action
                </th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($departments as $department): ?>
                <tr role="row">
                    <td>
                        <?php print $this->escapeHtml($department->DEPARTMENT_CODE) ?>
                    </td>
                    <td>
                        <?php print $this->escapeHtml($department->DEPARTMENT_NAME) ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default">
                                <a class="fa fa-ambulance btn-link"
                                   href="<?= $this->url("department", ["action" => "edit", "id" => $department->DEPARTMENT_ID]); ?>">
                                </a>
                            </button>
                            <button type="button" class="btn btn-default">
                                <a class="fa fa-trash-o btn-link"
                                   href="<?= $this->url("department", ["action" => "delete", "id" => $department->DEPARTMENT_ID]); ?>"></a>
                            </button>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>

    </div>
</div>
