
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/training/training-apply/add.js'));
?>

<?php
$form->setAttribute('role', 'form');

$employeeId = $form->get('employeeId');
$trainingId = $form->get('trainingId');
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$duration = $form->get('duration');
$title = $form->get('title');
$trainingType = $form->get('trainingType');
$description = $form->get('description');
$remarks = $form->get('remarks');
$isWithinCompany = $form->get('isWithinCompany');
$dailyTrainingHour = $form->get('dailyTrainingHour');
$submit = $form->get('submit');


//$form->setAttribute('action', $this->url('trainingRequest', ['action' => 'add']));
$form->prepare();
print $this->form()->openTag($form);
?>

<script>
    document.employeeList =<?=json_encode($employeeList);?>;
    document.pullEmployeeTraining = '<?php echo $this->url('trainingApply', ['action' => 'pullEmployeeTraining']); ?>';
</script>

<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    Apply For Advance
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class=" row">
                    
                    <div class="col-sm-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <?php print $this->formElement($employeeId); ?>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($trainingId); ?>
                            <?php print $this->formElement($trainingId); ?>
                            <?php print $this->formElementErrors()->render($trainingId, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($title); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($title); ?>
                            <?php print $this->formElementErrors()->render($title, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($trainingType); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($trainingType); ?>
                            <?php print $this->formElementErrors()->render($trainingType, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($description); ?>
                            <?php print $this->formElement($description); ?>
                            <?php print $this->formElementErrors()->render($description, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group required">
                                    <?php print $this->formLabel($startDate) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($startDate) ?>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate" class="form-control" value="">
                                </div>
                            </div>     
                        </div>        
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div  class="form-group required">
                                    <?php print $this->formLabel($endDate) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($endDate) ?>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate" class="form-control" value="" disabled="disabled">
                                </div>
                            </div>     
                        </div>        
                    </div>
                    <div class="col-sm-4">
                        <div   class="form-group required">
                            <?php print $this->formLabel($duration); ?>
                            <?php print $this->formElement($duration); ?>
                            <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class=" col-sm-4 ">
                        <div class="form-group padding-0">
                            <?php print $this->formLabel($isWithinCompany); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($isWithinCompany); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($isWithinCompany, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($dailyTrainingHour); ?>
                            <?php print $this->formElement($dailyTrainingHour); ?>
                            <?php print $this->formElementErrors()->render($dailyTrainingHour, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
                
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>


