<?php
/**
 * Load Javascript files here
 */
$this->headScript()
   ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/Service/index.js'));
?>

<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuService"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\service')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="serviceController">
    <div class="margin-top-20">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="input-group date" id="fromDate">
                                <input type="text" placeholder="From Date" name="fromDate" ng-model="fromDate" id="fromDate1" class="form-control"/>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="input-group date" id="toDate">
                                <input type="text" placeholder="To Date" name="toDate" ng-model="toDate1" id="toDate1" class="form-control"/>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                            <input type="hidden" name="employeeId" ng-model="employeeId" id="employeeId" value="<?php echo $employeeId; ?>"/>
                       
                        </div>
                        <div class="col-md-2">
                            <button ng-click="view()" id="myServiceHistory" class="btn btn-success">
                                VIEW
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="btn-group pull-right">
                        <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;"> Print </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Save as PDF </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Export to Excel </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
       
            <div id="serviceHistoryTable" >           
            </div>
        
        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
                <td>
                #: START_DATE #
                </td>
                <td>    
                #: END_DATE #
                </td>
                <td>
                #: SERVICE_EVENT_TYPE_NAME #
                </td>
                <td>
                #: FROM_SERVICE_TYPE_NAME # - #: TO_SERVICE_TYPE_NAME #
                </td>
                <td>
                #: FROM_BRANCH_NAME # - #: TO_BRANCH_NAME #
                </td>
                <td>
                #: FROM_DEPARTMENT_NAME # - #: TO_DEPARTMENT_NAME #
                </td>
                <td>
                #: FROM_DESIGNATION_TITLE # - #: TO_DESIGNATION_TITLE #
                </td>
                <td>
                #: FROM_POSITION_NAME # - #: TO_POSITION_NAME #
                </td>
                <td>
                 <a class=""
                 href="<?= $this->url("service",["action"=>'view']) ?>/#: JOB_HISTORY_ID #">
                        View
                    </a>
                </td>
            </tr>
        </script>
    </div>
</div>