<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/SelfService/Service/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php
$menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuService"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\service')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="serviceController" class="formbg">
    <div class="margin-top-20">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <input type="hidden" name="employeeId" ng-model="employeeId" id="employeeId" value="<?php echo $employeeId; ?>"/>
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label for="fromDate">From Date</label>
                                        <input type="text" id="fromDate" name="fromDate" ng-model="fromDate" class="form-control"/>
                                    </div>

                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label for="nepaliFromDate">&nbsp;</label>
                                        <input type="text" id="nepaliFromDate" name="nepaliFromDate"  class="form-control"/>
                                    </div>

                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label for="toDate">To Date</label>
                                        <input type="text"  id="toDate" name="toDate" ng-model="toDate" class="form-control"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label for="nepaliToDate">&nbsp;</label>
                                        <input type="text"  id="nepaliToDate" name="nepaliToDate" class="form-control"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=" col-sm-4 ">
                            <button ng-click="view()" id="myServiceHistory" class="btn btn-default form-control i-search">
                                VIEW
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="btn-group pull-right">
                        <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;" id="export"> Export to Excel </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div id="serviceHistoryTable" >           
        </div>

        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
            <td>
            #: (START_DATE == null) ? '-' : START_DATE #
            </td>
            <td>    
            #: (END_DATE == null) ? '-' : END_DATE #
            </td>
            <td>
            #: (SERVICE_EVENT_TYPE_NAME == null) ? ' ' : SERVICE_EVENT_TYPE_NAME #
            </td>
            <td>
            #: (FROM_SERVICE_TYPE_NAME == null) ? ' ' : FROM_SERVICE_TYPE_NAME # - #: (TO_SERVICE_TYPE_NAME == null) ? ' ' : TO_SERVICE_TYPE_NAME #
            </td>
            <td>
            #: (FROM_BRANCH_NAME == null) ? ' ' : FROM_BRANCH_NAME # - #: (TO_BRANCH_NAME == null) ? ' ' : TO_BRANCH_NAME #
            </td>
            <td>
            #: (FROM_DEPARTMENT_NAME == null) ? ' ' : FROM_DEPARTMENT_NAME # - #: (TO_DEPARTMENT_NAME == null) ? ' ' : TO_DEPARTMENT_NAME #
            </td>
            <td>
            #: (FROM_DESIGNATION_TITLE == null) ? ' ' : FROM_DESIGNATION_TITLE # - #: (TO_DESIGNATION_TITLE == null) ? ' ' : TO_DESIGNATION_TITLE #
            </td>
            <td>
            #: (FROM_POSITION_NAME == null) ? ' ' : FROM_POSITION_NAME # - #: (TO_POSITION_NAME == null) ? ' ' : TO_POSITION_NAME #
            </td>
            <td>
            <a class="btn  btn-icon-only btn-success"
            href="<?= $this->url("service", ["action" => 'view']) ?>/#: JOB_HISTORY_ID #" style="height:17px;" title="view">
            <i class="fa fa-search-plus"></i>
            </a>
            </td>
            </tr>
        </script>
    </div>
</div>