<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/SelfService/Service/view.js'));
?>



<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'jobHistory-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$employeeId->setAttributes(['disabled' => "disabled"]);
$startDate = $form->get('startDate');
$startDate->setAttributes(['disabled' => "disabled"]);
$startDate->setAttributes(['id' => "startDate"]);
$endDate = $form->get('endDate');
$endDate->setAttributes(['disabled' => "disabled"]);
$endDate->setAttributes(['id' => "endDate"]);
$serviceEventTypeId = $form->get('serviceEventTypeId');
$serviceEventTypeId->setValueOptions($serviceEventTypes);
$serviceEventTypeId->setAttributes(['disabled' => "disabled"]);
$toServiceTypeId = $form->get('toServiceTypeId');
$toServiceTypeId->setValueOptions($serviceTypes);
$toServiceTypeId->setAttributes(['disabled' => "disabled"]);
$toBranchId = $form->get('toBranchId');
$toBranchId->setValueOptions($branches);
$toBranchId->setAttributes(['disabled' => "disabled"]);
$toDepartmentId = $form->get('toDepartmentId');
$toDepartmentId->setValueOptions($departments);
$toDepartmentId->setAttributes(['disabled' => "disabled"]);
$toDesignationId = $form->get('toDesignationId');
$toDesignationId->setValueOptions($designations);
$toDesignationId->setAttributes(['disabled' => "disabled"]);
$toPositionId = $form->get('toPositionId');
$toPositionId->setValueOptions($positions);
$toPositionId->setAttributes(['disabled' => "disabled"]);


$form->prepare();
print $this->form()->openTag($form);
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\service')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <?php print $this->formElement($employeeId); ?>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($startDate); ?>
                                    <?php print $this->formElement($startDate) ?>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                           class="form-control" value="" disabled="disabled">
                                </div>
                            </div>     
                        </div>  
                        <div class="form-group">
                            <?php print $this->formLabel($toServiceTypeId); ?>
                            <?php print $this->formElement($toServiceTypeId); ?>
                            <?php print $this->formElementErrors()->render($toServiceTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toDepartmentId); ?>
                            <?php print $this->formElement($toDepartmentId); ?>
                            <?php print $this->formElementErrors()->render($toDepartmentId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="form-group">
                            <?php print $this->formLabel($toPositionId); ?>
                            <?php print $this->formElement($toPositionId); ?>
                            <?php print $this->formElementErrors()->render($toPositionId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($serviceEventTypeId); ?>
                            <?php print $this->formElement($serviceEventTypeId); ?>
                            <?php print $this->formElementErrors()->render($serviceEventTypeId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($endDate); ?>
                                    <?php print $this->formElement($endDate) ?>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                           class="form-control" value="" disabled="disabled">
                                </div>
                            </div>     
                        </div>        


                        <div class="form-group">
                            <?php print $this->formLabel($toBranchId); ?>
                            <?php print $this->formElement($toBranchId); ?>
                            <?php print $this->formElementErrors()->render($toBranchId, ['class' => 'help-block']); ?>
                        </div>





                        <div class="form-group">
                            <?php print $this->formLabel($toDesignationId); ?>
                            <?php print $this->formElement($toDesignationId); ?>
                            <?php print $this->formElementErrors()->render($toDesignationId, ['class' => 'help-block']); ?>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>