<?php
$this->headScript()->appendFile($this->basePath('js/system/role-setup/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'rolesetup-form');

$roleName = $form->get('roleName');
$remarks = $form->get('remarks');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('rolesetup', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSystem", "subMenu" => ["id" => "subMenuRoleSetup"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\rolesetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group<?= empty($roleName->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($roleName); ?>
                    <?php print $this->formElement($roleName); ?>
                    <span class="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($roleName, ['class' => 'help-block error']); ?>

                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                </div>

                <?php print $this->formSubmit($submit); ?>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>