<?php
$this->headScript()->appendFile($this->basePath('js/system/role-setup/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'rolesetup-form');

$roleName = $form->get('roleName');
$remarks = $form->get('remarks');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('rolesetup', ['action' => 'edit','id'=>$id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSystem", "subMenu" => ["id" => "subMenuRoleSetup"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\rolesetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                
                <div class=" row">
                    <div class="col-sm-4">
                <div class="form-group<?= empty($roleName->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($roleName); ?>
                    <span class="required" aria-required="true">*</span>
                    <?php print $this->formElement($roleName); ?>
                    <input type="hidden" id="roleId" value="<?php echo $id; ?>" />
                    <span class="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($roleName, ['class' => 'help-block error']); ?>
                    </div>
                    
                    <div class="col-sm-4">
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                </div>
                    </div>
                    
                </div>


                <?php print $this->formSubmit($submit); ?>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>