<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/system/role-setup/index.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>


<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSystem", "subMenu" => ["id" => "subMenuRoleSetup"]];echo json_encode($menu);?>;
    document.roles=<?= json_encode($roles); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\rolesetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('rolesetup', ['action' => 'add']) ?>" id="sample_editable_1_new" class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
 
    <div id="roleTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (SN == null) ? '-' : SN #
        </td>
        <td>
        #: (ROLE_NAME == null) ? '-' : ROLE_NAME #
        </td>
        <td>
        <a class="btn  btn-icon-only btn-success"
        href="<?= $this->url("rolesetup", ["action" => "edit"]); ?>/#:ROLE_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
         <a class="btn btn-icon-only btn-danger confirmation"
        href="<?= $this->url("rolesetup", ["action" => "delete"]); ?>/#:ROLE_ID #" id="bs_#:ROLE_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>
</div>

