<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/setup/advance/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuAdvance"]];
echo json_encode($menu); ?>;
    document.deleteURL ='<?= $this->url("restful", ["action" => "index"]) ?>';
    document.loans =<?php echo json_encode($list); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advance')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('advance', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                                          <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">      
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>      
        </div>
    </div>    
    <div id="loanTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (ADVANCE_CODE == null) ? '-' : ADVANCE_CODE #
        </td>
        <td>    
        #: (ADVANCE_NAME == null) ? '-' : ADVANCE_NAME #
        </td>
        <td>    
        #: MIN_SALARY_AMT # - #: MAX_SALARY_AMT #
        </td>
        <td>    
        #: (AMOUNT_TO_ALLOW == null) ? '-' : AMOUNT_TO_ALLOW #%
        </td>
        <td>    
        #: (MONTH_TO_ALLOW == null) ? '-' : MONTH_TO_ALLOW #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("advance", ["action" => "edit"]); ?>/#:ADVANCE_ID#" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="btn-delete confirmation"
        href="<?= $this->url("advance", ["action" => "delete"]); ?>/#:ADVANCE_ID#" id="bs_#:ADVANCE_ID #" style="height:17px;"> 
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>
 
</div>