<?php
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/albe-timeline/style-albe-timeline.css'));

$this->headLink()->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));
$this->headScript()->appendFile($this->basePath('dropzone/dropzone.min.js'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/albe-timeline/jquery-albe-timeline.js'));
$this->headScript()->appendFile($this->basePath('js/setup/job-history/edit.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'jobHistory-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);

$startDate = $form->get('startDate');
$endDate = $form->get('endDate');

$serviceEventTypeId = $form->get('serviceEventTypeId');
$serviceEventTypeId->setValueOptions($serviceEventTypes);

$toServiceTypeId = $form->get('toServiceTypeId');
$toServiceTypeId->setValueOptions($serviceTypes);


$toCompanyId = $form->get('toCompanyId');
$toCompanyId->setValueOptions($companies);


$toBranchId = $form->get('toBranchId');
$toBranchId->setValueOptions($branches);


$toDepartmentId = $form->get('toDepartmentId');
$toDepartmentId->setValueOptions($departments);


$toDesignationId = $form->get('toDesignationId');
$toDesignationId->setValueOptions($designations);


$toSalary = $form->get('toSalary');



$toPositionId = $form->get('toPositionId');
$toPositionId->setValueOptions($positions);

$retiredFlag = $form->get('retiredFlag');
$disabledFlag = $form->get('disabledFlag');
$eventDate = $form->get('eventDate');
$fileId = $form->get('fileId');

$retiredFlag->setAttribute('checked', $retiredFlagValue === "Y");
$disabledFlag->setAttribute('checked', $disabledFlagValue === "Y");

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('jobHistory', ['action' => 'edit', 'id' => $id]));


$form->prepare();
print $this->form()->openTag($form);
?>
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\jobHistory')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.wsGetHistoryList = '<?php echo $this->url('jobHistory', ['action' => 'getHistoryList']); ?>';
    document.uploadFileLink = '<?php echo $this->url('jobHistory', ['action' => 'uploadFile']); ?>';
    document.getFileDetailLink = '<?php echo $this->url('jobHistory', ['action' => 'getFileDetail']); ?>';
</script>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Job History
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->formElement($fileId); ?>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <?php print $this->formElement($employeeId); ?>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($startDate); ?>
                                    <?php print $this->formElement($startDate) ?>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                           class="form-control" value="">
                                </div>
                            </div>     
                        </div>     
                        <div class="form-group companyToggle">
                            <?php print $this->formLabel($toCompanyId); ?>
                            <?php print $this->formElement($toCompanyId); ?>
                            <?php print $this->formElementErrors()->render($toCompanyId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toDepartmentId); ?>
                            <?php print $this->formElement($toDepartmentId); ?>
                            <?php print $this->formElementErrors()->render($toDepartmentId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="form-group">
                            <?php print $this->formLabel($toPositionId); ?>
                            <?php print $this->formElement($toPositionId); ?>
                            <?php print $this->formElementErrors()->render($toPositionId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toSalary); ?>
                            <?php print $this->formElement($toSalary); ?>
                            <?php print $this->formElementErrors()->render($toSalary, ['class' => 'help-block']); ?>
                        </div>

                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($serviceEventTypeId); ?>
                            <?php print $this->formElement($serviceEventTypeId); ?>
                            <?php print $this->formElementErrors()->render($serviceEventTypeId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($endDate); ?>
                                    <?php print $this->formElement($endDate) ?>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                           class="form-control" value="">
                                </div>
                            </div>     
                        </div>        
                        <div class="form-group">
                            <?php print $this->formLabel($toBranchId); ?>
                            <?php print $this->formElement($toBranchId); ?>
                            <?php print $this->formElementErrors()->render($toBranchId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toDesignationId); ?>
                            <?php print $this->formElement($toDesignationId); ?>
                            <?php print $this->formElementErrors()->render($toDesignationId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toServiceTypeId); ?>
                            <?php print $this->formElement($toServiceTypeId); ?>
                            <?php print $this->formElementErrors()->render($toServiceTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($eventDate); ?>
                                    <?php print $this->formElement($eventDate) ?>
                                    <?php print $this->formElementErrors()->render($eventDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="eventDateNepali">&nbsp;</label>
                                    <input type="text" name="eventDateNepali" id="eventDateNepali"
                                           class="form-control" value="">
                                </div>
                            </div>     
                        </div>  
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($retiredFlag); ?>
                            <?php print $this->formElement($retiredFlag); ?>
                            <?php print $this->formElementErrors()->render($retiredFlag, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($disabledFlag); ?>
                            <?php print $this->formElement($disabledFlag); ?>
                            <?php print $this->formElementErrors()->render($disabledFlag, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="border-dotted border-bottom border-left border-right" style="height: 300px;width:300px;" id="dropZone">
                            <h4>Drop files here or click to upload.</h4>  
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formSubmit($submit); ?>
                </div>

            </div>
        </div>
        <div id="myTimeline"></div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>