<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/setup/job-history/edit.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'jobHistory-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employeesAll);
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$serviceEventTypeId = $form->get('serviceEventTypeId');
$serviceEventTypeId->setValueOptions($serviceEventTypes);
$fromServiceTypeId = $form->get('fromServiceTypeId');
$fromServiceTypeId->setValueOptions($serviceTypes);
$toServiceTypeId = $form->get('toServiceTypeId');
$toServiceTypeId->setValueOptions($serviceTypes);
$fromBranchId = $form->get('fromBranchId');
$fromBranchId->setValueOptions($branches);
$toBranchId = $form->get('toBranchId');
$toBranchId->setValueOptions($branches);
$fromDepartmentId = $form->get('fromDepartmentId');
$fromDepartmentId->setValueOptions($departments);
$toDepartmentId = $form->get('toDepartmentId');
$toDepartmentId->setValueOptions($departments);
$fromDesignationId = $form->get('fromDesignationId');
$fromDesignationId->setValueOptions($designations);
$toDesignationId = $form->get('toDesignationId');
$toDesignationId->setValueOptions($designations);
$fromPositionId = $form->get('fromPositionId');
$fromPositionId->setValueOptions($positions);
$toPositionId = $form->get('toPositionId');
$toPositionId->setValueOptions($positions);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('jobHistory', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.jobHistoryId =<?= $id ?>;
    document.employeeId =<?= $empId ?>;
    document.wsPullEmployeeDetailWithOptions = '<?php echo $this->url('jobHistory', ['action' => 'pullEmployeeDetailWithOptions']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\jobHistory')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <?php print $this->formElement($employeeId); ?>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($startDate); ?>
                                    <?php print $this->formElement($startDate) ?>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>        
                        <div class="form-group">
                            <?php print $this->formLabel($fromServiceTypeId); ?>
                            <?php print $this->formElement($fromServiceTypeId); ?>
                            <?php print $this->formElementErrors()->render($fromServiceTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromBranchId); ?>
                            <?php print $this->formElement($fromBranchId); ?>
                            <?php print $this->formElementErrors()->render($fromBranchId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromDepartmentId); ?>
                            <?php print $this->formElement($fromDepartmentId); ?>
                            <?php print $this->formElementErrors()->render($fromDepartmentId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="form-group">
                            <?php print $this->formLabel($fromDesignationId); ?>
                            <?php print $this->formElement($fromDesignationId); ?>
                            <?php print $this->formElementErrors()->render($fromDesignationId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromPositionId); ?>
                            <?php print $this->formElement($fromPositionId); ?>
                            <?php print $this->formElementErrors()->render($fromPositionId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($serviceEventTypeId); ?>
                            <?php print $this->formElement($serviceEventTypeId); ?>
                            <?php print $this->formElementErrors()->render($serviceEventTypeId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($endDate); ?>
                                    <?php print $this->formElement($endDate) ?>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>        
                        <div class="form-group">
                            <?php print $this->formLabel($toServiceTypeId); ?>
                            <?php print $this->formElement($toServiceTypeId); ?>
                            <?php print $this->formElementErrors()->render($toServiceTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toBranchId); ?>
                            <?php print $this->formElement($toBranchId); ?>
                            <?php print $this->formElementErrors()->render($toBranchId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="form-group">
                            <?php print $this->formLabel($toDepartmentId); ?>
                            <?php print $this->formElement($toDepartmentId); ?>
                            <?php print $this->formElementErrors()->render($toDepartmentId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="form-group">
                            <?php print $this->formLabel($toDesignationId); ?>
                            <?php print $this->formElement($toDesignationId); ?>
                            <?php print $this->formElementErrors()->render($toDesignationId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="form-group">
                            <?php print $this->formLabel($toPositionId); ?>
                            <?php print $this->formElement($toPositionId); ?>
                            <?php print $this->formElementErrors()->render($toPositionId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <?php if ($latestJobHistoryId == $id) { ?>
                    <div class="form-group">
                        <?php print $this->formSubmit($submit); ?>
                    </div>
                <?php } else { ?>
                    <div class="form-group" style="font-size:11px;">[note:You can only view this detail. If you wish to update, you need to go through latest service status of selected employee!!!!]</div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>