<?php
$this->headScript()->appendFile($this->basePath('js/setup/job-history/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'jobHistory-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$serviceEventTypeId = $form->get('serviceEventTypeId');
$serviceEventTypeId->setValueOptions($serviceEventTypes);
$fromServiceTypeId = $form->get('fromServiceTypeId');
$fromServiceTypeId->setValueOptions($serviceTypes);
$toServiceTypeId = $form->get('toServiceTypeId');
$toServiceTypeId->setValueOptions($serviceTypes);
$fromBranchId = $form->get('fromBranchId');
$fromBranchId->setValueOptions($branches);
$toBranchId = $form->get('toBranchId');
$toBranchId->setValueOptions($branches);
$fromDepartmentId = $form->get('fromDepartmentId');
$fromDepartmentId->setValueOptions($departments);
$toDepartmentId = $form->get('toDepartmentId');
$toDepartmentId->setValueOptions($departments);
$fromDesignationId = $form->get('fromDesignationId');
$fromDesignationId->setValueOptions($designations);
$toDesignationId = $form->get('toDesignationId');
$toDesignationId->setValueOptions($designations);
$fromPositionId = $form->get('fromPositionId');
$fromPositionId->setValueOptions($positions);
$toPositionId = $form->get('toPositionId');
$toPositionId->setValueOptions($positions);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('jobHistory', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.menu =<?php
$menu = ["id" => "menuService"];
echo json_encode($menu);
?>;
    document.jobHistoryId =<?= $id ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\jobHistory')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <?php print $this->formElement($employeeId); ?>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($startDate); ?>
                            <div class="input-group date" id="startDate">
                                <?php print $this->formElement($startDate) ?>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                            <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromServiceTypeId); ?>
                            <?php print $this->formElement($fromServiceTypeId); ?>
                            <?php print $this->formElementErrors()->render($fromServiceTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromBranchId); ?>
                            <?php print $this->formElement($fromBranchId); ?>
                            <?php print $this->formElementErrors()->render($fromBranchId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromDepartmentId); ?>
                            <?php print $this->formElement($fromDepartmentId); ?>
                            <?php print $this->formElementErrors()->render($fromDepartmentId, ['class' => 'help-block']); ?>
                        </div>

                        <div class="form-group">
                            <?php print $this->formLabel($fromDesignationId); ?>
                            <?php print $this->formElement($fromDesignationId); ?>
                            <?php print $this->formElementErrors()->render($fromDesignationId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($fromPositionId); ?>
                            <?php print $this->formElement($fromPositionId); ?>
                            <?php print $this->formElementErrors()->render($fromPositionId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php print $this->formLabel($serviceEventTypeId); ?>
                            <?php print $this->formElement($serviceEventTypeId); ?>
                            <?php print $this->formElementErrors()->render($serviceEventTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($endDate); ?>
                            <div class="input-group date" id="endDate">
                                <?php print $this->formElement($endDate) ?>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                            <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toServiceTypeId); ?>
                            <?php print $this->formElement($toServiceTypeId); ?>
                            <?php print $this->formElementErrors()->render($toServiceTypeId, ['class' => 'help-block']); ?>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($toBranchId); ?>
                            <?php print $this->formElement($toBranchId); ?>
                            <?php print $this->formElementErrors()->render($toBranchId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="form-group">
                            <?php print $this->formLabel($toDepartmentId); ?>
                            <?php print $this->formElement($toDepartmentId); ?>
                            <?php print $this->formElementErrors()->render($toDepartmentId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="form-group">
                            <?php print $this->formLabel($toDesignationId); ?>
                            <?php print $this->formElement($toDesignationId); ?>
                            <?php print $this->formElementErrors()->render($toDesignationId, ['class' => 'help-block']); ?>
                        </div>


                        <div class="form-group">
                            <?php print $this->formLabel($toPositionId); ?>
                            <?php print $this->formElement($toPositionId); ?>
                            <?php print $this->formElementErrors()->render($toPositionId, ['class' => 'help-block']); ?>
                        </div>




                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formSubmit($submit); ?>
                </div>

            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>