<?php
//Load JS files here

?>
<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuEmployee"]];echo json_encode($menu);?>;
</script>

<div class="page-bar">
    <ul class="page-breadcrumb">
    <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0) ?>
    </ul>

</div>

<div class="portlet box purple margin-top-10">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-user"></i>Table
        </div>
        <div class="actions">
            <a href="<?= $this->url('employee', ['action' => 'add']) ?>" class="btn btn-info btn-sm">
                <i class="fa fa-plus"></i>
                Add
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-bordered">
            <thead>
            <tr class="row">
                <th>
                    Employee Code
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Middle Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Date of Birth
                </th>
                <th>
                    Action
                </th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($list as $employee) : ?>
                <tr class="row">
                    <td>
                        <?php print $this->escapeHtml($employee->employeeCode) ?>
                    </td>

                    <td>
                        <?php print $this->escapeHtml($employee->firstName) ?>
                    </td>
                    <td>
                        <?php print $this->escapeHtml($employee->middleName) ?>
                    </td>
                    <td>
                        <?php print $this->escapeHtml($employee->lastName) ?>
                    </td>
                    <td>
                        <?php print $this->escapeHtml($employee->birthDate) ?>
                    </td>
                    <td>
                                <a href="<?= $this->url("employee", ["action" => "edit", "id" => $employee->employeeId, 'tab' => 1]) ?>"> Edit
                                </a> /
                                <a class=""
                                   href="<?= $this->url("employee", ["action" => "delete", "id" => $employee->employeeId]); ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


