<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'menusetup-form');

$menuCode = $form->get('menuCode');
$menuName = $form->get('menuName');
$url = $form->get('url');
$parentMenu = $form->get('parentMenu');
$parentMenu->setValueOptions($menuList);
$menuDescription = $form->get('menuDescription');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('menusetup', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<link href="<?= $this->basePath('css/listpage.css') ?>"
      rel="stylesheet" type="text/css"/>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\menusetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php print $this->formLabel($menuCode); ?>
                    <?php print $this->formElement($menuCode); ?>
                    <?php print $this->formElementErrors()->render($menuCode, ['class' => 'help-block error']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($menuName); ?>
                    <?php print $this->formElement($menuName); ?>
                    <?php print $this->formElementErrors()->render($menuName, ['class' => 'help-block error']); ?>
                </div>
                <div class="form-group<?= empty($url->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($url); ?>
                    <?php print $this->formElement($url); ?>
                </div>
                <?php print $this->formElementErrors()->render($url, ['class' => 'help-block error']); ?>

                <div class="form-group">
                    <?php print $this->formLabel($parentMenu); ?>
                    <?php print $this->formElement($parentMenu); ?>
                    <?php print $this->formElementErrors()->render($parentMenu, ['class' => 'help-block error']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($menuDescription); ?>
                    <?php print $this->formElement($menuDescription); ?>
                    <?php print $this->formElementErrors()->render($menuDescription, ['class' => 'help-block']); ?>
                </div>
                <?php print $this->formSubmit($submit); ?>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>