<?php
$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/jquery-ui/jquery-ui.min.js'))
    ->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/jstree/dist/jstree.min.js'))
    ->appendFile($this->basePath('js/system/menu-setup/index.js'))
    ->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'))
    ->appendFile($this->basePath('js/system/menu-setup/menuController.js'));
?>
<link href="<?= $this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<link href="<?= $this->basePath('assets/global/plugins/jstree/dist/themes/default/style.min.css') ?>"
      rel="stylesheet" type="text/css"/>

<script>
    document.menu =<?php $menu = ["id" => "menuSystem", "subMenu" => ["id" => "subMenuMenuSetup"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "action"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\menusetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris">
    <div class="row margin-top-20">
        <div ng-controller="menuUpdateController">
            <div class="col-sm-4">
                <div class="portlet box custom-box">
                    <div class="portlet-title">
                        <div class="row">
                            <div class="col-md-9" style="padding-right: 0px;">
                                <div class="input-group" style="margin-top:2%;">
                                    <span class="input-group-addon" id="basic-addon1"><i
                                            class="fa fa-search"></i></span>
                                    <input type="text" id="search" class="form-control" placeholder="Menus"
                                           aria-describedby="basic-addon1">
                                </div>
                            </div>
                            <div class="col-md-3 rlPadding">
                                <div class="btn-group open" style="margin-top:12%;">
                                    <a class="btn btn-success btn-sm" ng-click="$ctrl.open()" id="addParent">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="tree_3" class="tree-demo"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="portlet box custom-box">
                    <div class="portlet-title">
                        <div class="caption">
                            <span ng-bind="menuDtl.menuName"></span>
                        </div>
                        <div class="btn-group pull-right open" style="margin-top:1%">
                            <a class="btn btn-success btn-sm" id="addChild" ng-click="$ctrl.open()">
                                <i class="fa fa-plus"></i>Add Child
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="editForm" style="display: none;">
                            <form name="userForm" ng-submit="submitForm()" novalidate>
                                <div class="form-group">
                                    <label for="form-menuCode">Menu Code</label>
                                    <input name="menuCode" required="required" id="form-menuCode"
                                           class="form-menuCode form-control"
                                           type="text" value="" ng-model="menuDtl.menuCode">
                                    <div ng-show="userForm.$submitted || userForm.menuCode.$touched">
                                        <ul ng-show="userForm.menuCode.$error.required" class="help-block error">
                                            <li>Menu Code is required.</li>
                                        </ul>
                                    </div>
                                    <input name="menuId" required="required" id="form-menuId"
                                           class="form-menuId form-control"
                                           type="hidden" value="" ng-model="menuDtl.menuId">
                                </div>
                                <div class="form-group">
                                    <label for="form-menuName">Menu Name</label>
                                    <input name="menuName" required="required" id="form-menuName"
                                           class="form-menuName form-control"
                                           type="text" value="" ng-model="menuDtl.menuName">
                                    <div ng-show="userForm.$submitted || userForm.menuName.$touched">
                                        <ul ng-show="userForm.menuName.$error.required" class="help-block error">
                                            <li>Menu Name is required.</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="form-url">Url</label>
                                    <input name="url" required="required" id="form-url" class="form-url form-control"
                                           type="text"
                                           value="" ng-model="menuDtl.url">
                                    <div ng-show="userForm.$submitted || userForm.url.$touched">
                                        <ul ng-show="userForm.url.$error.required" class="help-block error">
                                            <li>Url Code is required.</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="form-menuDescription">Menu Description</label>
                                    <textarea name="menuDescription" id="form-menuDescription"
                                              class="form-menuDescription form-control"
                                              style="height: 50px;" ng-model="menuDtl.menuDescription"></textarea>
                                </div>
                                <button type="submit" class="btn green">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div ng-controller="ModalDemoCtrl as $ctrl" class="modal-demo">
        <script type="text/ng-template" id="myModalContent.html">
            <div class="modal-header">
                <button type="button" class="close" ng-click="$ctrl.cancel()"  aria-hidden="true"></button>
                <h4 class="modal-title">New Entry</h4>
            </div>
            <form name="userForm" novalidate>
                <div class="modal-body" style="background-color:#ffffff">
                    <div class="form-group">
                        <label for="form-menuCode">Menu Code</label>
                        <input name="menuCode" required="required" id="form-menuCode"
                               class="form-menuCode form-control"
                               type="text" value="" ng-model="menuDtl.menuCode">
                        <div ng-show="userForm.$submitted || userForm.menuCode.$touched">
                            <ul ng-show="userForm.menuCode.$error.required" class="help-block error">
                                <li>Menu Code is required.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="form-menuName">Menu Name</label>
                        <input name="menuName" required="required" id="form-menuName"
                               class="form-menuName form-control"
                               type="text" value="" ng-model="menuDtl.menuName">
                        <div ng-show="userForm.$submitted || userForm.menuName.$touched">
                            <ul ng-show="userForm.menuName.$error.required" class="help-block error">
                                <li>Menu Name is required.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="form-url">Url</label>
                        <input name="url" required="required" id="form-url" class="form-url form-control"
                               type="text"
                               value="" ng-model="menuDtl.url">
                        <div ng-show="userForm.$submitted || userForm.url.$touched">
                            <ul ng-show="userForm.url.$error.required" class="help-block error">
                                <li>Url is required.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="form-menuDescription">Menu Description</label>
                        <textarea name="menuDescription" id="form-menuDescription"
                                  class="form-menuDescription form-control"
                                  style="height: 50px;" ng-model="menuDtl.menuDescription"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" ng-click="$ctrl.cancel()">Close</button>
                    <button type="submit" class="btn green"  ng-click="submitForm()">Submit</button>
                </div>
            </form>
        </script>
        <button type="button" class="btn btn-default" ng-click="$ctrl.open()">Open me!</button>
    </div>


</div>