<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'position-form');

$positionName = $form->get('positionName');
$remarks = $form->get('remarks');
$status = $form->get('status');

$submit = $form->get('submit');
$submit->setAttribute('value', 'UPDATE');

$form->setAttribute('action', $this->url('position', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuPosition"]];echo json_encode($menu);?>;
</script>
<div class="container">
    <?= $this->navigation('Zend\Navigation\Position')->breadcrumbs()->setMinDepth(0) ?>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-default customShadow">
            <div class="panel-heading bg-master-lighter">
                <div class="panel-title">
                    <h3 class="panel-title">Position</h3>
                </div>
            </div>
            <div class="panel-body p-t-5">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group form-group-sm ">
                    <?php print $this->formLabel($positionName); ?>
                    <?php print $this->formElement($positionName); ?>
                    <?php print $this->formElementErrors()->render($positionName, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group form-group-sm">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group form-group-sm form-group-default-select2">
                    <?php print $this->formLabel($status); ?>
                    <?php print $this->formElement($status); ?>
                    <?php print $this->formElementErrors()->render($status, ['class' => 'help-block']); ?>
                </div>

                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
