<?php
/**
 * Load Javascript files here
 */

?>
<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuPosition"]];echo json_encode($menu);?>;
</script>
<div class="menu-bar">
    <?= $this->navigation('Zend\Navigation\Position')->breadcrumbs()->setMinDepth(0) ?>
</div>
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-user"></i>Table
        </div>
        <div class="actions">
            <a href="<?= $this->url('position', ['action' => 'add']) ?>" class="btn btn-default btn-sm">
                <i class="fa fa-pencil"></i> Add </a>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-bordered">
            <thead>
            <tr role="row">
                <th>
                    Position Code
                </th>
                <th>
                    Position Name
                </th>
                <th>
                    Action
                </th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($positions as $position): ?>
                <tr role="row">
                    <td>
                            <?php print $this->escapeHtml($position->POSITION_ID); ?>
                    </td>
                    <td class="v-align-middle sorting_1">
                            <?php print $this->escapeHtml($position->POSITION_NAME); ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default">
                                <a class="fa fa-edit btn-link"
                                   href="<?= $this->url("position", ["action" => "edit", "id" => $position->POSITION_ID]); ?>">
                                </a>
                            </button>
                            <button type="button" class="btn btn-default">
                                <a class="fa fa-trash-o btn-link"
                                   href="<?= $this->url("position", ["action" => "delete", "id" => $position->POSITION_ID]); ?>"></a>
                            </button>
                        </div>
                    </td>
                </tr>

            <?php endforeach; ?>

            </tbody>
        </table>
    </div>
</div>