<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/medical/medical-report/transaction-rep.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.pullBalanceLink = '<?= $this->url("medicalReport", ["action" => "pullBalance"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\medicalEntry')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div id="employeeList" >
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                    <button id="printExcel" class="btn btn-primary">Export To Excel</button>
                    <button id="printPdf" class="btn btn-primary">print</button>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i>
                                Export to Excel
                            </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Company</label>
                    <select multiple class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Branch</label>
                    <select multiple class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select multiple class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Position</label>
                    <select multiple class="form-control" name="position" id="positionId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Service Type</label>
                    <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <label>Service Event Type</label>
                    <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee Type</label>
                    <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Gender</label>
                    <select multiple class="form-control" name="gender" id="genderId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Functional Type</label>
                    <select multiple class="form-control" name="functionalType" id="functionalTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select multiple class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
            </div>

            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <div class="form-group">
                        <label>From Date(AD)</label>
                        <input type="text" id="fromDate" name="fromDate"  class="form-control reset-field" placeholder="From Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label>From Date(BS)</label>
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control reset-field" placeholder="From Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label>To Date(AD)</label>
                        <input type="text" id="toDate" name="toDate"  class="form-control reset-field" placeholder="To Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label>To Date(BS)</label>
                        <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control reset-field" placeholder="To Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <label>Report Type</label>
                    <select  class="form-control reset-field" name="reportType" id="reportType">
                        <option value="TF">Transfer</option>
                        <option value="TS">Transaction</option>
                    </select>
                </div>
            </div>


            <div class="row margin-top-10">
                <div class="col-sm-4 col-sm-offset-8">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>



    <div id="table">
    </div>


    <!--<div id="printDiv">-->
        <div id="printDiv" style="display: none;">
        <div class="col-sm-offset-2">
            <h3>SOALTEE CROWN PLAZA</h3>
            <b>Tachal Kathmandu</b> </br>
            Bank Transfer List(Medical) 
        </div>


        <table id="printTable" class="table table-bordered">
            <thead>
                <tr>
                    <th>Code</th>       
                    <th>Employee</th>       
                    <th>Department</th>       
                    <th>Functional Type</th>       
                    <th>Claim Of</th>       
                    <th>Account No</th>       
                    <th>Amt</th>       
                </tr>
            </thead>
            <tbody>

            </tbody>

        </table>


    </div>

    <!--start-->

    <!--end-->

</div>


