<div class="<?= ($assignedAppraisalDetail['COMPETENCIES_SETTING'] == 'Y') ? 'display-block' : 'display-none'; ?> appRemarks">
    <table class="table table-bordered" id="dataTables-exampl">
        <tr>
            <td class="label" style="color:#428bca;font:bold;"><b>COMPETENCIES AND
                    COMMENT</b></td>
        </tr>
        <tr>
            <td>
                <p style="width:800px;height:100px;color:black;font-size:10px;">
                    The appraisee and the appraiser should decide on the competencies which
                    are key to the job.
                    These competencies can feature from the individual job description.
                    Appraiser should give a rating and also add comments in the appropriate
                    space at the end of the review period using the following scale.
                    &nbsp;
                    (A- Exceeds expectation
                    B- Meets expectation
                    C- Needs improvement)
                </p>
            </td>
        </tr>
    </table>
</div>
