<div class="portlet-body" style="padding-top:1px; background-color: #fafafa; padding:4px 10px!important;">
    <h5 id="headingForPanel" style="font-weight:600">Personal Information</h5>
    <div class="row div-font-11" style="font-weight:600">
        <div class="col-xs-4 col-sm-4 col-md-4">
            <table>
                <tbody>
                    <tr height="30">
                        <td>
                            Appraisee's Name
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            $middleName = ($employeeDetail['MIDDLE_NAME'] == null || $employeeDetail['MIDDLE_NAME'] == "") ? " " : " " . $employeeDetail['MIDDLE_NAME'] . " ";
                            $employeeName = $employeeDetail['FIRST_NAME'] . $middleName . $employeeDetail['LAST_NAME'];
                            print_r($employeeName);
                            ?>  
                        </td>
                    </tr>

                    <tr height="30">
                        <td>
                            Department
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?= $employeeDetail['DEPARTMENT']; ?>
                        </td>
                    </tr>
                    <tr height="30">
                        <td>
                            Appraisal Period
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?= $assignedAppraisalDetail['START_DATE']; ?>
                            To
                            <?= $assignedAppraisalDetail['END_DATE']; ?>
                        </td>
                    </tr>
                    <tr height="30" id="availableDaysText">
                        <td>
                            Appraiser's Name
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            $middleName_A = ($assignedAppraisalDetail['MIDDLE_NAME_A'] == null || $assignedAppraisalDetail['MIDDLE_NAME_A'] == "") ? " " : " " . $assignedAppraisalDetail['MIDDLE_NAME_A'] . " ";
                            $employeeName_A = $assignedAppraisalDetail['FIRST_NAME_A'] . $middleName_A . $assignedAppraisalDetail['LAST_NAME_A'];
                            print_r($employeeName_A);
                            ?>       
                        </td>
                    </tr>
                    <tr height="30" id="availableDaysText">
                        <td>
                            Appraiser's Position
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            print_r($assignedAppraisalDetail['POSITION_NAME_A']);
                            ?>       
                        </td>
                    </tr>
                </tbody></table>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <table>
                <tbody>
                    <tr height="30">
                        <td>
                            Position
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?= $employeeDetail['POSITION']; ?>
                        </td>
                    </tr>
                    <tr height="30">
                        <td>
                            Designation
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?= $employeeDetail['DESIGNATION']; ?>  
                        </td>
                    </tr>
                    <tr height="30" id="availableDaysText">
                        <td>
                            Previous Appraisal Period
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            print_r($assignedAppraisalDetail['PREVIOUS_REVIEW_PERIOD']);
                            ?>       
                        </td>
                    </tr>
                    <tr height="30">
                        <td>
                            Reviewer's Name
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            $middleName_R = ($assignedAppraisalDetail['MIDDLE_NAME_R'] == null || $assignedAppraisalDetail['MIDDLE_NAME_R'] == "") ? " " : " " . $assignedAppraisalDetail['MIDDLE_NAME_R'] . " ";
                            $employeeName_R = $assignedAppraisalDetail['FIRST_NAME_R'] . $middleName_R . $assignedAppraisalDetail['LAST_NAME_R'];
                            print_r($employeeName_R);
                            ?>                                         
                        </td>
                    </tr>
                    <tr height="30" id="availableDaysText">
                        <td>
                            Reviewer's Position
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            print_r($assignedAppraisalDetail['POSITION_NAME_R']);
                            ?>       
                        </td>
                    </tr>
                </tbody></table>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <table>
                <tbody>
                    <tr height="30">
                        <td>
                            Branch
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?= $employeeDetail['BRANCH']; ?>
                        </td>
                    </tr>
                    <tr height="30">
                        <td>
                            Joining Date
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?= $employeeDetail['JOIN_DATE']; ?>  
                        </td>
                    </tr>
                    <tr height="30" id="availableDaysText">
                        <td>
                            Previous Rating
                        </td>
                        <td width="15">:</td>
                        <td>
                            <?php
                            print_r($assignedAppraisalDetail['PREVIOUS_RATING']);
                            ?>       
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
