<div class="margin-top-30 <?= ($assignedAppraisalDetail['KPI_SETTING'] == 'Y' || $assignedAppraisalDetail['COMPETENCIES_SETTING'] == 'Y') ? 'display-block' : 'display-none'; ?> appRemarks">
    <table class="table table-bordered" id="dataTables-examp">
        <tr>
            <td class="label" style="color:#428bca;font:bold;"><b>Remarks</b></td>
        </tr>
        <tr>
            <td>
                <p style="width:400px;height:50px;color:black;font-size:10px;">
                    (Please comment below indicating how much you see the Appraisee's work.
                    If you have ticked the No box you must discuss your views with the Appraisee
                    and the Appraiser.)

                </p>
            </td>
        </tr>
    </table>
</div>
