<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveapply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/LeaveManagement/leave-deduction/add.js'))
        ->appendFile($this->basePath('dropzone/dropzone.min.js'));
?>

<?php
$form->setAttribute('leaveDeduction', 'form');
$deductionDt = $form->get('deductionDt');
$noOfDays = $form->get('noOfDays');
$remarks = $form->get('remarks');
$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Deduct Leave');
$submit->setAttribute('id', 'request');

$form->setAttribute('action', $this->url('leavededuction', ['action' => 'add']));
$form->prepare();
print $this->form()->openTag($form);
?> 
<script>
    document.wsPullLeaveDetailWidEmployeeId = '<?= $this->url("leavededuction", ["action" => "pullLeaveDetailWidEmployeeId"]) ?>';
    document.wsPullLeaveDetail = '<?= $this->url("leavededuction", ["action" => "pullLeaveDetail"]) ?>';
</script>

<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption"> 
                    <i class="fa fa-user"></i>
                    Apply For Leave
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($employeeId->getMessages()) ? "" : "error" ?> ">
                            <?php print $this->formLabel($employeeId) ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="employeeId" id="employeeId" required="required"  class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                                <?php foreach ($employees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                <?php } ?>
                            </select>
                        </div>
                        <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block error']); ?> 
                    </div>
                </div>
                
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="leaveId">Leave Type</label>
                            <span class="required" aria-required="true">*</span>
                            <select name="leaveId" required="required" id="leaveId" class="form-control">
                                <option value="" disabled="" selected="" >Please select</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group disabled">
                            <label for="leaveId">Available Days</label>
                            <input type="text" READONLY name="availableDays"  required="required" id="availableDays"  class="form-control"  value="">
                            <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                        </div>
                    </div> 

                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group required  <?= empty($deductionDt->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($deductionDt) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($deductionDt) ?>
                                </div>
                                <?php print $this->formElementErrors()->render($deductionDt, ['class' => 'help-block error']) ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                           class="form-control" value="">
                                </div>
                            </div>     
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($noOfDays); ?>
                            <span class="required" aria-required="true"></span>
                            <?php print $this->formElement($noOfDays); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                            <span id="halfDayMsg" style="font-size:12px; color:green; font-weight: bold"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group padding-0" id="remarks">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                    </div>

                </div> 
                <?php print $this->formSubmit($submit); ?>
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>
