<?php
$this->headScript()->appendFile($this->basePath('plugins/bootstrap-timepicker/bootstrap-timepicker.min.js'));
$this->headScript()->appendFile($this->basePath('js/attendance/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceByHr-form');

$attendanceDt = $form->get('attendanceDt');
$inTime = $form->get('inTime');
$outTime = $form->get('outTime');
$inRemarks = $form->get('inRemarks');
$outRemarks = $form->get('outRemarks');
$totalHour = $form->get('totalHour');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('myattendance', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuMyAttendance"]];echo json_encode($menu);?>;
</script>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading bg-master-lighter">
                <div class="panel-title">
                    <h3 class="panel-title">Attendance Entry</h3>
                </div>
            </div>
            <div class="panel-body p-t-5">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group form-group-sm <?= empty($attendanceDt->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($attendanceDt); ?>
                    <?php print $this->formElement($attendanceDt); ?>
                </div>
                <?php print $this->formElementErrors()->render($attendanceDt, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm  <?= empty($inTime->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($inTime); ?>
                    <?php print $this->formElement($inTime); ?>
                </div>
                <?php print $this->formElementErrors()->render($inTime, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($outTime->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($outTime); ?>
                    <?php print $this->formElement($outTime); ?>
                </div>
                <?php print $this->formElementErrors()->render($outTime, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($inRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($inRemarks); ?>
                    <?php print $this->formElement($inRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($inRemarks, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($outRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($outRemarks); ?>
                    <?php print $this->formElement($outRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($outRemarks, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($totalHour->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($totalHour); ?>
                    <?php print $this->formElement($totalHour); ?>
                </div>
                <?php print $this->formElementErrors()->render($totalHour, ['class' => 'help-block error']); ?>


                <div class="">
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>
