<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/attendance/index.js'));
?>

<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuMyAttendance"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\myattendance')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="attendanceController">
    <div class="margin-top-20">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="input-group date" id="fromDate">
                                <input type="text" placeholder="From Date" id="fromDate1" name="fromDate" ng-model="fromDate" class="form-control"/>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="input-group date" id="toDate">
                                <input type="text" placeholder="To Date" id="toDate1" name="toDate" ng-model="toDate" class="form-control"/>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                            <input type="hidden" name="employeeId" ng-model="employeeId" id="employeeId" value="<?php echo $employeeId; ?>"/>
                        </div>
                        <div class="col-md-2">
                            <button ng-click="view()" id="myAttendance" class="btn btn-success">
                                VIEW
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="btn-group pull-right">
                        <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;"> Print </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Save as PDF </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Export to Excel </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="attendanceTable">
        </div>
        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
                <td>
                #: (ATTENDANCE_DT == null) ? '-' : ATTENDANCE_DT #
                </td>
                <td>    
                #: (IN_TIME == null) ? '-' : IN_TIME #
                </td>
                <td>
                #: (OUT_TIME == null) ? '-' : OUT_TIME #
                </td>
                <td>
                #: (TOTAL_HOUR == null) ? '-' : TOTAL_HOUR #
                </td>
                <td>
                #: (IN_REMARKS == null) ? '-' : IN_REMARKS #
                </td>
                <td>
                #: (OUT_REMARKS == null) ? '-' : OUT_REMARKS #
                </td>
            </tr>
        </script>
    </div>
</div>