<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/setup/service-question/index.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.editLink = '<?= $this->url("serviceQuestion", ["action" => "edit"]); ?>';
    document.deleteLink = '<?= $this->url("serviceQuestion", ["action" => "delete"]); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\serviceQuestion')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">

    <div class="portlet light bg-inverse">

        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <?php if ($acl['ALLOW_ADD'] == 'Y'): ?>
                    <a href="<?= $this->url('serviceQuestion', ['action' => 'add']) ?>" class="btn default btn-sm">
                        <i class="fa fa-plus-square icon-black"></i>
                        New 
                    </a>
                <?php endif; ?>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="serviceQuestionTable">

        </div>
    </div>
    <!--
    
    
        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
            <td>                 
            #: (QUESTION_EDESC == null) ? '-' : QUESTION_            EDESC #
            </td>
            <td>                 
            #: (PARENT_QUESTION_EDESC == null) ? '-' : PARENT_QUESTION_            EDESC #
            </td>
            <td>    
            #: (SERVICE_EVENT_TYPE_NAME == null) ? '-' : SERVICE_EVENT_TYPE_NAM            E #
            </            td>
            <td>    
            #: (QA_INDEX == null) ? '-' : QA_INDEX #
            </            td>
            <td>
            <a class="btn-edit"
            href="/#:QA_ID#" style="height:17px;">
            <i clas                        s="fa fa-edit                        "></i>
            </a>
            <a class="btn-delete confirmation"
            href="/#:QA_ID#" id="bs_#:QA_ID #" style="                            height:17px;"> 
            <i class="fa fa-trash-o"></i><                /a>
            </a>
            </td            >
            </tr>
        </script>-->
</div>
