<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
    ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/table2excel/src/jquery.table2excel.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/branch-wise-daily.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.wsBranchWiseDailyReport = '<?php echo $this->url('allreport', ['action' => 'branchWiseDailyReport']); ?>';
    document.comBraDepList =<?php echo json_encode($comBraList); ?>;
    document.monthId =<?php echo $monthId; ?>;
    document.branchId =<?php echo $branchId; ?>;
    document.name ='<?php echo $name; ?>';
    document.getFiscalYearMonthLink = '<?php echo $this->url('allreport', ['action' => 'getFiscalYearMonth']); ?>';
document.preference =<?php echo json_encode($preference) ?>;
</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>



<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <div class="indicator">
                <ul>
                    <li>
                        <div class="indicator-box indicator-color-present"></div> 
                        <span>Present</span>
                    </li>
                    <li>
                        <div class="indicator-box indicator-color-Absent"> </div>   
                        <span>Absent</span>
                    </li>
                    <li>
                        <div class="indicator-box indicator-color-leave"> </div> 
                        <span>leave</span>
                    </li>
                </ul>
            </div>
        </div>

        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li >
                        <a id="excelExport" href="javascript:;"  >
                            <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="actions">
            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Company</label>
                <select multiple class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Branch</label>
                <select multiple class="form-control" name="branchId" id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Department</label>
                <select multiple class="form-control" name="department" id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Designation</label>
                <select multiple class="form-control" name="designation" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Position</label>
                <select multiple class="form-control" name="position" id="positionId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Service Type</label>
                <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Service Event Type</label>
                <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee Type</label>
                <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Functional Type</label>
                <select multiple class="form-control" name="functionalType" id="functionalTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee</label>
                <select multiple class="form-control" name="employee" id="employeeId">
                </select>
            </div>

        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <select class="form-control"  id="fiscalYear" >
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control" id="fiscalMonth" >
                </select>
            </div>
<!--            <div class="  col-sm-3  bottomgap">-->
<!--               <select id="branchList">-->
<!---->
<!--                </select> -->
<!--            </div>-->
            <div class=" col-sm-3 bottomgap">
                <button id="generateReport" class="btn btn-block btn-customized">
                    Generate Report
                </button>

            </div>
        </div>
        <div class=" col-sm-3 bottomgap">
            <button id="printAsPDF" style="border-radius: 20px;" class="btn btn-sm blue-soft">PRINT</button>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div id="reportTable" class="kendo-report" style="overflow-x: auto;">
                </div>
            </div>
        </div>
    </div>
</div>


