<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/reportthree.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.wsDepartmentWiseDailyReport = '<?php echo $this->url('allreport', ['action' => 'departmentWiseDailyReport']); ?>';
    document.comBraDepList =<?php echo json_encode($comBraDepList); ?>;
    document.monthId =<?php echo $monthId; ?>;
    document.departmentId =<?php echo $departmentId; ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('allreport', ['action' => 'getFiscalYearMonth']); ?>';

</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>



<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <div class="indicator">
                <ul>
                    <li>
                        <div class="indicator-box indicator-color-present"></div> 
                        <span>Present</span>
                    </li>
                    <li>
                        <div class="indicator-box indicator-color-Absent"> </div>   
                        <span>Absent</span>
                    </li>
                    <li>
                        <div class="indicator-box indicator-color-leave"> </div> 
                        <span>leave</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="actions">
            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body">

        <div class="row margin-top-10">
            <div class="col-sm-2">
                <select class="form-control"  id="fiscalYear" >
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control" id="fiscalMonth" >
                </select>
            </div>
            <div class="  col-sm-3  bottomgap">
                <select id="departmentList">
                </select> 
            </div>
            <div class=" col-sm-3 bottomgap">
                <button id="generateReport" class="btn btn-block btn-customized">
                    Generate Report
                </button>

            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div id="reportTable" class="kendo-report">
                </div>
            </div>
        </div>

    </div>
</div>


