<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/reportthree.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.wsDepartmentWiseDailyReport = '<?php echo $this->url('allreport', ['action' => 'departmentWiseDailyReport']); ?>';
    document.comBraDepList =<?php echo json_encode($comBraDepList); ?>;
    document.monthList =<?php echo json_encode($monthList); ?>;
    document.monthId =<?php echo $monthId; ?>;
    document.departmentId =<?php echo $departmentId; ?>;

</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="">
    <div class="portlet solid default1 borderline1 shadow1 boxshadow gapboth">
        <div class="portlet-title border-bottom">
            <div class="caption">
                <i class="icon-filter"></i>
                <span class="caption-subject bold uppercase"> Filter</span>
                <span class="caption-helper">options...</span>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-3">
                    <select id="monthList" class="">

                    </select> 
                </div>
                <div class="col-sm-2">
                    <select id="countryList">

                    </select> 
                </div>
                <div class="col-sm-2">
                    <select id="branchList">

                    </select> 

                </div>
                <div class="col-sm-2">
                    <select id="departmentList">

                    </select> 

                </div>
                <div class="col-sm-2">
                    <button id="generateReport" class="btn btn-block btn-customized">
                        Generate Report
                    </button>

                </div>

            </div>
        </div>
    </div>
</div>
<div class="indicator">
    <ul>
        <li>
            <div class="indicator-box indicator-color-present"></div> 
            <span>Present</span>
        </li>
        <li>
            <div class="indicator-box indicator-color-Absent"> </div>   
            <span>Absent</span>
        </li>


        <li>
            <div class="indicator-box indicator-color-leave"> </div> 
            <span>leave</span>
        </li>


    </ul>
</div>
<div id="reportTable">
</div>
