<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/reporttwo.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>;
    </script>
<?php } ?>

<script>
    document.wsDepartmentWise = '<?php echo $this->url('allreport', ['action' => 'departmentWiseMonthReport']); ?>';
    document.comBraDepList =<?php echo json_encode($comBraDepList); ?>;
    document.departmentId =<?php echo $departmentId; ?>;
    document.linkToReportFour = '<?php echo $this->url('allreport', ['action' => 'employeeWise']); ?>';
</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
        <div class="tools indicator">
            <ul>
                <li>
                    <div class="indicator-box indicator-color-present"></div> 
                    <span>Present</span>
                </li>
                <li>
                    <div class="indicator-box indicator-color-Absent"> </div>   
                    <span>Absent</span>
                </li>
                <li>
                    <div class="indicator-box indicator-color-leave"> </div> 
                    <span>leave</span>
                </li>
            </ul>
        </div>
        <div class="actions">
            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>

    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-3">
                <select id="companyList">

                </select> 
            </div>
            <div class="col-sm-3">
                <select id="branchList">

                </select> 
            </div>
            <div class="col-sm-3">
                <select id="departmentList">
                </select> 
            </div>
            <div class="col-sm-3">
                <button id="generateReport" class="btn btn-block btn-sm btn-customized pull-right">
                    Generate Report
                </button>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-12">
                <div id="departmentMonthReport">
                </div>
            </div>
        </div>

    </div>
</div>
