<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/Report/AllReport/leaveReport.js'));
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.getLeaveReportWS = '<?= $this->url("allreport", ["action" => "getLeaveReportWS"]) ?>';
    document.allLeave = <?php echo json_encode($allLeave) ?>;
    document.ids=<?php echo json_encode(["fromDate"=>"","nepaliFromDate"=>"","toDate"=>"","nepaliToDate"=>""]) ?>;
    document.preference =<?php echo json_encode($preference) ?>;
</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li >
                        <a id="export" href="javascript:;" class="hris-export-to-excel" hris-export-to-excel-target="leaveReportTable">
                            <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                 <?php print $this->formElement($customWise); ?>
            </div>
        </div>
        <div id="EmpOptionsDiv">
            <div class="row margin-top-10">
            <div class="col-sm-2">
                <select class="form-control"  id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control"  id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control"  id="positionId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <select class="form-control"  id="serviceTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control"  id="serviceEventTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control"  id="employeeTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control"  id="employeeId">
                </select>
            </div>

        </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="fromDate" name="fromDate"  class="form-control reset-field" placeholder="From Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control reset-field" placeholder="From Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="toDate" name="toDate"  class="form-control reset-field" placeholder="To Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control reset-field" placeholder="To Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-4">
                <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button  id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>

    </div>
</div>

<div id="leaveReportTable">
</div>