<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/reporttwo.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/jquery.blockui.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>;
    </script>
<?php } ?>

<script>
    document.wsDepartmentWise = '<?php echo $this->url('allreport', ['action' => 'departmentWiseMonthReport']); ?>';
    document.comBraDepList =<?php echo json_encode($comBraDepList); ?>;
</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="">
    <div class="portlet solid default borderline shadow">
        <div class="portlet-title border-bottom">
            <div class="caption">
                <i class="icon-filter"></i>
                <span class="caption-subject bold uppercase"> Filter</span>
                <span class="caption-helper">options...</span>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-3">
                    <select id="countryList">

                    </select> 
                </div>
                <div class="col-sm-3">
                    <select id="branchList">

                    </select> 

                </div>
                <div class="col-sm-3">
                    <select id="departmentList">

                    </select> 

                </div>
                <div class="col-sm-3">
                    <button id="generateReport" class="btn btn-block">
                        Generate Report
                    </button>

                </div>

            </div>
        </div>
    </div>
</div>
<div id="departmentMonthReport">
</div>
