<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/reportone.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/jquery.blockui.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.wsUrl = '<?php echo $this->url('allreport', ['action' => 'departmentMonthReport']); ?>';
    document.wsDepartmentWise = '<?php echo $this->url('allreport', ['action' => 'departmentWiseMonthReport']); ?>';
    document.linkToReportTwo = '<?php echo $this->url('allreport', ['action' => 'reportTwo']); ?>';
    document.linkToReportThree = '<?php echo $this->url('allreport', ['action' => 'reportThree']); ?>';
    document.linkToReportFour = '<?php echo $this->url('allreport', ['action' => 'reportFour']); ?>';
</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div id="departmentMonthReport">
</div>
