<style>
    .btn.green:not(.btn-outline), .green {
        background-color: #63AB6A !important;
        border-color: #63AB6A !important;
    }
    abbr[title] {
        border-bottom: none !important;
        cursor: inherit !important;
        text-decoration: none !important;
    }
</style>
<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/search.js'));
$this->headScript()->appendFile($this->basePath('js/Report/AllReport/whereabouts-report.js'));

?>
<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.getWhereabouts = "<?php echo $this->url('allreport', ['action' => 'whereabouts']);?>";
    document.preference =<?php echo json_encode($preference) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\overtime-report')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="row">
    <div class="col-sm-12 ">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption"> Search Filter</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                    <a href="" class="fullscreen" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body hris-filter-container" style="display: block;">
                <div class="row">
                    <div class="col-sm-2">
                        <label>Company</label>
                        <select multiple class="form-control" name="company" id="companyId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Branch</label>
                        <select multiple class="form-control" name="branchId" id="branchId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Department</label>
                        <select multiple class="form-control" name="department" id="departmentId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Designation</label>
                        <select multiple class="form-control" name="designation" id="designationId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Position</label>
                        <select multiple class="form-control" name="position" id="positionId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Service Type</label>
                        <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                        </select>
                    </div>
                </div>
                <div class="row margin-top-10">
                    <div class="col-sm-2">
                        <label>Service Event Type</label>
                        <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee Type</label>
                        <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Gender</label>
                        <select multiple class="form-control" name="gender" id="genderId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Location</label>
                        <select multiple class="form-control" name="location" id="locationId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee</label>
                        <select multiple class="form-control" name="employee" id="employeeId">
                        </select>
                    </div>
                </div>

                <div class="row margin-top-10">
                    <div class="col-sm-2">
                        <input type="text" id="fromDate" name="fromDate"  class="form-control reset-field" placeholder="From Date"/>
                    </div>
                    <div class="col-sm-2">
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate"  class="form-control reset-field" placeholder="From Date Nepali"/>

                    </div>
                    <div class="col-sm-2">
                        <input type="text"  id="toDate" name="toDate"  class="form-control reset-field" placeholder="To Date"/>
                    </div>
                    <div class="col-sm-2">
                        <input type="text"  id="nepaliToDate" name="nepaliToDate" class="form-control reset-field" placeholder="To Date Nepali"/>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                            Reset
                            <i class="fa fa-refresh"></i>
                        </button>
                        <button id="search" class="btn btn-default btn-sm pull-right">
                            Search
                            <i class="fa fa-search"></i>
                        </button>  
                    </div>
                </div>
            </div>
        </div>
        <div class="portlet box ">
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div id="report">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>