<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/Report/AllReport/withOvertimeBot.js'));
$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
?>
<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('allreport', ['action' => 'getFiscalYearMonth']); ?>';
    document.linkToEmpower =<?php echo $linkToEmpower; ?>;
    document.withOvertimeWs = '<?php echo $this->url('allreport', ['action' => 'withOvertimeBot']); ?>';
    document.toEmpowerLink = '<?php echo $this->url('allreport', ['action' => 'toEmpower']); ?>';
    document.loadDataLink = '<?php echo $this->url('allreport', ['action' => 'loadData']); ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\allreport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li >
                        <a id="export" href="javascript:;" class="hris-export-to-excel" hris-export-to-excel-target="withOTReport">
                            <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Company</label>
                <select multiple class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Branch</label>
                <select multiple class="form-control" name="branchId" id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Department</label>
                <select multiple class="form-control" name="department" id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Designation</label>
                <select multiple class="form-control" name="designation" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Grade</label>
                <select multiple class="form-control" name="position" id="positionId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Service Type</label>
                <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Service Event Type</label>
                <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee Type</label>
                <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Gender</label>
                <select multiple class="form-control" name="gender" id="genderId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Location</label>
                <select multiple class="form-control" name="location" id="locationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee</label>
                <select multiple class="form-control" name="employee" id="employeeId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <select class="form-control"  id="fiscalYearId" >
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control" id="monthId" >
                </select>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="fromDate" name="fromDate"  class="form-control" placeholder="From Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="toDate" name="toDate"  class="form-control" placeholder="To Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-2"></div>
            <!-- <div class="col-sm-2">
                <button  id="loadData" class="btn btn-default btn-link">
                    Load Data
                    <i class="fa fa-copy"></i>
                </button>

            </div> -->
            <!--
            <div class="col-sm-2">
                <button  id="confirm" class="btn btn-default btn-link">
                    Confirm By HR
                    <i class="fa fa-check"></i>
                </button>

            </div>  
            --> 
            <div class="col-sm-4 col-sm-offset-4">
                <button class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button  id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>

    </div>
</div>

<div id="withOTReport">
</div>