<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/work-on-holiday/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'holidayWorkApprove-form');

$holidayId = $form->get('holidayId');
$holidayId->setValueOptions($holidays);
$holidayId->setAttributes(["disabled"=>"disabled"]);
$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled"=>"disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled"=>"disabled"]);
$duration = $form->get('duration');
$duration->setAttributes(["disabled"=>"disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled"=>"disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['required'=>'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required'=>'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('holidayWorkApprove', ['action' => 'view', 'id' => $id, 'role' => $role]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuManagerService","subMenu"=>["id"=>"subMenuHolidayWorktoApprove"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holidayWorkApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Work on Holiday Request Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="border-bottom">
                <div class="form-group">
                    <div class="row div-font-11">
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Employee Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $employeeName; ?>
                                    </td>
                                </tr>
                                
                                <tr height="30">
                                    <td>
                                        Your Role
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php if ($role == 3) {
                                                echo 'Approver';
                                            } else if ($role == 2) {
                                                echo 'Recommender';
                                            }else if($role==4){
                                                echo 'Recommender\Approver';
                                            } ?>
                                    </td>
                                </tr>                               
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>  
                                <tr height="30">
                                    <td>
                                        Requested Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $requestedDate; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Status
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        if ($status == 'RQ') {
                                            echo "Pending";
                                        } else if ($status == 'RC') {
                                            echo "Recommended";
                                        } else if ($status == 'AP') {
                                            echo "Approved";
                                        } else if ($status == "R") {
                                            echo "Rejected";
                                        } else if ($status == "C") {
                                            echo "Cancelled";
                                        } ?>
                                    </td>
                                </tr>
                                <?php if($role!=4){ ?>
                                <tr height="30">
                                    <td>
                                        <?= ($role==3)? "Recommender":"Approver"; ?>
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= ($role==3)? $recommender:$approver; ?>
                                    </td>
                                </tr> 
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($holidayId); ?>
                    <?php print $this->formElement($holidayId); ?>
                    <?php print $this->formElementErrors()->render($holidayId, ['class' => 'help-block']); ?>
                </div>               
                <div
                    class="form-group required  <?= empty($fromDate->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($fromDate) ?>
                    <?php print $this->formElement($fromDate) ?>
                </div>
                <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block error']) ?>

                <div
                    class="form-group required <?= empty($toDate->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($toDate) ?>
                    <?php print $this->formElement($toDate) ?>
                    <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block error']) ?>
                
                <div
                    class="form-group required <?= empty($duration->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($duration); ?>
                    <?php print $this->formElement($duration); ?>
                    <span id="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>

                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                </div>     
                <?php if ($role == 2) { ?>
                    <div
                        class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($recommendedRemarks); ?>
                        <?php print $this->formElement($recommendedRemarks); ?>
                    </div>
                <?php } ?>
                <?php  if($role==2 && ($status=='AP' || ($status=='R' && $approvedDT!=null))){ ?>
                    <div
                        class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                        <label>Reason for action [From Approver]</label>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php }  ?>

                <?php if ($role == 3 || $role==4) {
                        $recommendedRemarks->setAttributes(['disabled'=>'disabled']);
                        ?>
                    <?php if($role!=4){ ?>
                        <div
                            class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                            <label>Reason for action [From Recommender]</label>
                            <?php print $this->formElement($recommendedRemarks); ?>
                        </div>
                    <?php } ?>
                    <div
                        class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($approvedRemarks); ?>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php } ?>

                <?php
                if ($status == 'RQ' || ($status == 'RC' && $employeeId != $recommendedBy)) {
                    print $this->formSubmit($submit);
                    ?>
                    <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                <?php } ?>

            </div>

        </div>
    </div>
</div>

<?php

print $this->form()->closeTag();

?>