<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/print.js'))
        ->appendFile($this->basePath('js/manager-service/travel-approve/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelApprove-form');


$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setValue($detail['RECOMMENDED_REMARKS']);
$recommendedRemarks->setAttributes(['required' => 'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setValue($detail['APPROVED_REMARKS']);
$approvedRemarks->setAttributes(['required' => 'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');
$submit->setAttribute('id','approve');

$form->setAttribute('action', $this->url('travelApprove', ['action' => 'view', 'id' => $id, 'role' => $role]));

$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
    document.urlExpenseDetailList = '<?= $this->url("travelRequest", ["action" => "expenseDetailList"]) ?>';
</script>
<div ng-app="hris" ng-controller="printController">
    <div class="row margin-top-20">  
        <div class="col-sm-12">    
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>Travel Request Detail
                    </div>
                </div>
                <div class="portlet-body div-font-11">
                    <input type="hidden" id="travelId" value="<?php echo $id; ?>" />
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="travelCode">Employee Name : </label>
                                    </td>
                                    <td> <?php echo $employeeName; ?></td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="travelCode">Your Role : </label>
                                    </td>
                                    <td> <?php
                                        if ($role == 3) {
                                            echo 'Approver';
                                        } else if ($role == 2) {
                                            echo 'Recommender';
                                        } else if ($role == 4) {
                                            echo 'Recommender\Approver';
                                        }
                                        ?> 
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <?php if ($role != 4) { ?>
                                    <tr>
                                        <td>
                                            <?= ($role == 3) ? "Recommender" : "Approver"; ?> : 
                                        </td>
                                        <td>
                                            <?= ($role == 3) ? $recommender : $approver; ?>
                                        </td>
                                    </tr>     
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="travelCode">Travel Code :</label></td>
                                    <td><input type="text" disabled="disabled" value="<?php echo $detail['TRAVEL_CODE']; ?>" name="travelCode" id="travelCode" class="form-control"></td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="advanceAmount">Advance Amount :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $advanceAmt; ?>" name="advanceAmount" id="advanceAmount" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="destination">Destination :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['DESTINATION'] ?>" name="destination"  id="destination" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="purpose">Purpose :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['PURPOSE']; ?>" name="purpose"  id="purpose" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="departureDate">Departure Date :</label>
                                    </td>
                                    <td>
                                        <input  type="text" disabled="disabled" value="<?php echo $detail['DEPARTURE_DATE']; ?>" name="departureDate" id="departureDate" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="employeeCode">Returned Date :</label> 
                                    </td>
                                    <td>
                                        <input  value="<?php echo $detail['RETURNED_DATE']; ?>" type="text"  disabled="disabled" name="returnedDate" id="returnedDate" class="form-control"> 
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="advanceAmount">Requested Date :</label> 
                                    </td>
                                    <td>
                                        <input  value="<?php echo $requestedDate; ?>" type="text"  disabled="disabled" name="returnedDate" id="returnedDate" class="form-control"> 
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="destination">Status :</label> 
                                    </td>
                                    <td>
                                        <?php
                                        if ($status == 'RQ') {
                                            $currentStatus = "Pending";
                                        } else if ($status == 'RC') {
                                            $currentStatus = "Recommended";
                                        } else if ($status == 'AP') {
                                            $currentStatus = "Approved";
                                        } else if ($status == "R") {
                                            $currentStatus = "Rejected";
                                        } else if ($status == "C") {
                                            $currentStatus = "Cancelled";
                                        }else if($status=='CS'){
                                            $currentStatus = "Check Settlement";
                                        }else if($status=='SC'){
                                            $currentStatus = 'Settlement Checked';
                                        }
                                        ?>
                                        <input  value="<?php echo $currentStatus; ?>" type="text" disabled="disabled" name="returnedDate" id="returnedDate" class="form-control"> 
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%"><label for="form-approver">Approver :</label></td>  
                                    <td>
                                        <div class="md-radio-inline">
                                            <div class="md-radio"><input disabled="disabled" <?= ($detail['APPROVER_ROLE']=='CEO')?"checked":"" ?> type="radio" value="CEO" name="approverRole" id="approverRole+CEO" class="md-radiobtn radioButton approverRole"><label for="approverRole+CEO">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> CEO
                                                </label>
                                            </div>
                                            <div class="md-radio"><input disabled="disabled" <?= ($detail['APPROVER_ROLE']=='DCEO')?"checked":"" ?> type="radio" value="DCEO" name="approverRole" id="approverRole+DCEO" class="md-radiobtn radioButton approverRole"><label for="approverRole+DCEO">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> DCEO
                                                </label>
                                            </div>                            
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="margin-top-10 scrollbar-horizantal">
                        <table width="100%" align="center" class="table table-striped table-bordered table-hover no-footer customTable div-font-11">
                            <thead style="font-size:11px !important;">
                                <tr>
                                    <th colspan="6" align="center">Description of Travel and Place</th>
                                    <th rowspan="3">Mode of Travel</th>
                                    <th rowspan="3">Fare</th>
                                    <th rowspan="3">Daily Allowance</th>
                                    <th rowspan="3">Local Conveyence</th>
                                    <th rowspan="3">Misc. Expenses</th>
                                    <?php if($status=='SC'){ ?>
                                        <th rowspan="3">Total</th>
                                    <?php } ?>
                                    <th rowspan="3">Remarks</th>
                                </tr>
                                <tr>
                                    <th colspan="3">Departure</th>
                                    <th colspan="3">Destination</th>
                                </tr>
                                <tr>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Place</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Place</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($expenseDtlList as $expenseDtlRow) { ?>
                                    <tr>
                                        <td>
                                            <input type="text" value="<?= $expenseDtlRow['DEPARTURE_DATE']; ?>"  readonly="readonly" name="departureDate" size="13"/>
                                        </td>
                                        <td>
                                            <input type="text"  value="<?= $expenseDtlRow['DEPARTURE_TIME']; ?>" readonly="readonly" name="departureTime"  size="9" />
                                        </td>
                                        <td>
                                            <input type="text" value="<?= $expenseDtlRow['DEPARTURE_PLACE']; ?>"  readonly="readonly" name="departurePlace" size="11"/>
                                        </td>
                                        <td>
                                            <input  type="text" value="<?= $expenseDtlRow['DESTINATION_DATE']; ?>"   readonly="readonly" name="destinationDate" size="13"/>
                                        </td>
                                        <td>
                                            <input type="text" value="<?= $expenseDtlRow['DESTINATION_TIME']; ?>"  readonly="readonly" name="destinationTime" size="9"/>
                                        </td>
                                        <td>
                                            <input type="text" value="<?= $expenseDtlRow['DESTINATION_PLACE']; ?>"  readonly="readonly" name="destinationPlace" size="11"/>
                                        </td>
                                        <td>
                                            <select style="width: 110px;" class="form-control" name="transportType"  disabled="disabled" id="transportType" >
                                                <?php
                                                foreach ($transportType as $key => $value) {
                                                    $selected = ($key == $expenseDtlRow['TRANSPORT_TYPE']) ? "selected" : "";
                                                    ?>
                                                    <option value="<?= $key; ?>" <?= $selected; ?>><?= $value; ?></option>
                                                <?php } ?>
                                            </select>
                                        </td>
                                        <td>
                                            <?php if($status=='SC' && $expenseDtlRow['FARE_FLAG']=='Y'){ ?>
                                                <input type="number" value="<?= $expenseDtlRow['FARE']; ?>" readonly="readonly" name="fare" style="width: 60px;" step="0.01" min="0"/>
                                            <?php }else if($status!='SC'){  ?>
                                            <div class="md-checkbox pull-right">
                                                <input type="checkbox" id="fareFlag" name="fareFlag" disabled="disabled" <?=($expenseDtlRow['FARE_FLAG']=='Y')?"checked":""; ?> class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                                <label for="fareFlag">
                                                    <span class="inc"></span>
                                                    <span class="check"></span>
                                                    <span class="box"></span></label>
                                            </div>
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <?php if($status=='SC' && $expenseDtlRow['ALLOWANCE_FLAG']=='Y'){ ?>
                                                <input type="number" value="<?= $expenseDtlRow['ALLOWANCE']; ?>"  readonly="readonly" style="width: 60px;" step="0.01" min="0"/>
                                            <?php }else if($status!='SC'){  ?>
                                            <div class="md-checkbox pull-right">
                                                <input type="checkbox" id="fareFlag" name="allowanceFlag" disabled="disabled" <?=($expenseDtlRow['ALLOWANCE_FLAG']=='Y')?"checked":""; ?> class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                                <label for="allowanceFlag">
                                                    <span class="inc"></span>
                                                    <span class="check"></span>
                                                    <span class="box"></span></label>
                                            </div>
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <?php if($status=='SC' && $expenseDtlRow['LOCAL_CONVEYENCE_FLAG']=='Y'){ ?>
                                                <input type="number" value="<?= $expenseDtlRow['LOCAL_CONVEYENCE']; ?>"  readonly="readonly" style="width: 69px;" step="0.01" min="0"/>
                                            <?php }else if($status!='SC'){ ?>
                                            <div class="md-checkbox pull-right">
                                                <input type="checkbox" id="fareFlag" name="localConveyenceFlag" disabled="disabled" <?=($expenseDtlRow['LOCAL_CONVEYENCE_FLAG']=='Y')?"checked":""; ?> class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                                <label for="localConveyenceFlag">
                                                    <span class="inc"></span>
                                                    <span class="check"></span>
                                                    <span class="box"></span></label>
                                            </div>
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <?php if($status=='SC' && $expenseDtlRow['MISC_EXPENSES_FLAG']=='Y'){ ?>
                                                <input type="number" value="<?= $expenseDtlRow['MISC_EXPENSES']; ?>"  readonly="readonly" style="width: 60px;" step="0.01" min="0"/>
                                            <?php }else if($status!='SC'){  ?>
                                            <div class="md-checkbox pull-right">
                                                <input type="checkbox" id="fareFlag" name="miscExpenseFlag" disabled="disabled" <?=($expenseDtlRow['MISC_EXPENSES_FLAG']=='Y')?"checked":""; ?> class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                                <label for="miscExpenseFlag">
                                                    <span class="inc"></span>
                                                    <span class="check"></span>
                                                    <span class="box"></span></label>
                                            </div>
                                            <?php } ?>
                                        </td>
                                        <?php if($status=='SC'){ ?>
                                            <td>
                                                <input type="number" value="<?= $expenseDtlRow['TOTAL_AMOUNT']; ?>"  id="total"  readonly="readonly" name="total" style="width: 72px;" step="0.01" min="0"/>
                                            </td>
                                        <?php } ?>
                                        <td>
                                            <input type="text" value="<?= $expenseDtlRow['REMARKS']; ?>" readonly="readonly" size="11"/>
                                        </td>
                                    </tr>
                                <?php } ?>
                                <?php if($status=='SC'){ ?>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>
                                        </td>
                                        <td><b>Total:</b></td>
                                        <td>
                                            <input type="number" value="<?= $detail['REQUESTED_AMOUNT']; ?>"  readonly="readonly" id="sumAllTotal" step="0.01" min="0" readonly="readonly" style="width: 72px;" />
                                        </td>
                                        <td>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="submit_button" style="margin-top:2%;">
                        <?php if ($role == 2) { ?>
                            <div
                                class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($recommendedRemarks); ?>
                                    <?php print $this->formElement($recommendedRemarks); ?>
                            </div>
                        <?php } ?>
                        <?php if ($role == 2 && ($status == 'AP' || $status == 'SC' || ($status == 'R' && $approvedDT != null))) { ?>
                            <div
                                class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                                <label>Reason for action [From Approver]</label>
                                <?php print $this->formElement($approvedRemarks); ?>
                            </div>
                        <?php } ?>

                        <?php
                        if ($role == 3 || $role == 4) {
                            $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
                            ?>
                            <?php if ($role != 4) { ?>
                                <div
                                    class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                                    <label>Reason for action [From Recommender]</label>
                                    <?php print $this->formElement($recommendedRemarks); ?>
                                </div>
                            <?php } ?>
                            <div
                                class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($approvedRemarks); ?>
                                    <?php print $this->formElement($approvedRemarks); ?>
                            </div>
                        <?php } ?>

                        <?php
                        if ($status == 'RQ' || ($status == 'RC' && $employeeId != $recommendedBy)) {
                            print $this->formSubmit($submit);
                            ?>
                            <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                        <?php } ?>    
                    </div>

                </div>
            </div>
        </div>
    </div>

    <?php
    print $this->form()->closeTag();
    ?>

    <div class="row">
        <div id="printableArea" class="col-md-8"  style="border:1px solid; display: none;">
            <div class="wrapper">
                <div class="col-sm-8 col-sm-offset-2">
                    <ul id="headingList">
                        <li>
                            <?php if($empDtl['COMPANY_FILE_PATH']!=null || $empDtl['COMPANY_FILE_PATH']!=""){ ?>
                            <img src="<?= $this->basePath() . "/uploads/" . $empDtl['COMPANY_FILE_PATH']; ?>" style="float:left;" height="50" width="50"/>
                            <?php } ?>
                            <h2><?= strtoupper($empDtl['COMPANY_NAME']); ?></h2></li>
                        <li><h3>TRAVEL EXPENSE CLAIM FORM</h3></li>
                    </ul>
                </div>
            </div>
            <div class="wrapper font-common">
                <div class="formNo">
                    <ul>
                        <li>Form No: HRM-10</li>
                    </ul>
                </div>
                <div class="dateDtl">
                    <ul>
                        <li>TECF No:<?= $detail['TRAVEL_CODE']; ?></li>
                        <li>Date: <?php print_r($todayDate); ?></li>
                    </ul>
                </div>
            </div>

            <div class="wrapper font-common">
                <div id="employeeDtl">
                    <ul>
                        <li>
                            Name of Staff: <?= $employeeName; ?>
                        </li>
                        <li>
                            Purpose of Visit: <?= $detail['PURPOSE']; ?>
                        </li>
                        <li>Date of Travel Order: <?= $detail['REQUESTED_DATE']; ?></li>
                    </ul>
                </div>
                <div  id="employeeTrvlDtl">
                    <ul>
                        <li>
                            Designation: <?= $empDtl['DESIGNATION']; ?>
                        </li>
                        <li>
                            Departure Date:<?= $detail['DEPARTURE_DATE']; ?>
                        </li>
                        <li>Returned Date: <?= $detail['RETURNED_DATE']; ?></li>
                    </ul>
                </div>
            </div>

            <div class="wrapper font-common">
                <table id="expenseDtlTbl" width="100%" align="center" class="customTable div-font-11">
                    <thead style="font-size:11px !important;">
                        <tr>
                            <th colspan="6" align="center">Description of Travel and Place</th>
                            <th rowspan="3">Mode of Travel</th>
                            <th rowspan="3">Fare</th>
                            <th rowspan="3">Daily Allowance</th>
                            <th rowspan="3">Local Conveyence</th>
                            <th rowspan="3">Misc. Expenses</th>
                            <th rowspan="3">Total</th>
                            <th rowspan="3" class="lastColumn">Remarks</th>
                        </tr>
                        <tr>
                            <th colspan="3">Departure</th>
                            <th colspan="3">Destination</th>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Place</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Place</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $fare = 0;
                        $allowance = 0;
                        $localConveyence = 0;
                        $miscExpense = 0;
                        $totalAmount = 0;
                        foreach ($expenseDtlList as $expenseDtlRow) {
                            $fare += $expenseDtlRow['FARE'];
                            $allowance += $expenseDtlRow['ALLOWANCE'];
                            $localConveyence += $expenseDtlRow['LOCAL_CONVEYENCE'];
                            $miscExpense += $expenseDtlRow['MISC_EXPENSES'];
                            $totalAmount += $expenseDtlRow['TOTAL_AMOUNT'];
                            ?>
                            <tr>
                                <td>
                                    <?= $expenseDtlRow['DEPARTURE_DATE']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['DEPARTURE_TIME']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['DEPARTURE_PLACE']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['DESTINATION_DATE']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['DESTINATION_TIME']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['DESTINATION_PLACE']; ?>
                                </td>
                                <td>
                                    <?php
                                    foreach ($transportType as $key => $value) {
                                        if ($key == $expenseDtlRow['TRANSPORT_TYPE']) {
                                            echo $value;
                                        }
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['FARE']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['ALLOWANCE']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['LOCAL_CONVEYENCE']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['MISC_EXPENSES']; ?>
                                </td>
                                <td>
                                    <?= $expenseDtlRow['TOTAL_AMOUNT']; ?>
                                </td>
                                <td class="lastColumn"> 
                                    <?= $expenseDtlRow['REMARKS']; ?>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td>Total</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><?= $fare; ?></td>
                            <td><?= $allowance; ?></td>
                            <td><?= $localConveyence; ?></td>
                            <td><?= $miscExpense; ?></td>
                            <td><?= $totalAmount; ?></td>
                            <td class="lastColumn"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="wrapper font-common">
                <div id="employeeDtl1">
                    <ul>
                        <li>Advance taken for travel in Rs. <?= $advanceAmt ?> expenses incured during travel in Rs. <?= $totalAmount; ?>
                            Balance amount after expenses Rs. <?php
                            $balance = $advanceAmt - $totalAmount;
                            echo $balance;
                            ?></li>
                        <li>Total Expenses(in words): <?= $totalExpense; ?> </li>
                    </ul>
                </div>
            </div>

            <div class="wrapper font-common signature">
                <div class="signChecked">
                    <div class="border-dotted">
                        Checked and Found Correct
                    </div>
                </div>
                <div class="signEmployee1">
                    <div class="border-dotted">
                        Signature of Staff
                    </div>
                </div>
                <div class="signRecommender1">
                    <p style="height: {{ hgtRecommender}}px"><label ng-if="signRecommender"><?= ucwords(strtolower($recommender)); ?></label></p>
                    <div class="border-dotted" style="margin-left: 55px;">
                        Recommended By 
                    </div>
                </div>
                <div class="signApprover1">
                    <p style="height: {{ hgtApprover}}px"><label ng-if="signApprover"><?= ucwords(strtolower($approver)); ?></label></p>
                    <div class="border-dotted" style="float:right;">
                        Approved by
                    </div>
                </div>
            </div>

        </div>
        <?php if($status=='SC'){ ?>
            <div class="col-md-12" style="text-align:center;">
                <a class="btn btn-success" ng-click="printDiv('printableArea');"> Print</a>
            </div>
        <?php } ?>
    </div>

</div>