<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
    
<script>
    document.approveRejectUrl = '<?php echo $this->url('travelApprove', ['action' => 'batchApproveReject']); ?>';
</script>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/manager-service/travel-approve/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.deleteURL = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.travelApprove =<?php echo json_encode($travelApprove); ?>
</script>

<div class="margin-top-20">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div style="display: none;" class="row" id="acceptRejectDiv" >
            <div class="col-sm-2">
                <button id="btnApprove" class="btn btn-success btnApproveReject">Approve</button>
            </div>
            <div class="col-sm-2 ">
                <button id="btnReject" class="btn btn-success btnApproveReject">Reject</button>
            </div>
        </div>

    <div id="travelApproveTable">
    </div>
	</div>


    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        <input type='checkbox' id='#:TRAVEL_ID#' role-id='#:ROLE#'  class='k-checkbox row-checkbox'><label class='k-checkbox-label' for='#:TRAVEL_ID#'></label>    
        </td>
        <td>
        #: (FULL_NAME == null) ? ' ' : FULL_NAME #
        </td>
        <td>
        #: (FROM_DATE == null) ? '-' : FROM_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (DESTINATION == null) ? '-' : DESTINATION #
        </td>
        <td>
        #: (REQUESTED_AMOUNT == null) ? '-' : REQUESTED_AMOUNT #
        </td>
        <td>
        #: (REQUESTED_TYPE == null) ? '-' : REQUESTED_TYPE #
        </td>
        <td>
        # if(REQUESTED_TYPE=='Expense'){#
        <a class="btn-edit"
        href="<?= $this->url("travelApprove", ["action" => "expenseDetail"]); ?>/#:TRAVEL_ID #/#:ROLE #" style="height:17px;" title="view">
        <i class="fa fa-search-plus"></i>
        </a>
        # } else { #
        <a class="btn-edit"
        href="<?= $this->url("travelApprove", ["action" => "view"]); ?>/#:TRAVEL_ID #/#:ROLE #" style="height:17px;" title="view">
        <i class="fa fa-search-plus"></i>
        </a>
        # } #
        </td>
        </tr>
    </script>
</div>