<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/manager-service/travel-approve/status.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.ids =<?php echo json_encode(["travelRequestStatusId" => -1, "fromDate" => "", "nepaliFromDate" => "", "toDate" => "", "nepaliToDate" => ""]) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.expenseDetailLink ='<?= $this->url("travelApprove", ["action" => "expenseDetail"]) ?>';
    document.viewLink ='<?= $this->url("travelApprove", ["action" => "view"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="travelStatusListController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Search</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <select class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <select class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2 ">
                    <?php print $this->formElement($travelStatus); ?>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <input type="text" id="fromDate" name="fromDate" ng-model="fromDate" class="form-control" placeholder="From Date"/>
                </div>
                <div class="col-sm-2">
                    <input type="text" id="nepaliFromDate" name="nepaliFromDate"  class="form-control" placeholder="From Date Nepali"/>

                </div>
                <div class="col-sm-2">
                    <input type="text"  id="toDate" name="toDate" ng-model="toDate" class="form-control" placeholder="To Date"/>
                </div>
                <div class="col-sm-2">
                    <input type="text"  id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                </div>
                <input type="hidden" id="recomApproveId" value="<?php echo $recomApproveId; ?>"/>
                <div class="col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button ng-click="view()" id="viewTravelRequestStatus" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="margin-top-20">  

        <div id="travelRequestStatusTable">
        </div>
    </div>
<!--
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (FULL_NAME == null) ? ' ' : FULL_NAME #
        </td>
        <td>
        #: (FROM_DATE == null) ? '-' : FROM_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (DESTINATION == null) ? '-' : DESTINATION #
        </td>
        <td>
        #: (REQUESTED_AMOUNT == null) ? '-' : REQUESTED_AMOUNT #
        </td>
        <td>
        #: (REQUESTED_TYPE == null) ? '-' : REQUESTED_TYPE #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
        # if(REQUESTED_TYPE=='Expense'){#
        <a class="btn-edit"
        href="` + document.expenseDetailLink +`/#:TRAVEL_ID #/#:ROLE #" style="height:17px;" title="view">
        <i class="fa fa-search-plus"></i>
        </a>
        # } else { #
        <a class="btn-edit"
        href="` + document.viewLink + `/#:TRAVEL_ID #/#:ROLE #" style="height:17px;" title="view">
        <i class="fa fa-search-plus"></i>
        </a>
        # } #
        </td>
        </tr>
    </script>-->
</div>
