<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/holiday/add.js'));
?>

<script>
    /*
     * load js vars here
     * */
    document.menu =<?php $menu = ["id" => "menuHolidayManagement", "subMenu" => ["id" => "subMenuHolidaySetup"]];echo json_encode($menu);?>;
</script>

<?php
/*
 * flash message
 * */
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>
<?php

$holidayCode = $form->get('holidayCode');
$genderId = $form->get('genderId');
$branchId = $form->get('branchId');
$holidayEname = $form->get('holidayEname');
$holidayLname = $form->get('holidayLname');
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$halfday = $form->get('halfday');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$genderId->setValueOptions($genders);
$branchId->setValueOptions($branches);
?>

<?php
$form->setAttribute('role', 'form');
$form->setAttribute('action', $this->url('holidaysetup', ['action' => 'add']));
$form->prepare();

?>

<div class="container">
    <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0) ?>
</div>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-default customShadow">
            <div class="panel-heading bg-master-lighter">
                <div class="panel-title">
                    <h3 class="panel-title">Holiday</h3>
                </div>
            </div>
            <div class="panel-body p-t-5">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group form-group-sm <?= empty($holidayCode->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($holidayCode); ?>
                    <?php print $this->formElement($holidayCode); ?>
                </div>
                <?php print $this->formElementErrors()->render($holidayCode, ['class' => 'help-block error']); ?>


                <div class="form-group padding-0">
                    <?php print $this->formLabel($genderId); ?>
                    <div class="radio radio-success">
                        <?php $customRenderer($genderId); ?>
                    </div>
                </div>
                <?php print $this->formElementErrors()->render($genderId, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm form-group-default-select2">
                    <?php print $this->formLabel($branchId); ?>
                    <?php print $this->formElement($branchId); ?>
                </div>
                <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block error']) ?>


                <div class="form-group form-group-sm <?= empty($holidayEname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($holidayEname); ?>
                    <?php print $this->formElement($holidayEname); ?>
                </div>
                <?php print $this->formElementErrors()->render($holidayEname, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($holidayLname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($holidayLname); ?>
                    <?php print $this->formElement($holidayLname); ?>
                </div>
                <?php print $this->formElementErrors()->render($holidayLname, ['class' => 'help-block error']); ?>

                <div
                    class="form-group form-group-sm required input-group <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($startDate) ?>
                    <?php print $this->formElement($startDate) ?>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
                <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>


                <div
                    class="form-group form-group-sm required input-group <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($endDate) ?>
                    <?php print $this->formElement($endDate) ?>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
                <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>


                <div class="form-group padding-0">
                    <?php print $this->formLabel($halfday); ?>
                    <div class="radio radio-success">
                        <?php $customRenderer($halfday); ?>
                    </div>
                </div>
                <?php print $this->formElementErrors()->render($halfday, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>


                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
