<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/add.js'));
?>

<script>
    /*
     * load js vars here
     * */
    document.menu =<?php $menu = ["id" => "menuHolidays", "subMenu" => ["id" => "subMenuHolidaySetup"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>


<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<?php

$holidayCode = $form->get('holidayCode');
$genderId = $form->get('genderId');
$branchId = $form->get('branchId');
$holidayEname = $form->get('holidayEname');
$holidayLname = $form->get('holidayLname');
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$halfday = $form->get('halfday');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$genderId->setValueOptions($genders);
$branchId->setValueOptions($branches);
?>

<?php
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'holiday-Form');
$form->setAttribute('action', $this->url('holidaysetup', ['action' => 'add']));
$form->prepare();

?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holidaysetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group <?= empty($holidayCode->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($holidayCode); ?>
                    <?php print $this->formElement($holidayCode); ?>
                    <span class="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($holidayCode, ['class' => 'help-block error']); ?>


                <div class="form-group padding-0">
                    <?php print $this->formLabel($genderId); ?>
                    <div class="md-radio-inline">
                        <?php $customRenderer($genderId); ?>
                    </div>
                </div>
                <?php print $this->formElementErrors()->render($genderId, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default-select2">
                    <?php print $this->formLabel($branchId); ?>
                    <?php print $this->formElement($branchId); ?>
                </div>
                <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block error']) ?>


                <div class="form-group <?= empty($holidayEname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($holidayEname); ?>
                    <?php print $this->formElement($holidayEname); ?>
                    <span class="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($holidayEname, ['class' => 'help-block error']); ?>

                <div class="form-group <?= empty($holidayLname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($holidayLname); ?>
                    <?php print $this->formElement($holidayLname); ?>
                    <span class="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($holidayLname, ['class' => 'help-block error']); ?>

                <div class="form-group required ">
                    <label for="startDate">Start Date</label>
                    <div class="input-group date" id="startDate">
                        <input type="text" name="startDate" required="required"
                               class="form-control" value="" ng-model="holidayDtl.startDate">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                </div>

                <div class="form-group required">
                    <label for="endDate">End Date</label>
                    <div class="input-group date" id="endDate">
                        <input type="text" name="endDate" required="required" class="form-control"
                               value="" ng-model="holidayDtl.endDate">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($halfday); ?>
                    <div class="md-radio-inline">
                        <?php $customRenderer($halfday); ?>
                    </div>
                </div>
                <?php print $this->formElementErrors()->render($halfday, ['class' => 'help-block error']); ?>

                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>


                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
