<div class="col-md-6">
    <form method="POST" name="Holiday" role="form" action="/neo_hris/public/holiday/holidaysetup/edit" id="Holiday"
          class="ng-pristine ng-valid ng-binding">
        <div class="form-group form-group-default">
            <label for="holidayCode" class="fade">Holiday Code</label>
            <input name="holidayCode" required="required" id="holidayCode" class="form-control" type="text"
                   value="hellow">
        </div>

        <input type="text" ng-model="holidayDtl.HOLIDAY_CODE" class="ng-pristine ng-untouched ng-valid ng-not-empty">
        <div class="form-group padding-10">
            <label for="genderId">Gender</label>
            <div class="radio radio-success">
                <input checked="checked" type="radio" value="1" name="genderId" id="genderId+Male">
                <label for="genderId+Male">Male</label>
                <input type="radio" value="2" name="genderId" id="genderId+Female">
                <label for="genderId+Female">Female</label>
                <input type="radio" value="3" name="genderId" id="genderId+Other">
                <label for="genderId+Other">Other</label>
                <input type="radio" value="-1" name="genderId" id="genderId+All">
                <label for="genderId+All">All</label></div>
        </div>

        <div class="form-group form-group-default">
            <label for="holidayEname">Holiday Ename</label>
            <input name="holidayEname" required="required" id="holidayEname" class="form-control" type="text" value="">
        </div>

        <div class="form-group form-group-default">
            <label for="holidayLname">Holiday Lname</label>
            <input name="holidayLname" required="required" id="holidayLname" class="form-control" type="text" value="">
        </div>

        <div class="form-group form-group-default required input-group">
            <label for="startDate">Start Date</label>
            <input type="text" name="startDate" required="required" id="startDate" class="form-control" value="">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>

        <div class="form-group form-group-default required input-group">
            <label for="endDate">End Date</label>
            <input type="text" name="endDate" required="required" id="endDate" class="form-control" value="">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>

        <div class="form-group padding-10">
            <label for="halfday">Halfday</label>
            <div class="radio radio-success">
                <input checked="checked" type="radio" value="F" name="halfday" id="halfday+First Half">
                <label for="halfday+First Half">First Half</label>
                <input type="radio" value="S" name="halfday" id="halfday+Second Half">
                <label for="halfday+Second Half">Second Half</label>
                <input type="radio" value="N" name="halfday" id="halfday+Full Day">
                <label for="halfday+Full Day">Full Day</label>
            </div>
        </div>

        <div class="form-group form-group-default">
            <label for="remarks">Remarks</label>
            <input name="remarks" id="remarks" class="form-control" type="text" value="">
        </div>
        <input type="submit" name="submit" class="btn btn-primary pull-right" value="UPDATE"></form>
</div>


<div class="select2-drop select2-display-none select2-with-searchbox select2-drop-active" style="left: 116px; width: 182px; top: 166px; bottom: auto; display: none;">
    <div class="select2-search"><label for="s2id_autogen1_search" class="select2-offscreen">Holiday</label>
        <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"
            class="select2-input" role="combobox" aria-expanded="true" aria-autocomplete="list"
            aria-owns="select2-results-1" id="s2id_autogen1_search" placeholder=""
            aria-activedescendant="select2-result-label-16">
    </div>
    <div class="scroll-wrapper select2-results" style="position: relative;">
        <ul class="select2-results scroll-content" role="listbox" id="select2-results-1"
            style="height: auto; margin-bottom: 0px; margin-right: 0px; max-height: 93px;"></ul>
        <div class="scroll-element scroll-x">
            <div class="scroll-element_outer">
                <div class="scroll-element_size"></div>
                <div class="scroll-element_track"></div>
                <div class="scroll-bar" style="width: 96px;"></div>
            </div>
        </div>
        <div class="scroll-element scroll-y">
            <div class="scroll-element_outer">
                <div class="scroll-element_size"></div>
                <div class="scroll-element_track"></div>
                <div class="scroll-bar" style="height: 96px;"></div>
            </div>
        </div>
    </div>
</div>

<?PHP
$sql = new Sql($this->adapter);
$select = $sql->select();
$select->columns([
    new Expression("TO_CHAR(H.START_DATE, 'DD-MON-YYYY') AS START_DATE"),
    new Expression("TO_CHAR(H.END_DATE, 'DD-MON-YYYY') AS END_DATE"),
    new Expression("H.HOLIDAY_ID AS HOLIDAY_ID"),
    new Expression("H.HOLIDAY_CODE AS HOLIDAY_CODE"),
    new Expression("H.HOLIDAY_ENAME AS HOLIDAY_ENAME"),
    new Expression("H.HALFDAY AS HALFDAY"),
    new Expression("H.FISCAL_YEAR AS FISCAL_YEAR"),
    new Expression("H.REMARKS AS REMARKS"),
], true);
$select->from(['H' => Holiday::TABLE_NAME])
    ->join(['G' => 'HRIS_GENDERS'], 'H.GENDER_ID=G.GENDER_ID', ['GENDER_NAME'])
    ->join(['HB'=> 'HRIS_HOLIDAY_BRANCH'],'H.HOLIDAY_ID=HB.HOLIDAY_ID',['BRANCH_ID'])
    ->join(['B' => "HRIS_BRANCHES"], 'HB.BRANCH_ID=B.BRANCH_ID', ['BRANCH_NAME']);

$select->where(["H.STATUS='E'"]);
$statement = $sql->prepareStatementForSqlObject($select);
$result = $statement->execute();
return $result;
?>