<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/edit.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/holidayController.js'));
?>


<script>
    document.urlBranchList = '<?= $this->url("holidaysetup", ["action" => "branchList"]) ?>';
    document.urlDepartmentList = '<?= $this->url("holidaysetup", ["action" => "designationList"]) ?>';
    document.updateHolidayDetailWS = '<?= $this->url("holidaysetup", ["action" => "updateHolidayDetail"]) ?>';
    document.pullHolidayDetailWS = '<?= $this->url("holidaysetup", ["action" => "pullHolidayDetail"]) ?>';
</script>

<?php
$holidayFormElement->setAttributes(["ng-model" => "holidayId"]);

$startDate = $form->get('startDate');
$submit = $form->get('submit');
$submit->setAttribute('value', 'UPDATE');
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holidaysetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
        document.urlIndex = '<?= $this->url("holiday", ["action" => "index"]) ?>';
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="holidayController">
    <div id="hris-page-content">
        <div class="row margin-top-20">
            <div class="col-sm-12">
                <div class="portlet box custom-box form-box">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-user"></i>
                            Holiday Detail
                        </div>
                        <div class="actions">
                            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form name="holidayForm" id="holiday-form" ng-submit="update()" novalidate>
                            <input type="hidden" id="holidayId" value="<?= $selectedHoliday ?>"/>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="holidayEname">Holiday Ename</label>
                                        <span class="required" aria-required="true">*</span>
                                        <input name="holidayEname" required="required" id="holidayEname" class="form-control"
                                               type="text" value="" ng-model="holidayDtl.holidayEname">
                                        <div ng-show="holidayForm.$submitted || holidayForm.holidayEname.$touched">
                                            <ul ng-show="holidayForm.holidayEname.$error.required" class="help-block error">
                                                <li>Holiday Name is required.</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="holidayLname">Holiday Lname</label>
                                        <input name="holidayLname" id="holidayLname" class="form-control"
                                               type="text" value="" ng-model="holidayDtl.holidayLname">
                                    </div>
                                </div>
                            </div>

                            <div class=" row">
                                <div class="col-sm-6">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group required ">
                                                <label for="startDate">Start Date</label>
                                                <span class="required" aria-required="true">*</span>

                                                <input type="text" name="startDate" id="startDate" required="required"
                                                       class="form-control" value="" ng-model="holidayDtl.startDate">
                                                       <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                                                <div ng-show="holidayForm.$submitted || holidayForm.startDate.$touched">
                                                    <ul ng-show="holidayForm.startDate.$error.required" class="help-block error">
                                                        <li>Start Date is required.</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>     
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliStartDate">&nbsp;</label>
                                                <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                                       class="form-control" value="">
                                            </div>
                                        </div>     
                                    </div>  
                                </div>

                                <div class="col-sm-6">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group required">
                                                <label for="endDate">End Date</label>
                                                <span class="required" aria-required="true">*</span>
                                                <input type="text" id="endDate" name="endDate" required="required" class="form-control"
                                                       value="" ng-model="holidayDtl.endDate">
                                                       <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                                                <div ng-show="holidayForm.$submitted || holidayForm.endDate.$touched">
                                                    <ul ng-show="holidayForm.endDate.$error.required" class="help-block error">
                                                        <li>End Date is required.</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>     
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliEndDate">&nbsp;</label>
                                                <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                                       class="form-control" value="">
                                            </div>
                                        </div>     
                                    </div>        
                                </div>
                            </div>
                            <div class=" row">
                                <div class="col-sm-6">
                                    <div class="form-group padding-0">
                                        <label for="halfday">Halfday</label>
                                        <div class="md-radio-inline">
                                            <div class='md-radio'>
                                                <input type='radio' value='F' name='halfday' id='halfday+First Half' class='md-radiobtn'
                                                       ng-model="holidayDtl.halfday">
                                                <label for='halfday+First Half'>
                                                    <span></span>
                                                    <span class='check'></span>
                                                    <span class='box'></span> First Half
                                                </label>
                                            </div>
                                            <div class='md-radio'>
                                                <input type='radio' value='S' name='halfday' id='halfday+Second Half'
                                                       class='md-radiobtn' ng-model="holidayDtl.halfday">
                                                <label for='halfday+Second Half'>
                                                    <span></span>
                                                    <span class='check'></span>
                                                    <span class='box'></span> Second Half
                                                </label>
                                            </div>
                                            <div class='md-radio'>
                                                <input type='radio' value='N' name='halfday' id='halfday+Full Day' class='md-radiobtn'
                                                       ng-model="holidayDtl.halfday">
                                                <label for='halfday+Full Day'>
                                                    <span></span>
                                                    <span class='check'></span>
                                                    <span class='box'></span> Full Day
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="remarks">Remarks</label>
                                        <input name="remarks" id="remarks" class="form-control" type="text" value=""
                                               ng-model="holidayDtl.remarks">
                                    </div>
                                </div>
                            </div>
                            <button  id="submit" class="btn btn-success">
                                UPDATE
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>