<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/holiday/add.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));
$this->headScript()->appendFile($this->basePath('js/holiday/index.js'));

$this->headScript()->appendFile($this->basePath('plugins/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular/http.js'));
$this->headScript()->appendFile($this->basePath('js/angular/holidayController.js'));

?>

<script>
    document.menu =<?php $menu = ["id" => "menuHolidayManagement", "subMenu" => ["id" => "subMenuHolidaySetup"]];echo json_encode($menu);?>;
    document.urlBranchList = '<?= $this->url("webService", ["action" => "branchList"]) ?>';
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
</script>

<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}

$holidayFormElement->setAttributes(["ng-model" => "holidayId"]);
$branchFormElement->setAttribute("ng-model", "branchId");
$genderFormElement->setAttribute("ng-model", "genderId");

$holidayCode = $form->get('holidayCode');
$genderId = $form->get('genderId');
$branchId = $form->get('branchId');
$holidayEname = $form->get('holidayEname');
$holidayLname = $form->get('holidayLname');
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$halfday = $form->get('halfday');
$remarks = $form->get('remarks');
$submit = $form->get('submit');
$submit->setAttribute('value', 'UPDATE');

$genderId->setValueOptions($genders);

$form->setAttribute('role', 'form');
$form->setAttribute('action', $this->url('holidaysetup', ['action' => 'edit']));
$form->prepare();

?>
<div ng-app="hris" ng-controller="holidayController">
<div class="panel panel-transparent bg-light-color">
    <div class="p-t-20 p-r-10 p-l-20">
        <div class="row">
            <div class="col-md-2">
                <div class="form-group form-group-default-select2">
                    <label for="departmentId">Holiday</label>
                    <select name="holidayId" id="holidayId" ng-model="holidayDtl.holidayId" class="full-width select2-offscreen" data-init-plugin= "select2">
                        <?php foreach($holidayList as $holidays){?>
                            <option value="<?php print $holidays['HOLIDAY_ID']; ?>"><?php print $holidays['HOLIDAY_ENAME'];?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default-select2">
                    <?php print $this->formLabel($branchFormElement); ?>
                    <?php print $this->formElement($branchFormElement); ?>
                </div>
             </div>
            <div class="col-md-2">
                <div class="form-group form-group-default-select2">
                    <?php print $this->formLabel($genderFormElement); ?>
                    <?php print $this->formElement($genderFormElement); ?>
                </div>
            </div>
            <div class="col-md-1">
                <div class="form-group">
                    <label for="departmentId">&nbsp</label>
                    <button ng-click="filter()" id="viewHolidays" class="btn btn-block btn-primary pull-center">
                        Filter
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-heading p-b-0">
        <div class="panel-title">
            <h5 class="m-b-0 m-t-0">Holiday<span style="font-size:10px;"> Setup</span></h5>
        </div>
        <div class="btn-group pull-right">
            <a class="btn btn-default" href="<?= $this->url('holidaysetup', ['action' => 'add']) ?>">
                Add new
            </a>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group form-group-default">
                    <label for="holidayCode" class="fade">Holiday Code</label>
                    <input name="holidayCode" required="required" id="holidayCode" class="form-control" type="text" ng-model="holidayDtl.holidayCode">
                </div>
                <div class="form-group padding-10">
                    <label for="genderId">Gender</label>
                    <div class="radio radio-success">
                    <div class="radio radio-success">
                        <input checked="checked" type="radio" value="1" name="genderId" id="genderId+Male" ng-model="holidayDtl.genderId">
                        <label for="genderId+Male">Male</label>
                        <input type="radio" value="2" name="genderId" id="genderId+Female" ng-model="holidayDtl.genderId">
                        <label for="genderId+Female">Female</label>
                        <input type="radio" value="3" name="genderId" id="genderId+Other" ng-model="holidayDtl.genderId">
                        <label for="genderId+Other">Other</label>
                        <input type="radio" value="-1" name="genderId" id="genderId+All" ng-model="holidayDtl.genderId">
                        <label for="genderId+All">All</label>
                    </div>
                    </div>
                </div>

                <div class="form-group form-group-default">
                    <label for="holidayEname">Holiday Ename</label>
                    <input name="holidayEname" required="required" id="holidayEname" class="form-control" type="text" value="" ng-model="holidayDtl.holidayEname">
                </div>

                <div class="form-group form-group-default">
                    <label for="holidayLname">Holiday Lname</label>
                    <input name="holidayLname" required="required" id="holidayLname" class="form-control" type="text" value="" ng-model="holidayDtl.holidayLname">
                </div>

                <div class="form-group form-group-default required input-group">
                    <label for="startDate">Start Date</label>
                    <input type="text" name="startDate" required="required" id="startDate" class="form-control" value="" ng-model="holidayDtl.startDate">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>

                <div class="form-group form-group-default required input-group">
                    <label for="endDate">End Date</label>
                    <input type="text" name="endDate" required="required" id="endDate" class="form-control" value="" ng-model="holidayDtl.endDate">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>

                <div class="form-group padding-10">
                    <label for="halfday">Halfday</label>
                    <div class="radio radio-success">
                        <input checked="checked" type="radio" value="F" name="halfday" id="halfday+First Half" ng-model="holidayDtl.halfday">
                        <label for="halfday+First Half">First Half</label>
                        <input type="radio" value="S" name="halfday" id="halfday+Second Half" ng-model="holidayDtl.halfday">
                        <label for="halfday+Second Half">Second Half</label>
                        <input type="radio" value="N" name="halfday" id="halfday+Full Day" ng-model="holidayDtl.halfday">
                        <label for="halfday+Full Day">Full Day</label>
                    </div>
                </div>

                <div class="form-group form-group-default">
                    <label for="remarks">Remarks</label>
                    <input name="remarks" id="remarks" class="form-control" type="text"value="" ng-model="holidayDtl.remarks">
                </div>
                <button ng-click="update()" id="updateHoliday"  class="btn btn-primary pull-right">
                    UPDATE
                </button>
            </div>

            <div class="col-md-6">
                <h5>Branch List</h5>
                <ul>
                    <li>Jawalakhel <a href="#">Delete</a></li>
                    <li>Lagankhel <a href="#">Delete</a></li>
                    <li>New Road <a href="#">Delete</a></li>
                </ul>
                <a href="#">Add More</a>
            </div>

        </div>
    </div>
</div>
</div>