<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));
$this->headScript()->appendFile($this->basePath('js/holiday/index.js'));

$this->headScript()->appendFile($this->basePath('plugins/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular/http.js'));
$this->headScript()->appendFile($this->basePath('js/angular/controllers.js'));

?>

<script>
    document.menu =<?php $menu = ["id" => "menuHolidayManagement", "subMenu" => ["id" => "subMenuHolidaySetup"]];echo json_encode($menu);?>;
    document.urlBranchList = '<?= $this->url("webService", ["action" => "branchList"]) ?>';
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
</script>

<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}

$holidayFormElement->setAttributes(["ng-model" => "holidayId"]);
$branchFormElement->setAttribute("ng-model", "branchId");
$genderFormElement->setAttribute("ng-model", "genderId");
?>
<div ng-app="hris" ng-controller="holidayController">
<div class="panel panel-transparent bg-light-color">
    <div class="p-t-20 p-r-10 p-l-20">
        <div class="row">
            <div class="col-md-2">
                <div class="form-group form-group-default-select2">
                    <?php print $this->formLabel($holidayFormElement); ?>
                    <?php print $this->formElement($holidayFormElement); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-group-default-select2">
                    <?php print $this->formLabel($branchFormElement); ?>
                    <?php print $this->formElement($branchFormElement); ?>
                </div>
             </div>
            <div class="col-md-2">
                <div class="form-group form-group-default-select2">
                    <?php print $this->formLabel($genderFormElement); ?>
                    <?php print $this->formElement($genderFormElement); ?>
                </div>
            </div>
            <div class="col-md-1">
                <div class="form-group">
                    <label for="departmentId">&nbsp</label>
                    <button ng-click="filter()" id="viewHolidays" class="btn btn-block btn-primary pull-center">
                        Filter
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-heading p-b-0">
        <div class="panel-title">
            <h5 class="m-b-0 m-t-0">Holiday<span style="font-size:10px;"> Setup</span></h5>
        </div>
        <div class="btn-group pull-right">
            <a class="btn btn-default" href="<?= $this->url('holidaysetup', ['action' => 'add']) ?>">
                Add new
            </a>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="pull-right">
            <div class="col-xs-12">
                <input type="text" id="search-table" class="form-control pull-right" placeholder="Search">
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <table class="table customTable demo-table-search" id="tableWithSearch">
            <thead>
            <tr role="row">
                <th class="" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Holiday Code
                </th>
                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Branch
                </th>

                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Holiday Ename
                </th>
                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Start Date
                </th>
                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    End Date
                </th>
                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Half Day
                </th>
                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Fiscal Year
                </th>

                <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1"
                    colspan="1" aria-sort="ascending"
                    aria-label="Rendering engine: activate to sort column descending">
                    Action
                </th>

            </tr>
            </thead>
            <tbody id="target">

            <?php foreach ($holidayList as $holiday):
                ?>
                <tr role="row" ng-repeat="holiday in holidayList">
                    <td class="">
                        <p>
                            {{holiday.HOLIDAY_CODE}}
                        </p>
                    </td>

                    <td class="">
                        <p>
                            {{holiday.BRANCH_NAME}}
                        </p>
                    </td>
                    <td class="">
                        <p>
                            {{holiday.HOLIDAY_ENAME}}
                        </p>
                    </td>
                    <td class="">
                        <p>
                            {{holiday.START_DATE}}
                        </p>
                    </td>
                    <td class="">
                        <p>
                            {{holiday.END_DATE}}
                        </p>
                    </td>
                    <td class="">
                        <p>{{holiday.HALFDAY}}

                        </p>
                    </td>
                    <td class="">
                        <p>
                            {{holiday.FISCAL_YEAR}}
                        </p>
                    </td>

                    <td class="">
                        <a href="<?= $this->url("holidaysetup", ["action" => "edit", "id" => $holiday[\HolidayManagement\Model\Holiday::HOLIDAY_ID]]) ?>">Edit</a>
                        /
                        <a href="<?= $this->url("holidaysetup", ["action" => "delete", "id" => $holiday[\HolidayManagement\Model\Holiday::HOLIDAY_ID]]); ?>"
                           onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
    </div>
</div>
</div>