<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
$this->headScript()->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/add.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/holidayListController.js'));
?>

<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuHolidayManagement", "subMenu" => ["id" => "subMenuHolidaySetup"]];echo json_encode($menu);?>;
    document.url ="<?= $this->url('restful',['action','index']); ?>";
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holidaysetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="holidayListController">
    <div class="margin-top-20">
        <div class="row" style="position: relative;">
            <div class="col-sm-2">
                <label>From Date</label>
                <div class="input-group date" id="startDate">
                    <input type="text" placeholder="From Date" name="startDate" ng-model="startDate" id="startDate1"
                           class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label>To Date</label>
                <div class="input-group date" id="endDate">
                    <input type="text" placeholder="To Date" name="endDate" ng-model="endDate" id="endDate1"
                           class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($branches); ?>
                <?php print $this->formElement($branches); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($genders); ?>
                <?php print $this->formElement($genders); ?>
            </div>
            <div class="col-sm-4" style="position: absolute; bottom:0; right: 0;" >
                <div class="row">
                    <div class="col-sm-6">
                        <button ng-click="view()" id="viewHolidays" class="btn btn-sm yellow form-control">
                            View
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                    <div class="col-sm-6">
                        <div class="btn-group">
                            <a href="<?= $this->url('holidaysetup', ['action' => 'add']) ?>" id="sample_editable_1_new"
                               class="btn green"> Add New
                                <i class="fa fa-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="margin-top-20">
        <table class="table table-striped table-bordered table-hover no-footer">
            <thead>
            <tr role="row">
                <th>
                    Holiday Code
                </th>
                <th>
                    Holiday Name
                </th>
                <th>
                    From Date
                </th>
                <th>
                    To Date
                </th>
                <th>
                    Gender
                </th>
                <th>
                    Branch
                </th>
                <th>
                    Half Day
                </th>
                <th>
                    Action
                </th>
            </tr>
            </thead>
            <tbody>
                <tr role="row" ng-repeat="holiday in holidayList">
                    <td class="">
                        <span ng-bind="holiday.HOLIDAY_CODE"></span>
                    </td>
                    <td class="">
                        <span ng-bind="holiday.HOLIDAY_ENAME"></span>
                    </td>
                    <td class="">
                        <span ng-bind="holiday.START_DATE"></span>
                    </td>
                    <td class="">
                        <span ng-bind="holiday.END_DATE"></span>
                    </td>
                    <td class="">
                        <span ng-bind="holiday.GENDER_NAME"></span>
                    </td>
                    <td class="">
                        <ul ng-if="holiday.BRANCHES" id="branchList">
                            <li ng-repeat="values in holiday.BRANCHES">
                                - <span ng-bind="values.BRANCH_NAME"></span>
                            </li>
                        </ul>
                        <span ng-if="holiday.BRANCH_NAME" ng-bind="holiday.BRANCH_NAME"></span>
                    </td>
                    <td class="">
                        <span ng-bind="holiday.HALFDAY"></span>
                    </td>
                    <td class="">
                        <a href="<?= $this->url("holidaysetup", ["action" => "edit"]); ?>/{{holiday.HOLIDAY_ID}}">
                            Edit
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>