<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/holidayListController.js'));
?>


<script>
    document.ids =<?php echo json_encode(["startDate1" => "", "nepaliStartDate1" => "", "endDate1" => "", "nepaliEndDate1" => ""]) ?>;
    document.url = "<?= $this->url('restful', ['action', 'index']) ?>";
    document.editLink = '<?= $this->url("holidaysetup", ["action" => "edit"]) ?>';
    document.deleteLink = '<?= $this->url("holidaysetup", ["action" => "delete"]) ?>';
    document.pullHolidayListLink = '<?= $this->url("holidaysetup", ["action" => "pullHolidayList"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holidaysetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="holidayListController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('holidaysetup', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <label>From Date</label>
                        <div class="input-group date" id="startDate">
                            <input type="text" placeholder="From Date" name="startDate" ng-model="startDate" id="startDate1"
                                   class="form-control reset-field"/>       
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="nepaliStartDate">&nbsp;</label>
                        <div class="input-group">
                            <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                   class="form-control reset-field" value="">
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label>To Date</label>
                        <div class="input-group date" id="endDate">
                            <input type="text" placeholder="To Date" name="endDate" ng-model="endDate" id="endDate1"
                                   class="form-control reset-field"/>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="nepaliEndDate">&nbsp;</label>
                        <div class="input-group">
                            <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                   class="form-control reset-field" value="">
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right" style="margin-top:22px !important;">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button ng-click="view()" id="viewHolidays" class="btn btn-default btn-sm pull-right" style="margin-top:22px !important;">
                        View
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="">
        <div id="holidayTable">

        </div>
    </div>
</div>