<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/HolidayManagement/HolidaySetup/holidayListController.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>


<script>
    document.url = "<?= $this->url('restful', ['action', 'index']); ?>";
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holidaysetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="holidayListController" class="formbg">
    <div id="hris-page-content">
        <div class="margin-top-20">
            <div class="row" style="position: relative;">
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>From Date</label>
                                <div class="input-group date" id="startDate">
                                    <input type="text" placeholder="From Date" name="startDate" ng-model="startDate" id="startDate1"
                                           class="form-control"/>       
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nepaliStartDate">&nbsp;</label>
                                <div class="input-group">
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                           class="form-control" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>To Date</label>
                                <div class="input-group date" id="endDate">
                                    <input type="text" placeholder="To Date" name="endDate" ng-model="endDate" id="endDate1"
                                           class="form-control"/>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nepaliEndDate">&nbsp;</label>
                                <div class="input-group">
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                           class="form-control" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">

                    <button ng-click="view()" id="viewHolidays" class="btn btn-default form-control i-search" style="margin-top:22px !important;">
                        View
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>


            <div class="margin-top-20">
                <div class="row">

                    <div class="col-sm-6">
                        <div class="btn-group">
                            <a href="<?= $this->url('holidaysetup', ['action' => 'add']) ?>" id="sample_editable_1_new"
                               class="btn green"> Add New
                                <i class="fa fa-plus"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="btn-group pull-right">
                            <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                                <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="javascript:;" id="export"> Export to Excel </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>


            </div>
        </div>


        <div class="margin-top-20">
            <div id="holidayTable"></div>
        </div>

        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
            <td>
            #: (HOLIDAY_ENAME == null) ? '-' : HOLIDAY_ENAME #
            </td>
            <td>
            #: (START_DATE == null) ? '-' : START_DATE #
            </td>
            <td>
            #: (END_DATE == null) ? '-' : END_DATE #
            </td>
            <td>
            #: (HALFDAY == null) ? '-' : HALFDAY #
            </td>
            <td>
            <a class="btn-edit"
            href="<?= $this->url("holidaysetup", ["action" => "edit"]) ?>/#:HOLIDAY_ID#" style="height:17px;"> 
            <i class="fa fa-edit"></i>
            </a>
            </tr>
        </script>

    </div>
</div>