<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/add.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/leaveRequestController.js'));
?>


<?php
$form->setAttribute('role', 'form');

$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$noOfDays = $form->get('noOfDays');
$halfDay = $form->get('halfDay');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'Apply Leave');
$submit->setAttribute('id', 'request');

$form->setAttribute('action', $this->url('leavebalance', ['action' => 'apply', 'eid' => $employeeId, 'id' => $leaveId]));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
    document.employeeId =<?= json_encode($employeeId) ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leavebalance')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="leaveRequestController">
    <div class="row margin-top-20" >
        <div class="col-sm-12">
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>Apply For Leave
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <table>
                                    <tr height="25">
                                        <td>
                                            Employee Name
                                        </td><td width="15">:</td>
                                        <td>
                                            <?php echo $employeeName; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <table>
                                    <tr height="25">
                                        <td>
                                            Leave Name
                                        </td><td width="15">:</td>
                                        <td>
                                            <?php echo $leaveName; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div
                        class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                        <input readonly type="hidden" name="leaveId" class="form-control" id="leaveId" value="<?php echo $leaveId; ?>"/>
                    </div>


                    <div class=" row">
                        <div class="col-sm-4">
                            <div
                                class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($startDate) ?>
                                    <?php print $this->formElement($startDate) ?>
                            </div>
                            <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                        </div>

                        <div class="col-sm-4">
                            <div
                                class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($endDate) ?>
                                    <?php print $this->formElement($endDate) ?>
                                <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                            </div>
                            <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group disabled">
                                <label for="leaveId">Available Days</label>
                                <input type="text" READONLY name="availableDays" required="required" id="availableDays"  class="form-control"  value="<?php echo $balance; ?>">
                            </div>
                        </div>
                    </div>


                    <div class=" row">
                        <div class="col-sm-4">
                            <div
                                class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($noOfDays); ?>
                                    <?php print $this->formElement($noOfDays); ?>
                                <span id="errorMsg" style="font-size:11px; color:red;"></span>
                            </div>
                            <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                        </div>


                        <div class="col-sm-4">
                            <div class="form-group padding-0" id="remarks">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                            </div>
                        </div>

                    </div>


                    <?php if ($allowHalfDay == 'Y') { ?>
                        <div class="form-group padding-0" id="halfDay">
                            <?php print $this->formLabel($halfDay); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($halfDay); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($halfDay, ['class' => 'help-block error']); ?>
                    <?php } ?>









                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                    <?php print $this->formSubmit($submit); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>