<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));



$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/manager-service/salary-review/add.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
?>
<script>
    document.serviceHistoryList = '<?= $this->url('salaryReview', ['action' => 'history']) ?>';
    document.fetchLastSalaryReviewDate = '<?= $this->url('salaryReview', ['action' => 'lastReviewDate']) ?>';
    document.currentMonth = <?= json_encode($currentMonth) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salaryReview')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-money">
                    </i>
                    Salary Review
                </div>
            </div>
            <div class="portlet-body">
                <form action="<?= $this->url('salaryReview', ['action' => 'add']) ?>" method="POST">
                    <div class="form-group">
                        <?php print $this->formLabel($employeeElement); ?>
                        <?php print $this->formElement($employeeElement); ?>
                    </div>
                    <div class="form-group">
                        <label for="oldAmount">Old Amount</label>
                        <input type="number" required id="oldAmount" name="oldAmount" class="form-control" >
                    </div>
                    <div class="form-group">
                        <label for="oldAmount">New Amount</label>
                        <input type="number" required id="newAmount" name="newAmount" class="form-control" >
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="effectiveDate">Effective Date</label>
                            <input type="text" required id="effectiveDate" name="effectiveDate" class="form-control" >
                        </div>
                        <div class="form-group col-md-6">
                            <label for="effectiveNepaliDate">Effective Nepali Date</label>
                            <input type="text" required id="effectiveNepaliDate" name="effectiveNepaliDate" class="form-control" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="jobHistoryId"> Service Events  </label>
                        <select id="jobHistoryId" name="jobHistoryId" class="form-control" ></select>
                    </div>

                    <input type="submit" class="btn btn-success" />

                </form>

            </div>
        </div>
    </div>


</div>