<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/manager-service/salary-review/index.js'))
;
?>

<script>
    document.salaryDetails =<?= json_encode($salaryDetails) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salaryReview')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<div class="margin-top-20">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('salaryReview', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id ="export" class="hris-export-to-excel" hris-export-to-excel-target="salaryReviewTable">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="salaryReviewTable">
    </div>
	</div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>                 
         #: (FULL_NAME == null) ? ' ' : FULL_NAME #
        </td>
        <td> 
        #: (OLD_AMOUNT == null) ? '-' : OLD_AMOUNT #
        </td>
        <td>
        #: (NEW_AMOUNT == null) ? '-' : NEW_AMOUNT #
        </td>
        <td>
        #: (EFFECTIVE_DATE == null) ? '-' : EFFECTIVE_DATE #
        </td>
        <td>
        #: (JOB_HISTORY_ID == null) ? '-' : JOB_HISTORY_ID #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("salaryReview", ["action" => "edit"]) ?>/#:SALARY_DETAIL_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        </td>
        </tr>
    </script>
</div>