<?php
$this->headScript()
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/SelfService/pay-slip/index.js'))
        ->appendFile($this->basePath('js/jspdf.min.js'))
        ->appendFile($this->basePath('js/html2canvas.js'));
?>

<script>
    document.rules =<?= json_encode($rules) ?>;
    document.employeeId =<?= $employeeId ?>;
    document.pullPayRollGeneratedMonthsLink = "<?php echo $this->url("payslip", ["action" => "pullPayRollGeneratedMonths"]); ?>";
    document.fetchEmployeePaySlipLink = "<?php echo $this->url("payslip", ["action" => "fetchEmployeePaySlip"]); ?>";
    document.cssUrl = '<?= $this->basePath('css/custom.css') ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\payslip')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div ng-app="hris" ng-controller="paySlipController">
    <div class="row margin-top-10">
        <div class="col-sm-3 " >
            <div class="portlet solid default borderline shadow">
                <div class="portlet-title border-bottom">
                    <div class="caption">
                        <i class="icon-speech"></i>
                        <span class="caption-subject bold uppercase"> Months</span>
                        <span class="caption-helper">generated...</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="scroller" style="height:400px" data-rail-visible="1" data-rail-color="#fff" data-handle-color="#a1b2bd">
                        <div class="mt-radio-list">
                            <label class="c-mt-radio mt-radio"  ng-repeat="month in payRollGeneratedMonths"> 
                                {{month.MONTH_EDESC}}
                                <input ng-click="changeMonths(month.MONTH_ID)" type="radio" value="month.MONTH_ID" name="test" />
                                <span></span>
                            </label>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="portlet light tbl-box-shadow">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-speech"></i>
                        <span class="caption-subject bold uppercase"> PaySlip</span>
                        <span class="caption-helper"></span>
                    </div>
                    <div class="actions">
                        <a id="export" href="javascript:;" class="btn btn-circle red-sunglo btn-sm">
                            <i class="fa fa-plus" ></i> Export </a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body" id="paySlip">
                    <div ng-hide="paySlip == null"  data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-responsive">
                                    <table class="table customTable">
                                        <caption>
                                            Employee Detail
                                        </caption>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    Official Code
                                                </td>
                                                <td ng-bind="paySlip.employeeDetail.EMPLOYEE_CODE">

                                                </td>
                                                <td>
                                                    Name
                                                </td>
                                                <td >
                                                    <span ng-bind="paySlip.employeeDetail.FIRST_NAME">

                                                    </span>
                                                    <span ng-bind="paySlip.employeeDetail.MIDDLE_NAME">

                                                    </span>
                                                    <span ng-bind="paySlip.employeeDetail.LAST_NAME">

                                                    </span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Department
                                                </td>
                                                <td ng-bind="paySlip.employeeDetail.DEPARTMENT">

                                                </td>
                                                <td>
                                                    Month
                                                </td>
                                                <td >
                                                    <span ng-repeat="month in payRollGeneratedMonths| filter:monthId:month.MONTH_ID">
                                                        {{month.MONTH_EDESC}}
                                                    </span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Maritual Status
                                                </td>
                                                <td ng-bind="(paySlip.employeeDetail.MARITUAL_STATUS == 'M') ? 'Married' : 'Unmarried'">

                                                </td>
                                                <td>
                                                    Absent Days
                                                </td>
                                                <td ng-bind="paySlip.absentDays">

                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Present Days
                                                </td>
                                                <td ng-bind="paySlip.presentDays">

                                                </td>
                                                <td>
                                                    Net Amount
                                                </td>
                                                <td ng-bind="paySlip.calculatedValue">

                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="table-responsive">
                                    <table class="table customTable">
                                        <caption>
                                            Facilities and Renumerations (+)
                                        </caption>
                                        <tbody>
                                            <tr ng-repeat="rule in rules" ng-show="rule.PAY_TYPE_FLAG == 'A'"> 
                                                <td ng-bind="rule.PAY_EDESC">
                                                </td>
                                                <td ng-bind="paySlip.ruleValueKV[rule.PAY_ID]">

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="table-responsive">
                                    <table class="table customTable">
                                        <caption>
                                            Deductions and Savings (-)
                                        </caption>
                                        <tbody>
                                            <tr ng-repeat="rule in rules" ng-show="rule.PAY_TYPE_FLAG == 'D'"> 
                                                <td ng-bind="rule.PAY_EDESC">
                                                </td>
                                                <td ng-bind="paySlip.ruleValueKV[rule.PAY_ID]">

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

