<?php
$this->headLink()
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('js/search.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/GroupShiftAssign/index.js'));

?>

<script>
    document.pullEmployeeGroupShiftLink = '<?php echo $this->url("groupshiftassign", ["action" => "pullEmployeeGroupShift"]) ?>';
    document.pushEmployeeGroupShiftLink = '<?php echo $this->url("groupshiftassign", ["action" => "pushEmployeeGroupShift"]) ?>';
    document.getSearchDataLink = '<?php echo $this->url('groupshiftassign', ['action' => 'getSearchData']); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveassign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="assignController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Company</label>
                    <select multiple class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Branch</label>
                    <select multiple class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select multiple class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Position</label>
                    <select multiple class="form-control" name="position" id="positionId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Service Type</label>
                    <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <label>Service Event Type</label>
                    <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee Type</label>
                    <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Gender</label>
                    <select multiple class="form-control" name="gender" id="genderId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Location</label>
                    <select multiple class="form-control" name="location" id="locationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select multiple class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2">
                   <?php print $this->formLabel($ShiftGroupFormElement); ?>
                    <?php print $this->formElement($ShiftGroupFormElement); ?>
                </div> 
            </div>
            
            <div class="row margin-top-10">
                <div class=" col-sm-offset-8 col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button ng-click="view()" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    
    <div class="margin-top-20">
        <div class="table-responsive scrollbar-vertical" id="loadingDiv">
            <table class="table table-striped table-bordered table-hover no-footer customTable">
                <thead>
                    <tr role="row">
                        <th>Company</th>
                        <th>Branch</th>
                        <th>Department</th>
                        <th>Code</th>
                        <th>Name</th>
                        
                        <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </th>
                    </tr>
                </thead>
                <tbody id="target">
                    <tr role="row" ng-repeat="item in leaveList">
                        <td ng-bind="item.COMPANY_NAME"></td>
                        <td ng-bind="item.BRANCH_NAME"></td>
                        <td ng-bind="item.DEPARTMENT_NAME"></td>
                        <td ng-bind="item.EMPLOYEE_CODE"></td>
                        <td ng-bind="item.FULL_NAME"></td>
                        </td>
                        <td class="bs-checkbox " style="width: 100px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" ng-model="item.checked" type="checkbox"
                                           ng-change="checkUnit(item.checked)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-sm-2">
                <button class="btn btn-sm green pull-right" ng-click="assign()">
                    Assign
                    <i class="fa fa-edit"></i>
                </button>
            </div>
        </div>
    </div>

    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header">
        <h3 class="modal-title" id="modal-title">Document Upload</h3>
        </div>
        <div class="modal-body" id="modal-body">
        <div class="row">
        <div class="col-sm-12">
        <div id="dropZoneContainer" class="dropzone">
        </div>
        <div class="error" ng-show="!valid">Please upload Image.</div>
        </div>
        </div>
        </div>
        </div>
        <div class="modal-footer">
        <button class="btn btn-primary" type="button" ng-click="ok()">OK</button>
        <button class="btn btn-warning" type="button" ng-click="cancel()">Cancel</button>
        </div>
    </script>
</div>

