<?php 
$form->setAttribute('role','form');
$form->setAttribute('class','position-form');


$shiftCode = $form->get('shiftCode');
$shiftName = $form->get('shiftName');
$startTime = $form->get('startTime');
$endTime = $form->get('endTime');
$submit = $form->get('submit');

$submit = $form->get('submit');

$form->setAttribute('action',$this->url('shift',['action'=>'add']));

if ($this->messages) {
	print '<ul class="help-block bg-danger" style="background:#f3e250;">';
	foreach ($this->messages as $message) {
		print '<li>' . $message . '</li>';
	}
	print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading panel-title-head">
				<!--<div class="panel-title"> -->
					<h4>Shift Setup</h4>		
			</div>
			<div class="panel-body padding-5" style="margin-top:7px;">	
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($shiftCode); ?>
					<?php print $this->formElement($shiftCode); ?>
					<?php print $this->formElementErrors()->render($shiftCode,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default  emp-form-group">
					<?php print $this->formLabel($shiftName); ?>
					<?php print $this->formElement($shiftName); ?>
					<?php print $this->formElementErrors()->render($shiftName,['class'=>'help-block']);?>
				</div>

				<div class="form-group form-group-default  emp-form-group">
					<?php print $this->formLabel($startTime); ?>
					<?php print $this->formElement($startTime); ?>
					<?php print $this->formElementErrors()->render($startTime,['class'=>'help-block']);?>
				</div>

				<div class="form-group form-group-default  emp-form-group">
					<?php print $this->formLabel($endTime); ?>
					<?php print $this->formElement($endTime); ?>
					<?php print $this->formElementErrors()->render($endTime,['class'=>'help-block']);?>
				</div>

				<div class="panel-footer panel-footer-default">
					<?php  print $this->formSubmit($submit); ?>		
				</div>
				
			</div>
			
		</div>
	</div>
</div>
<?php

print $this->form()->closeTag();

?>