<div>
    <form action="<?php echo $this->url('auth/process', ['action' => 'authenticate']); ?>"  method="post">
        
    <label>You are Late! Fill Up the Details</label>
    <textarea rows="4" cols="30"name="remarks" required="required"></textarea>
    </br>
    <input class="btn btn-primary" type="submit">
    <a href="<?php echo $this->url('logout'); ?>" class="btn btn-danger pull-right"> Cancel </a>
    </form>
</div>

