<?php
    $lableData='';
if($type=='IN'){
    $lableData='You are Late! Fill Up The Remarks';
}else if($type=='OUT'){
    $lableData='You are trying to Checkout early Please!! Fill Up the Remarks';
}
?>
<div>
    <form action="<?php echo $this->url('checkout', ['action' => 'checkout']); ?>"  method="post">
        
    <label><?=$lableData?></label>
    <textarea rows="4" style="width:100%" name="remarks" required="required"></textarea>
    </br>
    <input class="btn btn-primary" type="submit">
    <a href="<?php echo $this->url('dashboard'); ?>" class="btn btn-danger pull-right"> Cancel </a>
    </form>
</div>

