<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/travel-request/add.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/advanceRequestController.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$toDate = $form->get('toDate');
$destination = $form->get('destination');
$requestedAmount = $form->get('requestedAmount');
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
//print_r($transportType); die();
$transportType = $form->get('transportType');
$transportType->setValueOptions($transportTypes);
$purpose = $form->get('purpose');
$travelCode = $form->get('travelCode');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('travelRequest', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuSelfService","subMenu"=>["id"=>"subMenuTravelRequest"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
    <div class="row margin-top-20" ng-app="hris" ng-controller="advanceRequestController">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <?php print $this->formLabel($travelCode); ?>
                    <?php print $this->formElement($travelCode); ?>
                    <?php print $this->formElementErrors()->render($travelCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($fromDate); ?>
                    <div class="input-group date" id="fromDate">
                        <?php print $this->formElement($fromDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($toDate); ?>
                    <div class="input-group date" id="toDate">
                        <?php print $this->formElement($toDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($destination); ?>
                    <?php print $this->formElement($destination); ?>
                    <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($purpose); ?>
                    <?php print $this->formElement($purpose); ?>
                    <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($requestedType); ?>
                    <?php print $this->formElement($requestedType); ?>
                    <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                </div>    
                <div class="form-group">
                    <?php print $this->formLabel($transportType); ?>
                    <?php print $this->formElement($transportType); ?>
                    <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                </div> 
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group padding-0">
                    <label for="noOfDays">
                        <input type="hidden" name="substituteEmployee" value="0"/>
                        <div class="md-checkbox">
                            <input type="checkbox" value="1" ng-model="substituteEmployee" ng-click="viewSubstituteEmployee(substituteEmployee)" id="substituteEmployee" class="md-check" name="substituteEmployee"/>
                            <label for="substituteEmployee">
                            <span></span>
                            <span class="check" style="left: 0px !important;"></span>
                            <span class="box" style="left: 0px !important;"></span>
                            Substitute Employee </label>
                        </div>
                    </label>
                    <div ng-if="travelSubstitute">
                        <select class="form-control" name="travelSubstitute" style="cursor: pointer;">
                        <?php foreach($employeeList as $key=>$value){ ?>
                            <option style="cursor: pointer;" value="<?php echo $key; ?>"><?php echo $value; ?></option>
                        <?php } ?>
                        </select>
                    </div>
                </div>

                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
