<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/travel-request/add.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/expense-request.js'));;

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled"=>"disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled"=>"disabled"]);
$travelCode = $form->get('travelCode');
$travelCode->setAttributes(["disabled"=>"disabled"]);
$destination = $form->get('destination');
$destination->setAttributes(["disabled"=>"disabled"]);
$purpose = $form->get('purpose');
$purpose->setAttributes(["disabled"=>"disabled"]);
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
$requestedType->setValueOptions(["ep"=>"Expense"]);
$requestedType->setAttributes(["disabled"=>"disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setValue("");
$requestedAmount->setAttributes(["required"=>"required"]);
$remarks = $form->get('remarks');
$remarks->setValue("");
$submit = $form->get('submit');
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('travelRequest', ['action' => 'expenseRequest','id'=>$id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuSelfService","subMenu"=>["id"=>"subMenuTravelRequest"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Travel Request Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group" style="margin-bottom: 0.5%">
                    <div class="row div-font-11">
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Advance Amount
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        Rs.<?php echo $advanceAmt; ?>
                                    </td>
                                </tr>
                                
                                
                            </table>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($travelCode); ?>
                    <?php print $this->formElement($travelCode); ?>
                    <?php print $this->formElementErrors()->render($travelCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($fromDate); ?>
                    <div class="input-group date" id="fromDate">
                        <?php print $this->formElement($fromDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($toDate); ?>
                    <div class="input-group date" id="toDate">
                        <?php print $this->formElement($toDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($destination); ?>
                    <?php print $this->formElement($destination); ?>
                    <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($purpose); ?>
                    <?php print $this->formElement($purpose); ?>
                    <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($requestedType); ?>
                    <?php print $this->formElement($requestedType); ?>
                    <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>

<?php

print $this->form()->closeTag();

?>