<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/spin.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/ladda.min.js'));
$this->headScript()
        ->appendFile($this->basePath('js/SelfService/travel-request/expense-request.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/expenseDtlController.js'));
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.urlExpenseRequest = '<?= $this->url("travelRequest", ["action" => "expenseRequest"]) ?>';
    document.urlTravelRequest = '<?= $this->url("travelRequest", ["action" => "index"]) ?>';
    document.urlExpenseDetailList = '<?= $this->url("travelRequest", ["action" => "expenseDetailList"]) ?>';
    document.urlDeleteExpenseDetail = '<?= $this->url("travelRequest", ["action" => "deleteExpenseDetail"]) ?>';</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20" ng-app="hris" ng-controller="expenseDtlController">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Travel Request Detail
                </div>
            </div>
            <div class="portlet-body div-font-11">
                <form name="travelExpenseForm" id="travelRequest-form" ng-submit="submitExpenseDtl()" novalidate>
                    <input type="hidden" id="travelId" value="<?= $id; ?>" />
                    <input type="hidden" id="requestedType" value="<?= $currentRequestType; ?>"/>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                           <table>
                                <tr>
                                    <td width="40%">
                                        <label for="purpose">Purpose :</label> 
                                    </td>
                                    <td>
                                        <input type="text"  value="" name="purpose" ng-model="travelDetail.purpose" required="required" id="purpose" class="form-control">
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.purpose.$touched">
                                            <ul ng-show="travelExpenseForm.purpose.$error.required" class="help-block error">
                                                <li>Purpose is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="advanceAmount">Advance Amount :</label> 
                                    </td>
                                    <td>
                                        <input type="text"  value="" name="advanceAmount" ng-model="travelDetail.advanceAmount" id="advanceAmount" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="destination">Destination :</label> 
                                    </td>
                                    <td>
                                        <input type="text"  value="" name="destination" ng-model="travelDetail.destination" required="required" id="destination" class="form-control">
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.destination.$touched">
                                            <ul ng-show="travelExpenseForm.destination.$error.required" class="help-block error">
                                                <li>Destination is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="departureDate">Departure Date :</label>
                                    </td>
                                    <td>
                                        <input dvalue="{{travelDetail.departureDateMain}}" datepicker type="text" required="required" ng-model="travelDetail.departureDateMain" name="departureDate" id="departureDate" class="form-control">
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.departureDate.$touched">
                                            <ul ng-show="travelExpenseForm.departureDate.$error.required" class="help-block error">
                                                <li>Departure Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="employeeCode">Returned Date :</label> 
                                    </td>
                                    <td>
                                        <input dvalue="{{travelDetail.returnedDate}}" datepicker value="" type="text" ng-model="travelDetail.returnedDate" required="required" name="returnedDate" id="returnedDate" class="form-control"> 
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.returnedDate.$touched">
                                            <ul ng-show="travelExpenseForm.returnedDate.$error.required" class="help-block error">
                                                <li>Returned Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%"><label for="form-approver">Approver :</label></td>  
                                    <td>
                                        <div class="md-radio-inline">
                                            <div class="md-radio"><input checked="checked" type="radio" value="CEO" name="approverRole" id="approverRole+CEO" class="md-radiobtn radioButton approverRole" ng-model="travelDetail.approverRole"><label for="approverRole+CEO">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> CEO
                                                </label>
                                            </div>
                                            <div class="md-radio"><input type="radio" value="DCEO" name="approverRole" id="approverRole+DCEO" class="md-radiobtn radioButton approverRole" ng-model="travelDetail.approverRole"><label for="approverRole+DCEO">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> DCEO
                                                </label>
                                            </div>                            
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
<!--                             <table>
                                <tr>
                                    <td width="40%">
                                        <label for="travelCode">Travel Code :</label></td>
                                    <td><input type="text" disabled="disabled" value="<?php // echo $detail['TRAVEL_ID']; ?>" name="travelCode" required="required" id="travelCode" class="form-control"></td>
                                </tr>
                            </table>-->
                        </div>
                    </div>
                    <div class="margin-top-10 scrollbar-horizantal">
                        <table width="100%" align="center" class="table table-striped table-bordered table-hover no-footer customTable div-font-11">
                            <thead style="font-size:11px !important;">
                                <tr>
                                    <th colspan="6" align="center">Description of Travel and Place</th>
                                    <th rowspan="3">Mode of Travel</th>
                                    <th rowspan="3">Fare</th>
                                    <th rowspan="3">Daily Allowance</th>
                                    <th rowspan="3">Local Conveyence</th>
                                    <th rowspan="3">Misc. Expenses</th>
                                    <th rowspan="3">Remarks</th>
                                    <th rowspan="3"></th>
                                </tr>
                                <tr>
                                    <th colspan="3">Departure</th>
                                    <th colspan="3">Destination</th>
                                </tr>
                                <tr>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Place</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Place</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="expenseDtlForm in expenseDtlFormList">
                                    <td>
                                        {{expenseDtlForm.total = expenseDtlForm.fare + expenseDtlForm.allowance + expenseDtlForm.localConveyence + expenseDtlForm.miscExpense; ""}}
                                        <input dvalue="{{expenseDtlForm.departureDate}}" datepicker type="text" required="required" name="departureDate_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.departureDate" size="11"/>
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.departureDate_{{expenseDtlForm.checkbox}}.$touched">
                                            <ul ng-show="travelExpenseForm.departureDate_{{expenseDtlForm.checkbox}}.$error.required" class="help-block error">
                                                <li>Departure Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" dvalue="{{expenseDtlForm.departureTime}}" timepicker required="required" name="departureTime_{{expenseDtlForm.checkbox}}"  size="7" ng-model="expenseDtlForm.departureTime"/>
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.departureTime_{{expenseDtlForm.checkbox}}.$touched">
                                            <ul ng-show="travelExpenseForm.departureTime_{{expenseDtlForm.checkbox}}.$error.required" class="help-block error">
                                                <li>Departure Time is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" required="required" name="departurePlace_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.departurePlace" size="11"/>
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.departurePlace_{{expenseDtlForm.checkbox}}.$touched">
                                            <ul ng-show="travelExpenseForm.departurePlace_{{expenseDtlForm.checkbox}}.$error.required" class="help-block error">
                                                <li>Departure Place is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input dvalue="{{expenseDtlForm.destinationDate}}" datepicker type="text" required="required" name="destinationDate_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.destinationDate" size="11"/>
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.destinationDate_{{expenseDtlForm.checkbox}}.$touched">
                                            <ul ng-show="travelExpenseForm.destinationDate_{{expenseDtlForm.checkbox}}.$error.required" class="help-block error">
                                                <li>Destination Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" dvalue="{{expenseDtlForm.destinationTime}}" timepicker required="required" name="destinationTime_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.destinationTime" size="7"/>
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.destinationTime_{{expenseDtlForm.checkbox}}.$touched">
                                            <ul ng-show="travelExpenseForm.destinationTime_{{expenseDtlForm.checkbox}}.$error.required" class="help-block error">
                                                <li>Destination Time is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" required="required" name="destinationPlace_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.destinationPlace" size="11"/>
                                        <div ng-show="travelExpenseForm.$submitted || travelExpenseForm.destinationPlace_{{expenseDtlForm.checkbox}}.$touched">
                                            <ul ng-show="travelExpenseForm.destinationPlace_{{expenseDtlForm.checkbox}}.$error.required" class="help-block error">
                                                <li>Destination Place is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <select style="width: 110px;" name="transportType" ng-model="expenseDtlForm.transportType" ng-options="transportTypes.name for transportTypes in transportTypeList track by transportTypes.id" required="required" id="transportType" class="form-control">
                                        </select>
                                    </td>
                                    <td>
                                        <div class="md-checkbox pull-right">
                                            <input type="checkbox" id="fareFlag_{{expenseDtlForm.checkbox}}" name="fareFlag_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.fareFlag" class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                            <label for="fareFlag_{{expenseDtlForm.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span></label>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="md-checkbox pull-right">
                                            <input type="checkbox" id="allowanceFlag_{{expenseDtlForm.checkbox}}" name="allowanceFlag_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.allowanceFlag" class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                            <label for="allowanceFlag_{{expenseDtlForm.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span></label>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="md-checkbox pull-right">
                                            <input type="checkbox" id="localConveyenceFlag_{{expenseDtlForm.checkbox}}" name="localConveyenceFlag_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.localConveyenceFlag" class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                            <label for="localConveyenceFlag_{{expenseDtlForm.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span></label>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="md-checkbox pull-right">
                                            <input type="checkbox" id="miscExpenseFlag_{{expenseDtlForm.checkbox}}" name="miscExpenseFlag_{{expenseDtlForm.checkbox}}" ng-model="expenseDtlForm.miscExpenseFlag" class="md-check ng-pristine ng-untouched ng-valid ng-empty">
                                            <label for="miscExpenseFlag_{{expenseDtlForm.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span></label>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" ng-model="expenseDtlForm.remarks" size="11"/>
                                    </td>
                                    <td width="1%"  class="checkboxgap">
                                        <div class="md-checkbox">
                                            <input type="checkbox" id="{{expenseDtlForm.checkbox}}" class="md-check"
                                                   ng-model="expenseDtlForm.checked">
                                            <label for="{{expenseDtlForm.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                            </label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <a href="javascript:;" class="btn btn-icon-only default pull-right"
                                           ng-click="addExpenseDtl()">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="deleteExpenseDtl()">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="submit_button" style="margin-top:2%;">
                        <button class="btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="submitBtn" name="submit" type="submit">
                            SUBMIT
                            <i class="fa fa-edit"></i>
                        </button>    
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

