<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
    document.deleteURL = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.travelRequestList =<?php echo json_encode($list); ?>;
    document.viewLink = '<?= $this->url("travelRequest", ["action" => "view"]) ?>';
    document.deleteLink = '<?= $this->url("travelRequest", ["action" => "delete"]) ?>';
    document.viewExpenseLink = '<?= $this->url("travelRequest", ["action" => "viewExpense"]) ?>';
    document.expenseRequestLink = '<?= $this->url("travelRequest", ["action" => "expenseRequest"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<div class="margin-top-20" ng-app="hris" ng-controller="travelRequestList">
    
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('travelRequest', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="travelTable">
    </div>
	</div>
  
<!--    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (FROM_DATE == null) ? '-' : FROM_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (DESTINATION == null) ? '-' : DESTINATION #
        </td>
        <td>
        #: (REQUESTED_AMOUNT == null) ? '-' : REQUESTED_AMOUNT #
        </td>
        <td>
        #: (REQUESTED_TYPE == null) ? '-' : REQUESTED_TYPE #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
        #if(REQUESTED_TYPE=='Expense'){ #
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "viewExpense"]) ?>/#: TRAVEL_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i>
        </a>
        #} else{ #
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "view"]) ?>/#: TRAVEL_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i>
        </a>
        # }#
        #if(ALLOW_TO_EDIT == 1 && REQUESTED_TYPE=='Expense'){#       
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "expenseRequest"]) ?>/#: TRAVEL_ID #" style="height:17px; margin-left: 6px;" title="update">
        <i class="fa fa-pencil-square-o"></i>
        </a>
        #}#
        #if(ALLOW_TO_EDIT == 1){#       
        <a class="confirmation btn-delete"
        href="<?= $this->url("travelRequest", ["action" => "delete"]) ?>/#: TRAVEL_ID #" id="bs_#:TRAVEL_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i>
        </a>
        #}#
        # if(ALLOW_TO_REQUEST_EX==1){#
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "expenseRequest"]) ?>/#: TRAVEL_ID #" style="height:17px; margin-left: 6px;" title="Expense Request">
        <i class="fa fa-send-o"></i>
        </a>
        #}#
        </td>
        </tr>
    </script>-->
</div>