<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuTravelRequest"]];
echo json_encode($menu); ?>;
    document.deleteURL ='<?= $this->url("restful", ["action" => "index"]) ?>';
    document.travelRequestList =<?php echo json_encode($list); ?>
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20" ng-app="hris" ng-controller="travelRequestList">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('travelRequest', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">      
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>      
        </div>
    </div>    
    <div id="travelTable">
    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (TRAVEL_CODE == null) ? '-' : TRAVEL_CODE #
        </td>
        <td>
        #: (FROM_DATE == null) ? '-' : FROM_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (DESTINATION == null) ? '-' : DESTINATION #
        </td>
        <td>
        #: (REQUESTED_AMOUNT == null) ? '-' : REQUESTED_AMOUNT #
        </td>
        <td>
        #: (REQUESTED_TYPE == null) ? '-' : REQUESTED_TYPE #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
        #if(REQUESTED_TYPE=='Expense'){ #
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "viewExpense"]) ?>/#: TRAVEL_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i>
        </a>
        #} else{ #
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "view"]) ?>/#: TRAVEL_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i>
        </a>
        # }#
        #if(ALLOW_TO_EDIT == 1 && REQUESTED_TYPE=='Expense'){#       
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "expenseRequest"]) ?>/#: TRAVEL_ID #" style="height:17px; margin-left: 6px;" title="update">
        <i class="fa fa-pencil-square-o"></i>
        </a>
        #}#
        #if(ALLOW_TO_EDIT == 1){#       
        <a class="confirmation btn-delete"
        href="<?= $this->url("travelRequest", ["action" => "delete"]) ?>/#: TRAVEL_ID #" id="bs_#:TRAVEL_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i>
        </a>
        #}#
        # if(ALLOW_TO_REQUEST_EX==1){#
        <a class="btn-edit"
        href="<?= $this->url("travelRequest", ["action" => "expenseRequest"]) ?>/#: TRAVEL_ID #" style="height:17px; margin-left: 6px;" title="Expense Request">
        <i class="fa fa-send-o"></i>
        </a>
        #}#
        </td>
        </tr>
    </script>
</div>