<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/travel-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled" => "disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled" => "disabled"]);
$destination = $form->get('destination');
$destination->setAttributes(["disabled" => "disabled"]);
$purpose = $form->get('purpose');
$purpose->setAttributes(["disabled" => "disabled"]);
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
$requestedType->setAttributes(["disabled" => "disabled"]);
$transportType = $form->get('transportType');
$transportType->setValueOptions($transportTypes);
$transportType->setAttributes(['disabled' => "disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled" => "disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('travelRequest', ['action' => 'add']));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Travel Request Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-md-6">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDate; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>
                                    <?php if ($advanceAmt > 0) { ?>
                                        <tr height="30">
                                            <td>
                                                Advance Amount
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                Rs.<?php echo $advanceAmt; ?>
                                            </td>
                                        </tr>
                                    <?php } ?>

                                </table>
                            </div>
                            <div class="col-md-6">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == 'RQ') {
                                                echo "Pending";
                                            } else if ($status == 'RC') {
                                                echo "Recommended";
                                            } else if ($status == 'AP') {
                                                echo "Approved";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>                               
                                </table>
                            </div>
                        </div>
                    </div>
                  
                    <div class="form-group">
                        <?php print $this->formLabel($fromDate); ?>
                        <div class="input-group date" id="fromDate">
                            <?php print $this->formElement($fromDate); ?>
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($toDate); ?>
                        <div class="input-group date" id="toDate">
                            <?php print $this->formElement($toDate); ?>
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($destination); ?>
                        <?php print $this->formElement($destination); ?>
                        <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                    </div>               
                    <div class="form-group">
                        <?php print $this->formLabel($purpose); ?>
                        <?php print $this->formElement($purpose); ?>
                        <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($requestedType); ?>
                        <?php print $this->formElement($requestedType); ?>
                        <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                    </div>   
                    <div class="form-group">
                        <?php print $this->formLabel($transportType); ?>
                        <?php print $this->formElement($transportType); ?>
                        <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                    </div> 
                    <div class="form-group">
                        <?php print $this->formLabel($requestedAmount); ?>
                        <?php print $this->formElement($requestedAmount); ?>
                        <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($remarks); ?>
                        <?php print $this->formElement($remarks); ?>
                        <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                    </div>
                </div>
                <div
                    class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Recommender]</label>
                    <?php print $this->formElement($recommendedRemarks); ?>
                </div>
                <div
                    class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Approver]</label>
                    <?php print $this->formElement($approvedRemarks); ?>
                </div>
            </div>
        </div>
    </div>
</div>

