<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
 
$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()
        ->appendFile($this->basePath('js/SelfService/travel-request/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled" => "disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled" => "disabled"]);
$departure = $form->get('departure');
$departure->setAttributes(["disabled" => "disabled"]);
$destination = $form->get('destination');
$destination->setAttributes(["disabled" => "disabled"]);
$purpose = $form->get('purpose');
$purpose->setAttributes(["disabled" => "disabled"]);
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions([$detail['REQUESTED_TYPE'] => $detail['REQUESTED_TYPE_DETAIL']]);
$requestedType->setAttributes(["disabled" => "disabled"]);
$transportType = $form->get('transportType');
$transportType->setValueOptions([$detail['TRANSPORT_TYPE'] => $detail['TRANSPORT_TYPE_DETAIL']]);
$transportType->setAttributes(['disabled' => "disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled" => "disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);
$noOfDays = $form->get('noOfDays');
$noOfDays->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('travelRequest', ['action' => 'add']));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
</script>
<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Travel Request Detail
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="border-bottom">
                <div class="form-group">
                    <div class="row div-font-11">
                        <div class="col-sm-4">
                            <table width="100%">
                                <tr height="30">
                                    <td>
                                        Requested Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['REQUESTED_DATE']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Status
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['STATUS_DETAIL']; ?>
                                    </td>
                                </tr>


                            </table>
                        </div>
                        <div class="col-sm-4">
                            <table width="100%">
                                <tr height="30">
                                    <td>
                                        Recommender
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $recommender; ?>
                                    </td>
                                </tr>

                            </table>
                        </div>
                        <div class="col-sm-4">
                            <table width="100%">  
                                <tr height="30">
                                    <td>
                                        Approver
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $approver; ?>
                                    </td>
                                </tr>                               
                            </table>
                        </div>
                    </div>
                </div>

                <div class=" row">

                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($fromDate); ?>
                                    <div class="input-group date" id="fromDate">
                                        <?php print $this->formElement($fromDate); ?>
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    </div>
                                    <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>    
                    </div>

                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($toDate); ?>
                                    <div class="input-group date" id="toDate">
                                        <?php print $this->formElement($toDate); ?>
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    </div>
                                    <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>     
                    </div>
                    
                    <div class="col-sm-4">
                        <div
                            class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($noOfDays); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($noOfDays); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                    </div>
                </div>

                
                <div class=" row">
                    <?php if(!$itnaryId){ ?>
                     <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($departure); ?>
                            <?php print $this->formElement($departure); ?>
                            <?php print $this->formElementErrors()->render($departure, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($destination); ?>
                            <?php print $this->formElement($destination); ?>
                            <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <?php } ?>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($purpose); ?>
                            <?php print $this->formElement($purpose); ?>
                            <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($requestedType); ?>
                            <?php print $this->formElement($requestedType); ?>
                            <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                        </div>   
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($transportType); ?>
                            <?php print $this->formElement($transportType); ?>
                            <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                        </div> 
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($requestedAmount); ?>
                            <?php print $this->formElement($requestedAmount); ?>
                            <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>   

                <?php if(!empty($files)){ ?>
                        <div class="row"> 
                            <div class="col-sm-6"> 
                                <label>Attachments</label>
                                    <div style="overflow: scroll; height:100px;" >
                                        <ul> 
                                            <?php foreach($files as $file){ ?>
                                                <a target="_blank" href="<?='../../../uploads/travel_documents/'.$file['FILE_IN_DIR_NAME']?>">
                                                    <li><?=$file['FILE_NAME']?></li></a>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                        </div>
                    <?php } ?>

                <?php if (isset($detail['SUB_EMPLOYEE_ID'])) { ?>
                    <div class="form-group padding-0">
                        <label for="noOfDays">
                            Substitute Employee 
                        </label>
                        <div>
                            <select disabled="disabled" class="form-control" name="travelSubstitute">
                                <option style="cursor: pointer;" selected><?php echo $detail['SUB_EMPLOYEE_NAME']; ?></option>
                            </select>
                        </div>
                    </div>
                    <div
                        class="form-group margin-top-10 required">
                        <label>Reason for action [From Sub. Employee] <?php echo $detail['SUB_APPROVED_FLAG_DETAIL']; ?></label>
                        <textarea disabled="disabled" name="subRemarks" id="form-subRemarks" class="form-subRemarks form-control" style="height: 50px; font-size:12px">
                            <?php echo $detail['SUB_REMARKS']; ?>
                        </textarea>
                    </div>
                <?php } ?>
                
                <div class="row">
                        <div class="col-md-12">
                            <?php
                             if ($itnaryId) {
                            echo $this->partial('travel/travel-itnary-request/itnaryPartialView.phtml', [
                                'itnaryId' => $itnaryId,
                                'travelItnaryDet' => $travelItnaryDet,
                                'travelItnaryMemDet' => $travelItnaryMemDet
                            ]);
                             }
                            ?>

                        </div>
                    </div>
                
                
            </div>
            <?php if ($detail['SUB_APPROVED_FLAG'] == 'Y') { ?>
                <div
                    class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Recommender]</label>
                    <?php print $this->formElement($recommendedRemarks); ?>
                </div>
                <div
                    class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Approver]</label>
                    <?php print $this->formElement($approvedRemarks); ?>
                </div>
            <?php } else if ($detail['SUB_APPROVED_FLAG'] == 'N') { ?>
                <div class="form-group" style="font-size:11px;">[note:You have to re-send leave detail!!!!]</div>
            <?php } ?>
        </div>
    </div>
</div>


<?php
print $this->form()->closeTag();
?>
<div style="border:1px solid; display: none;" id="printableArea" class="col-md-8">
    <div class="row">
        <div class="col-md-8 col-sm-offset-2">
            <ul id="headingList">
                <li>
                    <?php if ($detail['COMPANY_FILE_PATH'] != null || $detail['COMPANY_FILE_PATH'] != "") { ?>
                        <img src="<?= $this->basePath("uploads/" . $detail['COMPANY_FILE_PATH']); ?>" style="float:left;" height="50" width="50"/>
                    <?php } ?>
                    <h2><?= strtoupper($detail['COMPANY_NAME']); ?></h2></li>
                <li id="underline"><h3>Travel Authorization Form</h3></li>
            </ul>
        </div>
    </div>

    <div class="row font-common" style="min-height: 70px;">
        <div class="dtlTravel">
            <ul id="personalInfo">
                <li>Name: <?php echo $detail['FULL_NAME']; ?></li>
                <li>Place of Visit: <?= $detail['DESTINATION']; ?></li>
                <li>Purpose of Visit: <?= $detail['PURPOSE']; ?></li>
            </ul>
        </div>
        <div class="dtlDate">
            <ul id="personalInfo">
                <li>Date: <?php print_r($detail['REQUESTED_DATE']); ?></li>
            </ul>
        </div>
    </div>

    <div class="row font-common detailOfRequest">
        <ul id="personalInfo">
            <li>
                Visit Form : <?= $detail['FROM_DATE']; ?> To <?= $detail['TO_DATE']; ?> Total <?= $detail['DURATION']; ?> Day<?= ($detail['DURATION'] > 1) ? "s" : "" ?>
            </li>
            <li>
                Advance For Tour : Rs. <?= $detail['REQUESTED_AMOUNT'] ?> (<?= $advanceAmount; ?>)
            </li>
            <li>Mode of Transport: <?php echo $detail['TRANSPORT_TYPE_DETAIL']; ?></li>
        </ul>
    </div>

    <div class="row font-common signature">
        <div class="signEmployee">
            <div class="border-dotted">
                Signature of Employee
            </div>
        </div>
        <div class="signRecommender">
            <p style="height: 14px"><label><?= ucwords(strtolower($recommender)); ?></label></p>
            <div class="border-dotted" style="margin-left: 55px;">
                Recommended By 
            </div>
        </div>
        <div class="signApprover">
            <p style="height: 14px"><label><?= ucwords(strtolower($approver)); ?></label></p>
            <div class="border-dotted" style="float:right;">
                Approving Authority
            </div>
        </div>
    </div>

    <div class="row detailOfRequest" style="">
        <h4 style="margin-bottom:3px;">To Account Section:</h4>
        <div class="font-common">
            <p style="margin-top:0px;">
                Please provide to give him/her tour advance Rs. <?= $detail['REQUESTED_AMOUNT'] ?> which will be adjusted after presenting travel expenses & tour report within 15 days.
            </p>
        </div>
    </div>

    <div class="row font-common detailOfRequest1">
        <div class="signEmployee2">
            <div class="border-dotted1">
                Administration Department
            </div>
        </div>
    </div>
    <?php if (isset($detail['SUB_EMPLOYEE_ID'])) { ?>
        <div class="row detailOfRequest" style="margin-top: 4%;">
            <div class="font-common">
                <p style="margin-top:0px; font-size:11px;">
                    I am responsible to do his/her official works in his/her absence from office due to travelling/leave training.
                </p>
                <div class="dtlTravel">
                    <ul id="personalInfo">
                        <li>Name: <?= $detail['SUB_EMPLOYEE_NAME']; ?></li>
                        <li>Design: <?= $detail['SUB_DESIGNATION_TITLE']; ?></li>
                        <li>Date: <?= $detail['SUB_APPROVED_DATE']; ?></li>
                        <li>Signature: </li>
                    </ul>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<div class="col-md-12" style="text-align:center;display:<?php echo $detail['STATUS'] == 'AP' ? 'block' : 'none'; ?>">
    <a class="btn btn-success" id="print"> Print</a>
</div>
