<?php
$this->headScript()->appendFile($this->basePath('js/appraisal/type/add.js'));
//print_r($form); die();
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'appraisalType-form');

$appraisalTypeCode = $form->get('appraisalTypeCode');
$appraisalTypeEdesc = $form->get('appraisalTypeEdesc');
$appraisalTypeNdesc = $form->get('appraisalTypeNdesc');
$remarks = $form->get('remarks');
$serviceTypeId = $form->get('serviceTypeId');
$serviceTypes1 = ["0" => "none"]+$serviceTypes;
$serviceTypeId->setValueOptions($serviceTypes1);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('type', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuAppraisal", "subMenu" => ["id" => "subMenuType"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Type')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php print $this->formLabel($appraisalTypeCode); ?>
                    <?php print $this->formElement($appraisalTypeCode); ?>
                    <?php print $this->formElementErrors()->render($appraisalTypeCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($appraisalTypeEdesc); ?>
                    <?php print $this->formElement($appraisalTypeEdesc); ?>
                    <?php print $this->formElementErrors()->render($appraisalTypeEdesc, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($appraisalTypeNdesc); ?>
                    <?php print $this->formElement($appraisalTypeNdesc); ?>
                    <?php print $this->formElementErrors()->render($appraisalTypeNdesc, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($serviceTypeId); ?>
                    <?php print $this->formElement($serviceTypeId); ?>
                    <?php print $this->formElementErrors()->render($serviceTypeId, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>