<?php
$this->headScript()->appendFile($this->basePath('js/appraisal/type/add.js'));
//print_r($form); die();
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'appraisalType-form');

$appraisalTypeEdesc = $form->get('appraisalTypeEdesc');
$appraisalTypeNdesc = $form->get('appraisalTypeNdesc');
$durationType = $form->get('durationType');
$remarks = $form->get('remarks');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('type', ['action' => 'add']));

$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Type')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraisalTypeEdesc); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($appraisalTypeEdesc); ?>
                            <?php print $this->formElementErrors()->render($appraisalTypeEdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraisalTypeNdesc); ?>
                            <?php print $this->formElement($appraisalTypeNdesc); ?>
                            <?php print $this->formElementErrors()->render($appraisalTypeNdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($durationType); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($durationType); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($durationType, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>