<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuManagerService", "subMenu" => ["id" => "subMenuLeavetoApprove"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <table class="table" id="dataTable">
        <thead>
        <tr role="row">
            <th>
                Employee Name
            </th>
            <th>
                Leave Name
            </th>
            <th>
                Requested Date
            </th>
            <th>
                From Date
            </th>
            <th>
                To Date
            </th>
            <th>
                Duration
            </th>
            <th>
                Your Role
            </th>
            <th>
                Operation
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($list as $leaveRequestList):
            ?>
            <tr role="row">
                <td>
                    <?php
                    print $this->escapeHtml($leaveRequestList['FIRST_NAME'])." ".$this->escapeHtml($leaveRequestList['MIDDLE_NAME'])." ".$this->escapeHtml($leaveRequestList['LAST_NAME']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($leaveRequestList['LEAVE_ENAME']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($leaveRequestList['APPLIED_DATE']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($leaveRequestList['START_DATE']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($leaveRequestList['END_DATE']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($leaveRequestList['NO_OF_DAYS']);
                    ?>
                </td>
                <td>
                    <?php
                    $recommender = $this->escapeHtml($leaveRequestList['RECOMMENDER']);
                    $approver = $this->escapeHtml($leaveRequestList['APPROVER']);
                    if($id==$recommender){
                        echo "RECOMMENDER";
                        $role = "R";
                    }else if($id==$approver){
                        echo "APPROVER";
                        $role = "A";
                    }
                    ?>
                </td>
                <td>
                    <a class=""
                       href="<?= $this->url("leaveapprove", ["action" => "view", "id" =>$leaveRequestList['ID'],"role"=>$role]); ?>">
                        View
                    </a>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>


</div>