<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuManagerService", "subMenu" => ["id" => "subMenuLeaveStatus"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div ng-app="hris" ng-controller="leaveStatusListController">
    <div class="margin-top-20">
        <div class="row">
            <div class="col-sm-4">
                <?php print $this->formLabel($employees); ?>
                <?php print $this->formElement($employees); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($branches); ?>
                <?php print $this->formElement($branches); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($departments); ?>
                <?php print $this->formElement($departments); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($designations); ?>
                <?php print $this->formElement($designations); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($positions); ?>
                <?php print $this->formElement($positions); ?>
            </div>            
        </div>
        <div class="row margin-top-10">    
            <div class="col-sm-2">
                <?php print $this->formLabel($serviceTypes); ?>
                <?php print $this->formElement($serviceTypes); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($leaves); ?>
                <?php print $this->formElement($leaves); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($leaveStatus); ?>
                <?php print $this->formElement($leaveStatus); ?>
            </div>    
            <div class="col-sm-2">
                <label for="fromDate">From Date</label>
                <div class="input-group date" id="fromDate">
                    <input type="text" placeholder="From Date" id="fromDate1" name="fromDate" ng-model="fromDate" class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label for="toDate">To Date</label>
                <div class="input-group date" id="toDate">
                    <input type="text" placeholder="To Date" id="toDate1" name="toDate" ng-model="toDate" class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label height="45"></label>
                <button ng-click="view()" id="viewLeaveRequestStatus" class="btn btn-sm yellow form-control">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
    
    <div class="margin-top-20">   
        <div id="leaveRequestStatusTable">
        </div>
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: FIRST_NAME #  #: MIDDLE_NAME #  #: LAST_NAME #
        </td>
        <td>
        #: LEAVE_ENAME #
        </td>
        <td>
        #: APPLIED_DATE #
        </td>        
        <td>
        #: START_DATE #
        </td>
        <td>
        #: END_DATE #
        </td>
        <td>
        #: FN1 # #: MN1 # #: LN1 #
        </td>
        <td>
        #: FN2 # #: MN2 # #: LN2 #
        </td>
        <td>
        #: NO_OF_DAYS #
        </td>
        <td>
        #: STATUS #
        </td>
        <td>
            <a class=""
               href="<?= $this->url("leavestatus", ["action" => "view"])?>/#: ID #">
                View
            </a>
        </td>
        </tr>
    </script>
    
</div>  
    
    
    
<div class="row margin-top-20">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%; color:rgba(102, 102, 102, 0.92) !important;">
                        <i class="icon-layers"></i>
                        <span class="caption-subject sbold uppercase">Pending Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Leave Name
                        </th>
                        <th>
                            Requested Date
                        </th>
                        <th>
                            From Date
                        </th>
                        <th>
                            To Date
                        </th>
                        <th>
                            Duration
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($pendingList as $leaveRequestList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['FIRST_NAME']) . " " . $this->escapeHtml($leaveRequestList['MIDDLE_NAME']) . " " . $this->escapeHtml($leaveRequestList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['LEAVE_ENAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['APPLIED_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['START_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['END_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['NO_OF_DAYS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                $recommender = $this->escapeHtml($leaveRequestList['RECOMMENDER']);
                                $approver = $this->escapeHtml($leaveRequestList['APPROVER']);
                                if ($id == $recommender) {
                                    echo "RECOMMENDER";
                                    $role = 2;
                                } else if ($id == $approver) {
                                    echo "APPROVER";
                                    $role = 3;
                                }
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("leaveapprove", ["action" => "view", "id" => $leaveRequestList['ID'], "role" => $role]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-green icon-layers"></i>
                        <span class="font-green caption-subject sbold uppercase">Recommended Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable1">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Leave Name
                        </th>
                        <th>
                            Requested Date
                        </th>
                        <th>
                            From Date
                        </th>
                        <th>
                            To Date
                        </th>
                        <th>
                            Duration
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($recommendedList as $leaveRequestList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['FIRST_NAME']) . " " . $this->escapeHtml($leaveRequestList['MIDDLE_NAME']) . " " . $this->escapeHtml($leaveRequestList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['LEAVE_ENAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['APPLIED_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['START_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['END_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['NO_OF_DAYS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                $recommender = $this->escapeHtml($leaveRequestList['RECOMMENDER']);
                                $approver = $this->escapeHtml($leaveRequestList['APPROVER']);
                                if ($id == $recommender) {
                                    echo "RECOMMENDER";
                                    $role = 2;
                                } else if ($id == $approver) {
                                    echo "APPROVER";
                                    $role = 3;
                                }
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("leaveapprove", ["action" => "view", "id" => $leaveRequestList['ID'], "role" => $role]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-green icon-layers"></i>
                        <span class="font-green caption-subject sbold uppercase">Approved Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable2">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Leave Name
                        </th>
                        <th>
                            Requested Date
                        </th>
                        <th>
                            From Date
                        </th>
                        <th>
                            To Date
                        </th>
                        <th>
                            Duration
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($approvedList as $leaveRequestList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['FIRST_NAME']) . " " . $this->escapeHtml($leaveRequestList['MIDDLE_NAME']) . " " . $this->escapeHtml($leaveRequestList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['LEAVE_ENAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['APPLIED_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['START_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['END_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['NO_OF_DAYS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                $recommender = $this->escapeHtml($leaveRequestList['RECOMMENDER']);
                                $approver = $this->escapeHtml($leaveRequestList['APPROVER']);
                                if ($id == $recommender) {
                                    echo "RECOMMENDER";
                                    $role = 2;
                                } else if ($id == $approver) {
                                    echo "APPROVER";
                                    $role = 3;
                                }
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("leaveapprove", ["action" => "view", "id" => $leaveRequestList['ID'], "role" => $role]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-red icon-layers"></i>
                        <span class="font-red caption-subject sbold uppercase">Rejected Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable3">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Leave Name
                        </th>
                        <th>
                            Requested Date
                        </th>
                        <th>
                            From Date
                        </th>
                        <th>
                            To Date
                        </th>
                        <th>
                            Duration
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($rejectedList as $leaveRequestList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['FIRST_NAME']) . " " . $this->escapeHtml($leaveRequestList['MIDDLE_NAME']) . " " . $this->escapeHtml($leaveRequestList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['LEAVE_ENAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['APPLIED_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['START_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['END_DATE']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($leaveRequestList['NO_OF_DAYS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                $recommender = $this->escapeHtml($leaveRequestList['RECOMMENDER']);
                                $approver = $this->escapeHtml($leaveRequestList['APPROVER']);
                                if ($id == $recommender) {
                                    echo "RECOMMENDER";
                                    $role = 2;
                                } else if ($id == $approver) {
                                    echo "APPROVER";
                                    $role = 3;
                                }
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("leaveapprove", ["action" => "view", "id" => $leaveRequestList['ID'], "role" => $role]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>