<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('js/manager-service/leave-approve/status.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuManagerService", "subMenu" => ["id" => "subMenuLeaveStatus"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div ng-app="hris" ng-controller="leaveStatusListController">
    <div class="margin-top-20">
        <div class="row">
            <div class="col-sm-4">
                <?php print $this->formLabel($employees); ?>
                <?php print $this->formElement($employees); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($branches); ?>
                <?php print $this->formElement($branches); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($departments); ?>
                <?php print $this->formElement($departments); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($designations); ?>
                <?php print $this->formElement($designations); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($positions); ?>
                <?php print $this->formElement($positions); ?>
            </div>            
        </div>
        <div class="row margin-top-10">    
            <div class="col-sm-2">
                <?php print $this->formLabel($serviceTypes); ?>
                <?php print $this->formElement($serviceTypes); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($leaves); ?>
                <?php print $this->formElement($leaves); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($leaveStatus); ?>
                <?php print $this->formElement($leaveStatus); ?>
            </div>    
            <div class="col-sm-2">
                <label for="fromDate">From Date</label>
                <div class="input-group date" id="fromDate">
                    <input type="text" placeholder="From Date" id="fromDate1" name="fromDate" ng-model="fromDate" class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label for="toDate">To Date</label>
                <input type="hidden" id="recomApproveId" value="<?php echo $recomApproveId; ?>"/>
                <div class="input-group date" id="toDate">
                    <input type="text" placeholder="To Date" id="toDate1" name="toDate" ng-model="toDate" class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label height="45"></label>
                <button ng-click="view()" id="viewLeaveRequestStatus" class="btn btn-sm yellow form-control">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="btn-group pull-right">
            <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right">
                <li>
                    <a href="javascript:;" id="export"> Export to Excel </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="margin-top-20">  
        
        <div id="leaveRequestStatusTable">
        </div>
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (FIRST_NAME == null) ? ' ' : FIRST_NAME #
        #: (MIDDLE_NAME == null) ? ' ' : MIDDLE_NAME #
        #: (LAST_NAME == null) ? ' ' : LAST_NAME #
        </td>
        <td>
        #: (LEAVE_ENAME == null) ? '-' : LEAVE_ENAME #
        </td>
        <td>
        #: (APPLIED_DATE == null) ? '-' : APPLIED_DATE #
        </td>        
        <td>
        #: (START_DATE == null) ? '-' : START_DATE #
        </td>
        <td>
        #: (END_DATE == null) ? '-' : END_DATE #
        </td>
        <td>
        #: (NO_OF_DAYS == null) ? '-' : NO_OF_DAYS #
        </td>
        <td>
        #: (YOUR_ROLE == null) ? '-' : YOUR_ROLE #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
            <a class="btn  btn-icon-only btn-success"
               href="<?= $this->url("leaveapprove", ["action" => "view"])?>/#: ID #/#: ROLE #" style="height:17px;" title="view">
                <i class="fa fa-search-plus"></i></a>
            </a>
        </td>
        </tr>
    </script>
    
</div>  
    
    
