<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/travel-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelAdvance-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$travelCode = $form->get('travelCode');
$fromDate = $form->get('fromDate');
$toDate = $form->get('toDate');
$destination = $form->get('destination');
$requestedAmount = $form->get('requestedAmount');
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
$purpose = $form->get('purpose');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('travelApply', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuTravel","subMenu"=>["id"=>"subMenuApply"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <?php print $this->formLabel($employeeId); ?>
                    <?php print $this->formElement($employeeId); ?>
                    <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                </div>  
                <div class="form-group">
                    <?php print $this->formLabel($travelCode); ?>
                    <?php print $this->formElement($travelCode); ?>
                    <?php print $this->formElementErrors()->render($travelCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($fromDate); ?>
                    <div class="input-group date" id="fromDate">
                        <?php print $this->formElement($fromDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($toDate); ?>
                    <div class="input-group date" id="toDate">
                        <?php print $this->formElement($toDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($destination); ?>
                    <?php print $this->formElement($destination); ?>
                    <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($purpose); ?>
                    <?php print $this->formElement($purpose); ?>
                    <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($requestedType); ?>
                    <?php print $this->formElement($requestedType); ?>
                    <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
