<div class="modal fade" id="modal-program" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Academic Program</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form action="" method="post">
                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label for="academicProgramName">Academic Program Name</label>
                                    <input required="required" type="text" class="form-control" name="academicProgramName" id="academicProgramName"/>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label for="remarks">Remarks</label>
                                    <textarea class="form-control" name="remarks" id="remarks"></textarea>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary model-save-btn">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

