<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/advance-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'advance-form');

$advanceId = $form->get('advanceId');
$advanceId->setValueOptions($advances);
$requestedAmount = $form->get('requestedAmount');
$advanceDate = $form->get('advanceDate');
$reason = $form->get('reason');
$terms = $form->get('terms');

$requestedAmount->setAttribute('test', "test");
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');
$submit->setAttribute('id', 'advanceSubmit');

$form->setAttribute('action', $this->url('advanceRequest', ['action' => 'add']));


$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.pullAdvanceListLink = '<?php echo $this->url("advanceRequest", ["action" => "pullAdvanceList"]); ?>';
    document.pullAdvanceDetailByEmpIdLink = '<?php echo $this->url("advanceRequest", ["action" => "pullAdvanceDetailByEmpId"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advanceRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20" ng-app="hris" ng-controller="advanceDetailController">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <input type="hidden" id="form-employeeId" value="<?php echo $employeeId; ?>"/>


                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($advanceId); ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="advanceId" id="form-advanceId" required="required"  ng-model="advanceId" ng-change="advanceChange()" class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                                <?php foreach ($advances as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                <?php } ?>
                            </select>
                            <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                            <span ng-show="(allowAmt != null) && (allowTerms != null)" style="font-size:9px; font-weight: bold;">
                                Max Amount: <span ng-bind="allowAmt" style="font-size:9px; font-weight: bold;"></span>
                                Within : <span ng-bind="allowTerms" style="font-size:9px; font-weight: bold;"></span> Months
                            </span>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($requestedAmount); ?>
                            <span class="required" aria-required="true">*</span>
                            <input max="{{allowAmt}}" ng-model="requestedAmt" ng-change="requestChange()" type="number" name="requestedAmount" required="required" id="form-requestedAmount" class="form-requestedAmount form-control" min="1" step="0.01" value="<?= $requestedAmount->getValue() ?>">
                            <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($terms); ?>
                            <span class="required" aria-required="true">*</span>
                            <input max="{{allowTerms}}" ng-model="terms" ng-change="requestChange()" type="number" name="terms" required="required" id="form-terms" class="form-terms form-control" min="1" value="<?= $terms->getValue() ?>">
                            <?php print $this->formElementErrors()->render($terms, ['class' => 'help-block']); ?>
                        </div>
                        <span ng-show="salaryDeduction != null" style="font-size:9px; font-weight: bold;">
                            Deduction: {{salaryDeduction}} per month
                        </span>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($advanceDate); ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($advanceDate); ?>
                                    <?php print $this->formElementErrors()->render($advanceDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDate" id="nepaliDate"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>     
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($reason); ?>
                            <?php print $this->formElement($reason); ?>
                            <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
