<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/SelfService/advance-request/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.deleteURL = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.advanceRequestList =<?php echo json_encode($list)?>;
    document.viewLink ='<?= $this->url("advanceRequest", ["action" => "view"]) ?>';
    document.deleteLink ='<?= $this->url("advanceRequest", ["action" => "delete"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advanceRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('advanceRequest', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="advanceTable">
    </div>
	</div>
       
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (ADVANCE_NAME == null) ? '-' : ADVANCE_NAME #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (ADVANCE_DATE == null) ? '-' : ADVANCE_DATE #
        </td>
        <td>
        #: (REQUESTED_AMOUNT == null) ? '-' : REQUESTED_AMOUNT #
        </td>
        <td>
        #: (TERMS == null) ? '-' : TERMS #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("advanceRequest", ["action" => "view"]) ?>/#: ADVANCE_REQUEST_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i></a>
        </a>
        #if(ALLOW_TO_EDIT == 1){#       
        <a class="confirmation btn-delete"
        href="<?= $this->url("advanceRequest", ["action" => "delete"]) ?>/#: ADVANCE_REQUEST_ID #" id="bs_#:ADVANCE_REQUEST_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        #}#
        </td>
        </tr>
    </script>
</div>