<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advanceRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/advance-request/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'advance-form');

$advanceId = $form->get('advanceId');
$advanceId->setValueOptions($advances);
$advanceId->setAttributes(["disabled" => "disabled"]);

$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);

$advanceDate = $form->get('advanceDate');
$advanceDate->setAttributes(["disabled" => "disabled"]);

$reason = $form->get('reason');
$reason->setAttributes(["disabled" => "disabled"]);

$terms = $form->get('terms');
$terms->setAttributes(["disabled" => "disabled"]);

$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);

$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('advanceRequest', ['action' => 'add']));
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.advanceRequestData =<?php echo json_encode($advanceRequestData); ?>;
    document.wsGenerateAdvanceVoucher = '<?= $this->url("advanceRequest", ["action" => "generateAdvanceVoucher"]) ?>';
    document.pullAdvanceDetailByEmpIdLink = '<?php echo $this->url("advanceRequest", ["action" => "pullAdvanceDetailByEmpId"]); ?>';
</script>

<div class="row margin-top-20" ng-app="hris" ng-controller="advanceDetailController">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Advance Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>

            </div>
            <div class="portlet-body">
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDate; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == 'RQ') {
                                                echo "Pending";
                                            } else if ($status == 'RC') {
                                                echo "Recommended";
                                            } else if ($status == 'AP') {
                                                echo "Approved";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>                               
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" id="form-employeeId" value="<?php echo $employeeId; ?>"/>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($advanceId); ?>
                                <?php print $this->formElement($advanceId); ?>
                                <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                                <span>
                                    Max Amount: <span ng-bind="allowAmt" style="font-size:11px; font-weight: bold;"></span>
                                    Within : <span ng-bind="allowTerms" style="font-size:11px; font-weight: bold;"></span> Months
                                </span>
                            </div>               
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($requestedAmount); ?>
                                <?php print $this->formElement($requestedAmount); ?>
                                <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($terms); ?>
                                <?php print $this->formElement($terms); ?>
                                <?php print $this->formElementErrors()->render($terms, ['class' => 'help-block']); ?>
                            </div>
                            <span >
                                Deduction: {{salaryDeduction}} per month
                            </span>
                        </div>
                    </div>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($advanceDate); ?>
                                        <?php print $this->formElement($advanceDate); ?>
                                        <?php print $this->formElementErrors()->render($advanceDate, ['class' => 'help-block']); ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliDate" id="nepaliDate"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div> 

                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($reason); ?>
                                <?php print $this->formElement($reason); ?>
                                <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                    </div>


                </div>
                <div
                    class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Recommender]</label>
                    <?php print $this->formElement($recommendedRemarks); ?>
                </div>
                <div
                    class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Approver]</label>
                    <?php print $this->formElement($approvedRemarks); ?>
                </div>
                <div class="row">
                    <div class="col-sm-12" >
                        <button ng-show="voucherBtn.display" id="voucherBtn" class="btn btn-info pull-right" ng-bind="voucherBtn.text" ng-click="voucherBtn.fn()"> Generate Voucher </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header">
        <h3 class="modal-title" id="modal-title">Advance Voucher</h3>
        </div>
        <div class="modal-body" id="modal-body">
        <div class="form-body">
        <div class="form-group">
        <label class="control-label">Form Type</label>
        <select class="form-control">
        <option value="01">Red</option>
        <option value="02">Green</option>
        </select>
        <!-- <span class="help-block"> A block of help text. </span>-->
        </div>
        <div class="form-group">
        <label class="control-label">Account Code</label>
        <select class="form-control">
        <option value="01">Red</option>
        <option value="02">Green</option>
        </select>
        </div>
        </div>
        </div>
        <div class="modal-footer">
        <button class="btn btn-primary btn-sm" type="button" ng-click="ok()">OK</button>
        <button class="btn btn-warning btn-sm" type="button" ng-click="cancel()">Cancel</button>
        </div>
    </script>
</div>
