<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'serviceType-form');

$serviceTypeCode = $form->get('serviceTypeCode');
$serviceTypeName = $form->get('serviceTypeName');
$remarks = $form->get('remarks');
$status = $form->get('status');

$submit = $form->get('submit');
$submit->setAttribute('value','Add Service Type');

$form->setAttribute('action', $this->url('serviceType', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);

?>
    <script>
        document.menu=<?php $menu = ["id" => "menuSetup","subMenu"=>["id"=>"subMenuServiceType"]];echo json_encode($menu);?>;
    </script>

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 padding-30 bg-light-color">
            <div class="panel-heading panel-title-head">
                <h4>Service Type</h4>
            </div>
            <div class="panel-body padding-5" >
                <div class="form-group form-group-default ">
                    <?php print $this->formLabel($serviceTypeCode); ?>
                    <?php print $this->formElement($serviceTypeCode); ?>
                    <?php print $this->formElementErrors()->render($serviceTypeCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group form-group-default ">
                    <?php print $this->formLabel($serviceTypeName); ?>
                    <?php print $this->formElement($serviceTypeName); ?>
                    <?php print $this->formElementErrors()->render($serviceTypeName, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group form-group-default" >
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group form-group-default form-group-default-select2">
                    <?php print $this->formLabel($status); ?>
                    <?php print $this->formElement($status); ?>
                    <?php print $this->formElementErrors()->render($status, ['class' => 'help-block']); ?>
                </div>

                <?php print $this->formSubmit($submit); ?>

            </div>

        </div>
    </div>
<?php

print $this->form()->closeTag();

?>