<?php
/**
 * Load Javascript files here
 */

?>
<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>
<script>
    document.menu=<?php $menu = ["id" => "menuSetup","subMenu"=>["id"=>"subMenuServiceType"]];echo json_encode($menu);?>;
</script>
<div class="menu-bar">
    <?= $this->navigation('Zend\Navigation\serviceType')->breadcrumbs()->setMinDepth(0) ?>
</div>
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-user"></i>Table
        </div>
        <div class="actions">
            <a href="<?= $this->url('serviceType', ['action' => 'add']) ?>" class="btn btn-default btn-sm">
                <i class="fa fa-pencil"></i> Add </a>
        </div>
    </div>
    <div class="portlet-body">
            <table class="table">
                <thead>
                <tr role="row">
                    <th>
                        Service Type Code
                    </th>
                    <th>
                        Service Type Name
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($serviceTypeList as $serviceType): ?>
                    <tr role="row">
                        <td>
                                <?php print $this->escapeHtml($serviceType->SERVICE_TYPE_CODE); ?>
                        </td>
                        <td>
                                <?php print $this->escapeHtml($serviceType->SERVICE_TYPE_NAME); ?>
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">
                                    <a class="fa fa-edit btn-link"
                                       href="<?= $this->url("serviceType", ["action" => "edit", "id" => $serviceType->SERVICE_TYPE_ID]); ?>">
                                    </a>
                                </button>
                                <button type="button" class="btn btn-default">
                                    <a class="fa fa-trash-o btn-link"
                                       href="<?= $this->url("serviceType", ["action" => "delete", "id" => $serviceType->SERVICE_TYPE_ID]); ?>"></a>
                                </button>
                            </div>
                        </td>
                    </tr>

                <?php endforeach; ?>

                </tbody>
             </table>
         </div>
    </div>
</div>