<?php
$db_host = "192.168.4.44";
$db_user = "suyashk446";
$db_password = "Everest@8848";
$database = "kumari";


$connect = mysqli_connect($db_host, $db_user, $db_password, $database) or die("couldn't connect!!! to database");

//$employeeQuery = mysqli_query($connect, "SELECT * FROM EMPLOYEE_MASTER_SETUP WHERE OFFICIAL_CODE='$employeeCode'");
//$employeeDetail = mysqli_fetch_array($employeeQuery);
//$id = $employeeDetail['employee_code'];
$id = $employeeCode;

function getMonthcode($currentMonth) {


    if ($currentMonth == '1') {
        return '9';
    } elseif
    ($currentMonth == '2') {
        return '10';
    } elseif
    ($currentMonth == '3') {
        return '11';
    } elseif
    ($currentMonth == '4') {
        return '12';
    } elseif
    ($currentMonth == '5') {
        return '1';
    } elseif
    ($currentMonth == '6') {
        return '2';
    } elseif
    ($currentMonth == '7') {
        return '3';
    } elseif
    ($currentMonth == '8') {
        return '4';
    } elseif
    ($currentMonth == '9') {
        return '5';
    } elseif
    ($currentMonth == '10') {
        return '6';
    } elseif
    ($currentMonth == '11') {
        return '7';
    } else {
        if ($currentMonth == '12') {
            return '8';
        }
    }
}
if (!isset($_POST['mcode'])) {
//    $monthCode=getMonthcode($currentMonth);
    $monthCode = "";
} else if ($_POST['mcode'] == '') {
    //$monthCode=getMonthcode($currentMonth);
    $monthCode = "";
} else {
    $monthCode = $_POST['mcode'];
}

?>


<head>
    <style>
        html{
            line-height:15px;
        }
        table{
            border: 0px;
        }
        td{
            border: 0px;
        }
        tr{
            border: 0px;
        }
        .table>thead>tr>th, .table>tbody>tr>th, .table>tfoot>tr>th, .table>thead>tr>td, .table>tbody>tr>td, .table>tfoot>tr>td{
            padding: 2px 5px;
            border: 0px;
        }
        b{
            font-size: 12px;
        }
        .seperator{
            width: 100px;
        }
        .label{
            text-align: left;
            color: black;
            font-size: 12px;
            font-weight: bold;

        }
        .ui-widget input, .ui-widget select, .ui-widget textarea, .ui-widget button{
            width:100%;
            float:left;
        }

        fieldset.scheduler-border {
            border: 1px groove #ddd !important;
            padding: 0 1.4em 1.4em 1.4em !important;
            margin: 0 0 1.5em 0 !important;
            -webkit-box-shadow:  0px 0px 0px 0px #000;
            box-shadow:  0px 0px 0px 0px #000;
        }
        legend.scheduler-border {
            width:inherit; 
            padding:0 10px; 
            border-bottom:none;
            margin-top:15px;
        }

        .sliptable tbody tr td.lable
        {
            box-shadow:none !important;
        }
        .sliptable tr td{
            font-size:12px !important;
            font-weight:400 !important;
            color: #555555 !important;

        }

        .payslip-table {
            background-color: #ffffff;
            border: 1px solid #dddddd;
            box-shadow:-3px 2px 3px 1px #eeeeee;
            -moz-box-shadow:-3px 2px 3px 1px #eeeeee;
            -o-box-shadow:-3px 2px 3px 1px #eeeeee;
            -webkit-box-shadow:-3px 2px 3px 1px #eeeeee;
        }
        .sliptable
        {
            min-height:140px;
        }
        .form-data option{
            font-size:11px;
        }
        .form-data,.payslip-table td
        {
            font-size:12px;  
            color: #555555!important;
        }

        .sliptable thead {
            border-bottom: 1px solid #dddddd;
        }
        .btn-go{
            padding:5px !important;
            color:#fff !important;
            height:28px !important;
        }

    </style>
</head>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\payslip-previous')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php

function Period($connect) {
    $sql = "SELECT PERIOD_DT_CODE as mcode,DT_EDESC as mname  FROM HR_PERIOD_DETAIL ORDER BY to_number(PERIOD_DT_CODE)";
    $recs = array();
    $result = mysqli_query($connect, $sql);
    if ($result) {
        while ($row = mysqli_fetch_array($result)) {
            $recs[] = $row;
        }
    }
    return $recs;
}
$statuses = Period($connect);

function getMonthName($id) {
    $months = array('1' => 'Shrawan',
        '2' => 'Bhadra',
        '3' => 'Ashwin',
        '4' => 'Kartik',
        '5' => 'Mangsir',
        '6' => 'Poush',
        '7' => 'Magh',
        '8' => 'Falgun',
        '9' => 'Chaitra',
        '10' => 'Baisakh',
        '11' => 'Jestha',
        '12' => 'Ashadh'
    );
    echo $months[$id];
}

?>

<?php
if (isset($_POST['mcode'])) {
    $sql = "SELECT A.SHEET_NO, A.SAL_SHEET_CODE, B.EMPLOYEE_CODE,get_employee_name(B.EMPLOYEE_CODE) as employee_name ,
                B.BASIC_SALARY, B.BASIC_PERIOD,C.official_code,
                     B.CALC_BASIC, B.GRADE_CODE, B.MARITAL_STATUS, B.PRESENT_DAYS, B.WORK_DAYS,A.PERIOD_DT_CODE, 
                     B.OVERTIME_HOURS, B.LEAVE_WITH_PAY_DAYS, B.LEAVE_WITHOUT_PAY_DAYS, B.GROSS_AMOUNT,
                     B.NET_AMOUNT, B.EREMARKS, B.NREMARKS, B.HOLIDAYS, B.ABSENT_DAYS, B.HOLIDAYS,B.DEPARTMENT_CODE,
                     (SELECT department_name from department_master_setup where department_master_setup.department_code=B.DEPARTMENT_CODE) as department_name,
                     (SELECT grade_name from grade_master_setup where grade_master_setup.grade_code=B.GRADE_CODE) as grade_name,
                     (SELECT DT_EDESC from HR_PERIOD_DETAIL where HR_PERIOD_DETAIL.PERIOD_DT_CODE=A.PERIOD_DT_CODE) as MONTH
            FROM HR_SALARY_SHEET A , HR_SALARY_SHEET_DETAIL B,employee_master_setup C
            WHERE B.EMPLOYEE_CODE = '$id' 
            and  c.employee_code=b.employee_code
            AND a.SALARY_TYPE = 0 
            AND A.PERIOD_DT_CODE = '$_POST[mcode]'
            AND A.SHEET_NO = B.SHEET_NO";
} else {
    $sql = "SELECT A.SHEET_NO, A.SAL_SHEET_CODE, B.EMPLOYEE_CODE,get_employee_name(B.EMPLOYEE_CODE) as employee_name ,
                    B.BASIC_SALARY, B.BASIC_PERIOD,C.official_code,
                     B.CALC_BASIC, B.GRADE_CODE, B.MARITAL_STATUS, B.PRESENT_DAYS, B.WORK_DAYS,A.PERIOD_DT_CODE, 
                     B.OVERTIME_HOURS, B.LEAVE_WITH_PAY_DAYS, B.LEAVE_WITHOUT_PAY_DAYS, B.GROSS_AMOUNT,
                     B.NET_AMOUNT, B.EREMARKS, B.NREMARKS, B.HOLIDAYS, B.ABSENT_DAYS, B.HOLIDAYS,B.DEPARTMENT_CODE,
                     (SELECT department_name from department_master_setup where department_master_setup.department_code=B.DEPARTMENT_CODE) as department_name,
                     (SELECT grade_name from grade_master_setup where grade_master_setup.grade_code=B.GRADE_CODE) as grade_name,
                     (SELECT DT_EDESC from HR_PERIOD_DETAIL where HR_PERIOD_DETAIL.PERIOD_DT_CODE=A.PERIOD_DT_CODE) as MONTH
                    FROM HR_SALARY_SHEET A , HR_SALARY_SHEET_DETAIL B,employee_master_setup C
                    WHERE B.EMPLOYEE_CODE = '$id' 
                    and  c.employee_code=b.employee_code
                    AND a.SALARY_TYPE = 0 
                    AND A.PERIOD_DT_CODE = '$monthCode'
               AND A.SHEET_NO = B.SHEET_NO";
}
// var_dump($sql); exit;
$row = mysqli_query($connect, $sql);
$res = mysqli_fetch_assoc($row);

?>
<div class="panel panel-default margin-top-20">
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <h4> Generate Pay Slip </td></h4>
            <div class="page-heading">
                <table><tr><td class="label"></tr></table>
                </table>
                <form name="filter" method="post" action="">
                    <table class="table table-striped table-bordered table-hover" style="width:200px;">
                        <tr>
                            <th> Month  : </th>
                            <td><select name="mcode" class="form-data" style="width:100px;padding-top:3px;">
                                    <option value="">Select</option>
                                    <?php foreach ($statuses as $month) { ?>
                                        <option value="<?php echo $month['mcode']; ?>" <?php
                                        if (isset($_POST['mcode'])) {
                                            if ($_POST['mcode'] == $month['mcode']) {
                                                echo "selected";
                                            }
                                        }

                                        ?> > <?php echo $month['mname']; ?></option>
<?php }

?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" value="Go"class="btn btn-small btn-success" label="Filter"/></td>
                        </tr>           
                    </table>
                </form>
            </div>
                    <?php $salary_sheet = isset($res['SHEET_NO']) ? $res['SHEET_NO'] : null; ?>
            <table class="table" style="width:800px;margin-bottom:0px ">
                <tr>
                    <?php
                    $emp_rec = "SELECT e.employee_code,e.department_code,e.branch_code,e.marital_status,e.official_code,e.employee_name,
                                d.department_name,b.branch_name
                         from employee_master_setup e,department_master_setup d,branch_master_setup b
                         where b.branch_code=e.branch_code
                         and    d.department_code=e.department_code
                         and    e.employee_code='$id'";
                    $row = mysqli_query($connect, $emp_rec);
                    $result = mysqli_fetch_assoc($row);
                    $employee = strtolower($result['employee_name']);
                    $employee_name = ucwords($employee);

                    ?>
                    <td colspan="12" class="responsive-box">
                        <table class="table payslip-table">

                            <tr>
                                <td  class="label1"><b>Official Code</b></td>
                                <td>:</td>
                                <td><input type="hidden"  name="official_code" Value="<?php echo $result['official_code']; ?>"><?php echo $result['official_code']; ?></td>
                                <td  class="label1"><b>Name</b></td>
                                <td>:</td>
                                <td><input type="hidden"  name="EMPLOYEE_CODE" Value="<?php echo $res['EMPLOYEE_CODE']; ?>"><?php echo $employee_name; ?></td>
                            </tr>
                            <tr>
                                <td class="label1"><b>Department</b></td> <td>:</td>
                                <td><INPUT  TYPE="hidden" name="department_code" Value="<?php echo $result['department_code']; ?>"><?php echo $result['department_name']; ?></td>
                            </tr>
                            <tr>
                                <td class="label1"><b>Marital Status</b></td> <td>:</td>
                                <td><INPUT  TYPE="hidden" name="marital_status" Value="<?php echo $result['marital_status']; ?>"><?php echo $result['marital_status']; ?></td>

                                <td class="label1"><b>Month</b></td><td>:</td>
                                <td><INPUT  TYPE="hidden" name="MONTH" Value="<?php echo ($monthCode != "" && $monthCode != null) ? getMonthName($monthCode) : ""; ?>"><?php echo ($monthCode != "" && $monthCode != null) ? getMonthName($monthCode) : "" ?></td>

                            </tr>

                            <tr>
                                <td class="label1"><b>Present Days</b></td> <td>:</td>
                                <td><INPUT  TYPE="hidden" name="PRESENT_DAYS" Value="<?php echo $res['WORK_DAYS']; ?>"><?php echo $res['WORK_DAYS']; ?></td>
                                <td class="label1"><b>Absent Days</b></td> <td>:</td>
                                <td><INPUT  TYPE="hidden" name="ABSENT_DAYS" Value="<?php echo $res['ABSENT_DAYS']; ?>"><?php echo $res['ABSENT_DAYS']; ?></td>

                            </tr>
                            <tr>

                            </tr>
                            <tr>
                                <td class="label1"><b>Net Amount</b></td><td>:</td>
                                <td><INPUT  TYPE="hidden" name="NET_AMOUNT" Value="<?php echo $res['NET_AMOUNT']; ?>"><b><?php echo number_format($res['NET_AMOUNT'], 2, '.', ','); ?></b></td>
                            </tr>

                        </table>
                    </td>
                </tr>

                <tr>
                    <td colspan="10" class="responsive-box">
                        <fieldset class="scheduler-border" style="min-height:400px;">
                            <legend class="scheduler-border" style="font-size:15px;color:black;">Facilities and Remunerations (+)</legend>
                            <table class="table table-striped table-bordered table-hover sliptable" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>S.N</th>
                                        <th>Facilities and Remuneration</th>
                                        <th><span style="float:right;padding-right:5px;">Amount</span></th>
                                    </tr>

                                </thead>                                    
                                <tbody>
                                    <?php
                                    $counter = 1;
                                    if (!isset($_POST['mcode'])) {
                                        $_POST['mcode'] = $monthCode;
                                    }
                                    if (isset($salary_sheet)):
                                        $sum1 = 0.0;
                                        $qry = "SELECT 10 as pay_code,'Basic' as pay_edesc,'Basic' as pay_ndesc,calc_basic as amount,'1' as sheet_no FROM hr_salary_sheet_detail a, hr_salary_sheet c
                                    WHERE a.sheet_no=c.sheet_no
                                    and   c.sheet_no='$salary_sheet'
                                    and   c.period_dt_code='$_POST[mcode]'
                                    and   a.employee_code='$id'                                     
                                    UNION
                                    SELECT a.pay_code, b.pay_edesc,b.pay_ndesc,a.amount,c.sheet_no 
                                    FROM hr_salary_pay_detail a, hr_pay_setup b,hr_salary_sheet c
                                    WHERE a.sheet_no=c.sheet_no
                                    and   c.sheet_no='$salary_sheet'
                                    and   c.period_dt_code='$_POST[mcode]'
                                    and   a.employee_code='$id' 
                                    and   a.pay_code=b.pay_code 
                                    and   a.pay_type_flag='A' 
                                    and   b.INVISIBLE_ON_PAY_SLIP = 'N'
                                    
                                    ";
                                        // var_dump($qry); 
                                        $result = mysqli_query($connect, $qry);
                                        while ($branch = mysqli_fetch_assoc($result)) {

                                            ?>
                                        <td> <?php echo $counter++; ?></td>   
                                        <td> <?php echo $branch['pay_edesc']; ?></td>
                                        <td> <span style="float:right;padding-right:5px;"><?php
                                                echo number_format($branch['amount'], 2, '.', ',');
                                                if (!isset($branch['amount'])) {
                                                    $branch['amount'] = 0;
                                                }

                                                $sum1 += $branch['amount'];

                                                ?></span></td>
                                        </tr>

    <?php } ?>
                                    </hr>
                                    <td></td>
                                    <tr>

                                    <tr></tr>
                                    <tr> <td><b>Total</b></td><td></td>
                                        <td><span style="float:right;padding-right:5px;"><b><?php echo number_format($sum1, 2, '.', ',') ?></b></span></td></tr>
<?php endif; ?>

                                </tbody>                                
                            </table>

                        </fieldset>
                    </td>

                    <td colspan="10" class="responsive-box">
                        <fieldset class="scheduler-border" style="min-height:400px;">
                            <legend class="scheduler-border" style="font-size:15px;color:black;">Deductions and Savings (-)</legend>
                            <table class="table table-striped table-bordered table-hover sliptable" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>S.N</th>
                                        <th>Deductions and Savings</th>
                                        <th><span style="float:right;padding-right:5px;">Amount</span></th>
                                    </tr>
                                </thead>                                    
                                <tbody>
                                    <?php
                                    $counter = 1;
                                    if (isset($salary_sheet)):

                                        $sum = 0.0;
                                        $sql = "SELECT a.pay_code, b.pay_edesc,b.pay_ndesc,a.amount,c.sheet_no  FROM hr_salary_pay_detail a, hr_pay_setup b, hr_salary_sheet c
                                                WHERE a.sheet_no=c.sheet_no
                                                and   c.sheet_no='$salary_sheet'
                                                and   a.employee_code='$id' 
                                           
                                                and   c.period_dt_code='$_POST[mcode]'
                                                and   a.pay_code=b.pay_code 
                                                and   a.pay_type_flag='D' 
                                                and   b.INVISIBLE_ON_PAY_SLIP = 'N'  
                                                order by to_number(b.PRIORITY_INDEX)";
                                        // var_dump($sql); exit;

                                        $result = mysqli_query($connect, $sql);
                                        while ($branch = mysqli_fetch_assoc($result)) {

                                            ?>
                                        <td> <?php echo $counter++; ?></td>   
                                        <td> <?php echo $branch['pay_edesc']; ?></td>
                                        <td> <span style="float:right;padding-right:5px;"><?php
                                echo number_format($branch['amount'], 2, '.', ',');
                                $sum += $branch['amount'];

                                ?></span></td>
                                        </tr>
    <?php } ?>
                                    </hr>
                                    <td><b>Total</b></td><td></td>
                                    <td><span style="float:right;padding-right:5px;"><b><?php echo number_format($sum, 2, '.', ','); ?></b></span></td>
<?php endif; ?>
                                </tbody>                                
                            </table>
                        </fieldset>
                    </td>
                </tr>
            </table>

            <div class="printbutton" style="width:800px;">
                <a href="<?= $this->url('salarySheet', ['action' => 'printPayslip']) ?>/<?php echo $id; ?>/<?php echo $_POST['mcode']; ?>"><center><button type="print" class="btn btn-color-green btn-sm"  style="width:150px;"/>
                        <strong>Print</strong></a></div>
            </form>
        </div> 
    </div>
</div>
<script>
    $(function () {
        $('#from_date').datepicker({dateFormat: 'yy-mm-dd', minDate: 0});
        $('#to_date').datepicker({dateFormat: 'yy-mm-dd', minDate: 0});
        $("#request_date").datepicker({dateFormat: 'yy-mm-dd'});
        $("#extended_date").datepicker({dateFormat: 'yy-mm-dd'});
        $("#authorised_date").datepicker({dateFormat: 'yy-mm-dd'});
        $("#reimbursement_settlement_date").datepicker({dateFormat: 'yy-mm-dd'});
    });
</script>

<script>
    $(function () {
        $("#basic_information").addclass('active');
    });
</script>
<style>
    #basic_information{
        background-color: rgb(205, 205, 205);
    }
</style>
</body>
</html>
