<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/jstree/dist/themes/default/style.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/jstree/dist/jstree.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/appraisal/stage-question/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
    <script>
         document.urlHeadingList ='<?= $this->url("stageQuestion",['action'=>'headings']); ?>'; 
    </script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\StageQuestion')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div ng-app="hris" class="margin-top-20 formbg">
    <div style="margin-top:15px;margin-bottom:10px;">
        <div class="row">
            <div class="col-md-6">
            <select>
                <?php foreach($typeResult as $typeRow){ ?>
                <option><?php echo $typeRow['APPRAISAL_TYPE_EDESC']; ?></option>
                <?php } ?>
            </select>
            
            <div id="tree_3" class="tree-demo"></div>
            </div>
            <div class="col-md-6">
                <b>Stage Assign</b>
                <ul id="roleList">
                <?php
                foreach($stageList as $stageRow){ ?>
                <li><?php echo $stageRow['STAGE_EDESC']; ?></li>
                <?php } ?>
                </ul>
            </div>
        </div>  
<!--            <ul id="roleList">
                <?php // foreach($headingList as $headingRow){ ?>
                <li><a><?php // echo $headingRow['HEADING_EDESC']; ?></a>
                <?php // if(count($headingRow['QUESTIONS'])>0){ ?>
                    <ul>
                        <?php // foreach($headingRow['QUESTIONS'] as $questionRow){ ?>
                        <li><a href=""><?php // echo $questionRow['QUESTION_EDESC']; ?></a></li>
                        <?php // } ?>
                    </ul>
                <?php // } ?>
                </li>
                <?php // } ?>
            </ul>-->
    </div>
</div>
