<?php
/**
 * Load Javascript files here
 */

$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/travel-request/add.js'));


$form->setAttribute('role', 'form');

$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setValue($detail['RECOMMENDED_REMARKS']);
$recommendedRemarks->setAttributes(['required'=>'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setValue($detail['APPROVED_REMARKS']);
$approvedRemarks->setAttributes(['required'=>'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('travelStatus', ['action' => 'view', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu =<?php $menu = ["id" => "menuTravel", "subMenu" => ["id" => "subMenuTravelStatus"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
        document.employeeId=<?= json_encode($employeeId)?>;
    </script>

    <div class="page-bar">
        <?= $this->navigation('Zend\Navigation\travelStatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
    </div>
    
    <div class="row margin-top-20">  
    <div class="col-sm-12">    
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Travel Request Detail
                </div>
            </div>
            <div class="portlet-body div-font-11">
                    <input type="hidden" id="travelId" value="<?php echo $id; ?>" />
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="travelCode">Employee Name : </label>
                                    </td>
                                    <td> <?php echo $employeeName; ?></td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td>
                                        Recommender :  
                                    </td>
                                    <td>
                                        <?php echo $recommender; ?>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td>
                                        Approver :  
                                    </td>
                                    <td>
                                        <?php echo $approver; ?>
                                    </td>
                                </tr>     
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="travelCode">Travel Code :</label></td>
                                    <td><input type="text" disabled="disabled" value="<?php echo $detail['TRAVEL_CODE']; ?>" name="travelCode" id="travelCode" class="form-control"></td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                        <table>
                            <tr>
                                <td width="40%">
                                   <label for="advanceAmount">Advance Amount :</label> 
                                </td>
                                <td>
                                    <input type="text" disabled="disabled" value="<?php echo $advanceAmt; ?>" name="advanceAmount" id="advanceAmount" class="form-control">
                                </td>
                            </tr>
                        </table>
                    </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                        <table>
                            <tr>
                                <td width="40%">
                                   <label for="destination">Destination :</label> 
                                </td>
                                <td>
                                    <input type="text" disabled="disabled" value="<?php echo $detail['DESTINATION'] ?>" name="destination"  id="destination" class="form-control">
                                </td>
                            </tr>
                        </table>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                        <table>
                            <tr>
                                <td width="40%">
                                   <label for="purpose">Purpose :</label> 
                                </td>
                                <td>
                                    <input type="text" disabled="disabled" value="<?php echo $detail['PURPOSE']; ?>" name="purpose"  id="purpose" class="form-control">
                                </td>
                            </tr>
                        </table>
                    </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                        <table>
                            <tr>
                                <td width="40%">
                                    <label for="departureDate">Departure Date :</label>
                                </td>
                                <td>
                                    <input  type="text" disabled="disabled" value="<?php echo $detail['DEPARTURE_DATE']; ?>" name="departureDate" id="departureDate" class="form-control">
                                </td>
                            </tr>
                        </table>
                    </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                        <table>
                            <tr>
                                <td width="40%">
                                   <label for="employeeCode">Returned Date :</label> 
                                </td>
                                <td>
                                    <input  value="<?php echo $detail['RETURNED_DATE']; ?>" type="text"  disabled="disabled" name="returnedDate" id="returnedDate" class="form-control"> 
                                </td>
                            </tr>
                        </table>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                       <label for="advanceAmount">Requested Date :</label> 
                                    </td>
                                    <td>
                                        <input  value="<?php echo $requestedDt; ?>" type="text"  disabled="disabled" name="returnedDate" id="returnedDate" class="form-control"> 
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                       <label for="destination">Status :</label> 
                                    </td>
                                    <td>
                                        <?php
                                        if ($status == 'RQ') {
                                            $currentStatus = "Pending";
                                        } else if ($status == 'RC') {
                                            $currentStatus = "Recommended";
                                        } else if ($status == 'AP') {
                                            $currentStatus = "Approved";
                                        } else if ($status == "R") {
                                            $currentStatus = "Rejected";
                                        } else if ($status == "C") {
                                            $currentStatus = "Cancelled";
                                        } ?>
                                        <input  value="<?php echo $currentStatus; ?>" type="text" disabled="disabled" name="returnedDate" id="returnedDate" class="form-control"> 
                                    </td>
                                </tr>
                            </table>
                        </div> 
                    </div>
                <div class="margin-top-10 scrollbar-horizantal">
                    <table width="100%" align="center" class="table table-striped table-bordered table-hover no-footer customTable div-font-11">
                    <thead style="font-size:11px !important;">
                        <tr>
                            <th colspan="6" align="center">Description of Travel and Place</th>
                            <th rowspan="3">Mode of Travel</th>
                            <th rowspan="3">Fare</th>
                            <th rowspan="3">Daily Allowance</th>
                            <th rowspan="3">Local Conveyence</th>
                            <th rowspan="3">Misc. Expenses</th>
                            <th rowspan="3">Total</th>
                            <th rowspan="3">Remarks</th>
                        </tr>
                        <tr>
                            <th colspan="3">Departure</th>
                            <th colspan="3">Destination</th>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Place</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Place</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($expenseDtlList as $expenseDtlRow){ ?>
                        <tr>
                            <td>
                                <input type="text" value="<?= $expenseDtlRow['DEPARTURE_DATE']; ?>"  readonly="readonly" name="departureDate" size="13"/>
                            </td>
                            <td>
                                <input type="text"  value="<?= $expenseDtlRow['DEPARTURE_TIME']; ?>" readonly="readonly" name="departureTime"  size="9" />
                            </td>
                            <td>
                                <input type="text" value="<?= $expenseDtlRow['DEPARTURE_PLACE']; ?>"  readonly="readonly" name="departurePlace" size="11"/>
                            </td>
                            <td>
                                <input  type="text" value="<?= $expenseDtlRow['DESTINATION_DATE']; ?>"   readonly="readonly" name="destinationDate" size="13"/>
                            </td>
                            <td>
                                <input type="text" value="<?= $expenseDtlRow['DESTINATION_TIME']; ?>"  readonly="readonly" name="destinationTime" size="9"/>
                            </td>
                            <td>
                                <input type="text" value="<?= $expenseDtlRow['DESTINATION_PLACE']; ?>"  readonly="readonly" name="destinationPlace" size="11"/>
                            </td>
                            <td>
                                <select style="width: 110px;" class="form-control" name="transportType"  disabled="disabled" id="transportType" >
                                    <?php foreach($transportType as $key=>$value){ 
                                            $selected = ($key==$expenseDtlRow['TRANSPORT_TYPE']) ? "selected" : "";
                                        ?>
                                        <option value="<?= $key; ?>" <?= $selected; ?>><?= $value; ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>
                                <input type="number" value="<?= $expenseDtlRow['FARE']; ?>" readonly="readonly" name="fare" style="width: 60px;" step="0.01" min="0"/>
                            </td>
                            <td>
                                <input type="number" value="<?= $expenseDtlRow['ALLOWANCE']; ?>"  readonly="readonly" style="width: 60px;" step="0.01" min="0"/>
                            </td>
                            <td>
                                <input type="number" value="<?= $expenseDtlRow['LOCAL_CONVEYENCE']; ?>"  readonly="readonly" style="width: 69px;" step="0.01" min="0"/>
                            </td>
                            <td>
                                <input type="number" value="<?= $expenseDtlRow['MISC_EXPENSES']; ?>"  readonly="readonly" style="width: 60px;" step="0.01" min="0"/>
                            </td>
                            <td>
                                <input type="number" value="<?= $expenseDtlRow['TOTAL_AMOUNT']; ?>"  id="total"  readonly="readonly" name="total" style="width: 72px;" step="0.01" min="0"/>
                            </td>
                            <td>
                                <input type="text" value="<?= $expenseDtlRow['REMARKS']; ?>" readonly="readonly" size="11"/>
                            </td>
                        </tr>
                        <?php } ?>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                            </td>
                            <td><b>Total:</b></td>
                            <td>
                                 <input type="number" value="<?= $detail['REQUESTED_AMOUNT']; ?>"  readonly="readonly" id="sumAllTotal" step="0.01" min="0" readonly="readonly" style="width: 72px;" />
                            </td>
                            <td>
                            </td>
                        </tr>
                    </tbody>
                </table>
                </div>
                <div class="submit_button" style="margin-top:2%;">
                    <?php if (($status == 'RC' || $status == 'AP' || $status == 'R') && $recommApprove==0) {
                        $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
                        ?>
                        <div class="form-group padding-0">
                            <label>Reason for action [From Recommender]</label>
                            <?php print $this->formElement($recommendedRemarks); ?>
                        </div>
                    <?php } 
                    if($status=='RC' || $status=='RQ' || $status=='AP' || ($status=='R' && $approvedDT!=null)){ ?>
                    <div class="form-group padding-0">
                        <?php print $this->formLabel($approvedRemarks); ?>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                    <?php } ?>
                    
                    <?php if ($status == 'RQ' || $status == 'RC') { ?>
                        <?php print $this->formSubmit($submit); ?>
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                    <?php } ?>   
                </div>
            </div>
        </div>
    </div>
</div>
<?php

print $this->form()->closeTag();

?>
