<?php
//load js scripts
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/Payroll/Generate/generate.js'));
?>


<script>
    document.menu =<?php
$menu = ["id" => "menuPayroll", "subMenu" => ["id" => "subMenuGenerate"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.rules =<?= json_encode($rules) ?>;
    document.employeeList =<?= json_encode($employeeList) ?>;
    document.branches =<?= json_encode($branches) ?>;
    document.fiscalYears =<?= json_encode($fiscalYears) ?>;</script>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\generate')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="generateController">
    <div class="row margin-top-10">
        <div class="col-sm-2">
            <div class="portlet solid grey">
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-12 " >
                            <label>Generated Months</label>
                            <select class="form-control" ng-model="generatedMonthId" ng-change="viewMonthlySheet(generatedMonthId)" ng-options="month.MONTH_ID as month.MONTH_EDESC for month in payRollGeneratedMonths">
                                <option value="">Select Month</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-10">
            <div class="portlet solid grey">
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <label>Fiscal year</label>
                            <select class="form-control" ng-change="changeYear()" ng-model="fiscalYearId" ng-options="key as fiscalYear for (key, fiscalYear) in fiscalYears">
                                <option value="">Select Year</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <label>Months</label>
                            <select class="form-control" ng-model="monthId" ng-options="month.MONTH_ID as month.MONTH_EDESC for month in months" ng-change="viewMonthlySheetIfAvailable()">
                                <option value="">Select Month</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Branch</label>
                            <select class="form-control" ng-change="changeBranch()" ng-model="branchId" ng-options="key as branch for (key, branch) in branches">
                                <option value="">All</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Employee</label>
                            <select class="form-control" ng-change="viewMonthlySheetIfAvailable()"  ng-model="employeeId" ng-options="key as employee for (key, employee) in employeeList">
                                <option value="">All</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>
                                &nbsp;
                            </label>
                            <button id="generateBtn" class=" form-control red " regenerateFlag="false">
                                Generate
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>



    <div class="row margin-top-10">
        <div class="col-sm-12">
            <div id="salarySheetTable">
            </div>
        </div>
    </div>

</div>

<!--        <table class="table">
            <thead>
            <th>
                Employee Name
            </th>
            <th ng-repeat="rule in rules">
                <span ng-bind="rule"></span>
            </th>
            <th>
                Calculated Value
            </th>
            </thead>
            <tbody>
                <tr ng-repeat="(key, empDataVal) in employeeRuleValues">
                    <td ng-bind="employeeList[key]"></td>
                    <td ng-repeat="(ruleId, rule) in rules" ng-bind="empDataVal.ruleValueKV[ruleId]">
                    </td>
                    <td ng-bind="empDataVal.calculatedValue">

                    </td>
                </tr>

            </tbody>
        </table>-->