<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\overtimeStatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
/**
 * Load Javascript files here
 */
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/overtime-request/add.js'))
            ->appendFile($this->basePath('js/manager-service/overtime-approve/view.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('class', 'overtimeRequest-form');
$form->setAttribute('id', 'overtimeRequest-form');

$overtimeDate = $form->get('overtimeDate');
$overtimeDate->setAttributes(["disabled"=>"disabled"]);
$startTime = $form->get('startTime');
$startTime->setValue("10:00 AM");
$startTime->setAttributes(['readonly' => "readonly"]);
$endTime = $form->get('endTime');
$endTime->setValue("5:00 PM");
$endTime->setAttributes(['readonly' => "readonly"]);
$description = $form->get('description');
$description->setAttributes(["disabled"=>"disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled"=>"disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['required' => 'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required' => 'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');
$submit->setAttribute('id','approve');

$form->setAttribute('action', $this->url('overtimeStatus', ['action' => 'view', 'id' => $id]));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.employeeId =<?= json_encode($employeeId) ?>;
</script>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Overtime Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="border-bottom margin-bottom-10">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Employee Name
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $employeeName; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDt; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == 'RQ') {
                                                echo "Pending";
                                            } else if ($status == 'RC') {
                                                echo "Recommended";
                                            } else if ($status == 'AP') {
                                                echo "Approved";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group <?= empty($overtimeDate->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($overtimeDate); ?>
                                <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($overtimeDate); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($overtimeDate, ['class' => 'help-block error']); ?>
                        </div>     
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="nepaliDate">&nbsp;</label>
                                <input disabled="disabled" placeholder="Overtime Date Nepali" type="text" name="nepaliDate" id="nepaliDate"
                                           class="form-control" value="">
                            </div>
                        </div>  
                        <div class="col-sm-4">
                            <div class="form-group <?= empty($description->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($description); ?>
                                <?php print $this->formElement($description); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($description, ['class' => 'help-block error']); ?>
                        </div>
                    </div>     

                    <div class="row">
                        <div class="col-sm-8">
                        <table width='100%' style="margin-bottom:10px;">
                            <tr>
                                <td class="col-sm-4" style="padding:0px;"><label>Start Time</label></td>
                                <td class="col-sm-4" style="padding:0px;"><label>End Time</label></td>
                                <td><label>Total Hour</label></td>
                            </tr>
                            <?php foreach($overtimeDetails as $detail){ ?>
                            <tr height="30"> 
                                <td width="45%" style="padding-right:5px;">
                                    <input timepicker type="text" size="3" class="form-control" name="startTime[]"  value="<?= $detail['START_TIME']; ?>" required="required" readonly="readonly"/>
                                </td>
                                <td width="45%" style="padding:5px;">
                                    <input timepicker type="text" size="3"  class="form-control" name="endTime[]"   value="<?= $detail['END_TIME']; ?>" required="required" readonly="readonly"/>
                                </td>
                                <td width="45%" style="padding:5px;">
                                    <input type="text" size="3" class="form-control" name="totalHour[]"  value="<?= $detail['TOTAL_HOUR']; ?>"  required="required" readonly="readonly"/>
                                </td>
                            </tr>
                            <?php } ?>
                            <tr height="30">
                                </td>
                                <td>
                                </td>
                                <td width="45%" style="padding:5px;">
                                    <label class="pull-right">Total Hour:</label>
                                </td>
                                <td width="45%" style="padding:5px;"> 
                                    <input size="3" class="form-control" type="text" name="allTotalHour" id="sumAllTotal" step="0.01" min="0" readonly="readonly"  value="<?= $totalHour; ?>" />
                                </td>
                                <td>
                            </tr>
                        </table>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group <?= empty($remarks->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <?php
                if (($status == 'RC' || $status == 'AP' || $status == 'R') && $recommApprove == 0) {
                    $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
                    ?>
                    <div class="form-group padding-0">
                        <label>Reason for action [From Recommender]</label>
                        <?php print $this->formElement($recommendedRemarks); ?>
                    </div>
                    <?php
                }
                if ($status == 'RC' || $status == 'RQ' || $status == 'AP' || ($status == 'R' && $approvedDT != null)) {
                    ?>
                    <div class="form-group padding-0">
                        <?php print $this->formLabel($approvedRemarks); ?>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php } ?>

                <?php if ($status == 'RQ' || $status == 'RC') { ?>
                    <?php print $this->formSubmit($submit); ?>
                    <input type="submit" name="submit" class="btn btn-danger pull-right" value="Reject">
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>
