<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/please-wait/build/please-wait.css'));
$this->headLink()->appendStylesheet($this->basePath('css/please-wait-custom.css'));
$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/please-wait/build/please-wait.min.js'));
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/Payroll/salary-sheet-lock/index.js'));

?>
<script>
    document.data =<?php echo $data; ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('salarysheetlock', ['action' => 'getFiscalYearMonth']); ?>';
    document.pullGroupEmployeeLink = '<?php echo $this->url('salarysheetlock', ['action' => 'pullGroupEmployee']); ?>';
    document.bulkActionLink = '<?= $this->url("salarysheetlock", ["action" => "bulkApproveLock"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salarySheet')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-money"></i>Salary Sheet 
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Salary Type</label>
                <select class="form-control" name="salaryType" id="salaryTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Company</label>
                <select  class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Group</label>
                <select multiple="multiple" class="form-control" name="group" id="groupId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Sheet</label>
                <select class="form-control" name="allSheetId" id="allSheetId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <select id="fiscalYearId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="monthId">
                </select>
            </div>
            <div class="col-sm-4">
                <button id="viewBtn" style="margin-bottom: 20px;" class="btn yellow-saffron pull-right">View</button>
            </div>
        </div>
        
        <div id="employeeTableDiv">
            <div id="sheetTable">
            </div>
            <div style="display: none;" class="row margin-top-20" id="bulkActionDiv" >
                <div class="col-sm-2 " id="bulkApproveDiv">
                    <button action="approve" class="btn btn-primary">Approved</button>
                </div>
                <div class="col-sm-2 "id="bulkNotApproveDiv">
                    <button action="unapprove" class="btn btn-primary">Not Approved</button>
                </div>
                <div class="col-sm-4 ">
                </div>
                <div class="col-sm-2 " id="bulkLockDiv">
                    <button action="lock" class="btn btn-danger">Locked</button>
                </div>
                <!-- <div class="col-sm-2 " id="bulkUnlockDiv">
                    <button action="unlock" class="btn btn-primary">Unlocked</button>
                </div> -->
        </div>
    </div>
</div>
