<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/codemirror-5.19.0/lib/codemirror.css'));


$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/codemirror-5.19.0/lib/codemirror.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/ShiftAdjustment/form-wizard.js'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
        ->appendFile($this->basePath('js/AttendanceManagement/ShiftAdjustment/add.js'))
        ->appendFile($this->basePath('js/search.js'))
?>

<?php
$startTime = $form->get('startTime');
$endTime = $form->get('endTime');
$adjustmentStartDate = $form->get('adjustmentStartDate');
$adjustmentEndDate = $form->get('adjustmentEndDate');
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.addShiftAdjustUrl = '<?php echo $this->url('shiftAdjustment', ['action' => 'addShiftAdjustUrl']); ?>';


</script>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\rules')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="portlet box blue" id="form_wizard_1">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Shift Adjustment - <span class="step-title">
                Step 1 of 4 </span>
        </div>
        <div class="tools hidden-xs">
            <a href="javascript:;" class="collapse">
            </a>
            <a href="#portlet-config" data-toggle="modal" class="config">
            </a>
            <a href="javascript:;" class="reload">
            </a>
            <a href="javascript:;" class="remove">
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <form action="#" class="form-horizontal" id="submit_form" method="POST">
            <div class="form-wizard">
                <div class="form-body">
                    <ul class="nav nav-pills nav-justified steps">
                        <li>
                            <a href="#tab1" data-toggle="tab" class="step">
                                <span class="number">
                                    1 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Adjustment </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab2" data-toggle="tab" class="step">
                                <span class="number">
                                    2 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Shift Adjustment Assign </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab3" data-toggle="tab" class="step active">
                                <span class="number">
                                    3 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Finalize </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab4" data-toggle="tab" class="step">
                                <span class="number">
                                    4 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Confirm </span>
                            </a>
                        </li>
                    </ul>
                    <div id="bar" class="progress progress-striped" role="progressbar">
                        <div class="progress-bar progress-bar-success">
                        </div>
                    </div>
                    <div class="tab-content">
                        <div class="alert alert-danger display-none">
                            <button class="close" data-dismiss="alert"></button>
                            You have some form errors. Please check below.
                        </div>
                        <div class="alert alert-success display-none">
                            <button class="close" data-dismiss="alert"></button>
                            Your form validation is successful!
                        </div>
                        <div class="tab-pane active" id="tab1">
                            <h3 class="block">Shift Assign</h3>

                            <!--Start of tab1-->
                            <div class="row">
                                <div class="col-sm-6">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div
                                                class="form-group  required  <?= empty($adjustmentStartDate->getMessages()) ? "" : "error" ?>">
                                                    <?php print $this->formLabel($adjustmentStartDate) ?>
                                                    <?php print $this->formElement($adjustmentStartDate) ?>
                                            </div>
                                            <?php print $this->formElementErrors()->render($adjustmentStartDate, ['class' => 'help-block error']) ?>
                                        </div>    

                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliStartDate">&nbsp;</label>
                                                <div class="input-group">
                                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate"
                                                           class="form-control" value="">
                                                </div>   
                                            </div>    
                                        </div> 


                                    </div>
                                </div>

                                <div class="col-sm-6">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div
                                                class="form-group required  <?= empty($adjustmentEndDate->getMessages()) ? "" : "error" ?>">
                                                    <?php print $this->formLabel($adjustmentEndDate) ?>
                                                    <?php print $this->formElement($adjustmentEndDate) ?>
                                            </div>
                                            <?php print $this->formElementErrors()->render($adjustmentEndDate, ['class' => 'help-block error']) ?>
                                        </div>     
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliEndDate">&nbsp;</label>
                                                <div class="input-group">
                                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate"
                                                           class="form-control" value="">
                                                </div>
                                            </div>
                                        </div>     
                                    </div>   

                                </div>
                            </div>

                            <div class="row">

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($startTime) ?>
                                        <div class="input-group dropdown-select">
                                            <?php print $this->formElement($startTime) ?>
                                        </div>
                                    </div>
                                    <?php print $this->formElementErrors()->render($startTime, ['class' => 'help-block error']) ?>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group required">
                                        <?php print $this->formLabel($endTime) ?>
                                        <div class="input-group dropdown-select">
                                            <?php print $this->formElement($endTime) ?>
                                        </div>
                                    </div>
                                    <?php print $this->formElementErrors()->render($endTime, ['class' => 'help-block error']) ?>
                                </div>

                            </div>
                            <!--end of tab1-->



                        </div>
                        <div class="tab-pane" id="tab2">
                            <h3 class="block">Assign</h3>

                            <!--adjustment shift assign start-->
                            
                            <div class="" ng-app="hris" ng-controller="ShiftAjustmentController">

                            <div class="row">
                                <div class="col-sm-2">
                                    <select class="form-control" name="company" id="companyId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="branchId" id="branchId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="department" id="departmentId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="designation" id="designationId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="position" id="positionId">
                                    </select>
                                </div>
                            </div>
                            <div class="row margin-top-10 margin-bottom-20">
                                <div class="col-sm-2">
                                    <select class="form-control" name="serviceType" id="serviceTypeId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="gender" id="genderId">
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <select class="form-control" name="employee" id="employeeId">
                                    </select>
                                </div>
                                <div class="col-sm-4 ">
                                    <button  ng-click="view()" class="btn btn-default btn-sm pull-right">
                                        Search
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                                
                                
                                
                                </div>
                            <!--adjustemnt shift assign end-->







                        </div>
                        <div class="tab-pane" id="tab3">
                            <h3 class="block">Provide your billing and credit card details</h3>
                            <div class="form-group">
                                <label class="control-label col-md-3">Card Holder Name <span class="required">
                                        * </span>
                                </label>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" name="card_name"/>
                                    <span class="help-block">
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Card Number <span class="required">
                                        * </span>
                                </label>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" name="card_number"/>
                                    <span class="help-block">
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">CVC <span class="required">
                                        * </span>
                                </label>
                                <div class="col-md-4">
                                    <input type="text" placeholder="" class="form-control" name="card_cvc"/>
                                    <span class="help-block">
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Expiration(MM/YYYY) <span class="required">
                                        * </span>
                                </label>
                                <div class="col-md-4">
                                    <input type="text" placeholder="MM/YYYY" maxlength="7" class="form-control" name="card_expiry_date"/>
                                    <span class="help-block">
                                        e.g 11/2020 </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Payment Options <span class="required">
                                        * </span>
                                </label>
                                <div class="col-md-4">
                                    <div class="checkbox-list">
                                        <label>
                                            <input type="checkbox" name="payment[]" value="1" data-title="Auto-Pay with this Credit Card."/> Auto-Pay with this Credit Card </label>
                                        <label>
                                            <input type="checkbox" name="payment[]" value="2" data-title="Email me monthly billing."/> Email me monthly billing </label>
                                    </div>
                                    <div id="form_payment_error">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="tab4">
                            <h3 class="block">Confirm your account</h3>
                            <h4 class="form-section">Account</h4>
                            <div class="form-group">
                                <label class="control-label col-md-3">Username:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="username">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Email:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="email">
                                    </p>
                                </div>
                            </div>
                            <h4 class="form-section">Profile</h4>
                            <div class="form-group">
                                <label class="control-label col-md-3">Fullname:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="fullname">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Gender:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="gender">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Phone:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="phone">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Address:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="address">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">City/Town:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="city">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Country:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="country">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Remarks:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="remarks">
                                    </p>
                                </div>
                            </div>
                            <h4 class="form-section">Billing</h4>
                            <div class="form-group">
                                <label class="control-label col-md-3">Card Holder Name:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="card_name">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Card Number:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="card_number">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">CVC:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="card_cvc">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Expiration:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="card_expiry_date">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Payment Options:</label>
                                <div class="col-md-4">
                                    <p class="form-control-static" data-display="payment[]">
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <a href="javascript:;" class="btn default button-previous">
                                <i class="m-icon-swapleft"></i> Back </a>
                            <a href="javascript:;" class="btn blue button-next">
                                Continue <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                            <a href="javascript:;" class="btn green button-submit">
                                Submit <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>