<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/codemirror-5.19.0/lib/codemirror.css'));


$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/codemirror-5.19.0/lib/codemirror.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/ShiftAdjustment/form-wizard.js'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
        ->appendFile($this->basePath('js/AttendanceManagement/ShiftAdjustment/add.js'))
        ->appendFile($this->basePath('js/search.js'))
?>

<?php
$startTime = $form->get('startTime');
$endTime = $form->get('endTime');
$adjustmentStartDate = $form->get('adjustmentStartDate');
$adjustmentEndDate = $form->get('adjustmentEndDate');
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.wsGetEmployeeList = '<?php echo $this->url('shiftAdjustment', ['action' => 'getEmployeeList']); ?>';
    document.getShiftAdjustmentAE = '<?php echo $this->url('shiftAdjustment', ['action' => 'getShiftAdjustmentAssignedEmployees']); ?>';
    document.addShiftAdjustUrl = '<?php echo $this->url('shiftAdjustment', ['action' => 'addShiftAdjustUrl']); ?>';


</script>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\rules')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="portlet box blue" id="form_wizard_1">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Shift Adjustment - <span class="step-title">
                Step 1 of 4 </span>
        </div>
        <div class="tools hidden-xs">
            <a href="javascript:;" class="collapse">
            </a>
            <a href="#portlet-config" data-toggle="modal" class="config">
            </a>
            <a href="javascript:;" class="reload">
            </a>
            <a href="javascript:;" class="remove">
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <form action="<?php echo $this->url('shiftAdjustment', ['action' => 'shiftAdjustAdd']); ?>" class="form-horizontal" id="submit_form" method="POST">
            <div class="form-wizard">
                <div class="form-body">
                    <ul class="nav nav-pills nav-justified steps">
                        <li>
                            <a href="#tab1" data-toggle="tab" class="step">
                                <span class="number">
                                    1 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Adjustment </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab2" data-toggle="tab" class="step">
                                <span class="number">
                                    2 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Shift Adjustment Assign </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab3" data-toggle="tab" class="step active">
                                <span class="number">
                                    3 </span>
                                <span class="desc">
                                    <i class="fa fa-check"></i> Finalize </span>
                            </a>
                        </li>
                    </ul>
                    <div id="bar" class="progress progress-striped" role="progressbar">
                        <div class="progress-bar progress-bar-success">
                        </div>
                    </div>
                    <div class="tab-content">
                        <div class="alert alert-danger display-none">
                            <button class="close" data-dismiss="alert"></button>
                            You have some form errors. Please check below.
                        </div>
                        <div class="alert alert-success display-none">
                            <button class="close" data-dismiss="alert"></button>
                            Your form validation is successful!
                        </div>
                        <div class="tab-pane active" id="tab1">
                            <h3 class="block">Shift Assign</h3>

                            <!--Start of tab1-->
                            <div class="row">
                                <div class="col-sm-6">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div
                                                class="form-group  required  <?= empty($adjustmentStartDate->getMessages()) ? "" : "error" ?>">
                                                    <?php print $this->formLabel($adjustmentStartDate) ?>
                                                    <?php print $this->formElement($adjustmentStartDate) ?>
                                            </div>
                                            <?php print $this->formElementErrors()->render($adjustmentStartDate, ['class' => 'help-block error']) ?>
                                        </div>    

                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliStartDate">&nbsp;</label>
                                                <div class="input-group">
                                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate"
                                                           class="form-control" value="">
                                                </div>   
                                            </div>    
                                        </div> 


                                    </div>
                                </div>

                                <div class="col-sm-6">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div
                                                class="form-group required  <?= empty($adjustmentEndDate->getMessages()) ? "" : "error" ?>">
                                                    <?php print $this->formLabel($adjustmentEndDate) ?>
                                                    <?php print $this->formElement($adjustmentEndDate) ?>
                                            </div>
                                            <?php print $this->formElementErrors()->render($adjustmentEndDate, ['class' => 'help-block error']) ?>
                                        </div>     
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliEndDate">&nbsp;</label>
                                                <div class="input-group">
                                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate"
                                                           class="form-control" value="">
                                                </div>
                                            </div>
                                        </div>     
                                    </div>   

                                </div>
                            </div>

                            <div class="row">

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($startTime) ?>
                                        <div class="input-group dropdown-select">
                                            <?php print $this->formElement($startTime) ?>
                                        </div>
                                    </div>
                                    <span id="errorStartTime"></span>
                                    <?php print $this->formElementErrors()->render($startTime, ['class' => 'help-block error']) ?>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group required">
                                        <?php print $this->formLabel($endTime) ?>
                                        <div class="input-group dropdown-select">
                                            <?php print $this->formElement($endTime) ?>
                                        </div>
                                    </div>
                                    <span id="errorEndTime"></span>
                                    <?php print $this->formElementErrors()->render($endTime, ['class' => 'help-block error']) ?>
                                </div>

                            </div>
                            <!--end of tab1-->



                        </div>
                        <div class="tab-pane" id="tab2">
                            <h3 class="block">Assign</h3>

                            <!--adjustment shift assign start-->

                            <!--<div class="" ng-app="hris" ng-controller="ShiftAjustmentController">-->

                                <div class="row">
                                    <div class="col-sm-2">
                                        <select class="form-control" name="company" id="companyId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="branchId" id="branchId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="department" id="departmentId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="designation" id="designationId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="position" id="positionId">
                                        </select>
                                    </div>
                                </div>
                                <div class="row margin-top-10 margin-bottom-20">
                                    <div class="col-sm-2">
                                        <select class="form-control" name="serviceType" id="serviceTypeId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="gender" id="genderId">
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <select class="form-control" name="employee" id="employeeId">
                                        </select>
                                    </div>
                                    <div class="col-sm-4 ">
                                        <button type="button" id="filterEmp" class="btn btn-default btn-sm pull-right">
                                            Search
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>


                                <div class="scroller"  style="min-height:300px;height: 400px;" id="loadingDiv">
                                    <table id="employeeTable" class="table table-striped table-bordered table-hover no-footer custometbletwo">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Employee
                                                </th>
                                                <th>
                                                    Branch
                                                </th>
                                                <th>
                                                    Department
                                                </th>
                                                <th>
                                                    Designation
                                                </th>
                                                <th>
                                                    Position
                                                </th>
                                                <th>
                                                    Service Type
                                                </th>
                                                <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                                                    <div class="th-inner ">
                                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                            <input class="" type="checkbox" id="ckeckAll"/>
                                                            <span></span>
                                                        </label>
                                                    </div>
                                                    <div class="fht-cell" style="width: 46px;"></div>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>
                                </div>   

<!--                                <div class="row margin-top-30" >
                                    <div class="col-sm-10">
                                        <button class="pull-right btn btn-sm btn-primary"  ng-click="assign()">
                                            Assign
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </div>
                                </div>-->



                            <!--</div>-->
                            <!--adjustemnt shift assign end-->







                        </div>
                        <div class="tab-pane" id="tab3">
                            <h3 class="block">Finalize</h3>
                           
                            
                            
                           
                        </div>
                
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <a href="javascript:;" class="btn default button-previous">
                                <i class="m-icon-swapleft"></i> Back </a>
                            <a href="javascript:;" class="btn blue button-next">
                                Continue <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                            <a href="javascript:;" class="btn green button-submit">
                                Submit <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>