<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/AttendanceManagement/ShiftAdjustment/index.js'));
?>

<script>
    document.shiftsAdjust =<?php echo json_encode($shiftsAdjust) ?>;
    document.addLink ='<?= $this->url("shiftAdjustment", ["action" => "add"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\shiftAdjustment')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">

    <div class="portlet light bg-inverse">

        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('shiftAdjustment', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="shiftAdjustmentTable">
        </div>
    </div>
<!--
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (ADJUSTMENT_START_DATE == null) ? '-' : ADJUSTMENT_START_DATE #
        </td>
        <td>
        #: (ADJUSTMENT_END_DATE == null) ? '-' : ADJUSTMENT_END_DATE #
        </td>
        <td>
        #: (START_TIME == null) ? '-' : START_TIME #
        </td>
        <td>
        #: (END_TIME == null) ? '-' : END_TIME #
        </td>
        <td>
        <a class="btn-edit" 
        href="`+ document.addLink +`/#:ADJUSTMENT_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
        </td>
        </tr>
    </script>-->
</div>

