<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/ng-bootstrap-multiselect.js'));
$this->headScript()->appendFile($this->basePath('js/Payroll/FlatValue/flatValueDetailController.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-multiselect/js/bootstrap-multiselect.js'));
?>

<script>
    document.menu =<?php
$menu = ["id" => "menuPayroll", "subMenu" => ["id" => "subMenuFlatValue"], "subMenuChild" => ["id" => "subMenuChildFlatValueDetail"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.branches =<?= json_encode($branches) ?>;
    document.departments =<?= json_encode($departments) ?>;
    document.designations =<?= json_encode($designations) ?>;
    document.flatValues =<?= json_encode($flatValues) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\flatValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div ng-app="hris" ng-controller="flatValueDetailController">
    <div class="row margin-top-20">
        <div class="col-sm-3">

            <div class="portlet shadowlight">
                <div class="portlet-body topgapping">
                    <div class="row">
                        <div class="col-sm-12">
                            <label>
                                Flat Values
                            </label>
                            <div class="mltselect">
                                <multiselect
                                    ng-change="selectedFlatValuesChange()"
                                    ng-model="selectedFlatValues"
                                    options="flatValue.text for flatValue in flatValues"    
                                    data-multiple="true"                 
                                    data-compare-by="id"                 
                                    scroll-after-rows="5"                
                                    filter-after-rows="5"      
                                    max-width="100"                      
                                    tabindex="-1">                     
                                </multiselect>
                                <button ng-click="selectAllFlagFN()" class="select-option" ng-bind="selectAllFlag ? 'Deselect All' : 'Select All'">
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="portlet shadowlight">
                <div class="portlet-body topgapping">
                    <div class="row">
                        <div class="col-sm-3">
                            <label>
                                Branch
                            </label>
                            <select id="branch" class="form-control" ng-model="branch" ng-options="key as branch for (key,branch) in branches">
                                <option value="">All</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <label>
                                Department
                            </label>
                            <select id="department" class="form-control" ng-model="department"
                                    ng-options="key as department for (key,department) in departments">
                                <option value="">All</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <label>
                                Designation
                            </label>
                            <select id="designation" class="form-control" ng-model="designation"
                                    ng-options="key as designation for (key,designation) in designations">
                                <option value="">All</option>
                            </select>
                        </div>

                        <div class="col-sm-2">
<!--                            <label>
                                &nbsp;
                            </label>-->
<button ng-click="view()" class="btn btn-default form-control i-search pull-right" style="margin-top:21px;">
                                View
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="margin-top-20 scroller1">
        <div class="table-responsive">
        <table class="table customTable custom-width">
            <thead>
                <tr>
                    <th class="id-width">
                        Employee Id
                    </th>
                    <th class="flatwidth">
                        Employee Name
                    </th>
                    <th class="keyswidth" ng-repeat="keys in flatValuekeys" ng-bind="flatValuesI[keys]">

                    </th>
                </tr>
            </thead>
            <tbody >
                <tr ng-repeat="row in tableDataCopy">
                    <td ng-bind="row.EMPLOYEE_ID">

                    </td>
                    <td>
                        <span ng-bind="row.FIRST_NAME"></span>
                        <span ng-bind="row.MIDDLE_NAME"></span>
                        <span ng-bind="row.LAST_NAME"></span>
                    </td>
                    <td ng-repeat="keys in flatValuekeys">
                        <input class="form-control" type="number" ng-model="row[keys]">
                    </td>
                </tr>


            </tbody>
            <tfoot>
                <tr>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td ng-repeat="keys in flatValuekeys">
                        <input class="form-control" type="number" ng-model="colVal"
                               ng-change="changeAllColVal(keys, colVal)">
                    </td>
                </tr>
            </tfoot>
        </table>
        </div>
    </div>
    <div class="button-assign">
        <button class="btn btn-success pull-right" ng-click="setflatValue()">Assign flat Value</button>
    </div>
</div>