<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/Payroll/FlatValue/flatValueDetailController.js'));
?>

<script>
    document.menu =<?php
$menu = ["id" => "menuPayroll", "subMenu" => ["id" => "subMenuFlatValue"], "subMenuChild" => ["id" => "subMenuChildFlatValueDetail"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.branches =<?= json_encode($branches) ?>;
    document.departments =<?= json_encode($departments) ?>;
    document.designations =<?= json_encode($designations) ?>;
    document.flatValues =<?= json_encode($flatValues) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\flatValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div ng-app="hris" ng-controller="flatValueDetailController">
    <div class="row margin-top-20">
        <div class="col-sm-3">
            <label>flat Values</label>
        </div>
        <div class="col-sm-2">
            <label>Branch</label>
        </div>
        <div class="col-sm-2">
            <label>Department</label>
        </div>
        <div class="col-sm-2">
            <label>Designation</label>
        </div>
        <div class="col-sm-1">
        </div>
        <div class="col-sm-2">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <div class="mt-checkbox-list scroller" style="height: 100px;">
                <label class="mt-checkbox mt-checkbox-outline">
                    All
                    <input
                        type="checkbox"
                        value="-1"
                        ng-model="allflatValue"
                        ng-change="selectAllflatValue(allflatValue)">
                    <span></span>
                </label>
                <label class="mt-checkbox mt-checkbox-outline" ng-repeat="flatValue in flatValues">
                    {{flatValue.text}}
                    <input
                        ng-change="updateSelectAll()"
                        type="checkbox"
                        value="{{flatValue.id}}"
                        ng-model="flatValue.selected">
                    <span></span>
                </label>
            </div>
        </div>
        <div class="col-sm-2">
            <select class="form-control" ng-model="branch" ng-options="key as branch for (key,branch) in branches">
                <option value="">All</option>
            </select>
        </div>
        <div class="col-sm-2">
            <select class="form-control" ng-model="department"
                    ng-options="key as department for (key,department) in departments">
                <option value="">All</option>
            </select>
        </div>
        <div class="col-sm-2">
            <select class="form-control" ng-model="designation"
                    ng-options="key as designation for (key,designation) in designations">
                <option value="">All</option>
            </select>
        </div>

        <div class="col-sm-1">
        </div>
        <div class="col-sm-2">
            <button ng-click="view()" class="btn btn-sm yellow pull-right">
                View
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
    <div class="margin-top-20 scroller" style="height: 400px;">
        <table class="table "  >
            <thead>
                <tr>
                    <th>
                        Employee Id
                    </th>
                    <th>
                        Employee Name
                    </th>
                    <th ng-repeat="keys in flatValuekeys" ng-bind="flatValuesI[keys]">

                    </th>
                </tr>
            </thead>
            <tbody >
                <tr ng-repeat="row in tableDataCopy">
                    <td ng-bind="row.EMPLOYEE_ID">

                    </td>
                    <td>
                        <span ng-bind="row.FIRST_NAME"></span>
                        <span ng-bind="row.MIDDLE_NAME"></span>
                        <span ng-bind="row.LAST_NAME"></span>
                    </td>
                    <td ng-repeat="keys in flatValuekeys">
                        <input class="form-control" type="number" ng-model="row[keys]">
                    </td>
                </tr>


            </tbody>
            <tfoot>
                <tr>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td ng-repeat="keys in flatValuekeys">
                        <input class="form-control" type="number" ng-model="colVal"
                               ng-change="changeAllColVal(keys, colVal)">
                    </td>
                </tr>
            </tfoot>
        </table>

    </div>
    <div class="row">
        <button class="btn btn-success pull-right" ng-click="setflatValue()">Assign flat Value</button>
    </div>
</div>