<?php
$this->headScript()
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/Payroll/FlatValue/index.js'));
?>
<script>
    document.menu =<?php $menu = ["id" => "menuPayroll", "subMenu" => ["id" => "subMenuFlatValue"],"subMenuChild"=>["id"=>"subMenuChildFlatValueSetup"]];echo json_encode($menu);?>;
    document.flatValues=<?= json_encode($flatValues); ?>;
</script>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\flatValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('flatValue', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="flatValueTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (FLAT_CODE == null) ? '-' : FLAT_CODE #
        </td>
        <td>
        #: (FLAT_EDESC == null) ? '-' : FLAT_EDESC #
        </td>
        <td>
        #: (FLAT_LDESC == null) ? '-' : FLAT_LDESC #
        </td>
        <td>
        #: (SHOW_AT_RULE == null) ? '-' : SHOW_AT_RULE #
        </td>   
        <td>
        <a class=""
        href="<?= $this->url("flatValue", ["action" => "edit"]); ?>/#:FLAT_ID #">
        Edit
        </a> | 
         <a class=""
        href="<?= $this->url("flatValue", ["action" => "delete"]); ?>/#:FLAT_ID #">
        Delete
        </a>
        </td>
        </tr>
    </script>
    </div>