<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/Payroll/FlatValue/position-wise-flat-value.js'));
?>

<script>
    document.fiscalYears =<?php echo json_encode($fiscalYears); ?>;
    document.flatValues =<?php echo json_encode($flatValues); ?>;
    document.positions =<?php echo json_encode($positions); ?>;
    document.getPositionFlatLink = '<?php echo $this->url('flatValue', ['action' => 'getPositionWiseFlatValue']); ?>';
    document.setPositionFlatValueLink = '<?php echo $this->url('flatValue', ['action' => 'setPositionWiseFlatValue']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\flatValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Filter </span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Fiscal year</label>
                            <select class="form-control reset-field" id="fiscalYearId" >
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Pay Heads</label>
                            <select class="form-control reset-field" id="flatValueId" multiple="multiple">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Positions</label>
                            <select class="form-control reset-field" id="positionId" multiple="multiple">
                            </select>
                        </div>
                        <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                                Reset
                                <i class="fa fa-refresh"></i>
                        </button>
                        <button  id="searchEmployeesBtn" class="btn btn-default btn-sm pull-right">
                            Search
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row margin-top-20">
                <div class="col-sm-12">
                    <button id="assignFlatValueBtn" class="btn pull-right" >Assign Flat Value</button>
                </div>
            </div>
        </div>
        <div id="flatValueDetailTable">
        </div>
    </div>
</div>