<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$title = $form->get('title');
$title->setAttributes(["disabled" => "disabled"]);
$trainingType = $form->get('trainingType');
$trainingType->setValueOptions([$detail['TRAINING_TYPE'] => $detail['TRAINING_TYPE_DETAIL']]);
$trainingType->setAttributes(["disabled" => "disabled"]);
$description = $form->get('description');
$description->setAttributes(["disabled" => "disabled"]);
$startDate = $form->get('startDate');
$startDate->setAttributes(["disabled" => "disabled"]);
$endDate = $form->get('endDate');
$endDate->setAttributes(["disabled" => "disabled"]);
$duration = $form->get('duration');
$duration->setAttributes(["disabled" => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled" => "disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$approvedRemarks = $form->get('approvedRemarks');
$isWithinCompany = $form->get('isWithinCompany');
$isWithinCompany->setAttributes(['disabled' => 'disabled']);
$showBtns = false;
if (in_array($detail['STATUS'], ['RQ', 'RC'])) {
    $approvedRemarks->setAttributes(['required' => 'true']);
    $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
    $showBtns = true;
} else {
    $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
    $approvedRemarks->setAttributes(['disabled' => 'disabled']);
}

$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingStatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Training Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td> Employee Name</td>
                                        <td width="15">:</td>
                                        <td> <?php echo $detail['FULL_NAME']; ?> </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td> Recommender</td>
                                        <td width="15">:</td>
                                        <td> <?php echo $detail['RECOMMENDED_BY_NAME'] == null ? $detail['RECOMMENDER_NAME'] : $detail['RECOMMENDED_BY_NAME']; ?> </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td> Approver</td>
                                        <td width="15">:</td>
                                        <td> <?php echo $detail['APPROVED_BY_NAME'] == null ? $detail['APPROVER_NAME'] : $detail['APPROVED_BY_NAME']; ?> </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td> Your Role </td>
                                        <td width="15">:</td>
                                        <td> Admin </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>  Requested Date </td>
                                        <td width="15">:</td>
                                        <td> <?php echo $detail['REQUESTED_DATE_AD']; ?> | <?php echo $detail['REQUESTED_DATE_BS']; ?></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-md-4">
                                <table>  
                                    <tr height="30">
                                        <td> Status </td>
                                        <td width="15">:</td>
                                        <td>  <?php echo $detail['STATUS_DETAIL']; ?> </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($title); ?>
                                <?php print $this->formElement($title); ?>
                                <?php print $this->formElementErrors()->render($title, ['class' => 'help-block']); ?>
                            </div> 
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($trainingType); ?>
                                <?php print $this->formElement($trainingType); ?>
                                <?php print $this->formElementErrors()->render($trainingType, ['class' => 'help-block']); ?>
                            </div> 
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($description); ?>
                                <?php print $this->formElement($description); ?>
                                <?php print $this->formElementErrors()->render($description, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group required">
                                        <?php print $this->formLabel($startDate) ?>
                                        <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($startDate) ?>
                                        <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliStartDate">&nbsp;</label>
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate" class="form-control" value="">
                                    </div>
                                </div>     
                            </div>        
                        </div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div  class="form-group required">
                                        <?php print $this->formLabel($endDate) ?>
                                        <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($endDate) ?>
                                        <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliEndDate">&nbsp;</label>
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate" class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>     
                            </div>        
                        </div>
                        <div class="col-sm-4">
                            <div   class="form-group required">
                                <?php print $this->formLabel($duration); ?>
                                <?php print $this->formElement($duration); ?>
                                <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>
                            </div>
                        </div>
                        <div class=" col-sm-4 ">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($isWithinCompany); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($isWithinCompany); ?>
                                </div>
                                <?php print $this->formElementErrors()->render($isWithinCompany, ['class' => 'help-block error']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($recommendedRemarks); ?>
                            <?php print $this->formElement($recommendedRemarks); ?>
                            <?php print $this->formElementErrors()->render($recommendedRemarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($approvedRemarks); ?>
                            <?php print $this->formElement($approvedRemarks); ?>
                            <?php print $this->formElementErrors()->render($approvedRemarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <?php if ($showBtns): ?>
                        <?php  if($acl['HR_APPROVE']=='Y'){  ?>
                            <input type="submit" name="submit" class="btn btn-info pull-right" value="Approve">
                            <input type="submit" name="submit" class="btn btn-danger pull-left" value="Reject">
                        <?php }      ?>
                        <?php endif; ?>
                    </div>
                </div>
                <?php print $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
