<?php
$this->headLink()
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveAssign/assignController.js'));
$this->headScript()->appendFile($this->basePath('dropzone/dropzone.min.js'));
?>

<script>
    document.menu =<?php
$menu = ["id" => "menuLeave", "subMenu" => ["id" => "subMenuLeaveAssign"], "subMenuChild" => ["id" => "subMenuChildGroupAssign"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
    document.excelUploadUrl = '<?= $this->url('leaveassign', ["action" => "import"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveassign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$leaveFormElement->setAttributes(["ng-model" => "leaveId"]);
$branchFormElement->setAttribute("ng-model", "branchId");
$departmentFormElement->setAttribute("ng-model", "departmentId");
$genderFormElement->setAttribute("ng-model", "genderId");
$designationFormElement->setAttribute("ng-model", "designationId");
?>
<div ng-app="hris" ng-controller="assignController">
    <div class="margin-top-20  formbg mgap">
        <div class="row">
            <div class="col-xs-12 col-sm-2 cwidth1">
                <?php print $this->formLabel($leaveFormElement); ?>
                <?php print $this->formElement($leaveFormElement); ?>
            </div>
            <div class="col-xs-12 col-sm-2 cwidth2">
                <?php print $this->formLabel($genderFormElement); ?>
                <?php print $this->formElement($genderFormElement); ?>
            </div>
            <div class="col-xs-12 col-sm-2 cwidth3">
                <?php print $this->formLabel($branchFormElement); ?>
                <?php print $this->formElement($branchFormElement); ?>
            </div>
            <div class="col-xs-12 col-sm-3 cwidth4">
                <?php print $this->formLabel($designationFormElement); ?>
                <?php print $this->formElement($designationFormElement); ?>
            </div>
            <div class="col-xs-12 col-sm-3 cwidth5">
                <?php print $this->formLabel($departmentFormElement); ?>
                <?php print $this->formElement($departmentFormElement); ?>
            </div>
            <div class="col-xs-12 col-sm-2 pull-right">
                <button ng-click="view()" id="viewEmployees" class="btn btn-default form-control i-search " style="margin-top:21px !important;">
                    View
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>


    <div class="margin-top-20">
        <div class="row">
            <div class="col-md-offset-6 col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="<?php echo $this->url('leavebalance', ['action' => 'export']); ?>" id="export"> Export To Excel </a>
                        </li>
                        <li>
                            <a ng-click="importExcel()"> Import From Excel </a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="margin-top-20">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover no-footer customTable">
                <thead>
                    <tr role="row">
                        <th>Name</th>
                        <th>Leave</th>
                        <th>Job Title</th>
                        <th>Branch</th>
                        <th>Days</th>
                        <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </th>
                    </tr>
                </thead>
                <tbody id="target">
                    <tr role="row" ng-repeat="item in leaveList">
                        <td>
                            <span ng-bind="item.FIRST_NAME">
                            </span>
                            <span ng-bind="item.MIDDLE_NAME">
                            </span>
                            <span ng-bind="item.LAST_NAME">
                            </span>

                        </td>
                        <td ng-bind="leaveName">
                        </td>
                        <td ng-bind="item.DESIGNATION_TITLE">
                        </td>
                        <td ng-bind="item.BRANCH_NAME">
                        </td>
                        <td>
                            <input class="form-control input-sm" id="balance" style="width: 100px;" type="text" min="0" ng-model="item.BALANCE"/>
                        </td>
                        <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" ng-model="item.checked" type="checkbox"
                                           ng-change="checkUnit(item.checked)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-sm-offset-8 col-sm-2">
                <input class="form-control" type="number" ng-model="daysForAll"
                       ng-change="daysForAllChange(daysForAll)"
                       ng-show="daysForAllFlag"/>
            </div>
            <div class="col-sm-2">
                <button ng-show="daysForAllFlag" class="btn btn-sm green pull-right" ng-click="assign()">
                    Assign
                    <i class="fa fa-edit"></i>
                </button>
            </div>
        </div>
    </div>

    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header">
        <h3 class="modal-title" id="modal-title">Document Upload</h3>
        </div>
        <div class="modal-body" id="modal-body">
        <div class="row">
        <div class="col-sm-12">
        <div id="dropZoneContainer" class="dropzone">
        </div>
        <div class="error" ng-show="!valid">Please upload Image.</div>

        </div>
        </div>
        </div>
        </div>
        <div class="modal-footer">
        <button class="btn btn-primary" type="button" ng-click="ok()">OK</button>
        <button class="btn btn-warning" type="button" ng-click="cancel()">Cancel</button>
        </div>
    </script>


</div>

