<script>
    document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveAssign"]];echo json_encode($menu);?>;
</script>


<div class="panel panel-transparent">
    <div class="panel-heading">
        <div class="panel-title">
            <?= $employee['FIRST_NAME'] ?>
        </div>
        <div class="btn-group pull-right m-b-10">
            <a class="btn btn-default" href="<?= $this->url('leaveassign', ['action' => 'add', 'eid' => $id]) ?>">
                Add new</a>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <div id="detailedTable_wrapper" class="dataTables_wrapper form-inline no-footer">
                <table class="table table-hover table-condensed table-detailed dataTable no-footer" id="detailedTable"
                       role="grid">
                    <thead>
                    <tr role="row">
                        <th class="sorting_disabled" rowspan="1" colspan="1">Leave</th>
                        <th class="sorting_disabled" rowspan="1" colspan="1">Previous Year Bal</th>
                        <th class="sorting_disabled" rowspan="1" colspan="1">Total Days</th>
                        <th class="sorting_disabled" rowspan="1" colspan="1">Balance</th>
                        <th class="sorting_disabled" rowspan="1" colspan="1">Fiscal Year</th>
                        <th class="sorting_disabled" rowspan="1" colspan="1">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($assignList as $index => $assign) : ?>
                        <tr role="row" class="<?= ($index % 2 == 0) ? 'odd' : 'even' ?>">
                            <td class="v-align-middle semi-bold"><?= $assign['LEAVE_ENAME'] ?></td>
                            <td class="v-align-middle"><?= $assign['PREVIOUS_YEAR_BAL'] ?></td>
                            <td class="v-align-middle semi-bold"><?= $assign['TOTAL_DAYS'] ?></td>
                            <td class="v-align-middle"><?= $assign['BALANCE'] ?></td>
                            <td class="v-align-middle semi-bold"><?= $assign['FISCAL_YEAR'] ?></td>
                            <td class="v-align-middle">
                                <a href="<?= $this->url("leaveassign", ["action" => "edit",'eid'=>$id, "id" => $assign['EMPLOYEE_LEAVE_ASSIGN_ID']]) ?>">Edit</a>
                                /
                                <a href="<?= $this->url("leaveassign", ["action" => "delete", "eid"=>$id,"id" => $assign['EMPLOYEE_LEAVE_ASSIGN_ID']]) ?>">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>