<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveAssign/assignController.js'));

?>

<script>
    document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveAssign"], "subMenuChild" => ["id" => "subMenuChildLeaveAssign"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaveassign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$leaveFormElement->setAttributes(["ng-model" => "leaveId"]);
$branchFormElement->setAttribute("ng-model", "branchId");
$departmentFormElement->setAttribute("ng-model", "departmentId");
$genderFormElement->setAttribute("ng-model", "genderId");
$designationFormElement->setAttribute("ng-model", "designationId");
?>
<div ng-app="hris" class="margin-top-20" ng-controller="assignController">
    <div class="row">
        <div class="col-sm-2">
            <?php print $this->formLabel($leaveFormElement); ?>
        </div>
        <div class="col-sm-2">
            <?php print $this->formLabel($genderFormElement); ?>
        </div>
        <div class="col-sm-2">
            <?php print $this->formLabel($branchFormElement); ?>
        </div>
        <div class="col-sm-2">
            <?php print $this->formLabel($designationFormElement); ?>
        </div>
        <div class="col-sm-2">
            <?php print $this->formLabel($departmentFormElement); ?>
        </div>
        <div class="">

        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <?php print $this->formElement($leaveFormElement); ?>
        </div>
        <div class="col-sm-2">
            <div class=" form-group">
                <?php print $this->formElement($genderFormElement); ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div class=" form-group">
                <?php print $this->formElement($branchFormElement); ?>
            </div>
        </div>
        <div class="col-sm-2 ">
            <div class=" form-group">
                <?php print $this->formElement($designationFormElement); ?>
            </div>

        </div>
        <div class="col-sm-2">
            <div class=" form-group">
                <?php print $this->formElement($departmentFormElement); ?>
            </div>
        </div>
        <div class="col-sm-2 ">
            <button ng-click="view()" id="viewEmployees" class="btn btn-primary pull-right">
                View
            </button>
        </div>

    </div>

</div>
    <div class="margin-top-20">
        <table class="table table-striped table-bordered table-hover no-footer">
            <thead>
            <tr role="row">
                <th>Name</th>
                <th>Leave</th>
                <th>Job Title</th>
                <th>Branch</th>
                <th>Days</th>
                <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                    <div class="th-inner ">
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                            <span></span>
                        </label>
                    </div>
                    <div class="fht-cell" style="width: 46px;"></div>
                </th>
            </tr>
            </thead>
            <tbody id="target">
            <tr role="row" ng-repeat="item in leaveList">
                <td>
                    {{ item.FIRST_NAME }} {{ item.MIDDLE_NAME }} {{ item.LAST_NAME }}

                </td>
                <td>
                    {{item.LEAVE_ID}}
                </td>
                <td>
                    {{item.DESIGNATION_TITLE}}
                </td>
                <td>
                    {{item.BRANCH_NAME}}
                </td>
                <td>
                    <input class="form-control input-sm" id="balance" style="width: 100px;" type="text" min="0" ng-model="item.BALANCE"/>
                </td>
                <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                    <div class="th-inner ">
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" ng-model="item.checked" type="checkbox"
                                   ng-change="checkUnit(item.checked)"/>
                            <span></span>
                        </label>
                    </div>
                    <div class="fht-cell" style="width: 46px;"></div>
                </td>
            </tr>
            </tbody>
        </table>


        <div class="row">
            <div class="col-sm-offset-8 col-sm-2">
                <input class="form-control" type="number" ng-model="daysForAll"
                       ng-change="daysForAllChange(daysForAll)"
                       ng-show="daysForAllFlag"/>
            </div>
            <div class="col-sm-2">
                <button class="btn btn-info pull-right" ng-click="assign()">Assign</button>
            </div>
        </div>
    </div>
</div>