<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));
$this->headScript()->appendFile($this->basePath('js/leaveAssign/assign.js'));

?>

<script>
    document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveAssign"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
</script>


<div class="panel panel-transparent">
    <div class="panel-heading">
        <div class="panel-title">
            <div class="form-group-default-select2">
                <?php print $this->formElement($employeesFormElement); ?>
            </div>
        </div>
        <div class="btn-group pull-right m-b-10">
            <a class="btn btn-default" href="<?= $this->url('leaveassign', ['action' => 'add', 'eid' => $id]) ?>">
                Add new</a>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <div id="tableWithSearch_wrapper" class="dataTables_wrapper form-inline no-footer">
            <div class="table-responsive">
                <table class="table table-hover demo-table-search dataTable no-footer" id="tableWithSearch" role="grid"
                       aria-describedby="tableWithSearch_info">
                    <thead>
                    <tr role="row">
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Leave
                        </th>
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Prev Year Bal
                        </th>
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Total Days
                        </th>
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Balance
                        </th>
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Fiscal Year
                        </th>
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Action
                        </th>
                    </tr>
                    </thead>
                    </table>
                </div>
            </div>
        </div>


</div>