<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));
?>

<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveAssign"]];echo json_encode($menu);?>;
</script>
<div class="container">
    <?= $this->navigation('Zend\Navigation\leaveassign')->breadcrumbs()->setMinDepth(0) ?>
</div>
<div class="panel panel-transparent">
    <div class="panel-heading">
        <div class="pull-right">
            <div class="col-xs-12">
                <input type="text" id="search-table" class="form-control pull-right" placeholder="Search">
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <div id="tableWithSearch_wrapper" class="dataTables_wrapper form-inline no-footer">
            <div class="table-responsive">
                <table class="table table-hover demo-table-search dataTable no-footer" id="tableWithSearch" role="grid"
                       aria-describedby="tableWithSearch_info">
                    <thead>
                    <tr role="row">
                        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                            rowspan="1" aria-controls="basicTable" tabindex="0" class="sorting_desc">
                            Employee Code
                        </th>
                        <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1"
                            aria-controls="basicTable" tabindex="0" class="sorting">
                            First Name
                        </th>
                        <th aria-label="Activities: activate to sort column ascending" colspan="1" rowspan="1"
                            aria-controls="basicTable" tabindex="0" class="sorting">
                            Middle Name
                        </th>
                        <th aria-label="Status: activate to sort column ascending" colspan="1" rowspan="1"
                            aria-controls="basicTable" tabindex="0" class="sorting">
                            Last Name
                        </th>
                        <th aria-label="Last Update: activate to sort column ascending" colspan="1" rowspan="1"
                            aria-controls="basicTable" tabindex="0" class="sorting">
                            Date of Birth
                        </th>
                        <th aria-label="Last Update: activate to sort column ascending" colspan="1" rowspan="1"
                            aria-controls="basicTable" tabindex="0" class="sorting">
                            Action
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($employeeList as $employee) : ?>
                        <tr role="row">
                            <td class="v-align-middle sorting_1">
                                <p>
                                    <?php print $this->escapeHtml($employee->employeeCode) ?>
                                </p>
                            </td>
                            <td class="v-align-middle">
                                <p>
                                    <?php print $this->escapeHtml($employee->firstName) ?>
                                </p>
                            </td>
                            <td class="v-align-middle">
                                <p>
                                    <?php print $this->escapeHtml($employee->middleName) ?>
                                </p>
                            </td>
                            <td class="v-align-middle">
                                <p>
                                    <?php print $this->escapeHtml($employee->lastName) ?>

                                </p>
                            <td>
                                <?php print $this->escapeHtml($employee->birthDate) ?>
                            </td>
                            <td class="v-align-middle">
                                <p>
                                    <a href="<?= $this->url("leaveassign", ["action" => "assign", "eid" => $employee->employeeId]) ?>">Assign</a>
                                </p>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

