<?php
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/attendance/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceByHr-form');

$employeeId = $form->get('employeeId');
$attendanceDt = $form->get('attendanceDt');
$inTime = $form->get('inTime');
$inTime->setValue("10:00 AM");
$outTime = $form->get('outTime');
$outTime->setValue("5:00 PM");
$inRemarks = $form->get('inRemarks');
$outRemarks = $form->get('outRemarks');
$totalHour = $form->get('totalHour');
$totalHour->setValue("7.0");
$totalHour->setAttributes(['readonly' => "readonly"]);

$employeeId->setValueOptions($employees);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('attendancebyhr', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuAttendance", "subMenu" => ["id" => "subMenuAttendanceByHr"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attendancebyhr')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Attendance Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div
                    class="form-group <?= empty($employeeId->getMessages()) ? "" : "error" ?> ">
                    <?php print $this->formLabel($employeeId); ?>
                    <?php print $this->formElement($employeeId); ?>
                </div>
                <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block error']); ?>

                <div class="form-group <?= empty($attendanceDt->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($attendanceDt); ?>
                    <div class="input-group date" id="attendanceDt">
                        <?php print $this->formElement($attendanceDt); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
                <?php print $this->formElementErrors()->render($attendanceDt, ['class' => 'help-block error']); ?>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group <?= empty($inTime->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($inTime) ?>
                            <div class="input-group dropdown-select">
                                <?php print $this->formElement($inTime) ?>
                            </div>
                            <?php print $this->formElementErrors()->render($inTime, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group <?= empty($outTime->getMessages()) ? "" : "error" ?> pull-right">
                            <?php print $this->formLabel($outTime) ?>
                            <div class="input-group dropdown-select">
                                <?php print $this->formElement($outTime) ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($outTime, ['class' => 'help-block error']); ?>

                    </div>
                </div>

                <div class="form-group  <?= empty($inRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($inRemarks); ?>
                    <?php print $this->formElement($inRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($inRemarks, ['class' => 'help-block error']); ?>

                <div class="form-group <?= empty($outRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($outRemarks); ?>
                    <?php print $this->formElement($outRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($outRemarks, ['class' => 'help-block error']); ?>

                <div class="form-group <?= empty($totalHour->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($totalHour); ?>
                    <?php print $this->formElement($totalHour); ?>
                </div>
                <?php print $this->formElementErrors()->render($totalHour, ['class' => 'help-block error']); ?>


                <div class="">
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>
