<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('assets/global/plugins/pako-master/dist/pako_deflate.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
    ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('js/table2excel/src/jquery.table2excel.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/AttendanceManagement/by-hr/daily-performance-report.js'));
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.picUrl = '<?= $this->basePath('img/nobody_m.original.jpg'); ?>';
    document.pullAttendanceWS = '<?php echo $this->url('attendancebyhr', ['action' => 'dailyPerformanceReport']); ?>';
    document.pullInOutTimeLink = '<?php echo $this->url('attendancebyhr', ['action' => 'pullInOutTime']); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.allowShiftChange ='<?php echo $allowShiftChange; ?>';
    document.allowTimeChange ='<?php echo $allowTimeChange; ?>';
    var d = new Date();
</script>

<script type="x/kendo-template" id="page-template">
  <div class="page-template">
    <div class="header">
      <div>Maruti Cements Ltd.</div>
      <div>Daily Employee Performance Report As On: #:d.toDateString()#</div>
    </div>
  </div>
</script>

<style>
    /* Page Template for the exported PDF */
    .page-template {
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
    }
    .page-template .header {
        font-weight: bold;
        text-align: center;
      position: absolute;
      top: 30px;
      left: 30px;
      right: 30px;
      border-bottom: 1px solid #888;
    }
    .page-template .footer {
        font-weight: bold;
      position: absolute;
      bottom: 30px;
      left: 30px;
      right: 30px;
      border-top: 1px solid #888;
      text-align: left;
    }
    .page-template .watermark {
      font-weight: bold;
      font-size: 400%;
      text-align: center;
      margin-top: 30%;
      transform: rotate(-35deg) scale(1.7, 1.5);
    }

    /* Content styling */
    .customer-photo {
      display: inline-block;
      width: 32px;
      height: 32px;
      border-radius: 50%;
      background-size: 32px 35px;
      background-position: center center;
      vertical-align: middle;
      line-height: 32px;
      box-shadow: inset 0 0 1px #999, inset 0 0 10px rgba(0,0,0,.2);
      margin-left: 5px;
    }
    kendo-pdf-document .customer-photo {
      border: 1px solid #dedede;
    }
    .customer-name {
      display: inline-block;
      vertical-align: middle;
      line-height: 32px;
      padding-left: 3px;
    }
</style>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attendancebyhr')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF 
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Company</label>
                <select multiple class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Branch</label>
                <select multiple class="form-control" name="branchId" id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Department</label>
                <select multiple class="form-control" name="department" id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Designation</label>
                <select multiple class="form-control" name="designation" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Position</label>
                <select multiple class="form-control" name="position" id="positionId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Service Type</label>
                <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Service Event Type</label>
                <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee Type</label>
                <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Gender</label>
                <select multiple class="form-control" name="gender" id="genderId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Functional Type</label>
                <select multiple class="form-control" name="functionalType" id="functionalTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee</label>
                <select multiple class="form-control" name="employee" id="employeeId">
                </select>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($status); ?>
                <?php print $this->formElement($status); ?>
            </div> 
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <div class="form-group">
                    <label>From Date(AD)</label>
                    <input type="text" id="fromDate" name="fromDate"  class="form-control" placeholder="From Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>From Date(BS)</label>
                    <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>To Date(AD)</label>
                    <input type="text" id="toDate" name="toDate"  class="form-control" placeholder="To Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>To Date(BS)</label>
                    <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($presentStatus); ?>
                <?php print $this->formElement($presentStatus); ?>
            </div> 
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-offset-4 col-sm-8">
                <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div> 

<div id="table">
</div>

