<?php
$this->headScript()->appendFile($this->basePath('plugins/bootstrap-timepicker/bootstrap-timepicker.min.js'));
$this->headScript()->appendFile($this->basePath('js/attendance/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceByHr-form');

$employeeId = $form->get('employeeId');
$attendanceDt = $form->get('attendanceDt');
$inTime = $form->get('inTime');
$outTime = $form->get('outTime');
$inRemarks = $form->get('inRemarks');
$outRemarks = $form->get('outRemarks');
$totalHour = $form->get('totalHour');

$employeeId->setValueOptions($employees);

$submit = $form->get('submit');
$submit->setAttribute('value','Edit');

$form->setAttribute('action', $this->url('attendancebyhr', ['action' => 'edit','id'=>$id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);

?>
    <script>
        document.menu=<?php $menu = ["id" => "menuAttendanceManagement","subMenu"=>["id"=>"subMenuAttendanceByHr"]];echo json_encode($menu);?>;
    </script>

    <div class="row">
        <div class="col-sm-2">

        </div>
        <div class="col-sm-8 bg-light-color padding-30">
            <div class="panel-heading panel-title-head">
                <h4>Attendance Entry</h4>
            </div>
            <div class="panel-body " >
                <div class="form-group form-group-default <?= empty($employeeId->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($employeeId); ?>
                    <?php print $this->formElement($employeeId); ?>
                </div>
                <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($attendanceDt->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($attendanceDt); ?>
                    <?php print $this->formElement($attendanceDt); ?>
                </div>
                <?php print $this->formElementErrors()->render($attendanceDt, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default  <?= empty($inTime->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($inTime); ?>
                    <?php print $this->formElement($inTime); ?>
                </div>
                <?php print $this->formElementErrors()->render($inTime, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($outTime->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($outTime); ?>
                    <?php print $this->formElement($outTime); ?>
                </div>
                <?php print $this->formElementErrors()->render($outTime, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($inRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($inRemarks); ?>
                    <?php print $this->formElement($inRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($inRemarks, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($outRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($outRemarks); ?>
                    <?php print $this->formElement($outRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($outRemarks, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($totalHour->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($totalHour); ?>
                    <?php print $this->formElement($totalHour); ?>
                </div>
                <?php print $this->formElementErrors()->render($totalHour, ['class' => 'help-block error']); ?>




                <div class="">
                    <?php print $this->formSubmit($submit); ?>
                </div>
            </div>

        </div>
    </div>
<?php
print $this->form()->closeTag();
?>