<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuAttendanceManagement", "subMenu" => ["id" => "subMenuAttendanceByHr"]];echo json_encode($menu);?>;
</script>

<?php
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>

<div class="panel panel-transparent">
    <div class="panel-heading">
        <div class="btn-group pull-right m-b-10">
            <a class="btn btn-default" href="<?= $this->url('attendancebyhr', ['action' => 'add']) ?>">
                Attendance Entry
            </a>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <div id="tableWithDynamicRows_wrapper" class="dataTables_wrapper form-inline no-footer">
            <div class="table-responsive">
                <table class="table table-hover demo-table-dynamic dataTable no-footer" id="tableWithDynamicRows"
                       role="grid" aria-describedby="tableWithDynamicRows_info">
                    <thead>
                    <tr role="row">
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Employee Name
                        </th>
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Attendance Date
                        </th>
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Check In
                        </th>
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Check Out
                        </th>
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Late In Reason
                        </th>
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Early Out Reason
                        </th>
                        <th class="sorting_asc" tabindex="0" aria-controls="tableWithExportOptions" rowspan="1" colspan="1" aria-sort="ascending"
                            aria-label="Rendering engine: activate to sort column descending">
                            Action
                        </th>

                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($attendanceList as $attendances):
                        ?>
                        <tr role="row">
                            <td class="">
                                <p>
                                    <?php
                                    print $this->escapeHtml($attendances['FIRST_NAME']." ".$attendances['MIDDLE_NAME']." ".$attendances['LAST_NAME']); ?>
                                </p>
                            </td>
                            <td class="">
                                <p>
                                    <?php print $this->escapeHtml($attendances['ATTENDANCE_DT']); ?>
                                </p>
                            </td>
                            <td class="">
                                <p>
                                    <?php print $this->escapeHtml($attendances['IN_TIME']); ?>
                                </p>
                            </td>
                            <td class="">
                                <p>
                                    <?php print $this->escapeHtml($attendances['OUT_TIME']); ?>
                                </p>
                            </td>
                            <td class="">
                                <p>
                                    <?php print $this->escapeHtml($attendances['IN_REMARKS']); ?>
                                </p>
                            </td>
                            <td class="">
                                <p>
                                    <?php print $this->escapeHtml($attendances['OUT_REMARKS']); ?>
                                </p>
                            </td>

                            <td class="">
                                <a href="<?= $this->url("attendancebyhr", ["action" => "edit", "id" => $attendances['ID']]) ?>">Edit</a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>