<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
    ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/AttendanceManagement/by-hr/raw-attd.js'));

?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.pullAttendanceWS = '<?php echo $this->url('attendancebyhr', ['action' => 'rawAttendance']); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attendancebyhr')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Employee</label>
                <select multiple class="form-control" name="employee" id="employeeId">
                </select>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>From Date(AD)</label>
                    <input type="text" id="fromDate" name="fromDate"  class="form-control" placeholder="From Date" required="required" />
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>From Date(BS)</label>
                    <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>To Date(AD)</label>
                    <input type="text" id="toDate" name="toDate"  class="form-control" placeholder="To Date"/>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>To Date(BS)</label>
                    <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                </div>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-offset-4 col-sm-4">
                <button id="reset" class="btn default btn-sm pull-right">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div> 
<div id="table">
</div>

