<?php
/**
 * Load Javascript files here
 */

$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/leaveStatus.js'));


$form->setAttribute('role', 'form');

$leaveId = $form->get('leaveId');
$leaveId->setValueOptions($leave);
$leaveId->setAttributes(['disabled' => "disabled"]);
$startDate = $form->get('startDate');
$startDate->setAttributes(['disabled' => "disabled"]);
$endDate = $form->get('endDate');
$endDate->setAttributes(['disabled' => "disabled"]);
$noOfDays = $form->get('noOfDays');
$noOfDays->setAttributes(['disabled' => "disabled"]);
$halfDay = $form->get('halfDay');
$halfDay->setAttributes(['disabled' => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(['disabled' => 'disabled']);

$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['required' => 'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required' => 'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('leavestatus', ['action' => 'view', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu =<?php $menu = ["id" => "menuLeave", "subMenu" => ["id" => "subMenuLeaveStatus"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
        document.employeeId=<?= json_encode($employeeId)?>;
    </script>

    <div class="page-bar">
        <?= $this->navigation('Zend\Navigation\leavestatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
    </div>
    <div class="row margin-top-20">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>leave Request Detail
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="border-bottom margin-bottom-10">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <table>
                                        <tr height="30">
                                            <td>
                                                Employee Name
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php echo $employeeName; ?>
                                            </td>
                                        </tr>
                                        <tr height="30">
                                            <td>
                                                Requested Date
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php echo $requestedDt; ?>
                                            </td>
                                        </tr>
                                        <tr height="30">
                                            <td>
                                                Recommender
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php echo $recommender; ?>
                                            </td>
                                        </tr>
                                        <tr height="30">
                                            <td>
                                                Status
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php
                                                if ($status == 'RQ') {
                                                    echo "Pending";
                                                } else if ($status == 'RC') {
                                                    echo "Recommended";
                                                } else if ($status == 'AP') {
                                                    echo "Approved";
                                                } else if ($status == "R") {
                                                    echo "Rejected";
                                                } else if ($status == "C") {
                                                    echo "Cancelled";
                                                } ?>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <table>
                                        <tr height="30">
                                            <td>
                                                Total Assigned Days
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php echo $totalDays; ?>
                                            </td>
                                        </tr>
                                        <tr height="30">
                                            <td>
                                                Available Days
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php echo $availableDays; ?>
                                            </td>
                                        </tr>
                                        <tr height="30">
                                            <td>
                                                Approver
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                <?php echo $approver; ?>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div
                            class="form-group required <?= empty($leaveId->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($leaveId); ?>
                            <?php print $this->formElement($leaveId); ?>
                        </div>

                        <div
                            class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($startDate) ?>
                            <div class="input-group">
                                <?php print $this->formElement($startDate) ?>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>

                        <div
                            class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($endDate) ?>
                            <div class="input-group">
                                <?php print $this->formElement($endDate) ?>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>

                        <div
                            class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($noOfDays); ?>
                            <?php print $this->formElement($noOfDays); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>

                        <?php if($allowHalfDay=='Y'){  ?>
                           <div class="form-group padding-0" id="halfDay">
                               <?php print $this->formLabel($halfDay); ?>
                               <div class="md-radio-inline">
                                   <?php $customRenderer($halfDay); ?>
                               </div>
                           </div>
                           <?php print $this->formElementErrors()->render($halfDay, ['class' => 'help-block error']); ?>
                        <?php } ?>
                        <?php if ($remarkDtl != null) { ?>
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                            </div>
                        <?php } ?>
                    </div>

                    <?php if ($status == 'RC' || $status == 'AP' || $status == 'R') {
                        $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
                        ?>
                        <div class="form-group padding-0">
                            <label>Reason for action [From Recommender]</label>
                            <?php print $this->formElement($recommendedRemarks); ?>
                        </div>
                    <?php } ?>

                    <div class="form-group padding-0">
                        <?php print $this->formLabel($approvedRemarks); ?>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>

                    <?php if ($status == 'RQ' || $status == 'RC') { ?>
                        <?php print $this->formSubmit($submit); ?>
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
<?php

print $this->form()->closeTag();

?>