<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/training/training-attendance/attendance.js'));
?>

<script>
    document.updateUrl = '<?= $this->url("trainingAtt", ["action" => "updateTrainingAtd"]); ?>';
    document.trainingId = '<?= $trainingId; ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingAtt')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if (!empty($list)) {

    $todayDate = date("d-M-Y");
    $fromDate = $list[0]['START_DATE'];
    $toDate = $list[0]['END_DATE'];


    $daterange = new DatePeriod(new DateTime($fromDate), new DateInterval('P1D'), new DateTime($toDate));

    $colDates = [];
    foreach ($daterange as $date) {
        $tempDate = $date->format("d-M-Y");
        array_push($colDates, $tempDate);
    }
    array_push($colDates, $toDate);
}
?>



<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
        </div>

        <?php
        if (!empty($list)) {
            ?>
            <div id="example">
                <table id="grid" class="table">
                    <colgroup>
                        <col />
                        <?php
                        foreach ($colDates as $dates) {
                            ?>
                            <col />
                            <?php
                        }
                        ?>
                    </colgroup>
                    <thead>
                        <tr>
                            <th data-field="name">Name</th>
                            <?php
                            foreach ($colDates as $dates) {
                                ?>
                                <th><?= $dates ?></th>
                                <?php
                            }
                            ?>

                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($list as $listData) {
                            ?>
                            <tr>
                                <td><?php echo $listData['FIRST_NAME'] . ' ' . $listData['MIDDLE_NAME'] . ' ' . $listData['LAST_NAME']; ?></td>
                                <?php
//                            strtotime()
                                $i = 1;
                                foreach ($colDates as $dates) {
                                    if (strtotime($dates) <= strtotime($todayDate)) {
                                        ?>
                                        <td><input data-empId="<?= $listData['EMPLOYEE_ID'] ?>" data-AttDate="<?= $dates ?>" class="trainingAtdChk" type="checkbox" ></td>
                                            <?php
                                        } else {
                                            ?>
                                        <td><input  type="checkbox" disabled="disabled"></td>
                                        <?php
                                    }
                                    $i++;
                                }
                                ?>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
            <?php
        } else {
            ?>
            <div>
                NO Employee Assigned In Training

            </div>
            <?php
        }
        ?>



    </div>
</div>