<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/training/training-attendance/attendance.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
//    document.list =<?php // echo json_encode($list);  ?>
</script>

<?php
echo '<pre>';
//print_r($list[0]);

$fromDate = $list[0]['START_DATE'];
$toDate = $list[0]['END_DATE'];
echo $fromDate;
echo $toDate;

$period = new DatePeriod(
        new DateTime($fromDate), new DateInterval('P1D'), new DateTime($toDate)
);

foreach ($period as $date) {
    print_r($date);
//    $arrayDates[] = $date->format('Y-m-d');
}

//print_r($arrayDates);

die();
?>



<div class="margin-top-20">

    <div class="portlet light bg-inverse">

        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id ="export" class="hris-export-to-excel" hris-export-to-excel-target="grid">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>


        <div id="example">
            <table id="grid">
                <colgroup>
                    <col />
                    <col />
                </colgroup>
                <thead>
                    <tr>
                        <th data-field="name">Car Make</th>
                        <th data-field="date">date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Volvo</td>
                        <td><input type="checkbox"></td>
                    </tr>
                    <tr>
                        <td>Lancia</td>
                        <td><input type="checkbox"></td>
                    </tr>
                </tbody>
            </table>

        </div>


        <div id="TrainingAttendance">
        </div>


        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
            <td>                     
            #: (FIRST_NAME == null) ? '-' : F                IRST_NAME #
            </td>
            </tr>
        </script>
    </div>