<?php
$this->headScript()->appendFile($this->basePath('js/setup/emp-current-posting/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'empCurrentPosting-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$serviceTypeId = $form->get('serviceTypeId');
$serviceTypeId->setValueOptions($serviceTypes);
$branchId = $form->get('branchId');
$branchId->setValueOptions($branches);
$departmentId = $form->get('departmentId');
$departmentId->setValueOptions($departments);
$designationId = $form->get('designationId');
$designationId->setValueOptions($designations);
$positionId = $form->get('positionId');
$positionId->setValueOptions($positions);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('empCurrentPosting', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>

<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuCurrentPosting"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\empCurrentPosting')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Employee Current Posting
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php print $this->formLabel($employeeId); ?>
                    <?php print $this->formElement($employeeId); ?>
                    <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($serviceTypeId); ?>
                    <?php print $this->formElement($serviceTypeId); ?>
                    <?php print $this->formElementErrors()->render($serviceTypeId, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($branchId); ?>
                    <?php print $this->formElement($branchId); ?>
                    <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($departmentId); ?>
                    <?php print $this->formElement($departmentId); ?>
                    <?php print $this->formElementErrors()->render($departmentId, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($designationId); ?>
                    <?php print $this->formElement($designationId); ?>
                    <?php print $this->formElementErrors()->render($designationId, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($positionId); ?>
                    <?php print $this->formElement($positionId); ?>
                    <?php print $this->formElementErrors()->render($positionId, ['class' => 'help-block']); ?>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
