<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/AttendanceManagement/calculate-overtime/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
?>

<script>
    document.ids=<?php echo json_encode(["statusId"=>"All","employeeTypeId"=>"-1","fromDate"=>"","nepaliFromDate"=>"","toDate"=>"","nepaliToDate"=>""]) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\calculateOvertime')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="attendanceWidOTListController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="javascript::" class="btn default btn-sm" data-toggle="modal" data-target="#myModal">
                    <i class="fa fa-plus-square icon-black"></i> Calculate Overtime </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li id="export">
                            <a href="javascript:;">
                                <i class="fa fa-pencil" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <select class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <select class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <?php print $this->formElement($status); ?>
                </div>
                <div class="col-sm-2">
                    <?php print $this->formElement($employeeType); ?>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="fromDate" name="fromDate" ng-model="fromDate" class="form-control" placeholder="From Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="toDate" name="toDate" ng-model="toDate" class="form-control" placeholder="To Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-4 ">
                    <div style="float: left;margin-top: 1%;font-size: 12px;">
                        <label>Overtime Only</label>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input class="" type="checkbox" id="overtimeOnly" name="overtimeOnly"/>
                            <span></span>
                        </label>
                    </div>
                    <button id="reset" class="btn default btn-sm pull-right">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                     <button ng-click="view()" id="viewAttendanceList" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="attendanceWidOTTable">
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (IN_REMARKS == null) ? '-' : IN_REMARKS #
        </td>
        <td>
        #: (OUT_REMARKS == null) ? '-' : OUT_REMARKS #
        </td>
        <td>
        <ul id="branchList">  
        #  ln=DETAILS.length #
        #for(var i=0; i<ln; i++) { #
        <li>
        #=i+1 #) #=DETAILS[i].START_TIME # - #=DETAILS[i].END_TIME #
        </li>
        #}#
        </ul>
        </td>
        <td>
        <ul id="branchList">  
        #  ln=DETAILS.length #
        #for(var i=0; i<ln; i++) { #
        <li>
        #=i+1 #) #=DETAILS[i].TOTAL_HOUR #
        </li>
        #}#
        </ul>
        </td>
        </tr>
        <tr>
            <td colspan="3">
                <span class="pull-right">Total Hour</span>
            </td>
            <td>#: OVERTIME_IN_HOUR #</td>
        </tr>
    </script>
    
    <div class="modal fade calculateOvertimeFormModal" id="myModal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Please Select Date</h4>
            </div>
              <form name="calculateOvertimeForm" id="calculateOvertimeForm" method="post" action="<?= $this->url("calculateOvertime",["action"=>"calculate"]) ?>">
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>From Date</label>
                            <input type="text" name="fromDate" id="fromDate1" value="" class="form-control"/>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label style="height:14px;"></label>
                            <input type="text" id="nepaliFromDate1" class="form-control" value="">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>To Date</label>
                            <input type="text" name="toDate" id="toDate1" value="" class="form-control"/>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label style="height:14px;"></label>
                            <input type="text" id="nepaliToDate1" class="form-control" value="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-default" id="resetForm">Reset</button>
              <button type="submit" class="btn green">Submit</button>
            </div>
              </form>
          </div>
        </div>
    </div>
    
</div>