<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/attendance/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceByHr-form');

$employeeId = $form->get('employeeId');
$employeeId->setAttributes(['disabled' => 'disabled']);

$attendanceDt = $form->get('attendanceDt');
$attendanceDt->removeAttribute('required');
$attendanceDt->setAttributes(['readonly' => 'readonly']);
$attendanceDt->setAttributes(['disabled' => 'disabled']);


$inTime = $form->get('inTime');
if ($inTime->getValue() == null || $inTime->getValue() == "") {
    $inTime->setValue("10:00 AM");
}
$inTime->setAttributes(['disabled' => "disabled"]);
$outTime = $form->get('outTime');
if ($outTime->getValue() == null || $outTime->getValue() == "") {
    $outTime->setValue("5:00 PM");
}
$inRemarks = $form->get('inRemarks');
$inRemarks->setAttributes(['readonly' => "readonly"]);
$outRemarks = $form->get('outRemarks');
$outRemarks->setAttributes(['readonly' => "readonly"]);
$totalHour = $form->get('totalHour');
$totalHour->setAttributes(['readonly' => "readonly"]);
if ($totalHour->getValue() == null || $totalHour->getValue() == "") {
    $totalHour->setValue("7.0");
}
$employeeId->setValueOptions($employees);
$employeeId->setAttributes(['disabled' => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('attendancebyhr', ['action' => 'edit', 'id' => $id]));


$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\calculateOvertime')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div
                            class="form-group <?= empty($employeeId->getMessages()) ? "" : "error" ?> ">
                                <?php print $this->formLabel($employeeId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($employeeId); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group <?= empty($attendanceDt->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($attendanceDt); ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($attendanceDt); ?>
                                </div>
                                <?php print $this->formElementErrors()->render($attendanceDt, ['class' => 'help-block error']); ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDate" id="nepaliDate"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>    

                    </div>

                    <div class="col-sm-4">
                    </div>
                </div>



                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($inTime->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($inTime) ?>
                            <span class="required" aria-required="true">*</span>
                            <div class="input-group dropdown-select">
                                <?php print $this->formElement($inTime) ?>
                            </div>
                            <?php print $this->formElementErrors()->render($inTime, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group <?= empty($outTime->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($outTime) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <div class="input-group dropdown-select">
                                        <?php print $this->formElement($outTime) ?>
                                    </div>
                                </div>
                                <?php print $this->formElementErrors()->render($outTime, ['class' => 'help-block error']); ?>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group <?= empty($totalHour->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($totalHour); ?>
                                    <?php print $this->formElement($totalHour); ?>
                                </div>
                                <?php print $this->formElementErrors()->render($totalHour, ['class' => 'help-block error']); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group  <?= empty($inRemarks->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($inRemarks); ?>
                            <?php print $this->formElement($inRemarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($inRemarks, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($outRemarks->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($outRemarks); ?>
                            <?php print $this->formElement($outRemarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($outRemarks, ['class' => 'help-block error']); ?>
                    </div>
                    <?php if(count($overtimeDetails)>0){ ?>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label>Overtime Detail</label>
                            <hr style="margin-top:0px; margin-bottom:5px;">
                            <table width='100%' style="margin-bottom:10px;">
                            <tr>
                                <td class="col-sm-4" style="padding:0px;"><label>Start Time</label></td>
                                <td class="col-sm-4" style="padding:0px;"><label>End Time</label></td>
                                <td><label>Total Hour</label></td>
                            </tr>
                            <?php foreach($overtimeDetails as $detail){ ?>
                            <tr height="30"> 
                                <td width="45%" style="padding-right:5px;">
                                    <input timepicker type="text" size="3" class="form-control" name="startTime[]"  value="<?= $detail['START_TIME']; ?>" required="required" readonly="readonly"/>
                                </td>
                                <td width="45%" style="padding:5px;">
                                    <input timepicker type="text" size="3"  class="form-control" name="endTime[]"   value="<?= $detail['END_TIME']; ?>" required="required" readonly="readonly"/>
                                </td>
                                <td width="45%" style="padding:5px;">
                                    <input type="text" size="3" class="form-control" name="totalHour[]"  value="<?= $detail['TOTAL_HOUR']; ?>"  required="required" readonly="readonly"/>
                                </td>
                            </tr>
                            <?php } ?>
                            <tr height="30">
                                </td>
                                <td>
                                </td>
                                <td width="45%" style="padding:5px;">
                                    <label class="pull-right">Total Hour:</label>
                                </td>
                                <td width="45%" style="padding:5px;"> 
                                    <input size="3" class="form-control" type="text" name="allTotalHour" id="sumAllTotal" step="0.01" min="0" readonly="readonly"  value="<?= $overtimeInHour; ?>" />
                                </td>
                                <td>
                            </tr>
                        </table>
                        </div>
                    </div>
                    <?php } ?>
                </div>

            </div>

        </div>
    </div>
</div>

