<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'designation-form');

$designationCode = $form->get('designationCode');
$designationTitle = $form->get("designationTitle");
$basicSalary = $form->get("basicSalary");
$status = $form->get("status");

$submit = $form->get("submit");
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('designation', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu=<?php $menu = ["id" => "menuSetup","subMenu"=>["id"=>"subMenuDesignation"]];echo json_encode($menu);?>;
</script>

<div class="row">

    <div class="col-sm-8 bg-light-color padding-30">
        <div class="row panel-title-head" style="margin-bottom: 2%">
            <div class="col-xs-9 col-sm-9 col-md-9">
                <div class="panel-heading padding-5">
                    <h4>Add Designation</h4>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 pull-right">
                <div class="pull-right m-b-10">
                    <a href="<?= $this->url("designation",["action","index"])?>" style="margin-left:16%;">
                        <button class="btn btn-default btn-cons"><i class="fa fa-arrow-left"></i>
                            <span>Back </span></button>
                    </a>
                </div>
            </div>
        </div>

            <div class="panel-body padding-0" >
                <?php print $this->form()->openTag($form);?>
                <div class="form-group form-group-default ">
                    <?= $this->formLabel($designationCode) ?>
                    <?= $this->formElement($designationCode); ?>
                    <?= $this->formElementErrors()->render($designationCode, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group form-group-default ">
                    <?= $this->formLabel($designationTitle) ?>
                    <?= $this->formElement($designationTitle); ?>
                    <?= $this->formElementErrors()->render($designationTitle, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group form-group-default ">
                    <?= $this->formLabel($basicSalary) ?>
                    <?= $this->formElement($basicSalary); ?>
                    <?= $this->formElementErrors()->render($basicSalary, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group form-group-default form-group-default-select2">
                    <?php print $this->formLabel($status); ?>
                    <?php print $this->formElement($status); ?>
                    <?php print $this->formElementErrors()->render($status, ['class' => 'help-block']); ?>
                </div>

                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>

            </div>
    </div>
    <div class="col-sm-2">

    </div>
</div>


