<?php
$this->headScript()->appendFile($this->basePath('js/setup/designation/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'designation-form');

$designationCode = $form->get('designationCode');
$designationTitle = $form->get("designationTitle");
$basicSalary = $form->get("basicSalary");
$status = $form->get("status");

$submit = $form->get("submit");
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('designation', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuDesignation"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Designation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?= $this->formLabel($designationCode) ?>
                    <?= $this->formElement($designationCode); ?>
                    <?= $this->formElementErrors()->render($designationCode, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($designationTitle) ?>
                    <?= $this->formElement($designationTitle); ?>
                    <?= $this->formElementErrors()->render($designationTitle, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($basicSalary) ?>
                    <?= $this->formElement($basicSalary); ?>
                    <?= $this->formElementErrors()->render($basicSalary, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($status); ?>
                    <?php print $this->formElement($status); ?>
                    <?php print $this->formElementErrors()->render($status, ['class' => 'help-block']); ?>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>


