<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'designation-form');

$designationCode = $form->get('designationCode');
$designationTitle = $form->get("designationTitle");
$basicSalary = $form->get("basicSalary");
$status = $form->get("status");

$submit = $form->get("submit");
$submit->setAttribute('value', 'UPDATE');

$form->setAttribute('action', $this->url('designation', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();

?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuDesignation"]];echo json_encode($menu);?>;
</script>
<div class="container">
    <?= $this->navigation('Zend\Navigation\Designation')->breadcrumbs()->setMinDepth(0) ?>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-default customShadow">
            <div class="panel-heading bg-master-lighter">
                <div class="panel-title">
                    <h3 class="panel-title">Designation</h3>
                </div>
            </div>
            <div class="panel-body p-t-5">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group form-group-sm ">
                    <?= $this->formLabel($designationCode) ?>
                    <?= $this->formElement($designationCode); ?>
                    <?= $this->formElementErrors()->render($designationCode, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group form-group-sm ">
                    <?= $this->formLabel($designationTitle) ?>
                    <?= $this->formElement($designationTitle); ?>
                    <?= $this->formElementErrors()->render($designationTitle, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group form-group-sm ">
                    <?= $this->formLabel($basicSalary) ?>
                    <?= $this->formElement($basicSalary); ?>
                    <?= $this->formElementErrors()->render($basicSalary, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group form-group-sm form-group-default-select2">
                    <?php print $this->formLabel($status); ?>
                    <?php print $this->formElement($status); ?>
                    <?php print $this->formElementErrors()->render($status, ['class' => 'help-block']); ?>
                </div>

                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>

            </div>
        </div>
    </div>
</div>

