<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuDesignation"]];echo json_encode($menu);?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Designation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('designation', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <table class="table" id="dataTable">
        <thead>
        <tr role="row">
            <th>
                Designation Title
                Code
            </th>
            <th>
                Designation Detail
            </th>
            <th>
                Action
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($designations as $designation): ?>
            <tr role="row">
                <td>
                    <?php print $this->escapeHtml($designation->DESIGNATION_CODE) ?>
                </td>
                <td>
                    <?php print $this->escapeHtml($designation->DESIGNATION_TITLE) ?>
                </td>
                <td>
                    <a href="<?= $this->url("designation", ["action" => "edit", "id" => $designation->DESIGNATION_ID]) ?>">
                        Edit
                    </a> /
                    <a href="<?= $this->url("designation", ["action" => "delete", "id" => $designation->DESIGNATION_ID]); ?>">
                        Delete
                    </a>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>

</div>