<?php

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

?>
<a href="<?php echo $this->url('designation',["action"=>"add"]) ?>">Add New</a>


<table role="grid" class="table table-hover dataTable no-footer" id="employeelist">

    <thead>
    <tr role="row">
        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1" rowspan="1"
            aria-controls="basicTable" tabindex="0" class="sorting_desc" style="width: 218px;">Designation Title
            Code
        </th>
        <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="basicTable"
            tabindex="0" class="sorting" style="width: 219px;">Designation Detail
        </th>
        <th aria-label="Last Update: activate to sort column ascending" colspan="1" rowspan="1"
            aria-controls="basicTable" tabindex="0" class="sorting" style="width: 155px;">
            Action
        </th>
    </tr>
    </thead>
    <tbody>

<?php  foreach($designations as $designation):?>
    <tr role="row">
        <td class="v-align-middle sorting_1">
            <p>
                <?php print $this->escapeHtml($designation->DESIGNATION_CODE) ?>
            </p>
        </td>
        <td class="v-align-middle sorting_1">
            <p>
                <?php print $this->escapeHtml($designation->DESIGNATION_TITLE) ?>
            </p>
        </td>
        <td class="v-align-middle sorting_1">
            <a href="<?= $this->url("designation",["action"=>"edit","id"=>$designation->DESIGNATION_ID]) ?>" >Edit</a>
            <a href="<?= $this->url("designation",["action"=>"delete","id"=>$designation->DESIGNATION_ID]); ?>" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>

        </td>
    </tr>

<?php endforeach;?>

    </tbody>
</table>

