<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/advance/advance-apply/advanceController.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('id', 'advanceAdvance-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$advanceId = $form->get('advanceId');
$advanceId->setValueOptions($advances);
$requestedAmount = $form->get('requestedAmount');
$advanceDate = $form->get('advanceDate');
$reason = $form->get('reason');
$terms = $form->get('terms');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('advanceApply', ['action' => 'add']));

$form->prepare();
?>
<script>
    document.menu =<?php
$menu = ["id" => "menuAdvance", "subMenu" => ["id" => "subMenuApply"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advanceApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20" ng-app="hris" ng-controller="advanceController">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <select name="employeeId"  required="required"  ng-model="employeeId" ng-change="employeeChange()" class="form-control">
                        <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                        <?php foreach ($employees as $key => $value) { ?>
                            <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                        <?php } ?>
                    </select>
                    <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                </div>  
                <div class="form-group">
                    <?php print $this->formLabel($advanceId); ?>
                    <select name="advanceId" required="required" ng-options="key as value for (key,value) in advanceList track by key" ng-model="advanceId" ng-change="advanceChange()"  class="form-control">
                        <option style="display:none" value="" disabled="" selected>select a type</option>
                    </select>
                    <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                    <span ng-show="(allowAmt !== null) && (allowTerms !== null)">
                        Max Amount: <span ng-bind="allowAmt" style="font-size:11px; font-weight: bold;"></span>
                        Within : <span ng-bind="allowTerms" style="font-size:11px; font-weight: bold;"></span> Months
                    </span>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <input max="{{allowAmt}}" ng-model="requestedAmt" ng-change="requestChange()" type="number" name="requestedAmount" required="required" id="form-requestedAmount" class="form-requestedAmount form-control" step="0.01" value="">
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($terms); ?>
                    <input max="{{allowTerms}}" ng-model="terms" ng-change="requestChange()" type="number" name="terms" required="required" id="form-terms" class="form-terms form-control" min="1" value="">
                    <?php print $this->formElementErrors()->render($terms, ['class' => 'help-block']); ?>
                </div>
                <span ng-show="salaryDeduction !== null">
                    Deduction: {{salaryDeduction}} per month
                </span>
                <div class="form-group">
                    <?php print $this->formLabel($advanceDate); ?>
                    <div class="input-group date" id="startDate">
                        <?php print $this->formElement($advanceDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($advanceDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($reason); ?>
                    <?php print $this->formElement($reason); ?>
                    <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
