<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/work-on-dayoff/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'workOnDayoff-form');

$fromDate = $form->get('fromDate');
$toDate = $form->get('toDate');
$duration = $form->get('duration');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('workOnDayoff', ['action' => 'add']));


$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\workOnDayoff')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>         
                <div
                    class="form-group required  <?= empty($fromDate->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($fromDate) ?>
                        <?php print $this->formElement($fromDate) ?>
                </div>
                <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block error']) ?>

                <div
                    class="form-group required <?= empty($toDate->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($toDate) ?>
                        <?php print $this->formElement($toDate) ?>
                    <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block error']) ?>

                <div
                    class="form-group required <?= empty($duration->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($duration); ?>
                        <?php print $this->formElement($duration); ?>
                    <span id="errorMsg" style="font-size:11px; color:red;"></span>
                </div>
                <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>

                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
