
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));

$this->headScript()->appendFile($this->basePath('js/customer/contract-attendance/emp-wise-report.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.monthList =<?php echo json_encode($monthList); ?>;
    document.pullEmpWiseMonthlyReport = '<?= $this->url("contract-attendance", ["action" => "pullEmpWiseMonthlyReport"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\customer-contract')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                                                <li >
                                                    <a href="javascript:;" id="excelExport">
                                                        <i class="fa fa-file-excel-o" ></i>
                                                        Export to Excel
                                                    </a>
                                                </li>
                                                <li >
                                                    <a href="javascript:;" id="pdfExport">
                                                        <i class="fa fa-file-pdf-o" ></i> 
                                                        Export to PDF 
                                                    </a>
                                                </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row margin-top-20">

            <div class="col-md-3">
                <div class="form-group">
                    <select id="monthSelect" class="form-control"></select>
                </div>
            </div>
            <div class="col-md-3">
                <input type="button" id="viewBtn" class="btn btn-primary" value="view">
            </div>

        </div>


        <div class="row">
            <div class="col-md-12">
                <div id="grid">

                </div>

            </div>
        </div>

    </div>
</div>
