
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));

$this->headScript()->appendFile($this->basePath('js/customer/contract-attendance/index.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.viewLink = '<?= $this->url("contract-attendance", ["action" => "view"]); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.customerList =<?php echo json_encode($customerList); ?>;
    document.employeeList =<?php echo json_encode($employeeList); ?>;
    document.monthList =<?php echo json_encode($monthList); ?>;
    document.pullCustomerMonthlyAttendanceUrl = '<?= $this->url("contract-attendance", ["action" => "pullCustomerMonthlyAttendance"]); ?>';
    document.pullAttendanceAbsentData = '<?= $this->url("contract-attendance", ["action" => "pullAttendanceAbsentData"]); ?>';
    document.updateAttendanceData = '<?= $this->url("contract-attendance", ["action" => "updateAttendanceData"]); ?>';
    document.pullCustomerLocation = '<?= $this->url("contract-attendance", ["action" => "pullCustomerLocation"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\customer-contract')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <!--                        <li >
                                                    <a href="javascript:;" id="excelExport">
                                                        <i class="fa fa-file-excel-o" ></i>
                                                        Export to Excel
                                                    </a>
                                                </li>
                                                <li >
                                                    <a href="javascript:;" id="pdfExport">
                                                        <i class="fa fa-file-pdf-o" ></i> 
                                                        Export to PDF 
                                                    </a>
                                                </li>-->
                    </ul>
                </div>
            </div>
        </div>

        <div class="row margin-top-20">

            <div class="col-md-3">
                <div class="form-group">
                    <select id="customerSelect" class="form-control"></select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <select id="locationSelect" class="form-control"></select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <select id="monthSelect" class="form-control"></select>
                </div>
            </div>
            <div class="col-md-3">
                <input type="button" id="viewBtn" class="btn btn-primary" value="view">
            </div>

        </div>


        <div class="row">
            <div class="col-md-12">
                <div id="grid">

                </div>

            </div>
        </div>

    </div>
</div>


<!--modal to assign employee Assign-->
<div class="modal fade" id="subEmpModal"    role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Attendance</h4>
            </div>
            <div class="modal-body modalpopup_s2">

                <!--                <div class="row">
                                    <div class="col-md-3">
                                        date:
                                        </br>
                                        designation:
                                        </br>
                                        employee:
                                        </br>
                                        location:
                                        </br>
                                        startTime:
                                        </br>
                                        endTime:
                
                                    </div>
                                    <div class="col-md-4">
                                        date:
                                        </br>
                                        designation:
                                        </br>
                                        employee:
                                        </br>
                                        location:
                                        </br>
                                        startTime:
                                        </br>
                                        endTime:
                
                                    </div>
                                </div>-->

                <div class="row">
                    <div class="col-md-3">
                        Status : 
                    </div>
                    <div class="col-md-4 modalpopup_s2">
                        <select class="form-control"  required='required'  id="attdStatus" name='attdStatus' >
                            <option value="PR">Present</option>
                            <option value="AB">Absent</option>
                            <option value="LV">Leave</option>
                            <option value="DO">Day Off</option>
                            <option value="PH">Public Holiday</option>
                            <!--<option value="PT">Partial</option>-->
                        </select>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        Normal hour : 
                    </div>
                    <div class="col-md-4 modalpopup_s2">
                        <input class="form-control"   id="normalHour" name='normalHour' type='text' data-format='H:mm' data-template='HH : mm'></br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        OT Hour: 
                    </div>
                    <div class="col-md-4 modalpopup_s2">
                        <input class="form-control"   id="otHour" name='otHour' type='text' data-format='H:mm' data-template='HH : mm'></br>
                    </div>
                </div>




                <div class="row">
                    <div class="col-md-3 ">
                        Substitute Employee : 
                    </div>
                    <div class="col-md-4 modalpopup_s2">
                        <select class="form-control"  required='required'  id="subEmployee" name='subEmployee' >
                        </select>
                    </div>
                </div>

                <div id="subRateDiv">

                    <div class="row">
                        <div class="col-md-3">
                            Posting Type : 
                        </div>
                        <div class="col-md-4 modalpopup_s2">
                            <select class="form-control"  required='required'  id="postingType" name='postingType' >
                                <option value="SU" selected="SELECTED">Substitute</option>
                                <option value="OT">Over Time</option>
                            </select>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-3">
                            Sub Rate : 
                        </div>
                        <div class="col-md-3">
                            <input id="rate" class="form-control" type="number">
                        </div>
                    </div>

                    <div class="row" >
                        <div class="col-md-3">
                            Sub OT Type : 
                        </div>
                        <div class="col-md-3">
                            <select id="otType" class="form-control">
                                <option value="H">Hourly Rate</option>
                                <option value="P">Percent</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="row" >
                        <div class="col-md-3">
                            Sub OT Rate : 
                        </div>
                        <div class="col-md-3">
                            <input id="otRate" class="form-control" type="number">
                        </div>
                    </div>

                </div>






            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="updateAttendanceBtn" type="button" class="btn btn-primary">Update</button>
            </div>
        </div>
    </div>
</div>
