<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'))
        ->appendFile($this->basePath('js/customer/contract-attendance/view.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.templateLink = '<?= $this->url("contract-attendance", ["action" => "exportTemplate", "id" => $id]); ?>';
    document.UploadExcelLink = '<?= $this->url("contract-attendance", ["action" => "uploadAttendance", "id" => $id]); ?>';
    document.contractId = '<?= $id ?>';
    document.monthDetails =<?= json_encode($monthDetails) ?>;
    document.downloadExcelLink = '<?= $this->url("contract-attendance", ["action" => "exportTemplate", "id" => $id]) ?>';
    document.pullEmployeeAssignBy = '<?= $this->url('contract-attendance', ['action' => 'pullAttendanceContractMonthly', 'id' => $id]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\customer-contract')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a   id="templateExport">
                                <i class="fa fa-file-excel-o" ></i>
                                Export Template for attendance
                            </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i>
                                Export to Excel
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <form enctype="multipart/form-data" action="<?= $this->url("contract-attendance", ["action" => "uploadAttendance", "id" => $id]); ?>" method="post" id="import_excel">  
            <div class="row margin-top-20">
                <div class="col-lg-3">
                    <label>Month</label>
                    <select required="required" id="monthSelect" name="monthId">
                    </select>
                </div>

            </div>

            <div class="row margin-top-20">
                <div class="col-sm-4">
                    <label>Select Excel Attedance Upload</label>  
                    <input required="required" type="file" name="excel_file" id="excel_file" />  
                    <input type="submit" value="submit"> 
                </div>

                <div class="col-sm-2">
                    <!--<a id="uploadBtn" class="btn btn-primary">Upload</a>-->
                </div>


            </div>
        </form>  

        <div id="table">

        </div>




    </div>
</div>

