<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/SelfService/performance-appraisal/index.js'));
?>


<script>
    document.appraisals =<?= json_encode($list) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\performanceAppraisal')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

    <div class="margin-top-20" ng-app="hris" ng-controller="appraisalList">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="appraisalListTable">

    </div>
	</div>
    
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (APPRAISAL_EDESC == null) ? '-' : APPRAISAL_EDESC #
        </td>
        <td>    
        #: (APPRAISAL_TYPE_EDESC == null) ? '-' : APPRAISAL_TYPE_EDESC #
        </td>
        <td>    
        #: (STAGE_EDESC == null) ? '-' : STAGE_EDESC #
        </td>
        <td>    
        #: (START_DATE == null) ? '-' : START_DATE #
        </td>
        <td>    
        #: (END_DATE == null) ? '-' : END_DATE #
        </td>
        <td>
        # if(ALLOW_ADD){ #
        <a class="btn-edit"
        href="<?= $this->url("performanceAppraisal", ["action" => "view"]); ?>/#:APPRAISAL_ID#" style="height:17px;">
        <i class="fa fa-search-plus"></i>
        </a>
        # }else if(ALLOW_EDIT){ #
        <a class="btn-edit"
        href="<?= $this->url("performanceAppraisal", ["action" => "view"]); ?>/#:APPRAISAL_ID#" title="view" style="height:17px;">
        <i class="fa fa-search-plus"></i>
        </a>
        #} #
        </td>
        </tr>
    </script>
</div>
