<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/loan-request/add.js'));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\performanceAppraisal')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                Annual Performance Appraisal
            </div>
            <div class="btn-group pull-right open" style="margin-top:1%">
               
            </div>
        </div>
        <div class="portlet-body">
        </div>
    </div>
</div>
