<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaverequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php 
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/LeaveManagement/leave-carry-forward/add.js'))
                    ;
?>


<?php
$form->setAttribute('role', 'form');
$noOfDays = $form->get('noOfDays');
$employeeId = $form->get('employeeId');
$submit = $form->get('submit');
$submit->setAttribute('value', 'Carry Forward Leave');
$submit->setAttribute('id', 'request');

$form->setAttribute('action', $this->url('leavecarryforward', ['action' => 'add']));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.leaveMaxEncash = '<?php echo $leaveMaxEncash; ?>';
    document.pushLeaveFileLink = '<?php echo $this->url('leaveapply', ['action' => 'pushLeaveFileLink']); ?>';
    document.uploadUrl = '<?= $this->url('leaveapply', ['action' => 'fileUpload']); ?>';
    document.wsPullLeaveDetailWidEmployeeId = '<?= $this->url("leavecarryforward", ["action" => "pullLeaveDetailWidEmployeeId"]) ?>';
    document.wsPullLeaveDetail = '<?= $this->url("leaverequest", ["action" => "pullLeaveDetail"]) ?>';
    document.wsFetchAvailableDays = '<?= $this->url("leavecarryforward", ["action" => "fetchAvailableDays"]) ?>';
    document.wsValidateLeaveRequest = '<?= $this->url("leaverequest", ["action" => "validateLeaveRequest"]) ?>';
    
</script>

<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    Leave carry Forward
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
               
                <div class=" row">
                     <div class="col-sm-4">
                        <div class="form-group <?= empty($employeeId->getMessages()) ? "" : "error" ?> ">
                            <?php print $this->formLabel($employeeId) ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="employeeId" id="employeeId" required="required"  class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                                <?php foreach ($employees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                <?php } ?>
                            </select>
                        </div>
                        <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block error']); ?> 
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="leaveId">Leave Type</label>
                            <span class="required" aria-required="true">*</span>
                            <select name="leaveId" required="required" id="leaveId" class="form-control">
                                <option value="" disabled="" selected="" >Please select</option>
                                <?php foreach ($leave as $key => $value) { ?>
                                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group disabled">
                            <label for="leaveId">Available Days</label>
                            <input type="text" READONLY name="availableDays"  required="required" id="availableDays"  class="form-control"  value="">
                           <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group disabled">
                            <label for="leaveId">Leave Days For Carry Forward</label>
                            <input type="number" name="carryforward"  required="required" step="0.1" readonly id="carryforward"  class="form-control"  value="">
                            
                           
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group disabled">
                            <label for="leaveId">Leave Days For Encashment</label>                            
                            <input type="number" name="encashment" readonly step="0.1"  required="required" id="encashment"  class="form-control"  value="">
                           
                        </div>
                    </div>


                </div>

             
             

                
                </div>

                <?php print $this->formSubmit($submit); ?>

            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>


