<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/SelfService/holiday/index.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuHolidayList"]];echo json_encode($menu);?>;
    document.holidays=<?php echo json_encode($holidays); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\holiday')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <div id="holidayTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: HOLIDAY_CODE #
        </td>
        <td>
        #: HOLIDAY_ENAME #
        </td>
        <td>
        #: START_DATE #
        </td>
        <td>
        #: END_DATE #
        </td>
        <td>
        #: HALF_DAY #
        </td>
        </td>
        </tr>
    </script>

</div>