<?php
$this->headScript()->appendFile($this->basePath('js/manager-service/appraisal-review/add.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular-messages.min.js'));
$this->headScript()->appendFile($this->basePath('js/user-form-error.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/performance-appraisal/kpiController.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/performance-appraisal/competenciesController.js'));

?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\appraisal-review')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php

if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<script>
    document.listurl = '<?= $this->url("appraisal-review", ["action" => "index"]) ?>';
</script>
    <div class="row margin-top-20" ng-app="hris">
    <div class="col-md-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <?=
                    $assignedAppraisalDetail['APPRAISAL_EDESC'];
                    ?>
                </div>
                <div class="btn-group pull-right open" style="margin-top:1%">

                </div>
            </div>
            <div class="portlet-body" style="padding-top:1px;">
                <h5 id="headingForPanel"><b>Personal Information</b></h5>
                <div class="row div-font-11">
                    <div class="col-md-4">
                        <table>
                            <tbody>
                                <tr height="30">
                                    <td>
                                        Appraisee's Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        $middleName = ($employeeDetail['MIDDLE_NAME'] == null || $employeeDetail['MIDDLE_NAME'] == "") ? " " : " " . $employeeDetail['MIDDLE_NAME'] . " ";
                                        $employeeName = $employeeDetail['FIRST_NAME'] . $middleName . $employeeDetail['LAST_NAME'];
                                        print_r($employeeName);
                                        ?>  
                                    </td>
                                </tr>

                                <tr height="30">
                                    <td>
                                        Department
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['BRANCH_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Appraisal Period
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $assignedAppraisalDetail['START_DATE']; ?>
                                        To
                                        <?= $assignedAppraisalDetail['END_DATE']; ?>
                                    </td>
                                </tr>
                            </tbody></table>
                    </div>
                    <div class="col-md-4">
                        <table>
                            <tbody>
                                <tr height="30">
                                    <td>
                                        Position
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['POSITION_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Joining Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['JOIN_DATE']; ?>  
                                    </td>
                                </tr>
                                <tr height="30" id="availableDaysText">
                                    <td>
                                        Appraiser's Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        $middleName_A = ($assignedAppraisalDetail['MIDDLE_NAME_A'] == null || $assignedAppraisalDetail['MIDDLE_NAME_A'] == "") ? " " : " " . $assignedAppraisalDetail['MIDDLE_NAME_A'] . " ";
                                        $employeeName_A = $assignedAppraisalDetail['FIRST_NAME_A'] . $middleName_A . $assignedAppraisalDetail['LAST_NAME_A'];
                                        print_r($employeeName_A);
                                        ?>       
                                    </td>
                                </tr>
                            </tbody></table>
                    </div>
                    <div class="col-md-4">
                        <table>
                            <tbody>
                                <tr height="30">
                                    <td>
                                        Branch
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['BRANCH_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Reviewer's Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        $middleName_R = ($assignedAppraisalDetail['MIDDLE_NAME_R'] == null || $assignedAppraisalDetail['MIDDLE_NAME_R'] == "") ? " " : " " . $assignedAppraisalDetail['MIDDLE_NAME_R'] . " ";
                                        $employeeName_R = $assignedAppraisalDetail['FIRST_NAME_R'] . $middleName_R . $assignedAppraisalDetail['LAST_NAME_R'];
                                        print_r($employeeName_R);
                                        ?>                                         
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="portlet-body" style="padding-top:1px;">
                <h5 id="headingForPanel"><b>Performance Evaluation</b></h5>
                <div class="portlet-body">
                    <div class="tabbable-line menusetuptab" style="padding-top:0px">
                        <ul class="nav nav-tabs" id="tabList">
                            <?php if($assignedAppraisalDetail['KPI_SETTING']=='Y'){?>
                            <li class="active">
                                <a href="#portlet_tab2_KPI" data-toggle="tab"> KPI </a>
                            </li>
                            <?php }?>
                            <?php if($assignedAppraisalDetail['COMPETENCIES_SETTING']=='Y'){ ?>
                            <li>
                                <a href="#portlet_tab2_COM" data-toggle="tab"> Competencies </a>
                            </li>
                            <?php } ?>
                            <?php if(count($questionTemplate)>0){ ?>
                            <li class="<?= (($assignedAppraisalDetail['KPI_SETTING']=='N') &&  ($assignedAppraisalDetail['COMPETENCIES_SETTING']=='N') && ($tab==1)) ?'active':''?>">
                                <a href="#portlet_tab2_1" data-toggle="tab"> Appraisee's Evaluation </a>
                            </li>
                            <?php } ?>
                            <?php if(count($appraiserQuestionTemplate)>0 && $appraiserAvailableAnswer==true){ ?>
                            <li class="<?= ($tab==2)?"active":""; ?>">
                                <a href="#portlet_tab2_2" data-toggle="tab"> Appraiser's Evaluation </a>
                            </li>
                            <?php } ?>
                            <?php if(count($reviewerQuestionTemplate)>0){ ?>
                            <li class="<?= ($tab==3)?"active":""; ?>">
                                <a href="#portlet_tab2_3" data-toggle="tab"> Reviewer's Evaluation </a>
                            </li>
                            <?php } ?>
                            <?php if(count($appraiseeQuestionTemplate)>0 && $appraiseeAvailableAnswer==true){ ?>
                            <li class="">
                                <a href="#portlet_tab2_4" data-toggle="tab"> Appraisee's Feedback </a>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="tab-content margin-top-15" id="tabContent">
                        <input type="hidden" value="<?= $assignedAppraisalDetail['EMPLOYEE_ID']; ?>" name="employeeId" id="employeeId"/>
                        <input type="hidden" value="<?= $assignedAppraisalDetail['APPRAISAL_ID']; ?>" name="appraisalId" id="appraisalId"/>
                        <input type='hidden' value="<?= $assignedAppraisalDetail['STAGE_ID']; ?>" id="currentStageId" />
                        <?php 
                        $disabledKPICOM = ($assignedAppraisalDetail['STAGE_ID']!=1)?"disabled":"";  ?>
                        <div class="tab-pane <?= (($assignedAppraisalDetail['KPI_SETTING']=='Y')) ?'active':''?>" id="portlet_tab2_KPI" ng-controller="kpiController">
                            <form name="KPIForm" id="KPIForm" ng-submit="submitKPIForm()" novalidate>
                            <table class="table">
                                <thead>
                                <tr>
                                    <?php if($assignedAppraisalDetail['STAGE_ID']==1){ ?>
                                    <th style="width:5%;"></th>
                                    <?php } ?>
                                    <th style="width:5%;">S.N.</th>
                                    <th>KPI Detail</th>
                                    <th>Success Criteria</th>
                                    <th style="width:10%;">Weight</th>
                                    <?php if($keyAchievementDtlNum>0){ ?>
                                    <th>Key Achievement</th>
                                    <th>Self Rating</th>
                                    <?php } ?>
                                    <?php if($appraiserRatingDtlNum>0){ ?>
                                    <th>Appraiser Rating</th>
                                    <?php } ?>
                                </tr>
                                </thead>
                                <tr ng-repeat="KPI in KPIList">
                                    <?php if($assignedAppraisalDetail['STAGE_ID']==1){?>
                                    <td>
                                        <div class="md-checkbox">
                                            <input type="checkbox" id="{{KPI.checkbox}}" class="md-check"
                                                   ng-model="KPI.checked">
                                            <label for="{{KPI.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                            </label>
                                        </div>
                                    </td>
                                    <?php } ?>
                                    <td><span ng-bind="KPI.counter"></span></td>
                                    <td>
                                        <textarea cols="25" rows="20" class="form-control" style="height:150px!important" name="title_{{KPI.checkbox}}" ng-model="KPI.title" required="required" <?=$disabledKPICOM; ?>></textarea>
                                        <div ng-show="KPIForm.$submitted || KPIForm.title_{{KPI.checkbox}}.$touched">
                                            <ul ng-show="KPIForm.title_{{KPI.checkbox}}.$error.required" class="help-block error">
                                                <li>KPI Detail is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <textarea cols="25" rows="20" class="form-control" style="height:150px!important" name="successCriteria_{{KPI.checkbox}}" ng-model="KPI.successCriteria" required="required" <?=$disabledKPICOM; ?>></textarea>
                                        <div ng-show="KPIForm.$submitted || KPIForm.successCriteria_{{KPI.checkbox}}.$touched">
                                            <ul ng-show="KPIForm.successCriteria_{{KPI.checkbox}}.$error.required" class="help-block error">
                                                <li>Success Criteria is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td> 
                                        <input type="number" name="weight_{{KPI.checkbox}}" value="" size="3" ng-model="KPI.weight" required="required" min="0" step='1' <?=$disabledKPICOM; ?> style="width:100%;"/>
                                        <div ng-show="KPIForm.$submitted || KPIForm.weight_{{KPI.checkbox}}.$touched">
                                            <ul ng-show="KPIForm.weight_{{KPI.checkbox}}.$error.required" class="help-block error">
                                                <li>Weight is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <?php if($keyAchievementDtlNum>0){ ?>
                                    <td>
                                        <textarea cols="25" rows="20" class="form-control" style="height:150px!important" name="keyAchievement_{{KPI.checkbox}}" ng-model="KPI.keyAchievement" required="required" disabled="disabled"></textarea>
                                        <div ng-show="KPIForm.$submitted || KPIForm.keyAchievement_{{KPI.checkbox}}.$touched">
                                            <ul ng-show="KPIForm.keyAchievement_{{KPI.checkbox}}.$error.required" class="help-block error">
                                                <li>Key Achievement is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td style="width: 10%">
                                        <input type="number" name="selfRating_{{KPI.checkbox}}" value="" size="3" ng-model="KPI.selfRating" required="required" min="0" step='1' style=" width:100%;" disabled="disabled" />
                                        <div ng-show="KPIForm.$submitted || KPIForm.selfRating_{{KPI.checkbox}}.$touched">
                                            <ul ng-show="KPIForm.selfRating_{{KPI.checkbox}}.$error.required" class="help-block error">
                                                <li>Self Rating is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <?php } ?>
                                    <?php if($appraiserRatingDtlNum>0){ ?>
                                    <td style="width: 10%">
                                        <input type="number" name="appraiserRating_{{KPI.checkbox}}" value="" size="3" ng-model="KPI.appraiserRating" required="required" min="0" step='1' style=" width:100%;" disabled='disabled'/>
                                        <div ng-show="KPIForm.$submitted || KPIForm.appraiserRating_{{KPI.checkbox}}.$touched">
                                            <ul ng-show="KPIForm.appraiserRating_{{KPI.checkbox}}.$error.required" class="help-block error">
                                                <li>Appraiser Rating is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <?php } ?>
                                </tr>
                                <?php if($appraiserRatingDtlNum>0){ ?>
                                <tr>
                                    <td colspan="6">
                                        ANNUAL RATING ON KEY PERFORMANCE INDICATOR:
                                    </td>
                                    <td>
                                        <input type="number" disabled="disabled" value="{{calculateAnnualRating(KPIList)}}" name="annualRating" id="annualRating" ng-model="annualRating" style="width:100%;"/>
                                    </td>
                                </tr>
                                <?php } ?>
                                <?php if($assignedAppraisalDetail['STAGE_ID']==1){?>
                                <tr>
                                    <td style="width:10%;">
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="addKPI()" id="plushIcon">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="deleteKPI()" id="plushIcon">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                    <td></td>
                                    <td colspan="2">
                                        <input type="hidden" name="sumTotal" value="{{sumAllTotal(KPIList)}}" ng-model="sumTotal"/>
                                        <div  use-form-error="isGeaterHundred" use-error-expression="sumTotal" ng-messages="KPIForm.$error" class="errors">
                                            <div ng-message="isGeaterHundred" class="help-block error pull-right">{{KPIErrorMsg}}</div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <button type="submit" id="submit" class="btn btn-success pull-right">
                                                NEXT
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                <?php } ?>
                            </table>
                            </form>
                        </div>
                        
                        <div class="tab-pane" id="portlet_tab2_COM" ng-controller="competenciesController">
                            <form name="competenciesForm" id="competenciesForm" ng-submit="submitCompetenciesForm()" novalidate>
                            <table class="table">
                                <thead>
                                <tr>
                                    <?php if($assignedAppraisalDetail['STAGE_ID']==1){ ?>
                                    <th style="width:5%;"></th>
                                    <?php } ?>
                                    <th style="width:5%;">S.N.</th>
                                    <th>Competencies</th>
                                    <?php if($appCompetenciesRatingDtlNum>0){?>
                                    <th>Rating</th>
                                    <th>Appraiser's Comments</th>
                                    <?php } ?>
                                </tr>
                                </thead>
                                <tr ng-repeat="competencies in competenciesList">
                                    <?php if($assignedAppraisalDetail['STAGE_ID']==1){ ?>
                                    <td>
                                        <div class="md-checkbox">
                                            <input type="checkbox" id="{{competencies.checkbox}}" class="md-check"
                                                   ng-model="competencies.checked">
                                            <label for="{{competencies.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                            </label>
                                        </div>
                                    </td>
                                    <?php } ?>
                                    <td><span ng-bind="competencies.counter"></span></td>
                                    <td>
                                        <textarea cols="25" rows="20" class="form-control" style="height:25px!important" name="title_{{competencies.checkbox}}" ng-model="competencies.title" required="required" <?=$disabledKPICOM; ?>></textarea>
                                        <div ng-show="competenciesForm.$submitted || competenciesForm.title_{{competencies.checkbox}}.$touched">
                                            <ul ng-show="competenciesForm.title_{{competencies.checkbox}}.$error.required" class="help-block error">
                                                <li>Competencies Detail is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <?php if($appCompetenciesRatingDtlNum>0){?>
                                    <td width='10%'>
                                        <input type="text" name="rating_{{competencies.checkbox}}" value="" size="3" ng-model="competencies.rating" required="required" min="0" step='1' style=" width:100%;" disabled='disabled'/>
                                        <div ng-show="competenciesForm.$submitted || competenciesForm.rating_{{competencies.checkbox}}.$touched">
                                            <ul ng-show="competenciesForm.rating_{{competencies.checkbox}}.$error.required" class="help-block error">
                                                <li>Appraiser Rating is required.</li>
                                            </ul>
                                        </div> 
                                    </td>
                                    <td>
                                        <textarea cols="25" rows="20" class="form-control" style="height:150px!important" name="comments_{{competencies.checkbox}}" ng-model="competencies.comments" required="required" disabled='disabled'></textarea>
                                        <div ng-show="competenciesForm.$submitted || competenciesForm.comments_{{competencies.checkbox}}.$touched">
                                            <ul ng-show="competenciesForm.comments_{{competencies.checkbox}}.$error.required" class="help-block error">
                                                <li>Appraiser's Comment is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <?php } ?>
                                </tr>
                                <?php if($appCompetenciesRatingDtlNum>0){ 
                                    ?>
                                <tr>
                                    <td colspan="2">
                                        ANNUAL RATING ON COMPETENCIES:
                                    </td>
                                    <td>
                                        
                                        <input type="text" disabled="disabled" value="<?= $assignedAppraisalDetail['ANNUAL_RATING_COMPETENCY'];?>" name="annualRatingCompetency" id="annualRatingCompetency" style="width:100%;"/>
                                    </td>
                                    <td></td>
                                </tr>
                                <?php } ?>
                                <?php if($assignedAppraisalDetail['STAGE_ID']==1){ ?>
                                <tr>
                                    <td style="width:10%;">
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="addCompetencies()" id="plushIcon">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="deleteCompetencies()" id="plushIcon">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                    <td></td>
                                    <td>
                                        <div class="form-group">
                                            <button type="submit" id="submit" class="btn btn-success pull-right">
                                                SUBMIT
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                <?php }?>
                            </table>
                            </form>
                        </div>
                        <div class="tab-pane <?= (($assignedAppraisalDetail['KPI_SETTING']=='N') &&  ($assignedAppraisalDetail['COMPETENCIES_SETTING']=='N') && $tab==1) ?'active':''?>" id="portlet_tab2_1">
                            <form method="post" action="<?= $this->url("appraisal-review",['action'=>'view','appraisalId'=>$appraisalId,'employeeId'=>$employeeId,'tab'=>1]) ?>" name="performanceAppraisalForm" id="appraisalReview">
                            <div class="row">
                                <?php 
                                $disabled = ($questionForCurStage==0 && $appraiseeAvailableAnswer===true)?'disabled':'';
                                $questionOnPreTab = 0;
                                foreach ($questionTemplate as $questionTemplateRow) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $questionTemplateRow['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($questionTemplateRow['QUESTIONS'] as $questionRow) { ?>
                                                    <div class="col-md-12 margin-top-10">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label><h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7></label>   
                                                                <?php 
                                                                $keyForQuestion = ($questionRow['ANSWER']==null || count($questionRow['ANSWER'])==0)?$questionRow['QUESTION_ID']:array_keys($questionRow['ANSWER'])[0];
                                                                if($questionRow['APPRAISEE_FLAG']=='Y'){
                                                                    if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                    <div class="md-radio-inline">
                                                                        <?php $customRenderer($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")); ?>
                                                                    </div>
                                                                    <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                        <div class="md-checkbox-inline">
                                                                            <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")); ?>
                                                                        </div>
                                                                    <?php } else{
                                                                        print_r($this->formElement($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")));
                                                                    }
                                                                } 
                                                                ?>
                                                            </div>
                                                            <?php if($questionRow['APPRAISEE_RATING']=='Y'){ ?>
                                                                <div class="col-sm-1">
                                                                    <label>Self Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForQuestion.".sr]"?>" value="<?= ($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['RATING']:null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" disabled="disabled"/>
                                                                </div>
                                                            <?php } 
                                                            if(count($questionRow['ANSWER'])>0 && array_values($questionRow['ANSWER'])[0]['APPRAISER_ANSWER_ID']!=null){
                                                            $keyForAppQuestion = (array_values($questionRow['ANSWER'])[0]['APPRAISER_ANSWER_ID']==null)?$questionRow['QUESTION_ID']:array_values($questionRow['ANSWER'])[0]['APPRAISER_ANSWER_ID'];
                                                            if($questionRow['APPRAISER_FLAG']=='Y'){ ?>
                                                            <div class="col-sm-3">
                                                                <label>Appraiser's Comment:</label>
                                                                <?php if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                    <div class="md-radio-inline">
                                                                        <?php $customRenderer($performanceAppraisalObj("answer[".$keyForAppQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['APPRAISER_ANSWER']:null,"disabled")); ?>
                                                                    </div>
                                                                <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                    <div class="md-checkbox-inline">
                                                                        <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForAppQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['APPRAISER_ANSWER']:null,"disabled")); ?>
                                                                    </div>
                                                                <?php } else{
                                                                   print_r($this->formElement($performanceAppraisalObj("answer[".$keyForAppQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['APPRAISER_ANSWER']:null,"disabled")));
                                                                }?>
                                                            </div>
                                                            <?php }
                                                            if($questionRow['APPRAISER_RATING']=='Y'){ ?>
                                                                <div class="col-sm-1">
                                                                    <label>Appraiser Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForAppQuestion.".ar]"?>" value="<?= ($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['APPRAISER_RATING_VAL']:null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" disabled='disabled'/>
                                                                </div>
                                                            <?php }
                                                            }
                                                            if((count($questionRow['ANSWER'])>0 && array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']!=null) || $questionForCurStage>0){
                                                            $keyForRevQuestion = (array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']==null)?$questionRow['QUESTION_ID']:array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID'];
                                                                if($questionRow['REVIEWER_FLAG']=='Y'){ 
                                                                    $questionOnPreTab+=1;
                                                                    ?>
                                                                    <div class="col-sm-3">
                                                                        <label>Reviewer's Comment:</label>
                                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']:0; ?>" name="answerId[]"/>
                                                                        <?php if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                            <div class="md-radio-inline">
                                                                                <?php $customRenderer($performanceAppraisalObj("answer[".$keyForRevQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER']:null,$disabled)); ?>
                                                                            </div>
                                                                            <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                                <div class="md-checkbox-inline">
                                                                                    <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForRevQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER']:null,$disabled)); ?>
                                                                                </div>
                                                                            <?php } else{
                                                                                print_r($this->formElement($performanceAppraisalObj("answer[".$keyForRevQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER']:null,$disabled)));
                                                                            }?>
                                                                    </div>
                                                                <?php }?>
                                                                <?php if($questionRow['REVIEWER_RATING']=='Y'){ 
                                                                    $questionOnPreTab+=1;
                                                                    if($questionRow['REVIEWER_FLAG']=='N'){?>
                                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']:0; ?>" name="answerId[]"/>
                                                                        <input type="hidden" value="" name="<?= "answer[".$keyForRevQuestion."]";?>"/>
                                                                    <?php } ?>
                                                                <div class="col-sm-1">
                                                                    <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']:0; ?>" name="answerId[]"/>
                                                                    <label>Reviewer Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForRevQuestion.".rr]"?>" value="<?= ($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_RATING_VAL']:null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" <?= $disabled; ?> required="required"/>
                                                                </div>
                                                            <?php }
                                                                }?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                            <?php if(($questionForCurStage>0 && $questionOnPreTab>0)||($questionOnPreTab>0 && $appraiseeAvailableAnswer!==true)){ ?>
                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success pull-right">
                                            NEXT
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            </form>
                        </div>
                        <div class="tab-pane <?= ($tab==2)?"active":""; ?>" id="portlet_tab2_2">
                            <form method="post" action="<?= $this->url("appraisal-review",['action'=>'view','appraisalId'=>$appraisalId,'employeeId'=>$employeeId,'tab'=>2]) ?>" name="performanceAppraisalForm" id="appraisalReview1">
                            <div class="row">
                                <?php
                                foreach ($appraiserQuestionTemplate as $appraiserQuestionRow) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $appraiserQuestionRow['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($appraiserQuestionRow['QUESTIONS'] as $questionRow) { ?>
                                                    <div  class="col-md-12 margin-bottom-10"> 
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label><h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7> </label>  
                                                                <?php 
                                                                $keyForQuestion = ($questionRow['ANSWER']==null || count($questionRow['ANSWER'])==0)?$questionRow['QUESTION_ID']:array_keys($questionRow['ANSWER'])[0];
                                                                if($questionRow['APPRAISER_FLAG']=='Y'){
                                                                    if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                    <div class="md-radio-inline">
                                                                        <?php $customRenderer($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")); ?>
                                                                    </div>
                                                                    <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                        <div class="md-checkbox-inline">
                                                                            <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")); ?>
                                                                        </div>
                                                                    <?php } else{
                                                                        print_r($this->formElement($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")));
                                                                    }
                                                                }
                                                                ?>
                                                            </div>
                                                            <?php if($questionRow['APPRAISER_RATING']=='Y'){ ?>
                                                            <div class="col-sm-1">
                                                                <label>Self Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForRevQuestion.".rr]"?>" value="<?= ($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['RATING']:null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" disabled="disabled"/>
                                                            </div>
                                                            <?php }
                                                            if((count($questionRow['ANSWER'])>0 && array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']!=null)||$questionForCurStage>0){
                                                            $keyForRevQuestion = (array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']==null)?$questionRow['QUESTION_ID']:array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID'];
                                                                if($questionRow['REVIEWER_FLAG']=='Y'){ 
                                                                    $questionOnPreTab+=1;
                                                                    ?>
                                                                    <div class="col-sm-3">
                                                                        <label>Reviewer's Comment:</label>
                                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']:0; ?>" name="answerId[]"/>
                                                                        <?php if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                            <div class="md-radio-inline">
                                                                                <?php $customRenderer($performanceAppraisalObj("answer[".$keyForRevQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER']:null,$disabled)); ?>
                                                                            </div>
                                                                            <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                                <div class="md-checkbox-inline">
                                                                                    <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForRevQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER']:null,$disabled)); ?>
                                                                                </div>
                                                                            <?php } else{
                                                                                print_r($this->formElement($performanceAppraisalObj("answer[".$keyForRevQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER']:null,$disabled)));
                                                                            }?>
                                                                    </div>
                                                                <?php }?>
                                                                <?php if($questionRow['REVIEWER_RATING']=='Y'){ 
                                                                    $questionOnPreTab+=1;
                                                                    if($questionRow['REVIEWER_FLAG']=='N'){?>
                                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']:0; ?>" name="answerId[]"/>
                                                                        <input type="hidden" value="" name="<?= "answer[".$keyForRevQuestion."]";?>"/>
                                                                    <?php } ?>
                                                                <div class="col-sm-2">
                                                                    <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_ANSWER_ID']:0; ?>" name="answerId[]"/>
                                                                    <label>Reviewer Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForRevQuestion.".rr]"?>" value="<?= ($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['REVIEWER_RATING_VAL']:null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" <?= $disabled; ?> required="required"/>
                                                                </div>
                                                            <?php }
                                                                }?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <?php if(($assignedAppraisalDetail['KPI_SETTING']=='Y') && ($assignedAppraisalDetail['COMPETENCIES_SETTING']=='Y') && ($appraiserRatingDtlNum>0 || $appCompetenciesRatingDtlNum>0)){ ?>
                                <div class="col-sm-12">
                                    <label>
                                Overall Rating:
                                    </label>
                                    <input type="text" disabled="disabled" id="appraiserOverallRating"  name="appraiserOverallRating"/>
                                </div>
                                <?php } ?>
                            </div>
                                <?php if(($questionForCurStage>0 && $questionOnPreTab>0)||($questionOnPreTab>0 && $appraiseeAvailableAnswer!==true)){ ?>
                                    <div class="row margin-top-10">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <button type="submit" id="submit" class="btn btn-success pull-right">
                                                    NEXT
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </form>
                        </div>
                        <div class="tab-pane <?= ($tab==3)?"active":""; ?>" id="portlet_tab2_3">
                            <form method="post" action="<?= $this->url("appraisal-review",['action'=>'view','appraisalId'=>$appraisalId,'employeeId'=>$employeeId,'tab'=>3]) ?>" name="performanceAppraisalForm" id="appraisalReview2">
                            <div class="row">
                                <?php
                                foreach ($reviewerQuestionTemplate as $reviewerQuestionList) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $reviewerQuestionList['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($reviewerQuestionList['QUESTIONS'] as $reviewerQuestionRow) { ?>
                                                    <div  class="col-md-12 margin-bottom-10"> 
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label> <h7 style="font-size:12px;"><?php echo $reviewerQuestionRow['QUESTION_EDESC']; ?></h7>  </label> 
                                                                <?php 
                                                                $keyForRQuestion = ($reviewerQuestionRow['ANSWER']==null || count($reviewerQuestionRow['ANSWER'])==0)?$reviewerQuestionRow['QUESTION_ID']:array_keys($reviewerQuestionRow['ANSWER'])[0];
                                                                if($reviewerQuestionRow['REVIEWER_FLAG']=='Y'){ ?>
                                                                <input type="hidden" value="<?= (count($reviewerQuestionRow['ANSWER'])>0)?array_keys($reviewerQuestionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                                    <?php if($reviewerQuestionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                    <div class="md-radio-inline">
                                                                        <?php $customRenderer($performanceAppraisalObj("answer[".$keyForRQuestion."]", $reviewerQuestionRow['ANSWER_TYPE'],(count($reviewerQuestionRow['QUESTION_OPTIONS'])>0)?$reviewerQuestionRow['QUESTION_OPTIONS']:null,($reviewerQuestionRow['ANSWER']!=null && count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]['ANSWER']:null,$disabled)); ?>
                                                                    </div>
                                                                    <?php } else if($reviewerQuestionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                        <div class="md-checkbox-inline">
                                                                            <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForRQuestion."][]", $reviewerQuestionRow['ANSWER_TYPE'],(count($reviewerQuestionRow['QUESTION_OPTIONS'])>0)?$reviewerQuestionRow['QUESTION_OPTIONS']:null,($reviewerQuestionRow['ANSWER']!=null && count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]['ANSWER']:null,$disabled)); ?>
                                                                        </div>
                                                                    <?php } else{
                                                                        print_r($this->formElement($performanceAppraisalObj("answer[".$keyForRQuestion."]", $reviewerQuestionRow['ANSWER_TYPE'],(count($reviewerQuestionRow['QUESTION_OPTIONS'])>0)?$reviewerQuestionRow['QUESTION_OPTIONS']:null,($reviewerQuestionRow['ANSWER']!=null && count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]['ANSWER']:null,$disabled)));
                                                                    }
                                                                }
                                                                ?>
                                                            </div>
                                                            <?php if($reviewerQuestionRow['REVIEWER_RATING']=='Y'){ 
                                                                if($reviewerQuestionRow['REVIEWER_FLAG']=='N'){?>
                                                                <input type="hidden" value="<?= (count($reviewerQuestionRow['ANSWER'])>0)?array_keys($reviewerQuestionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                                <input type="hidden" value="" name="<?= "answer[".$keyForRQuestion."]"; ?>"/>
                                                             <?php }?>
                                                            <div class="col-sm-1">
                                                                <input type="hidden" value="<?= (count($reviewerQuestionRow['ANSWER'])>0)?array_keys($reviewerQuestionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                                <label>Self Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForRQuestion.".rr]"?>" value="<?= ($reviewerQuestionRow['ANSWER']!=null||count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]['RATING']:null ?>" <?= $disabled ?> min="<?= $reviewerQuestionRow['MIN_VALUE'] ?>" max="<?= $reviewerQuestionRow['MAX_VALUE'] ?>" required="required"/>
                                                            </div>
                                                            <?php }?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <?php if(($assignedAppraisalDetail['KPI_SETTING']=='Y') && ($assignedAppraisalDetail['COMPETENCIES_SETTING']=='Y')){ ?>
                                <div class="col-sm-12">
                                    <label style="font-size:12px !important;">
                                I agree with the Appraiser's overall performance assessment. Agree? 
                                    </label>
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input class="" <?= $disabled ?> type="hidden" name="reviewerAgree" id="reviewerAgree" value="N"/>
                                        <input class="" <?= $disabled ?> <?= ($assignedAppraisalDetail['REVIEWER_AGREE']=='Y')?"checked":""; ?> type="checkbox" name="reviewerAgree" id="reviewerAgree" value="Y"/>
                                        <span></span>
                                    </label>
                                </div>
                                <?php } ?>
                            </div>
                            <?php if($questionForCurStage>0 || $appraiseeAvailableAnswer!==true){ ?>
                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success pull-right">
                                            SUBMIT
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            </form>
                        </div>
                        <div class="tab-pane" id="portlet_tab2_4">
                            <form method="post" action="" name="performanceAppraisalForm">
                            <div class="row">
                                <?php
                                foreach ($appraiseeQuestionTemplate as $appraiseeQuestionRow) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $appraiseeQuestionRow['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($appraiseeQuestionRow['QUESTIONS'] as $questionRow) { ?>
                                                    <div  class="col-md-12 margin-bottom-10">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label><h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7> </label> 
                                                                <?php 
                                                                $keyForQuestion = ($questionRow['ANSWER']==null || count($questionRow['ANSWER'])==0)?$questionRow['QUESTION_ID']:array_keys($questionRow['ANSWER'])[0];
                                                                if($questionRow['APPRAISEE_FLAG']=='Y'){
                                                                    if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                                    <div class="md-radio-inline">
                                                                        <?php $customRenderer($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")); ?>
                                                                    </div>
                                                                    <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                                        <div class="md-checkbox-inline">
                                                                            <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")); ?>
                                                                        </div>
                                                                    <?php } else{
                                                                        print_r($this->formElement($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['ANSWER']:null,"disabled")));
                                                                    }
                                                                }
                                                                ?>
                                                            </div>
                                                            <?php if($questionRow['APPRAISEE_RATING']=='Y'){ ?>
                                                                <div class="col-sm-1">
                                                                    <label>Self Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForQuestion.".sr]"?>" value="<?= ($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]['RATING']:null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" disabled="disabled"/>
                                                                </div>
                                                            <?php }?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <?php if(($assignedAppraisalDetail['KPI_SETTING']=='Y') && ($assignedAppraisalDetail['COMPETENCIES_SETTING']=='Y')){ ?>
                                <div class="col-sm-12">
                                    <label style="font-size:12px !important;">
                                Have you had the opportunity for a full discussion on the report and agree. Agree? 
                                    </label>
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input class="" disabled="disabled" type="checkbox" name="appraiseeAgree" id="appraiseeAgree" value="Y" <?= ($assignedAppraisalDetail['APPRAISEE_AGREE']=='Y')?"checked":"" ?>/>
                                        <span></span>
                                    </label>
                                </div>
                                <?php } ?>
                            </div>
<!--                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success">
                                            SUBMIT
                                        </button>
                                    </div>
                                </div>
                            </div>-->
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

