<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/loan-request/add.js'));
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\appraisal-review')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php

if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-md-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <?=
                    $assignedAppraisalDetail['APPRAISAL_EDESC'];
                    ?>
                </div>
                <div class="btn-group pull-right open" style="margin-top:1%">

                </div>
            </div>
            <div class="portlet-body" style="padding-top:1px;">
                <h5 id="headingForPanel"><b>Personal Information</b></h5>
                <div class="row div-font-11">
                    <div class="col-md-4">
                        <table>
                            <tbody>
                                <tr height="30">
                                    <td>
                                        Appraisee's Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        $middleName = ($employeeDetail['MIDDLE_NAME'] == null || $employeeDetail['MIDDLE_NAME'] == "") ? " " : " " . $employeeDetail['MIDDLE_NAME'] . " ";
                                        $employeeName = $employeeDetail['FIRST_NAME'] . $middleName . $employeeDetail['LAST_NAME'];
                                        print_r($employeeName);
                                        ?>  
                                    </td>
                                </tr>

                                <tr height="30">
                                    <td>
                                        Department
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['BRANCH_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Appraisal Period
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $assignedAppraisalDetail['START_DATE']; ?>
                                        To
                                        <?= $assignedAppraisalDetail['END_DATE']; ?>
                                    </td>
                                </tr>
                            </tbody></table>
                    </div>
                    <div class="col-md-4">
                        <table>
                            <tbody>
                                <tr height="30">
                                    <td>
                                        Position
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['POSITION_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Joining Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['JOIN_DATE']; ?>  
                                    </td>
                                </tr>
                                <tr height="30" id="availableDaysText">
                                    <td>
                                        Appraiser's Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        $middleName_A = ($assignedAppraisalDetail['MIDDLE_NAME_A'] == null || $assignedAppraisalDetail['MIDDLE_NAME_A'] == "") ? " " : " " . $assignedAppraisalDetail['MIDDLE_NAME_A'] . " ";
                                        $employeeName_A = $assignedAppraisalDetail['FIRST_NAME_A'] . $middleName_A . $assignedAppraisalDetail['LAST_NAME_A'];
                                        print_r($employeeName_A);
                                        ?>       
                                    </td>
                                </tr>
                            </tbody></table>
                    </div>
                    <div class="col-md-4">
                        <table>
                            <tbody>
                                <tr height="30">
                                    <td>
                                        Branch
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $employeeDetail['BRANCH_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Reviewer's Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        $middleName_R = ($assignedAppraisalDetail['MIDDLE_NAME_R'] == null || $assignedAppraisalDetail['MIDDLE_NAME_R'] == "") ? " " : " " . $assignedAppraisalDetail['MIDDLE_NAME_R'] . " ";
                                        $employeeName_R = $assignedAppraisalDetail['FIRST_NAME_R'] . $middleName_R . $assignedAppraisalDetail['LAST_NAME_R'];
                                        print_r($employeeName_R);
                                        ?>                                         
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="portlet-body" style="padding-top:1px;">
                <h5 id="headingForPanel"><b>Performance Evaluation</b></h5>
                <div class="portlet-body">
                    <div class="tabbable-line menusetuptab" style="padding-top:0px">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#portlet_tab2_1" data-toggle="tab"> Appraisee's Evaluation </a>
                            </li>
                            <?php if(count($appraiserQuestionTemplate)>0){ ?>
                            <li class="">
                                <a href="#portlet_tab2_2" data-toggle="tab"> Appraiser's Evaluation </a>
                            </li>
                            <?php } ?>
                            <?php if(count($appraiseeQuestionTemplate)>0){ ?>
                            <li class="">
                                <a href="#portlet_tab2_4" data-toggle="tab"> Appraisee's Feedback </a>
                            </li>
                            <?php } ?>
                            <?php if(count($reviewerQuestionTemplate)>0){ ?>
                            <li class="">
                                <a href="#portlet_tab2_3" data-toggle="tab"> Reviewer's Evaluation </a>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="tab-content margin-top-15" >
                        <div class="tab-pane active" id="portlet_tab2_1">
                            <form method="post" action="" name="performanceAppraisalForm">
                            <div class="row">
                                <?php foreach ($questionTemplate as $questionTemplateRow) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $questionTemplateRow['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($questionTemplateRow['QUESTIONS'] as $questionRow) { ?>
                                                    <div class="col-md-4">    
                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_keys($questionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                        <h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7>  
                                                        <?php 
                                                        $keyForQuestion = ($questionRow['ANSWER']==null || count($questionRow['ANSWER'])==0)?$questionRow['QUESTION_ID']:array_keys($questionRow['ANSWER'])[0];
                                                        if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                        <div class="md-radio-inline">
                                                            <?php $customRenderer($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")); ?>
                                                        </div>
                                                        <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                            <div class="md-checkbox-inline">
                                                                <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")); ?>
                                                            </div>
                                                        <?php } else{
                                                            print_r($this->formElement($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null||count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")));
                                                        }
                                                        ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
<!--                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success">
                                            SUBMIT
                                        </button>
                                    </div>
                                </div>
                            </div>-->
                            </form>
                        </div>
                        <div class="tab-pane" id="portlet_tab2_2">
                            <form method="post" action="" name="performanceAppraisalForm">
                            <div class="row">
                                <?php
                                foreach ($appraiserQuestionTemplate as $appraiserQuestionRow) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $appraiserQuestionRow['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($appraiserQuestionRow['QUESTIONS'] as $questionRow) { ?>
                                                    <div  class="col-md-4 margin-bottom-10">  
                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_keys($questionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                        <h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7>  
                                                        <?php 
                                                        $keyForQuestion = ($questionRow['ANSWER']==null || count($questionRow['ANSWER'])==0)?$questionRow['QUESTION_ID']:array_keys($questionRow['ANSWER'])[0];
                                                        if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                        <div class="md-radio-inline">
                                                            <?php $customRenderer($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")); ?>
                                                        </div>
                                                        <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                            <div class="md-checkbox-inline">
                                                                <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")); ?>
                                                            </div>
                                                        <?php } else{
                                                            print_r($this->formElement($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")));
                                                        }
                                                        ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
<!--                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success">
                                            SUBMIT
                                        </button>
                                    </div>
                                </div>
                            </div>-->
                            </form>
                        </div>
                        <div class="tab-pane" id="portlet_tab2_4">
                            <form method="post" action="" name="performanceAppraisalForm">
                            <div class="row">
                                <?php
                                foreach ($appraiseeQuestionTemplate as $appraiseeQuestionRow) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $appraiseeQuestionRow['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($appraiseeQuestionRow['QUESTIONS'] as $questionRow) { ?>
                                                    <div  class="col-md-4 margin-bottom-10">
                                                        <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_keys($questionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                        <h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7>  
                                                        <?php 
                                                        $keyForQuestion = ($questionRow['ANSWER']==null || count($questionRow['ANSWER'])==0)?$questionRow['QUESTION_ID']:array_keys($questionRow['ANSWER'])[0];
                                                        if($questionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                        <div class="md-radio-inline">
                                                            <?php $customRenderer($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")); ?>
                                                        </div>
                                                        <?php } else if($questionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                            <div class="md-checkbox-inline">
                                                                <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForQuestion."][]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")); ?>
                                                            </div>
                                                        <?php } else{
                                                            print_r($this->formElement($performanceAppraisalObj("answer[".$keyForQuestion."]", $questionRow['ANSWER_TYPE'],(count($questionRow['QUESTION_OPTIONS'])>0)?$questionRow['QUESTION_OPTIONS']:null,($questionRow['ANSWER']!=null && count($questionRow['ANSWER'])>0)?array_values($questionRow['ANSWER'])[0]:null,"disabled")));
                                                        }
                                                        ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
<!--                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success">
                                            SUBMIT
                                        </button>
                                    </div>
                                </div>
                            </div>-->
                            </form>
                        </div>
                        <div class="tab-pane" id="portlet_tab2_3">
                            <form method="post" action="<?= $this->url("appraisal-review",['action'=>'view','appraisalId'=>$appraisalId,'employeeId'=>$employeeId]) ?>" name="performanceAppraisalForm">
                            <div class="row">
                                <?php
                                $disabled = ($questionForCurStage==0)?'disabled':'';
                                foreach ($reviewerQuestionTemplate as $reviewerQuestionList) { ?>
                                    <div class="col-md-12 margin-bottom-10">
                                        <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                                            <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $reviewerQuestionList['HEADING_EDESC']; ?></h6>
                                            <div class="row">
                                                <?php foreach ($reviewerQuestionList['QUESTIONS'] as $reviewerQuestionRow) { ?>
                                                    <div  class="col-md-4 margin-bottom-10"> 
                                                        <input type="hidden" value="<?= (count($reviewerQuestionRow['ANSWER'])>0)?array_keys($reviewerQuestionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                                        <h7 style="font-size:12px;"><?php echo $reviewerQuestionRow['QUESTION_EDESC']; ?></h7>  
                                                        <?php 
                                                        $keyForRQuestion = ($reviewerQuestionRow['ANSWER']==null || count($reviewerQuestionRow['ANSWER'])==0)?$reviewerQuestionRow['QUESTION_ID']:array_keys($reviewerQuestionRow['ANSWER'])[0];
                                                        if($reviewerQuestionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                                        <div class="md-radio-inline">
                                                            <?php $customRenderer($performanceAppraisalObj("answer[".$keyForRQuestion."]", $reviewerQuestionRow['ANSWER_TYPE'],(count($reviewerQuestionRow['QUESTION_OPTIONS'])>0)?$reviewerQuestionRow['QUESTION_OPTIONS']:null,($reviewerQuestionRow['ANSWER']!=null && count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]:null,$disabled)); ?>
                                                        </div>
                                                        <?php } else if($reviewerQuestionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                            <div class="md-checkbox-inline">
                                                                <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForRQuestion."][]", $reviewerQuestionRow['ANSWER_TYPE'],(count($reviewerQuestionRow['QUESTION_OPTIONS'])>0)?$reviewerQuestionRow['QUESTION_OPTIONS']:null,($reviewerQuestionRow['ANSWER']!=null && count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]:null,$disabled)); ?>
                                                            </div>
                                                        <?php } else{
                                                            print_r($this->formElement($performanceAppraisalObj("answer[".$keyForRQuestion."]", $reviewerQuestionRow['ANSWER_TYPE'],(count($reviewerQuestionRow['QUESTION_OPTIONS'])>0)?$reviewerQuestionRow['QUESTION_OPTIONS']:null,($reviewerQuestionRow['ANSWER']!=null && count($reviewerQuestionRow['ANSWER'])>0)?array_values($reviewerQuestionRow['ANSWER'])[0]:null,$disabled)));
                                                        }
                                                        ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                            <?php if($questionForCurStage>0){ ?>
                            <div class="row margin-top-10">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-success">
                                            SUBMIT
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

