<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/setup/academic-degree/index.js'));
?>

<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuAcademicDegree"]];echo json_encode($menu);?>;
    document.academicDegrees=<?php echo json_encode($academicDegrees);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\academicDegree')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('academicDegree', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="academicDegreeTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (ACADEMIC_DEGREE_CODE == null) ? '-' : ACADEMIC_DEGREE_CODE #
        </td>
        <td>
        #: (ACADEMIC_DEGREE_NAME == null) ? '-' : ACADEMIC_DEGREE_NAME #
        </td>
        <td>
        #: WEIGHT #
        </td>
        <td>
        <a class=""
        href="<?= $this->url("academicDegree", ["action" => "edit"]) ?>/#:ACADEMIC_DEGREE_ID #">
        Edit
        </a> /
        <a class=""
        href="<?= $this->url("academicDegree", ["action" => "delete"]); ?>/#:ACADEMIC_DEGREE_ID #">
        Delete
        </a>
        </td>
        </tr>
    </script>
</div>