<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/mustache.js'))
        ->appendFile($this->basePath('assets/global/plugins/jsPDF-master/dist/jspdf.debug.js'))
        ->appendFile($this->basePath('js/Payroll/payrollReport/letterToBank.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('payrollReport', ['action' => 'getFiscalYearMonth']); ?>';
    document.pullLetterToBankDetail = '<?= $this->url("payrollReport", ["action" => "pullLetterToBankDetail"]) ?>';
    document.salaryType =<?php echo json_encode($salaryType); ?>;
    document.bankType =<?php echo json_encode($bankType); ?>;
    document.preference =<?php echo json_encode($preference) ?>;
    document.incomes =<?php echo json_encode($incomes); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.taxExcemptions =<?php echo json_encode($taxExcemptions); ?>;
    document.otherTax =<?php echo json_encode($otherTax); ?>;
    document.miscellaneous =<?php echo json_encode($miscellaneous); ?>;
    document.bMiscellaneou =<?php echo json_encode($bMiscellaneou); ?>;
    document.cMiscellaneou =<?php echo json_encode($cMiscellaneou); ?>;
    document.sumOfExemption =<?php echo json_encode($sumOfExemption); ?>;
    document.sumOfOtherTax =<?php echo json_encode($sumOfOtherTax); ?>;
</script>

<style>
.table-condensed>thead>tr>th, .table-condensed>thead>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tbody>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>tfoot>tr>td {
    padding: 0px;
}    
</style>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\monthlyValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Year</label>
                            <select id="fiscalYearId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Month</label>
                            <select id="monthId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Bank</label>
                            <select class="form-control" name="bankType" id="bankTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Salary Type</label>
                            <select class="form-control reset-field" name="salaryType" id="salaryTypeId">
                            </select>
                        </div>
                    </div>
                    
                    <div class="row margin-top-10">
                        <div class="col-sm-4 col-sm-offset-8">
                            <button id="reset" class="btn default btn-sm pull-right">
                                Reset
                                <i class="fa fa-refresh"></i>
                            </button>
                            <button  id="searchEmployeesBtn" class="btn btn-default btn-sm pull-right">
                                Search
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                        
                        
                </div>
            </div>

            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="tools">
                        <a href="" class="fullscreen" data-original-title="" title=""> </a>
                    </div>

                    <div class="actions">
                        <div class="btn-group">
                            <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-copy"></i> Tools
                                <i class="fa fa-angle-down "></i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li >
                                    <a href="javascript:;" id="excelExport">
                                        <i class="fa fa-file-excel-o" ></i>
                                        Export to Excel
                                    </a>
                                </li>
                                <li >
                                    <a href="javascript:;" id="pdfExport">
                                        <i class="fa fa-file-pdf-o" ></i> 
                                        Export to PDF 
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
                <div class="portlet-body">
                        <div id="table" style="padding:5%;">
                    </div>
					 <div id="kendoTable" style="padding:5%; display:none;">
                    </div>
                        
                </div>
                
                



            </div>
        </div>
    </div>
</div>