<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/mustache.js'))
        ->appendFile($this->basePath('assets/global/plugins/jsPDF-master/dist/jspdf.debug.js'))
        ->appendFile($this->basePath('js/Payroll/payrollReport/taxYearly.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('payrollReport', ['action' => 'getFiscalYearMonth']); ?>';
    document.pulltaxYearlyLink = '<?= $this->url("payrollReport", ["action" => "pulltaxYearly"]) ?>';
    document.salaryType =<?php echo json_encode($salaryType); ?>;
    document.preference =<?php echo json_encode($preference) ?>;
    document.incomes =<?php echo json_encode($incomes); ?>;
    document.taxExcemptions =<?php echo json_encode($taxExcemptions); ?>;
    document.otherTax =<?php echo json_encode($otherTax); ?>;
    document.miscellaneous =<?php echo json_encode($miscellaneous); ?>;
    document.bMiscellaneou =<?php echo json_encode($bMiscellaneou); ?>;
    document.cMiscellaneou =<?php echo json_encode($cMiscellaneou); ?>;
    document.sumOfExemption =<?php echo json_encode($sumOfExemption); ?>;
    document.sumOfOtherTax =<?php echo json_encode($sumOfOtherTax); ?>;
</script>

<style>
.table-condensed>thead>tr>th, .table-condensed>thead>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tbody>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>tfoot>tr>td {
    padding: 0px;
}    
</style>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\monthlyValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <label>Company</label>
                            <select multiple class="form-control" name="company" id="companyId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Branch</label>
                            <select multiple class="form-control" name="branchId" id="branchId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Department</label>
                            <select multiple class="form-control" name="department" id="departmentId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Designation</label>
                            <select multiple class="form-control" name="designation" id="designationId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Position</label>
                            <select multiple class="form-control" name="position" id="positionId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Service Type</label>
                            <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                            </select>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Service Event Type</label>
                            <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Employee Type</label>
                            <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Gender</label>
                            <select multiple class="form-control" name="gender" id="genderId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Functional Type</label>
                            <select multiple class="form-control" name="functionalType" id="functionalTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Employee</label>
                            <select multiple class="form-control" name="employee" id="employeeId">
                            </select>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Year</label>
                            <select id="fiscalYearId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Month</label>
                            <select id="monthId">
                            </select>
                        </div>
<!--                        <div class="col-sm-2">
                            <label>Variables</label>
                            <select multiple class="form-control" name="otVariable" id="otVariable">
                            </select>
                        </div>-->
<!--                        <div class="col-sm-2">
                            <label>Extra Fields</label>
                            <select multiple class="form-control" name="extraFields" id="extraFields">
                            </select>
                        </div>-->
<!--                        <div class="col-sm-2">
                            <label>Report Type</label>
                            <select class="form-control" name="reportType" id="reportType">
                                <option value="GS">Group Sheet</option>
                                <option value="GD">Group Detail</option>
                                <option value="S">Summary</option>
                            </select>
                        </div>-->
                        <div class="col-sm-2">
                            <label>Salary Type</label>
                            <select class="form-control" name="salaryType" id="salaryTypeId">
                            </select>
                        </div>
                    </div>
                    
<!--                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Group Variables</label>
                            <select class="form-control" name="groupVariable" id="groupVariable">
                            </select>
                        </div>
                    </div>-->
                    
                    <div class="row margin-top-10">
                        <div class="col-sm-4 col-sm-offset-8">
                            <button id="reset" class="btn default btn-sm pull-right">
                                Reset
                                <i class="fa fa-refresh"></i>
                            </button>
                            <button  id="searchEmployeesBtn" class="btn btn-default btn-sm pull-right">
                                Search
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                        
                        
                </div>
            </div>

            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="tools">
                        <a href="" class="fullscreen" data-original-title="" title=""> </a>
                    </div>

                    <div class="actions">
                        <div class="btn-group">
                            <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-copy"></i> Tools
                                <i class="fa fa-angle-down "></i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li >
                                    <a href="javascript:;" id="excelExport">
                                        <i class="fa fa-file-excel-o" ></i>
                                        Export to Excel
                                    </a>
                                </li>
                                <li >
                                    <a href="javascript:;" id="pdfExport">
                                        <i class="fa fa-file-pdf-o" ></i> 
                                        Export to PDF 
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
                <div class="portlet-body">
                        <div id="table">
                    </div>
                        
                </div>
                
                



            </div>
        </div>
    </div>
</div>