<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/bootstrap-timepicker/bootstrap-timepicker.min.js'));
$this->headScript()->appendFile($this->basePath('js/shift/add.js'));
?>
<script>
    document.menu =<?php $menu = ["id" => "menuAttendanceManagement", "subMenu" => ["id" => "subMenuShiftSetup"]];echo json_encode($menu);?>;
</script>

<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'position-form');

$shiftCode = $form->get('shiftCode');
$shiftEname = $form->get('shiftEname');
$shiftLname = $form->get('shiftLname');

$startTime = $form->get('startTime');
$endTime = $form->get('endTime');

$halfDayEndTime = $form->get('halfDayEndTime');
$halfTime = $form->get('halfTime');

$lateIn = $form->get('lateIn');
$earlyOut = $form->get('earlyOut');

$startDate = $form->get('startDate');
$endDate = $form->get('endDate');

$weekday1 = $form->get('weekday1');
$weekday2 = $form->get('weekday2');
$weekday3 = $form->get('weekday3');
$weekday4 = $form->get('weekday4');
$weekday5 = $form->get('weekday5');
$weekday6 = $form->get('weekday6');
$weekday7 = $form->get('weekday7');

$currentShift = $form->get('currentShift');
$twoDayShift = $form->get('twoDayShift');
$defaultShift = $form->get('defaultShift');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

?>
<div class="container">
    <?php // add the following line: ?>
    <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0) ?>
</div>
<?php
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>

<?php

$form->setAttribute('action', $this->url('shiftsetup', ['action' => 'add']));
$form->prepare();

?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default customShadow">
            <div class="panel-heading bg-master-lighter">
                <div class="panel-title">
                    <h3 class="panel-title">Shift</h3>
                </div>
            </div>
            <div class="panel-body p-t-5 p-l-25">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="row">
                    <div class="col-sm-6">
                        <div
                            class="form-group form-group-sm  <?= empty($shiftCode->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($shiftCode); ?>
                            <?php print $this->formElement($shiftCode); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($shiftCode, ['class' => 'help-block error']); ?>
                    </div>
                    <div class="col-sm-6"></div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div
                            class="form-group form-group-sm  <?= empty($shiftEname->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($shiftEname); ?>
                            <?php print $this->formElement($shiftEname); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($shiftEname, ['class' => 'help-block error']); ?>

                    </div>
                    <div class="col-sm-6">
                        <div
                            class="form-group form-group-sm  <?= empty($shiftLname->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($shiftLname); ?>
                            <?php print $this->formElement($shiftLname); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($shiftLname, ['class' => 'help-block error']); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group form-group-sm required input-group bootstrap-timepicker ">
                            <?php print $this->formLabel($startTime) ?>
                            <?php print $this->formElement($startTime) ?>
                            <span class="input-group-addon"><i class="pg-clock"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($startTime, ['class' => 'help-block error']) ?>

                        <div class="form-group form-group-sm required input-group bootstrap-timepicker">
                            <?php print $this->formLabel($endTime) ?>
                            <?php print $this->formElement($endTime) ?>
                            <span class="input-group-addon"><i class="pg-clock"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($endTime, ['class' => 'help-block error']) ?>

                    </div>
                    <div class="col-sm-6">
                        <div class="form-group form-group-sm required input-group bootstrap-timepicker">
                            <?php print $this->formLabel($halfDayEndTime) ?>
                            <?php print $this->formElement($halfDayEndTime) ?>
                            <span class="input-group-addon"><i class="pg-clock"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($halfDayEndTime, ['class' => 'help-block error']) ?>

                        <div class="form-group form-group-sm required input-group bootstrap-timepicker">
                            <?php print $this->formLabel($halfTime) ?>
                            <?php print $this->formElement($halfTime) ?>
                            <span class="input-group-addon"><i class="pg-clock"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($halfTime, ['class' => 'help-block error']) ?>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group padding-0">
                            <?php print $this->formLabel($lateIn); ?>
                            <div class="radio radio-complete">
                                <?php $customRenderer($lateIn); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($lateIn, ['class' => 'help-block error']); ?>

                    </div>
                    <div class="col-sm-6">
                        <div class="form-group padding-0">
                            <?php print $this->formLabel($earlyOut); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($earlyOut); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($earlyOut, ['class' => 'help-block error']); ?>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div
                            class="form-group form-group-sm required input-group <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($startDate) ?>
                            <?php print $this->formElement($startDate) ?>
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>

                    </div>
                    <div class="col-sm-6">
                        <div
                            class="form-group form-group-sm required input-group <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($endDate) ?>
                            <?php print $this->formElement($endDate) ?>
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                        <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>

                    </div>
                </div>
                <div class="row bg-master-lightest">
                    <div class="col-sm-6 ">
                        <div class="form-group padding-0">
                            <?php print $this->formLabel($weekday1); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday1); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday1, ['class' => 'help-block error']); ?>

                        <div class="form-group  padding-0">
                            <?php print $this->formLabel($weekday3); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday3); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday3, ['class' => 'help-block error']); ?>

                        <div class="form-group padding-0">
                            <?php print $this->formLabel($weekday5); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday5); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday5, ['class' => 'help-block error']); ?>

                    </div>


                    <div class="col-sm-6 ">
                        <div class="form-group padding-0">
                            <?php print $this->formLabel($weekday2); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday2); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday2, ['class' => 'help-block error']); ?>


                        <div class="form-group padding-0">
                            <?php print $this->formLabel($weekday4); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday4); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday4, ['class' => 'help-block error']); ?>

                        <div class="form-group padding-0">
                            <?php print $this->formLabel($weekday6); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday6); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday6, ['class' => 'help-block error']); ?>

                        <div class="form-group padding-0">
                            <?php print $this->formLabel($weekday7); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($weekday7); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($weekday7, ['class' => 'help-block error']); ?>

                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group padding-0">
                            <?php print $this->formLabel($currentShift); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($currentShift); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($currentShift, ['class' => 'help-block error']); ?>

                        <div class="form-group padding-0">
                            <?php print $this->formLabel($defaultShift); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($defaultShift); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($defaultShift, ['class' => 'help-block error']); ?>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group padding-0 ">
                            <?php print $this->formLabel($twoDayShift); ?>
                            <div class="radio radio-success">
                                <?php $customRenderer($twoDayShift); ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($twoDayShift, ['class' => 'help-block error']); ?>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group form-group-sm">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>

                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>

