<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));
?>
<script>
    document.menu =<?php $menu = ["id" => "menuAttendanceManagement", "subMenu" => ["id" => "subMenuShiftSetup"]];echo json_encode($menu);?>;
</script>

<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>

<div class="panel panel-transparent bg-light-color">
    <div class="panel-heading">
        <div class="panel-title">
            <h5>Shift</h5>
        </div>
        <div class="btn-group pull-right m-b-10">
            <a class="btn btn-default" href="<?= $this->url('shiftsetup', ['action' => 'add']) ?>">
                Add new
            </a>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="pull-right">
            <div class="col-xs-12">
                <input type="text" id="search-table" class="form-control pull-right" placeholder="Search">
            </div>
        </div>
        <div class="clearfix"></div>

    </div>
    <div class="panel-body">
        <table class="table customTable demo-table-search" id="tableWithSearch">
            <thead>
            <tr role="row">
                <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                    rowspan="1"
                    aria-controls="basicTable" tabindex="0" class="sorting_desc">Shift Code
                </th>
                <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1"
                    aria-controls="basicTable"
                    tabindex="0" class="sorting">Shift Name
                </th>
                <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1"
                    aria-controls="basicTable"
                    tabindex="0" class="sorting">Start Time
                </th>
                <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1"
                    aria-controls="basicTable"
                    tabindex="0" class="sorting">End Time
                </th>
                <th aria-label="Last Update: activate to sort column ascending" colspan="1" rowspan="1"
                    aria-controls="basicTable" tabindex="0" class="sorting">
                    Action
                </th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($shiftList as $shift):
                ?>
                <tr role="row">
                    <td class="v-align-middle sorting_1">
                        <p>
                            <?php print $this->escapeHtml($shift['SHIFT_CODE']); ?>
                        </p>
                    </td>
                    <td class="v-align-middle sorting_1">
                        <p>
                            <?php print $this->escapeHtml($shift['SHIFT_ENAME']); ?>
                        </p>
                    </td>
                    <td class="v-align-middle sorting_1">
                        <p>
                            <?php print $this->escapeHtml($shift['START_TIME']); ?>
                        </p>
                    </td>
                    <td class="v-align-middle sorting_1">
                        <p>
                            <?php print $this->escapeHtml($shift['END_TIME']); ?>
                        </p>
                    </td>
                    <td class="v-align-middle sorting_1">
                        <a href="<?= $this->url("shiftsetup", ["action" => "edit", "id" => $shift['SHIFT_ID']]) ?>">Edit</a> /
                        <a href="<?= $this->url("shiftsetup", ["action" => "delete", "id" => $shift['SHIFT_ID']]); ?>"
                           onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                    </td>
                </tr>

            <?php endforeach; ?>

            </tbody>
        </table>

    </div>
</div>