<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/AttendanceManagement/ShiftSetup/index.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
?>
<script>
    document.menu =<?php $menu = ["id" => "menuAttendance", "subMenu" => ["id" => "subMenuShiftSetup"]];echo json_encode($menu);?>;
    document.shifts=<?php echo json_encode($shifts); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\shiftsetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb');?>
</div>

<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('shiftsetup', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="shiftTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (SHIFT_CODE == null) ? '-' : SHIFT_CODE #
        </td>
        <td>
        #: (SHIFT_ENAME == null) ? '-' : SHIFT_ENAME #
        </td>
        <td>
        #: (START_TIME == null) ? '-' : START_TIME #
        </td>
        <td>
        #: (END_TIME == null) ? '-' : END_TIME #
        </td>
        <td>
        <a class="btn  btn-icon-only btn-success" 
        href="<?= $this->url("shiftsetup", ["action" => "edit"]); ?>/#:SHIFT_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
        <a class="btn  btn-icon-only btn-danger confirmation" 
        href="<?= $this->url("shiftsetup", ["action" => "delete"]); ?>/#:SHIFT_ID #" id="bs_#:SHIFT_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i>
        </a>
        </td>
        </tr>
    </script>
</div>