<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/loan-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'loanApprove-form');

$loanId = $form->get('loanId');
$loanId->setValueOptions($loans);
$loanId->setAttributes(["disabled"=>"disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled"=>"disabled"]);
$loanDate = $form->get('loanDate');
$loanDate->setAttributes(["disabled"=>"disabled"]);
$reason = $form->get('reason');
$reason->setAttributes(["disabled"=>"disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['required'=>'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required'=>'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('loanApprove', ['action' => 'view', 'id' => $id, 'role' => $role]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuManagerService","subMenu"=>["id"=>"subMenuLoantoApprove"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\loanApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Loan Request Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Requested Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $requestedDate; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Your Role
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php if ($role == 3) {
                                                echo 'Approver';
                                            } else if ($role == 2) {
                                                echo 'Recommender';
                                            } ?>
                                    </td>
                                </tr>                               
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>  
                                <tr height="30">
                                    <td>
                                        Status
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        if ($status == 'RQ') {
                                            echo "Pending";
                                        } else if ($status == 'RC') {
                                            echo "Recommended";
                                        } else if ($status == 'AP') {
                                            echo "Approved";
                                        } else if ($status == "R") {
                                            echo "Rejected";
                                        } else if ($status == "C") {
                                            echo "Cancelled";
                                        } ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        <?= ($role==3)? "Recommender":"Approver"; ?>
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= ($role==3)? $recommender:$approver; ?>
                                    </td>
                                </tr>                               
                            </table>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($loanId); ?>
                    <?php print $this->formElement($loanId); ?>
                    <?php print $this->formElementErrors()->render($loanId, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($loanDate); ?>
                    <div class="input-group date" id="startDate">
                        <?php print $this->formElement($loanDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($loanDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($reason); ?>
                    <?php print $this->formElement($reason); ?>
                    <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                </div>
                <?php if ($role == 2) { ?>
                    <div
                        class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($recommendedRemarks); ?>
                        <?php print $this->formElement($recommendedRemarks); ?>
                    </div>
                <?php } ?>

                <?php if ($role == 3) {
                    $recommendedRemarks->setAttributes(['disabled'=>'disabled']);
                    ?>
                    <div
                        class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                        <label>Reason for action [From Recommender]</label>
                        <?php print $this->formElement($recommendedRemarks); ?>
                    </div>
                    <div
                        class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($approvedRemarks); ?>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php } ?>

                <?php
                if ($status == 'RQ' || ($status == 'RC' && $employeeId != $recommendedBy)) {
                    print $this->formSubmit($submit);
                    ?>
                    <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                <?php } ?>

            </div>

        </div>
    </div>
</div>

<?php

print $this->form()->closeTag();

?>