
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/other/bonus/calculation.js'));
?>


<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.bonusList = [
        {
            EMPLOYEE_NAME: "Ukesh Gaiju",
            BONUS_AMOUNT: "12000"
        },
        {
            EMPLOYEE_NAME: "Subin Manandhar",
            BONUS_AMOUNT: "15000"
        },
        {
            EMPLOYEE_NAME: "Rajan Thapa Shrestha",
            BONUS_AMOUNT: "15000"
        }
    ];
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\bonus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div id="bonusTable">
    </div>
    <div class="table-toolbar margin-top-20">
        <div class="row">
            <div class="col-md-12">
                <div class="btn-group pull-right">
                    <a href="#" id="sample_editable_1_new" class="btn green"> Calculate
                        <i class="fa fa-save"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (EMPLOYEE_NAME == null) ? '-' : EMPLOYEE_NAME #
        </td>
        <td> 
        #: (BONUS_AMOUNT== null) ? '-' : BONUS_AMOUNT#
        </td>
        </tr>
    </script>
</div>

