<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/advance/advance-status/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advanceStatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="advanceStatusListController">
     <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <select class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <select class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <?php print $this->formElement($advances); ?>
                </div>
                <div class="col-sm-2">
                    <?php print $this->formElement($advanceStatus); ?>
                </div>   
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="fromDate1" name="fromDate" ng-model="fromDate" class="form-control" placeholder="From Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="toDate1" name="toDate" ng-model="toDate" class="form-control" placeholder="To Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2 col-lg-offset-2">
                     <button ng-click="view()" id="viewLeaveRequestStatus" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="margin-top-20">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-offset-6 col-md-6">
                    <label height="45"></label>
                    <div class="btn-group pull-right">
                        <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;" id="export"> Export to Excel </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div> </div>
    </div>


    <div class="margin-top-20">
        <div id="advanceRequestStatusTable">
        </div>
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td> 
        #: (FIRST_NAME == null) ? ' ' : FIRST_NAME #
        #: (MIDDLE_NAME == null) ? ' ' : MIDDLE_NAME #
        #: (LAST_NAME == null) ? ' ' : LAST_NAME #
        </td>
        <td>
        #: (ADVANCE_NAME == null) ? '-' : ADVANCE_NAME #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>        
        <td>
        #: (ADVANCE_DATE == null) ? '-' : ADVANCE_DATE #
        </td>
        <td>
        #: (REQUESTED_AMOUNT == null) ? '-' : REQUESTED_AMOUNT #
        </td>
        <td>
        #: (RECOMMENDER_NAME == null) ? '-' : RECOMMENDER_NAME #
        </td>
        <td>
        #: (APPROVER_NAME == null) ? '-' : APPROVER_NAME #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("advanceStatus", ["action" => "view"]) ?>/#: ADVANCE_REQUEST_ID #" style="height:17px;" title="view">
        <i class="fa fa-search-plus"></i>
        </a>
        </td>
        </tr>
    </script>

</div>    



