<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/please-wait/build/please-wait.css'));
$this->headLink()->appendStylesheet($this->basePath('css/please-wait-custom.css'));
$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/please-wait/build/please-wait.min.js'));
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/Payroll/salary-sheet/index.js'));

?>
<script>
    document.data =<?php echo $data; ?>;
    document.data['loading-icon'] = '<?php echo $this->basePath('img/payroll-icon.png'); ?>';
    document.getFiscalYearMonthLink = '<?php echo $this->url('salarySheet', ['action' => 'getFiscalYearMonth']); ?>';
    document.pullGroupEmployeeLink = '<?php echo $this->url('salarySheet', ['action' => 'pullGroupEmployee']); ?>';
    document.deleteLink = '<?= $this->url("salarySheet", ["action" => "deleteSheet"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salarySheet')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-money"></i>Salary Sheet 
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li >
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li >
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF 
                        </a>
                    </li>
                    <li >
                        
                        <a href="<?php echo $this->basePath('uploads/PAYROLL_LOG.txt'); ?>" download="log.txt">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Download payroll log 
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Salary Type</label>
                <select class="form-control" name="salaryType" id="salaryTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Company</label>
                <select  class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Group</label>
                <select multiple="multiple" class="form-control" name="group" id="groupId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Sheet</label>
                <select class="form-control" name="allSheetId" id="allSheetId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <select id="fiscalYearId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="monthId">
                </select>
            </div>
            <div class="col-sm-6">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <input type="text" id="fromDate"  class="form-control" placeholder="From Date"/>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <input type="text" id="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <input type="text" id="toDate" class="form-control" placeholder="To Date"/>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <input type="text" id="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-2">
                 <label>Pay Heads</label>
                 <select multiple class="form-control reset-field" name="allPayHeads" id="allPayHeads">
                            </select>
            </div>
            <div class="col-sm-10">
                <button id="generateBtn" class="btn blue-hoki pull-right">Generate</button>
                <button id="viewBtn" class="btn yellow-saffron pull-right">View</button>
            </div>
        </div>
        
        <!--<div id="employeeTableDiv" class="row" style="height:200px;overflow:auto;">-->
        <div id="employeeTableDiv" class="row">
            <div class="col-lg-6 col-ms-6 col-sm-6">
                <div id="employeeTable">
                </div>
            </div>
            <div class="col-lg-6 col-ms-6 col-sm-6 margin-top-30">
                <div id="sheetTable">
                </div>
            </div>
        </div>
        
        <div id="table" class="margin-top-10">
        </div>
    </div>
</div>
<h4 class="close-please-wait" id="please-wait-options" >
    <button type="button" class="btn red default btn-lg" id="cancelBtn">Cancel</button>
    <button type="button" class="btn blue default btn-lg" action="pause" id="pauseBtn">Pause</button>
</h4>