<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/Payroll/salary-sheet/pay-value-modified.js'));
?>
<script>
    window.data =<?php echo $data; ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salarySheet')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Portlet </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="" class="fullscreen" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body" style="display: block;">
                    <div class="row">
                        <div class="col-sm-2">
                            <select class="form-control" id="fiscalYearId" >
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" id="monthId" >
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select  class="form-control" name="company" id="companyId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="group" id="groupId">
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="portlet">
                <div class="portlet-title">
                    <div class="caption">
                        <div class="tools">
                            <a href="" class="fullscreen" data-original-title="" title=""> </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="table">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>