<?php
$this->headScript()->appendFile($this->basePath('js/Payroll/salary-sheet/payslip.js'));
?>
<script>
    document.getFiscalYearMonthLink = '<?php echo $this->url('salarySheet', ['action' => 'getFiscalYearMonth']); ?>';
    document.getSearchDataLink = '<?php echo $this->url('salarySheet', ['action' => 'getSearchData']); ?>';
    document.salaryType =<?php echo $salaryType; ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salarySheet')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-money"></i>Payslip
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li >
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li >
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF 
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <select id="fiscalYearId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="monthId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="employeeId">
                </select>
            </div>
            <div class="col-sm-2">
                <!--<label>Salary Type</label>-->
                <select class="form-control" name="salaryType" id="salaryTypeId">
                </select>
            </div>
            <div class="col-sm-2 col-sm-offset-2">
                <button id="viewBtn" class="btn btn-info pull-right">View</button>
            </div>
        </div>
        <div id="paySlipView" class="margin-top-10">
            <tr><td colspan="4"><h3><b><span id="yearMonthDetails"></span></b></h3>  </td> </tr>
            <table class="table table-bordered">
                <thead>
                <th colspan="2">Addition</th>
                <th colspan="2">Deduction</th>
                </thead>
                <tbody id="paySlipBody">
                </tbody>
            </table>
        </div>
    </div>
</div>