<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/jobHistorySearch.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()
        ->appendFile($this->basePath('js/setup/recommend-approve/comBranchDeptDesignSearch.js'))
        ->appendFile($this->basePath('js/travel/recommender-approver/index.js'));
?>

<script>
    document.url = '<?= $this->url("recommenderApprover", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.employeeList =<?php echo json_encode($employeeList); ?>;
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\recommenderApprover')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="" ng-app="hris" ng-controller="groupAssignController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <select class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <select class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-4 col-sm-offset-4">
                    <label height="45"></label>
                    <button id="reset" class="btn default btn-sm pull-right">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button ng-click="view()" id="viewEmployees" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    
    <div class="">
        <div class="margin-top-20 scrollbar-vertical" id="loadingDiv">
            <table class="table table-striped table-bordered table-hover no-footer customTable">
                <thead>
                    <tr>
                        <th>
                            Employee Code
                        </th>
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Recommender Assigned
                        </th>
                        <th>
                            Approver Assigned
                        </th>
                        <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="employee in employeeList">
                        <td>
                            <span ng-bind="employee.EMPLOYEE_CODE"></span>
                        </td>
                        <td>
                            <span ng-bind="employee.FIRST_NAME"></span>
                            <span ng-bind="employee.MIDDLE_NAME"></span>
                            <span ng-bind="employee.LAST_NAME"></span>
                        </td>
                        <td>                       
                            <span ng-bind="employee.RECOMMENDER_NAME"></span>
                        </td>
                        <td>
                            <span ng-bind="employee.APPROVER_NAME"></span>
                        </td>

                        <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" ng-model="employee.checked" type="checkbox"
                                           ng-change="checkUnit(item.checked)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row margin-top-20" ng-show="assignShowHide">                   
        <div class="col-sm-3">
            <label for="designationId" style="width:100%">Recommender</label>
            <div class="row">
                <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                    <select name="recommendBy" required="required" id="recommenderId" class="form-control" ng-options="recomm.name for recomm in recommenderOptions track by recomm.id" ng-model="recommenderSelected">
                    </select>   
                </div>
                <div class="col-md-3 rlPadding recommenderWrap" style="padding:0px 0px !important;">
                    <a class="btn-edit" href="javascript::" ng-click="open(2)" style="height:22px; padding: 0px 7px !important;">
                        <i class="fa fa-search" style="height:17px;"></i>
                    </a>
                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                        <input class="" ng-model="recommenderAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="recommenderAssign"/>
                        <span></span>
                    </label>
                </div>  
            </div>
        </div>

        <div class="col-sm-3">
            <label for="designationId" style="width:100%">Approver</label>             
            <div class="row">
                <div class="col-md-9 parentDiv" style="padding-right: 0px;">                                
                    <select name="approvedBy" id="approverId" class="form-control" ng-options="approve.name for approve in approverOptions track by approve.id" ng-model="approverSelected">
                    </select>   
                </div>
                <div class="col-md-3 rlPadding approverWrap" style="padding:0px 0px !important;">
                    <a class="btn-edit" href="javascript::" ng-click="open(3)" style="height:22px; padding: 0px 7px !important;">
                        <i class="fa fa-search" style="height:17px;"></i>
                    </a>
                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                        <input class="" ng-model="approverAssign" ng-click="checkReportingHierarchy()" type="checkbox" id="approverAssign"/>
                        <span></span>
                    </label>
                </div>  
            </div>
        </div>      
        <div class="col-sm-2 " ng-show="showHideAssignBtn">
            <label height="45"></label>
            <button id="assignBtn" ng-click="assign()" class="btn btn-default form-control i-search mt-ladda-btn ladda-button mt-progress-demo">
                Assign
                <i class="fa fa-edit"></i>
            </button>

        </div>
    </div>
    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header"> 
        <button type="button" class="close" ng-click="cancel()" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span> 
        </button> 
        <h4 class="modal-title">Filter For <span ng-bind="role"></span> </h4> 
        </div>
        <div class="modal-body"> 
        <div class="row">
        <div class="col-sm-4">
            <label for="branchId">Company</label>
            <select class="form-control" name="company" id="recomCompanyId">
            </select>
        </div>
        <div class="col-sm-4">
            <label for="branchId">Branch</label>
            <select class="form-control" name="branchId" id="recomBranchId">
            </select>
        </div>
        <div class="col-sm-4">
            <label for="branchId">Department</label>
            <select class="form-control" name="department" id="recomDepartmentId">
            </select>
        </div>
        </div>
        <div class="row" style="margin-top:10px;">
        <div class="col-sm-4">
            <label for="branchId">Designation</label>
            <select class="form-control" name="designation" id="recomDesignationId">
            </select>
        </div>
        <div class="col-sm-4">
            <label for="branchId">Employee</label>
            <select class="form-control" name="employee" id="recomEmployeeId">
            </select>
        </div>
        </div>
        <div class="row">                   
        <div class="col-sm-3">
        <label height="45"></label>
        <button ng-click="filterForRole()" id="filterForRole" class="btn btn-default form-control i-search">
        Search
        <i class="fa fa-search"></i>
        </button>
        </div>

        </div>
        </div> 
    </script>
</div>
</div>
