<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/setup/recommend-approve/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'recommendApprove-form');

$employeeId = $form->get('employeeId');
$recommendBy = $form->get('recommendBy');
$approvedBy = $form->get('approvedBy');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('recommendapprove', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuRecommenderApprover"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\recommendapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="recommedApproverController">
    <div class="row margin-top-20">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>New Entry
                    </div>
                </div>
                <div class="portlet-body">
                    <?php
                    print $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
                        <?php print $this->formLabel($employeeId); ?>
                        <select name="employeeId" required="required" ng-model="employeeId" ng-change="change()" id="employeeId" class="form-control">
                            <option value="" disabled="" selected="" class="ng-binding">Please select</option>
                            <?php foreach($employees as $key => $value){ ?>
                                <option value="<?php echo $key?>"><?php echo $value?></option>
                            <?php } ?>
                        </select>
                        <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                    </div>

                    <div class="form-group">
                        <?php print $this->formLabel($recommendBy); ?>
                        <select name="recommendBy" required="required" id="recommendBy" class="form-control" ng-options="recomm.name for recomm in recommenderOptions track by recomm.id" ng-model="recommenderSelected">
                        </select>
                        <?php print $this->formElementErrors()->render($recommendBy, ['class' => 'help-block']); ?>
                    </div>

                    <div class="form-group">
                        <?php print $this->formLabel($approvedBy); ?>
                        <select name="approvedBy" id="approvedBy" class="form-control" ng-options="approve.name for approve in approverOptions track by approve.id" ng-model="approverSelected">
                        </select>
                        <?php print $this->formElementErrors()->render($approvedBy, ['class' => 'help-block']); ?>
                    </div>
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>