<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/spin.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/ladda.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()
    ->appendFile($this->basePath('js/setup/recommend-approve/override.js'));
?>

<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchLink = '<?php echo $this->url('recommendapprove', ["action" => "pullEmployeeForRecAppAssign"]); ?>';
    document.assignReportingHierarchyOverride = '<?php echo $this->url('recommendapprove', ["action" => "overrideAssign"]); ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\recommendapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Company</label>
                <select multiple class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Branch</label>
                <select multiple class="form-control" name="branchId" id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Department</label>
                <select multiple class="form-control" name="department" id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Designation</label>
                <select multiple class="form-control" name="designation" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Position</label>
                <select multiple class="form-control" name="position" id="positionId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Service Type</label>
                <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Service Event Type</label>
                <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee Type</label>
                <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee</label>
                <select multiple class="form-control" name="employee" id="employeeId">
                </select>
            </div>

            <div class="col-sm-2">
                <label>Type</label>
                <select class="form-control" name="type" id="type">
                    <option value="">----</option>
                    <option value="LV">LEAVE</option>
                    <option value="TV">TRAVEL</option>
                    <option value="TR">TRAINING</option>
                </select>
            </div>

            <div id="leaveTypeDiv" class="col-sm-2" style="display: none">
                <label for="leaveType">Leave type</label>
                <select class="form-control" name="leaveType[]" id="leaveType">
                    <?php foreach($leaveList as $key => $value ){?>
                        <option value='<?=$key?>'><?=$value?></option>
                    <?php  }?>
                </select>
            </div>

            <div class="col-sm-2">
                <label height="45"></label>
                <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button  id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div>

<div class="scroller" style="min-height:300px;height: 400px;" id="loadingDiv">
    <table id="employeeTable" class="table table-striped table-bordered table-hover no-footer ">
        <thead>
        <tr>
            <th>
                Code
            </th>
            <th>
                Employee
            </th>
            <th>
                Recommender
            </th>
            <th>
                Approver
            </th>
            <th>
                TYPE
            </th>
            <th>
                NAME
            </th>
            <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                <div class="th-inner ">
                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                        <input id="masterCheckElement" class="" type="checkbox"/>
                        <span></span>
                    </label>
                </div>
                <div class="fht-cell" style="width: 46px;"></div>
            </th>
        </tr>
        </thead>
    </table>
</div>

<div class="row margin-top-20" id = "assign">

    <div class='col-sm-2'>
        <div class="form-group">
            <label for="recomender">Recommender</label>
            <select class="form-control" name="recomender[]" id="recomender">
                <?php foreach($employeeList as $key => $value ){?>
                    <option value='<?=$key?>'><?=$value?></option>
                <?php  }?>
            </select>
        </div>
    </div>

    <div class='col-sm-2'>
        <div class="form-group">
            <label for="approver">Approver</label>
            <select class="form-control" name="approver[]" id="approver">
                <?php foreach($employeeList as $key => $value ){?>
                    <option value='<?=$key?>'><?=$value?></option>
                <?php  }?>
            </select>
        </div>
    </div>

    <div class="row margin-top-30">
        <div class="col-sm-4">
            <a id="assignBtn" class="btn btn-primary pull-right">Assign</a>
            </button>
        </div>
    </div>

</div>

