<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/SelfService/training-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'trainingRequest-form');

$trainingId = $form->get('trainingId');
$trainingId->setValueOptions($trainings);
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$duration = $form->get('duration');
$title = $form->get('title');
$trainingType = $form->get('trainingType');
$trainingType->setValueOptions($trainingTypes);
$description = $form->get('description');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('trainingRequest', ['action' => 'add']));


$form->prepare();
?>
<script>
//    document.holidayList =<?php
//json_encode($holidayObjList) 
//
?>;
    document.trainingList =<?= json_encode($trainingList) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($trainingId); ?>
                            <span class="required" aria-required="true">*</span>
                            <span> 
                                [ list by setup
                                <input type="hidden" name="companyList" value="0"/>
                                <input type="checkbox" name="companyList" checked="checked" value="1" id="companyList"/>
                                ]</span>
                            <?php print $this->formElement($trainingId); ?>
                            <?php print $this->formElement($title); ?>
                            <?php print $this->formElementErrors()->render($trainingId, ['class' => 'help-block']); ?>
                            <?php print $this->formElementErrors()->render($title, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($trainingType); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($trainingType); ?>
                            <?php print $this->formElementErrors()->render($trainingType, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div
                                    class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($startDate) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($startDate) ?>
                                </div>
                                <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>        

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div
                                    class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($endDate) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($endDate) ?>
                                    <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                                </div>
                                <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>        


                    </div>
                    <div class="col-sm-4">
                        <div
                            class="form-group required <?= empty($duration->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($duration); ?>
                                <?php print $this->formElement($duration); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($description); ?>
                            <?php print $this->formElement($description); ?>
                            <?php print $this->formElementErrors()->render($description, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
