<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/SelfService/training-request/datepick.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'trainingRequest-form');

$trainingId = $form->get('trainingId');
$trainingId->setValueOptions($trainings);
$trainingId->setAttributes(["disabled" => "disabled"]);
$startDate = $form->get('startDate');
$startDate->setAttributes(["disabled" => "disabled"]);
$endDate = $form->get('endDate');
$endDate->setAttributes(["disabled" => "disabled"]);
$duration = $form->get('duration');
$duration->setAttributes(["disabled" => "disabled"]);
$title = $form->get('title');
$title->setAttributes(["disabled" => "disabled"]);
$trainingType = $form->get('trainingType');
$trainingType->setValueOptions($trainingTypes);
$trainingType->setAttributes(["disabled" => "disabled"]);
$description = $form->get('description');
$description->setAttributes(["disabled" => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled" => "disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('trainingRequest', ['action' => 'add']));


$form->prepare();
?>
<script>
    document.trainingList =<?= json_encode($trainingList) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Training Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="border-bottom">

                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDate; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>                               
                                </table>
                            </div>
                            <div class="col-md-4">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == 'RQ') {
                                                echo "Pending";
                                            } else if ($status == 'RC') {
                                                echo "Recommended";
                                            } else if ($status == 'AP') {
                                                echo "Approved";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($trainingId); ?>
                                <span class="required" aria-required="true">*</span>
                                <span> 
                                    [ list by setup
                                    <input type="hidden" name="companyList" value="0"/>
                                    <?php
                                    if ($trainingIdSelected != 0) {
                                        $checked = "checked";
                                    } else {
                                        $checked = "";
                                    }
                                    ?>
                                    <input type="checkbox" name="companyList" <?php echo $checked; ?> value="1" id="companyList" disabled="disabled"/>
                                    ]</span>
                                <?php
                                if ($trainingIdSelected != 0) {
                                    print $this->formElement($trainingId);
                                } else if ($trainingIdSelected == 0) {
                                    print $this->formElement($title);
                                }
                                ?>
                                <?php print $this->formElementErrors()->render($trainingId, ['class' => 'help-block']); ?>
                                <?php print $this->formElementErrors()->render($title, ['class' => 'help-block']); ?>
                            </div>               
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($trainingType); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($trainingType); ?>
                                <?php print $this->formElementErrors()->render($trainingType, ['class' => 'help-block']); ?>
                            </div> 
                        </div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($startDate) ?>
                                        <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($startDate) ?>
                                    </div>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliStartDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>        

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($endDate) ?>
                                        <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($endDate) ?>
                                        <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                                    </div>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliEndDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>        

                        </div>
                        <div class="col-sm-4">
                            <div
                                class="form-group required <?= empty($duration->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($duration); ?>
                                    <?php print $this->formElement($duration); ?>
                                <span id="errorMsg" style="font-size:11px; color:red;"></span>
                            </div>
                            <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block error']); ?>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($description); ?>
                                <?php print $this->formElement($description); ?>
                                <?php print $this->formElementErrors()->render($description, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Recommender]</label>
                    <?php print $this->formElement($recommendedRemarks); ?>
                </div>
                <div
                    class="form-group margin-top-10 required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Approver]</label>
                    <?php print $this->formElement($approvedRemarks); ?>
                </div>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
