<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/service-question/emp-service-question/serviceQuestionList.js'));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\empServiceQuestion')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20" ng-app="hris" ng-controller="serviceQuestionList"> 
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <form name="empServiceQuestionForm" action="<?= $this->url('empServiceQuestion',['action'=>"add"]) ?>" method="post">
                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="employeeId">Employee</label>
                                <span class="required" aria-required="true">*</span>
                                <select name="employeeId" id="employeeId" class="form-control">
                                    <?php foreach($employees as $key=>$value){ ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="serviceEventTypeId">Service Event Type</label>
                                <span class="required" aria-required="true">*</span>
                                <select required="required" name="serviceEventTypeId" id="serviceEventTypeId" class="form-control" ng-model="serviceEventType" ng-change="serviceEventTypeChange(serviceEventType)">
                                    <option value="" disabled="" selected="" class="ng-binding">Please select</option>                       
                                    <?php foreach($serviceEventTypes as $key=>$value){ ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="questionDate">Date</label>
                                <span class="required" aria-required="true">*</span>
                                <input type="text" name="questionDate" class="form-control"/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12" ng-repeat="serviceQuestion in serviceQuestionList">
                            <div class="form-group" ng-style="serviceQuestion.subQuestion === true && {'margin-bottom': '0px'}">
                                <label>{{serviceQuestion.sn}}. <span ng-bind="serviceQuestion.questionEdesc"></span></label>
                                <input ng-if="serviceQuestion.subQuestion==true" type="hidden" name="serviceQuestionAnswer[{{serviceQuestion.qaId}}]" value=""/>
                                <input ng-if="serviceQuestion.subQuestion==false" type="text" name="serviceQuestionAnswer[{{serviceQuestion.qaId}}]" value="" class="form-control"/>
                            </div>
                            <div ng-if="serviceQuestion.subQuestion==true" ng-repeat="subQuestion in serviceQuestion.subQuestionList">
                                <div class="form-group">
                                    <label>{{subQuestion.sn}}. <span ng-bind="subQuestion.questionEdesc"></span></label>
                                    <input ng-if="subQuestion.subQuestion==true" type="hidden" name="serviceQuestionAnswer[{{subQuestion.qaId}}]" value=""/>
                                    <input ng-if="subQuestion.subQuestion==false" type="text" name="serviceQuestionAnswer[{{subQuestion.qaId}}]" value="" class="form-control"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-success" value="SUBMIT">
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
