/*Late In */
SELECT COUNT (*)
  FROM (SELECT A.EMPLOYEE_ID,
               S.START_TIME,
               A.IN_TIME,
               ( ( (TRUNC (S.START_TIME) - S.START_TIME))
                - (TRUNC (A.IN_TIME) - A.IN_TIME))
                  LATE_HRS,
               S.LATE_IN - TRUNC (S.LATE_IN) LATE_GRACE
          FROM HRIS_ATTENDANCE_DETAIL A, HRIS_SHIFTS S
         WHERE     1 = 1
               AND A.EMPLOYEE_ID = :V_EMPLOYEE_ID
               AND A.SHIFT_ID = S.SHIFT_ID
               AND A.IN_TIME BETWEEN :V_FORM_DATE AND :V_TO_DATE
               ) ATTEN
 WHERE ATTEN.LATE_HRS > LATE_GRACE
 
 
 /* Early Out */
 SELECT COUNT (*)
  FROM (SELECT A.EMPLOYEE_ID,
               S.END_TIME,
               A.OUT_TIME,
                 ((TRUNC (A.OUT_TIME) - A.OUT_TIME)- ( (TRUNC (S.END_TIME) - S.END_TIME)))
                  EARLY_HRS,
               S.EARLY_OUT - TRUNC (S.EARLY_OUT) EARLY_GRACE
          FROM HRIS_ATTENDANCE_DETAIL A, HRIS_SHIFTS S
         WHERE     1 = 1
               AND A.EMPLOYEE_ID = :V_EMPLOYEE_ID
               AND A.SHIFT_ID = S.SHIFT_ID
               AND A.IN_TIME BETWEEN :V_FORM_DATE AND :V_TO_DATE
               ) ATTEN
 WHERE ATTEN.EARLY_HRS > EARLY_GRACE
 
 
 
 /* Missed Punch*/
 
 SELECT COUNT(*) MISMATCH FROM(
  SELECT COUNT (*), ATTENDANCE_DT
    FROM HRIS_ATTENDANCE
   WHERE EMPLOYEE_ID = :V_EMPLOYEE_ID
   AND  ATTENDANCE_DT BETWEEN :V_FORM_DATE AND :V_TO_DATE
   HAVING MOD(COUNT(*),2) <> 0
GROUP BY ATTENDANCE_DT)
 
 
/* PRESENT DAY */ 
SELECT COUNT (*)
  FROM HRIS_ATTENDANCE_DETAIL
 WHERE    IN_TIME IS NOT NULL
       OR LEAVE_ID IS NOT NULL
       OR HOLIDAY_ID IS NOT NULL
       OR TRAINING_ID IS NOT NULL
       OR     TRAVEL_ID IS NOT NULL
          AND DAYOFF_FLAG = 'N'
          AND ATTENDANCE_DT BETWEEN :V_FORM_DATE AND :V_TO_DATE
                
 
/* ABSENT DAY */  
SELECT COUNT (*)
  FROM HRIS_ATTENDANCE_DETAIL
 WHERE     IN_TIME IS NULL
       AND LEAVE_ID IS NULL
       AND HOLIDAY_ID IS NULL
       AND TRAINING_ID IS NULL
       AND TRAVEL_ID IS NULL
       AND DAYOFF_FLAG = 'N'
       AND ATTENDANCE_DT BETWEEN :V_FORM_DATE AND :V_TO_DATE
	   

/* LEAVE COUNT */
SELECT COUNT (*)
  FROM HRIS_ATTENDANCE_DETAIL
 WHERE     LEAVE_ID IS NOT NULL
       AND DAYOFF_FLAG = 'N'
       AND ATTENDANCE_DT BETWEEN :V_FORM_DATE AND :V_TO_DATE
       
/*WORK ON HOLIDAY COUNT */
	   SELECT COUNT (*)
  FROM HRIS_ATTENDANCE_DETAIL
 WHERE    HOLIDAY_ID IS NOT NULL
         AND IN_TIME IS NOT NULL
         AND OUT_TIME IS NOT NULL
       AND DAYOFF_FLAG = 'N'
       AND ATTENDANCE_DT BETWEEN :V_FORM_DATE AND :V_TO_DATE	   
	   
/* ON TOUR/TRAVEL COUNT */
SELECT COUNT (*)
  FROM HRIS_ATTENDANCE_DETAIL
 WHERE     TRAVEL_ID IS NOT NULL
       AND DAYOFF_FLAG = 'N'
       AND ATTENDANCE_DT BETWEEN :V_FORM_DATE AND :V_TO_DATE	   
	   
/* 
 