<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/fullcalendar/fullcalendar.min.css'))
    ->appendStylesheet($this->basePath('css/dashboard.employee.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-daterangepicker/moment.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/fullcalendar/fullcalendar.min.js'))
    ->appendFile($this->basePath('assets/global/scripts/metronic.js'))
    ->appendFile($this->basePath('assets/admin/pages/scripts/index.js'))
    ->appendFile($this->basePath('js/dashboard/employee-dashboard.js'));
?>

<div class="employeedashboard">
    <div class="emplyoee-dashboard clearfix">
        <div class="employe-descbox">
            <div class="col-sm-1 col-md-1 profile_pic">
                <img src="<?php print $this->basePath("img/nobody_m.original.jpg"); ?>">
            </div>
            <div class="col-sm-3 col-md-3 employee-details">
                <?php
                $email = trim($employeeDetail['EMAIL_OFFICIAL']) ? trim($employeeDetail['EMAIL_OFFICIAL']) : trim($employeeDetail['EMAIL_PERSONAL']);
                $service[0] = $employeeDetail['SERVICE_YEARS'] ? ((1 == $employeeDetail['SERVICE_YEARS']) ? "1 Year" : $employeeDetail['SERVICE_YEARS'] . " Years") : "";
                $service[1] = $employeeDetail['SERVICE_MONTHS'] ? ((1 == $employeeDetail['SERVICE_MONTHS']) ? "1 Month" : $employeeDetail['SERVICE_MONTHS'] . " Months") : "";
                $service[2] = $employeeDetail['SERVICE_DAYS'] ? ((1 == $employeeDetail['SERVICE_DAYS']) ? "1 Day" : $employeeDetail['SERVICE_DAYS'] . " Days") : "";
                $serviceDays = trim(implode(" ", $service));
                ?>
                <h4 class="font-weight-bold"><?php print $employeeDetail['FULL_NAME']; ?></h4>
                <?php if($email) : ?>
                <span><?php print $email; ?></span><br>
                <?php endif; ?>
                <span><?php print trim($employeeDetail['DESIGNATION_TITLE']); ?></span><br>
                <span>At work for : <?php print $serviceDays ? $serviceDays : 0; ?></span><br>
            </div>
            <div class="col-md-5">
                <div class="row detailsbox">
                    <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                        <div class="employee_details-box hexagon-bg1">
                            <span><?php print $employeeDetail['PRESENT_DAY']; ?></span>
                            <div class="face1"></div>
                            <div class="face2"></div>
                            <div class="headtitle">Present</div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                        <div class="employee_details-box hexagon-bg2">
                            <span><?php print $employeeDetail['LEAVE']; ?></span>
                            <div class="face1"></div>
                            <div class="face2"></div>
                            <div class="headtitle">On Leave</div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                        <div class="employee_details-box hexagon-bg3">
                            <span><?php print $employeeDetail['TRAINING']; ?></span>
                            <div class="face1"></div>
                            <div class="face2"></div>
                            <div class="headtitle">Training</div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                        <div class="employee_details-box hexagon-bg4">
                            <span><?php print $employeeDetail['TOUR']; ?></span>
                            <div class="face1"></div>
                            <div class="face2"></div>
                            <div class="headtitle">On Tour</div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                        <div class="employee_details-box hexagon-bg5">
                            <span><?php print $employeeDetail['WOH']; ?></span>
                            <div class="face1"></div>
                            <div class="face2"></div>
                            <div class="headtitle">WOH</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
                <div class="col-hris pull-right">
                    <ul>
                        <li class="col-md-4">
                            <div class="hris efficiency efficiency-bg1">
                                <span><?php print $employeeDetail['LATE_IN']; ?></span>
                                <div>Late In</div>
                            </div>
                        </li>
                        <li class="col-md-4">
                            <div class="hris efficiency efficiency-bg2">
                                <span><?php print $employeeDetail['EARLY_OUT']; ?></span>
                                <div>Early Out</div>
                            </div>
                        </li>
                        <li class="col-md-4">
                            <div class="hris efficiency efficiency-bg3">
                                <span><?php print $employeeDetail['MISSED_PUNCH']; ?></span>
                                <div>Missed Punch</div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?php /*
            <div class="employeestatusbox clearfix">
                <div class="row">
                    <div class="col-sm-3 col-md-3">
                        <h4 class="font-weight-bold">Employee Status</h4>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="employee-status-details">
                            <ul>
                                <li>
                                    <span>0.5/26</span>
                                    Attendence
                                </li>
                                <li>
                                    <span>1/10</span>
                                    Leave
                                </li>
                                <li>
                                    <span>0</span>
                                    Awards
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3 col-md-3">
                        <div id="dashboard-report-range1" class="pull-right tooltips btn btn-sm btn-custom-color active" data-container="body" data-placement="bottom" data-original-title="Change dashboard date range">
                            <i class="fa fa-calendar"></i>&nbsp;<span class="thin uppercase visible-lg-inline-block"><?php print date('d M Y') ?></span>&nbsp; <i class="fa fa-angle-down"></i>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row detailsbox">
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg1">
                                    <span><?php print $employeeDetail['PRESENT_DAY']; ?></span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle">Present</div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg2">
                                    <span><?php print $employeeDetail['LEAVE']; ?></span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle">On Leave</div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg3">
                                    <span><?php print $employeeDetail['TRAINING']; ?></span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle">Training</div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg4">
                                    <span><?php print $employeeDetail['TOUR']; ?></span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle">On Tour</div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg5">
                                    <span><?php print $employeeDetail['WOH']; ?></span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle">WOH</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            */ ?>

            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light calendar ">
                        <div class="portlet-title ">
                            <div class="caption">
                                <i class="fa fa-calendar font-green-sharp"></i>
                                <span class="caption-subject font-green-sharp bold uppercase">Calendar</span>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="calendar"></div>
                            <div class="calendar-colorbox">
                                <ul>
                                    <li>
                                        <div class="color-box colorbox-color1">
                                        </div>
                                        <span>Holiday</span>
                                    </li>
                                    <li>
                                        <div class="color-box colorbox-color2">
                                        </div>
                                        <span>Important notice</span>
                                    </li>
                                    <li>
                                        <div class="color-box colorbox-color3">
                                        </div>
                                        <span>Meeting</span>
                                    </li>
                                    <li>
                                        <div class="color-box colorbox-color4">
                                        </div>
                                        <span>Message</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="profile-content">
                        <div class="row">
                            <div class="col-md-12 noticeboard">
                                <div class="portlet-body">
                                    <div class="portlet light">
                                        <div class="portlet-title tabbable-line">
                                            <div class="caption caption-md">
                                                <i class="icon-globe theme-font hide"></i>
                                                <span class="caption-subject bold uppercase">Notice Board</span>
                                            </div>
                                        </div>
                                        <div class="noticeboard-list row">
                                            <ul>
                                                <?php foreach($employeeNotice as $notice) : ?>
                                                    <li style="width:100%;">
                                                        <div class="calendardate-box col-sm-2 col-md-2">
                                                            <span><?php print $notice['NEWS_DAY']; ?></span><br>
                                                            <?php print $notice['NEWS_MONTH_YEAR']; ?>
                                                        </div>
                                                        <div class="notice-details col-sm-10 col-md-10">
                                                            <h5 class="title-color caption-subject  bold"><?php print $notice['NEWS_TITLE']; ?></h5>
                                                            <p><?php print $notice['NEWS_EDESC']; ?></p>
                                                        </div>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                        <!--END TABS-->
                                    </div>
                                </div>
                            </div>
                            <!-- END PORTLET -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row widget-row">
                <div class="col-sm-6 col-md-6">
                    <!-- BEGIN WIDGET THUMB -->
                    <div class="wigetbox wigetbox-colorone clearfix widget-thumb widget-bg-color-lightgreen margin-bottom-20 bordered green-haze">
                        <div class="widget-thumb-wrap widget-thumb-wrap-bgone">
                            <h4 class="widget-thumb-heading">Average Office Hrs</h4>
                            <div class="widget-thumb-body">
                                <?php
                                $avgOfficeHourParts[0] = $employeeDetail['AVG_HOURS'] ? ((1 == $employeeDetail['AVG_HOURS']) ? "1 hr" : $employeeDetail['AVG_HOURS'] . " hrs") : "";
                                $avgOfficeHourParts[1] = $employeeDetail['AVG_MINUTES'] ? ((1 == $employeeDetail['AVG_MINUTES']) ? "1 min" : $employeeDetail['AVG_MINUTES'] . " mins") : "";
                                $avgOfficeHours = trim(implode(" ", $avgOfficeHourParts));
                                ?>
                                <span class="widget-thumb-body-stat" data-counter="counterup"><?php print $avgOfficeHours ? $avgOfficeHours : 0; ?></span>
                            </div>
                        </div>
                        <div>
                            <div class="icons">
                                <i class="widget-thumb-icon  fa fa-user colorone"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- BEGIN WIDGET THUMB -->
                <div class="col-sm-6 col-md-6">
                    <div class="wigetbox wigetbox-colortwo clearfix widget-thumb widget-bg-color-lightgreen margin-bottom-20 bordered green-haze">
                        <div class="widget-thumb-wrap widget-thumb-wrap-bgtwo">
                            <h4 class="widget-thumb-heading">Average Timesheet Hrs</h4>
                            <div class="widget-thumb-body">
                                <span class="widget-thumb-body-stat" data-counter="counterup">7,644</span>
                            </div>
                        </div>
                        <div>
                            <div class="icons">
                                <i class="widget-thumb-icon fa fa-user-plus colortwo"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6">
                    <!-- BEGIN WIDGET THUMB -->
                    <div class="wigetbox wigetbox-colorthree clearfix widget-thumb widget-bg-color-lightgreen margin-bottom-20 bordered green-haze">
                        <div class="widget-thumb-wrap widget-thumb-wrap-bgthree">
                            <h4 class="widget-thumb-heading">Total OT Hrs</h4>
                            <div class="widget-thumb-body">
                                <span class="widget-thumb-body-stat" data-counter="counterup">7,644</span>
                            </div>
                        </div>
                        <div>
                            <div class="icons">
                                <i class="widget-thumb-icon fa fa fa-user-times colorthree"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <!-- BEGIN WIDGET THUMB -->
                    <div class="wigetbox wigetbox-colorfour clearfix widget-thumb margin-bottom-20 bordered green-haze">
                        <div class="widget-thumb-wrap widget-thumb-wrap-bgfour">
                            <h4 class="widget-thumb-heading">Work on Holiday</h4>
                            <div class="widget-thumb-body">
                                <ul>
                                    <li class="line">
                                        <span class="widget-thumb-body-stat" data-counter="counterup"><?php print $employeeDetail['CUR_MONTH_WOH']; ?></span>
                                        This Month
                                    </li>
                                    <li>
                                        <span class="widget-thumb-body-stat" data-counter="counterup"><?php print $employeeDetail['PREV_MONTH_WOH']; ?></span>
                                        Last Month
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div>
                            <div class="icons">
                                <i class="widget-thumb-icon  fa fa-users colorfour"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="datepickeform">
                        <div class="form-body">
                            <h3 class="form-section">Todo</h3>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Due for today 28 march 2017 </label>
                                        <input id="firstName" class="form-control" placeholder="Chee Kin" type="text" />
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label">Evalution</label>
                                        <input id="datepicker" class="form-control" placeholder="Chee Kin" type="text" />
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input id="firstName" class="form-control" placeholder="Chee Kin" type="text" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END CONTENT -->
                </div>

                <div class="col-md-12 holidays">
                    <!-- BEGIN PORTLET -->
                    <div class="portlet light">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject bold uppercase">Upcoming Holidays</span>
                            </div>
                        </div>

                        <div class="portlet-body">
                            <div class="row">
                                <div class="upcomingholidays">
                                    <div class="upcomingholidays-loading" style="display:none;height:100%;width:100%;position:absolute;top:0;left:0;"></div>
                                    <ul class="feeds" style="visibility:visible;">
                                        <?php foreach($upcomingHolidays as $holiday) : ?>
                                        <li class="col1bg">
                                            <div class="col1">
                                                <div class="cont">
                                                    <div class="cont-col2">
                                                        <div class="desc">
                                                            <span class="label label-sm "><?php print $holiday['HOLIDAY_ENAME']; ?></span>
                                                            <span class="label label-sm "><?php print $holiday['DAYS_REMAINING'] . "Day(s) Remaining"; ?></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col2">
                                                <div class="date"><?php printf("%s %s", $holiday['WEEK_DAY'], $holiday['START_DATE']); ?></div>
                                            </div>
                                        </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="birthday-wishes">
                    <div class="col-md-12 col-sm-12">
                        <!-- BEGIN PORTLET-->
                        <div class="portlet light ">
                            <div class="portlet-title tabbable-line tabline">
                                <div class="caption">
                                    <i class="fa fa-birthday-cake font-green-sharp"></i>
                                    <span class="caption-subject font-green-sharp ">Birthday Wishes</span>
                                </div>
                                <ul class="nav nav-tabs">
                                    <li class="ln-birthday active">
                                        <a id="ln-birthday-today" class="ln-nav-tab-birthday" href="javascript:void(0);" data-toggle="tab" aria-expanded="true">Today</a>
                                    </li>
                                    <li class="ln-birthday">
                                        <a id="ln-birthday-upcoming" class="ln-nav-tab-birthday" href="javascript:void(0);" data-toggle="tab" aria-expanded="false">Upcoming</a>
                                    </li>
                                </ul>
                            </div>

                            <div class="row">
                                <div class="tab-content birday-person-list">
                                    <div class="tab-pane active" id="tab-birthday-today">
                                        <?php for($i=0; $i<5; $i++) : ?>
                                            <div class="person-list clearfix">
                                                <div class="col-md-3 col-sm-3">
                                                    <div class="person-pic">
                                                        <img src="<?php print $this->basePath('img/nobody_m.original.jpg'); ?>" alt="person picture">
                                                    </div>
                                                </div>
                                                <div class="col-xs-9 col-md-9 col-sm-9">
                                                    <div class="person-details">
                                                        <h4>Rajan Shrestha</h4>
                                                        <span>Web Designer</span>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endfor; ?>
                                    </div>
                                    <div class="tab-pane" id="tab-birthday-upcoming" style="display:none;">
                                        <?php for($i=0; $i<3; $i++) : ?>
                                            <div class="person-list clearfix">
                                                <div class="col-md-3 col-sm-3">
                                                    <div class="person-pic">
                                                        <img src="<?php print $this->basePath('img/nobody_m.original.jpg'); ?>" alt="person picture">
                                                    </div>
                                                </div>
                                                <div class="col-xs-9 col-md-9 col-sm-9">
                                                    <div class="person-details">
                                                        <h4>Rajan Shrestha</h4>
                                                        <span>Web Designer</span>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endfor; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="clearfix"></div>

</div>