<script>
    document.menu =<?php
$menu = ["id" => "menuDashBoard", "subMenu" => ["id" => "subMenuDashBoard"]];
echo json_encode($menu);
?>;
</script>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<?php $counter = 0; ?>
<?php foreach ($dashboardItems as $dashboardItem) : ?>
    <?php if ($counter % 2 == 0) { ?>
        <div class="row">
        <?php } ?>
        <?php
        print $this->partial($dashboardItem['path'], $dashboardItem['data']);
        ?>
        <?php if ($counter % 2 == 1 || ($counter + 1 == sizeof($dashboardItems))) { ?>
        </div>
    <?php } ?>
    <?php $counter++; ?>
<?php endforeach; ?>





