<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advance-approve')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'));
$this->headScript()->appendFile($this->basePath('js/advance/advance-approve/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'advance-form');

$advanceId = $form->get('advanceId');
$advanceId->setValueOptions($advances);
$advanceId->setAttributes(["disabled" => "disabled"]);

$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);

$dateOfadvance = $form->get('dateOfadvance');
$dateOfadvance->setAttributes(["disabled" => "disabled"]);

$reason = $form->get('reason');
$reason->setAttributes(["disabled" => "disabled"]);

$deductionRate = $form->get('deductionRate');
$deductionRate->setAttributes(["disabled" => "disabled"]);

$deductionIn = $form->get('deductionIn');
$deductionIn->setAttributes(["disabled" => "disabled"]);

$recommendedRemarks = $form->get('recommendedRemarks');
$approvedRemarks = $form->get('approvedRemarks');

$showBtns = false;
if ($role == 2 && $detail['STATUS'] == "RQ") {
    $recommendedRemarks->setAttributes(['required' => 'true']);
    $approvedRemarks->setAttributes(['disabled' => 'disabled']);
    $showBtns = true;
} else if (($role == 3 && $detail['STATUS'] == "RC") || ($role == 4 && in_array($detail['STATUS'], ['RQ', 'RC']))) {
    $approvedRemarks->setAttributes(['required' => 'true']);
    $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
    $showBtns = true;
} else {
    $recommendedRemarks->setAttributes(['disabled' => 'disabled']);
    $approvedRemarks->setAttributes(['disabled' => 'disabled']);
}
$form->prepare();
?>
<script>
    document.advanceRequestData =<?php echo json_encode($detail); ?>;
</script>

<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Advance Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>

            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                           Employee Name
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <strong><?php echo $employeeName; ?></strong>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            echo $statusDetail;
                                            ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDate; ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>                               
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" id="form-employeeId" value="<?php echo $employeeId; ?>"/>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($advanceId); ?>
                                <?php print $this->formElement($advanceId); ?>
                                <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                            </div>               
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($requestedAmount); ?>
                                <?php print $this->formElement($requestedAmount); ?>
                                <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($dateOfadvance); ?>
                                        <?php print $this->formElement($dateOfadvance); ?>
                                        <?php print $this->formElementErrors()->render($dateOfadvance, ['class' => 'help-block']); ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliDate" id="nepalidateOfadvance"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div> 

                        </div>

                    </div>

                    <div class=" row">
                         <?php
                        if ($detail['DEDUCTION_TYPE'] == 'S') {
                            ?>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($deductionRate); ?>
                                <?php print $this->formElement($deductionRate); ?>
                                <?php print $this->formElementErrors()->render($deductionRate, ['class' => 'help-block']); ?>
                                <span ><?php
                                    $monthlyDeductAmt = ($detail['DEDUCTION_RATE'] / 100) * $detail['SALARY'];
                                    echo 'RS.' . $monthlyDeductAmt;
                                    ?></span>
                            </div>
                        </div>
                         <?php
                        }
                        ?>
                        
                         <?php
                        if ($detail['DEDUCTION_TYPE'] == 'M') {
                            ?>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($deductionIn); ?>
                                <?php print $this->formElement($deductionIn); ?>
                                <?php print $this->formElementErrors()->render($deductionIn, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                         <?php
                        }
                        ?>
                        

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($reason); ?>
                                <?php print $this->formElement($reason); ?>
                                <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($recommendedRemarks); ?>
                                <?php print $this->formElement($recommendedRemarks); ?>
                                <?php print $this->formElementErrors()->render($recommendedRemarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($approvedRemarks); ?>
                                <?php print $this->formElement($approvedRemarks); ?>
                                <?php print $this->formElementErrors()->render($approvedRemarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <?php if ($showBtns): ?>
                                <input type="submit" name="submit" class="btn btn-info pull-right" id="approve" value="Approve">
                                <input type="submit" name="submit" class="btn btn-danger pull-left" value="Reject">
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php print $this->form()->closeTag(); ?>
            </div>

        </div>
    </div>
</div>
