<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaverequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/add.js'));
?>


<?php
$form->setAttribute('role', 'form');

$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$noOfDays = $form->get('noOfDays');
$halfDay = $form->get('halfDay');
$remarks = $form->get('remarks');

$gracePeriod = $form->get('gracePeriod');
$submit = $form->get('submit');
$submit->setAttribute('value', 'Apply Leave');
$submit->setAttribute('id', 'request');

$form->setAttribute('action', $this->url('leaverequest', ['action' => 'add']));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.wsPullLeaveDetailWidEmployeeId = '<?= $this->url("leaveapply", ["action" => "pullLeaveDetailWidEmployeeId"]) ?>';
    document.wsPullLeaveDetail = '<?= $this->url("leaveapply", ["action" => "pullLeaveDetail"]) ?>';
    document.wsFetchAvailableDays = '<?= $this->url("leaveapply", ["action" => "fetchAvailableDays"]) ?>';
</script>

<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    Apply For Leave
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group">
                    <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="leaveId">Leave Type</label>
                            <span class="required" aria-required="true">*</span>
                            <select name="leaveId" required="required" id="leaveId" class="form-control">
                                <option value="" disabled="" selected="" >Please select</option>
                                <?php foreach ($leave as $key => $value) { ?>
                                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group disabled">
                            <label for="leaveId">Available Days</label>
                            <input type="text" READONLY name="availableDays"  required="required" id="availableDays"  class="form-control"  value="">
                            <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <div class=" row">

                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($startDate) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($startDate) ?>
                                </div>
                                <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                           class="form-control" value="">
                                </div>
                            </div>     
                        </div>

                    </div>

                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div
                                    class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($endDate) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($endDate) ?>
                                    <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                                </div>
                                <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                           class="form-control" value="">
                                </div>
                            </div>     
                        </div>

                    </div>
                    <div class="col-sm-4">
                        <div
                            class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($noOfDays); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($noOfDays); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4" id="substituteEmployeeCol">
                        <label for="substituteEmployee">Substitute Employee </label>
                        <span class="required" aria-required="true">*</span>
                        <select required class="form-control" name="leaveSubstitute" id="leaveSubstitute" style="cursor: pointer;">
                            <option style="cursor: pointer;" value="">---</option>
                            <?php foreach ($employeeList as $key => $value) { ?>
                                <option style="cursor: pointer;" value="<?php echo $key; ?>"><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class=" col-sm-4 " id="gracePeriodCol">
                        <div class="form-group" >
                            <?php print $this->formLabel($gracePeriod); ?>
                            <?php print $this->formElement($gracePeriod); ?>
                        </div>

                        <?php print $this->formElementErrors()->render($gracePeriod, ['class' => 'help-block error']); ?>
                    </div>
                    <div class=" col-sm-4 " id="halfDayCol">
                        <div class="form-group" >
                            <?php print $this->formLabel($halfDay); ?>
                            <?php print $this->formElement($halfDay); ?>
                        </div>

                        <?php print $this->formElementErrors()->render($halfDay, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group padding-0" id="remarks">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                    </div>

                </div>
                <?php print $this->formSubmit($submit); ?>

            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>