<?php
$this->headScript()->appendFile($this->basePath('js/appraisal/question/add.js'));
//print_r($form); die();
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'appraisalQuestion-form');

$questionCode = $form->get('questionCode');
$questionEdesc = $form->get('questionEdesc');
$questionNdesc = $form->get('questionNdesc');
$orderNo = $form->get('orderNo');
$minValue = $form->get('minValue');
$maxValue = $form->get('maxValue');
$remarks = $form->get('remarks');
$answerType = $form->get('answerType');
$answerType->setValueOptions($answerTypeList);
$headingId = $form->get('headingId');
$headingId->setValueOptions($headings);
$appraiseeFlag = $form->get('appraiseeFlag');
$appraiserFlag = $form->get('appraiserFlag');
$reviewerFlag = $form -> get('reviewerFlag');
$appraiseeRating = $form->get('appraiseeRating');
$appraiserRating = $form->get('appraiserRating');
$reviewerRating = $form->get('reviewerRating');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('question', ['action' => 'edit','id'=>$id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Question')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php print $this->formLabel($questionCode); ?>
                    <?php print $this->formElement($questionCode); ?>
                    <?php print $this->formElementErrors()->render($questionCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($questionEdesc); ?>
                    <?php print $this->formElement($questionEdesc); ?>
                    <?php print $this->formElementErrors()->render($questionEdesc, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($questionNdesc); ?>
                    <?php print $this->formElement($questionNdesc); ?>
                    <?php print $this->formElementErrors()->render($questionNdesc, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($answerType); ?>
                    <?php print $this->formElement($answerType); ?>
                    <?php print $this->formElementErrors()->render($answerType, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($headingId); ?>
                    <?php print $this->formElement($headingId); ?>
                    <?php print $this->formElementErrors()->render($headingId, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($orderNo); ?>
                    <?php print $this->formElement($orderNo); ?>
                    <?php print $this->formElementErrors()->render($orderNo, ['class' => 'help-block']); ?>
                </div>
                
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraiseeFlag); ?>
                            <div class="md-radio-inline">
                                <?php  $customRenderer($appraiseeFlag); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($appraiseeFlag, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraiserFlag); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($appraiserFlag); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($appraiserFlag, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php print $this->formLabel($reviewerFlag); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($reviewerFlag); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($reviewerFlag, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraiseeRating); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($appraiseeRating); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($appraiseeRating, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraiserRating); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($appraiserRating); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($appraiserRating, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php print $this->formLabel($reviewerRating); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($reviewerRating); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($reviewerRating, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <?php print $this->formLabel($minValue); ?>
                            <?php print $this->formElement($minValue); ?>
                            <?php print $this->formElementErrors()->render($minValue, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <?php print $this->formLabel($maxValue); ?>
                            <?php print $this->formElement($maxValue); ?>
                            <?php print $this->formElementErrors()->render($maxValue, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>