
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('js/customer/contract-employees/index.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.viewLink = '<?= $this->url("contract-employees", ["action" => "view"]); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.customerList =<?php echo json_encode($customerList); ?>;
    document.pullContractList = '<?= $this->url("contract-employees", ["action" => "fetchAllContractCustomerWise"]); ?>';
    document.pullContractDetails = '<?= $this->url("contract-employees", ["action" => "fetchContractDetails"]); ?>';
    document.pullDesignationWiseEmpAssign = '<?= $this->url("contract-employees", ["action" => "fetchContractDesginationWiseEmployeeAssign"]); ?>';
    document.employeeList =<?= json_encode($employeeList); ?>;
    document.locationList =<?= json_encode($locationList) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\customer-contract')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
        </div>

        <div class="row margin-top-20">

            <div class="col-md-3">
                <select id="CustomerSelect"></select>
            </div>
            <div class="col-md-3">
                <select id="ContractSelect"></select>
            </div>
            <div class="col-md-3">
                <input type="button" id="viewBtn" class="btn btn-primary" value="view">
            </div>

        </div>
        <form method="post" action="<?= $this->url("contract-employees", ["action" => "employeeAssign"]) ?>">
            
            <input id='customerId' type="hidden" name='customerId'>
            <input id='contractId' type="hidden" name='contractId'>


            <div class="row margin-top-20">

                <div class="col-md-12">
                    <table class="table" id="assignTable">

                    </table>

                </div>
            </div>
            
            <div class="row" id="submitBtn">
                <div class="col-sm-2">
                    <input type="submit" value="Update">
                </div>
            </div>


        </form>

    </div>
</div>

