<?php

return [
    'Zend\Mail',
    'Zend\I18n',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Hydrator',
    'Zend\Navigation',
    'Zend\Db',
    'Zend\ServiceManager\Di',
    'Zend\Session',
    'Zend\Mvc\Plugin\Prg',
    'Zend\Mvc\Plugin\Identity',
    'Zend\Mvc\Plugin\FlashMessenger',
    'Zend\Mvc\Plugin\FilePrg',
    'Zend\Mvc\I18n',
    'Zend\Log',
    'Zend\Form',
    'Zend\Cache',
    'Zend\Router',
    'Zend\Validator',
    'Zend\Navigation',
    'Zend\Mvc\Console',
    'Application',
    'Setup',
    'LeaveManagement',
    'HolidayManagement',
    'AttendanceManagement',
    'SelfService',
    'RestfulService',
    'Payroll',
    'ManagerService',
    'System',
    'Training',
    'Appraisal',
    'Loan',
    'Advance',
    'Notification',
    'Travel',
    'WorkOnHoliday',
    'WorkOnDayoff',
    'Asset',
    'Other',
    'Report',
    'Overtime',
    'ServiceQuestion',
    'MobileApi',
    'Customer',
    'Medical',
    'PayrollApi',
    'Cafeteria',
    'KioskApi',
    'Cron'
];



