<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/cafeteria/cafeteria-activity/activity.js'));


?>
<script>
   
</script>
<style>
    .table-wrapper {
        font-size: 150%;
        max-height: 300px;
        max-width: 80%;
        overflow: scroll;
        display:inline-block;
      }
</style>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\loanApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.menuList = <?=json_encode($menuList)?>;
    document.timeList = <?=json_encode($timeList)?>;
    document.mapList = <?=json_encode($mapList)?>;
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.acl =<?php echo json_encode($acl); ?>;
</script>   
    
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase">Data Record Entry System</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
      <!--       <a id="add" class="btn default btn-sm">
                <i class="fa fa-plus-square icon-black"></i> New </a>
           <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF
                        </a>
                    </li>
                </ul>
            </div>-->
        </div>
    </div>
    

<!--        <div class="row margin-top-10">
            <div class=" col-sm-offset-8 col-sm-4">
                <button class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>-->
<form method="post" action="<?=$this->url('cafeteria-activity', ['action' => 'activity'])?>" id="cafeteria-activity">
<div class="container">
    <div class="row">
    <div class="col-sm-4">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered left-table">
                <tr>
                    <td>
                        <div class="form-group">
                        <label for="logDate">Log Date</label>  <span class="required" aria-required="true">*</span>
                        <input type="text" name="logDate" required="required" id="logDate" class="form-control" value="">                                                                   
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                        <label for="nepaliDate">&nbsp;</label>
                        <input type="text" name="nepaliLogDate" id="nepaliLogDate" class="form-control" value="">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="control-label">
                            Menu Time:</label></td><td>
                                <div class="form-group">
                            <select name="menuTime" id="menuTime">
                                <option value="-">--</option>
                                <?php foreach($timeList as $item){ ?>
                                <option value="<?=$item['TIME_ID']?>"><?=$item['TIME_NAME']?></option>
                                <?php } ?>
                            </select></div>
                        </td>
                </tr>
                <tr>
                    <td>
                            <label class="control-label">
                                Pay Type:</label></td><td><div class="form-group">
                            <select name="payType" id="payType">
                                <option value="p">payable</option>
                                <option value="c">complementary</option>
                            </select>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Employee</label></td><td><div class="form-group">
                        <select name="employee" required="required" id="employeeId" class="form-control">
                    </select>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <button type="submit" id="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    </div>
        <div class="col-sm-8 right-table" id="menuTable">
            
        </div>
        </div>
</form>    
    </div>
    
