
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\retirement-gratuity')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    New Entry
                </div>
            </div>
            <div class="portlet-body">
                <form>
                    <div class="form-group <?= empty($employees->getMessages()) ? "" : "has-error" ?>">
                        <?php print $this->formLabel($employees); ?>
                        <?php print $this->formElement($employees); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($designation); ?>
                        <?php print $this->formElement($designation); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($servePeriod); ?>
                        <?php print $this->formElement($servePeriod); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($salaryOfTheMonth); ?>
                        <?php print $this->formElement($salaryOfTheMonth); ?>
                    </div>
                    <div class="form-group">
                        <?php print $this->formLabel($gratuityAmount); ?>
                        <?php print $this->formElement($gratuityAmount); ?>
                    </div>

                    <?php print $this->formSubmit($submit); ?>
                </form>
            </div>
        </div>
    </div>

</div>