<?php

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'loanAdvance-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$loanAdvanceId = $form->get('loanAdvanceId');
$loanAdvanceId->setValueOptions($loanAdvanceList);
$requestAmount = $form->get('requestAmount');
$repaymentPeriod = $form->get('repaymentPeriod');
$advanceAmount = $form->get('advanceAmount');
$repaymentAmount = $form->get('repaymentAmount');
$reason = $form->get('reason');

$submit = $form->get('submit');
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('loanRequest', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuSelfService","subMenu"=>["id"=>"subMenuLoanAdvanceRequest"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\loanRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class="form-group">
                    <?php print $this->formLabel($loanAdvanceId); ?>
                    <?php print $this->formElement($loanAdvanceId); ?>
                    <?php print $this->formElementErrors()->render($loanAdvanceId, ['class' => 'help-block']); ?>
                </div>
               
                <div class="form-group">
                    <?php print $this->formLabel($requestAmount); ?>
                    <?php print $this->formElement($requestAmount); ?>
                    <?php print $this->formElementErrors()->render($requestAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($advanceAmount); ?>
                    <?php print $this->formElement($advanceAmount); ?>
                    <?php print $this->formElementErrors()->render($advanceAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($repaymentAmount); ?>
                    <?php print $this->formElement($repaymentAmount); ?>
                    <?php print $this->formElementErrors()->render($repaymentAmount, ['class' => 'help-block']); ?>
                </div>
                
                <div class="form-group">
                    <?php print $this->formLabel($repaymentPeriod); ?>
                    <?php print $this->formElement($repaymentPeriod); ?>
                    <?php print $this->formElementErrors()->render($repaymentPeriod, ['class' => 'help-block']); ?>
                </div>
                
                <div class="form-group">
                    <?php print $this->formLabel($reason); ?>
                    <?php print $this->formElement($reason); ?>
                    <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                </div>

                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
