<?php
$this->headScript()->appendFile($this->basePath('js/appraisal/default-rating/add.js'));
//print_r($form); die();
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'appraisalDefaultRating-form');

$defaultValue = $form->get('defaultValue');
$minValue = $form->get('minValue');
$maxValue = $form->get('maxValue');
$appraisalTypeId = $form->get('appraisalTypeId');
$appraisalTypeId->setValueOptions($appraisalTypes);
$designationIds = $form->get('designationIds');
$designationIds->setValueOptions($designations);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('defaultRating', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\defaultRating')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                
                 <div class=" row">
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($defaultValue); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($defaultValue); ?>
                            <?php print $this->formElementErrors()->render($defaultValue, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($minValue); ?>
                            <?php print $this->formElement($minValue); ?>
                            <?php print $this->formElementErrors()->render($minValue, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                     
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($maxValue); ?>
                            <?php print $this->formElement($maxValue); ?>
                            <?php print $this->formElementErrors()->render($maxValue, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                
                 <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraisalTypeId); ?>
                            <?php print $this->formElement($appraisalTypeId); ?>
                            <?php print $this->formElementErrors()->render($appraisalTypeId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($designationIds); ?>
                            <?php print $this->formElement($designationIds); ?>
                            <?php print $this->formElementErrors()->render($designationIds, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>