<?php if (count($appraiseeQuestionTemplate) > 0 && $appraiseeAvailableAnswer == true) { ?>
    <h3>Appraisee's Feedback</h3>
    <div class="row">
        <?php foreach ($appraiseeQuestionTemplate as $appraiseeQuestionRow) { ?>
            <div class="col-md-12 margin-bottom-10">
                <div style="">
                    <h6 style="" class="appHeading"><?php echo $appraiseeQuestionRow['HEADING_EDESC']; ?></h6>
                    <div class="row questionWrapRow">
                        <div class="questionWrap">
                            <?php foreach ($appraiseeQuestionRow['QUESTIONS'] as $questionRow) { ?>
                                <div  class="col-md-12 margin-bottom-5 appQuestion">
                                    <div class="row">
                                        <div class="col-sm-8">
                                            <label><h7 style="font-size:12px;"><?php echo $questionRow['QUESTION_EDESC']; ?></h7> </label> 
                                            <?php
                                            $keyForQuestion = ($questionRow['ANSWER'] == null || count($questionRow['ANSWER']) == 0) ? $questionRow['QUESTION_ID'] : array_keys($questionRow['ANSWER'])[0];
                                            if ($questionRow['APPRAISEE_FLAG'] == 'Y') {
                                                print_r($this->formElement($performanceAppraisalObj("answer[" . $keyForQuestion . "]", $questionRow['ANSWER_TYPE'], (count($questionRow['QUESTION_OPTIONS']) > 0) ? $questionRow['QUESTION_OPTIONS'] : null, ($questionRow['ANSWER'] != null && count($questionRow['ANSWER']) > 0) ? array_values($questionRow['ANSWER'])[0]['ANSWER'] : null, "disabled")));
                                            }
                                            ?>
                                        </div>
                                        <?php if ($questionRow['APPRAISEE_RATING'] == 'Y') { ?>
                                            <div class="col-sm-1">
                                                <label>Self Rating:</label><input class="form-control" type="number" name="<?= "answer[" . $keyForQuestion . ".sr]" ?>" value="<?= ($questionRow['ANSWER'] != null || count($questionRow['ANSWER']) > 0) ? array_values($questionRow['ANSWER'])[0]['RATING'] : null ?>"  min="<?= $questionRow['MIN_VALUE'] ?>" max="<?= $questionRow['MAX_VALUE'] ?>" disabled="disabled"/>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if (($assignedAppraisalDetail['KPI_SETTING'] == 'Y') && ($assignedAppraisalDetail['COMPETENCIES_SETTING'] == 'Y')) { ?>
            <div class="col-sm-12 margin-bottom-15">
                <label style="font-size:12px !important;">
                    Have you had the opportunity for a full discussion on the report and agree. Agree? 
                </label>
                <div>
                    <div class="radio-inline">
                        <input disabled="disabled" type="radio" id="appraiseeAgree1" name="appraiseeAgree" value="Y" <?= ($assignedAppraisalDetail['APPRAISEE_AGREE'] == 'Y') ? "checked" : ""; ?>>
                        <label for="appraiseeAgree1"> Yes </label>
                    </div>
                    <div class="radio-inline">
                        <input disabled="disabled" type="radio" id="appraiseeAgree2" name="appraiseeAgree" value="N" <?= ($assignedAppraisalDetail['APPRAISEE_AGREE'] == 'N') ? "checked" : ""; ?>>
                        <label for="appraiseeAgree2"> No </label>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>