<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/bootstrap-multiselect/css/bootstrap-multiselect.css'));


$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/ng-bootstrap-multiselect.js'));
$this->headScript()
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/setup/recommend-approve/comBranchDeptDesignSearch.js'))
        ->appendFile($this->basePath('js/Payroll/MonthlyValue/detailController.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-multiselect/js/bootstrap-multiselect.js'));
?>

<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.monthlyValues =<?= json_encode($monthlyValues) ?>;
    document.searchValues =<?php echo json_encode($searchValues); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\monthlyValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div ng-app="hris" ng-controller="monthlyValueDetailController">
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <select class="form-control" >
                            </select>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <select class="form-control" name="company" id="companyId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="branchId" id="branchId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="department" id="departmentId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="designation" id="designationId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="position" id="positionId">
                            </select>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <select class="form-control" name="serviceType" id="serviceTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="employeeType" id="employeeTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" name="employee" id="employeeId">
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <button id="reset" class="btn default btn-sm pull-right">
                                Reset
                                <i class="fa fa-refresh"></i>
                            </button>
                            <button ng-click="view()" id="viewEmployees" class="btn btn-default btn-sm pull-right">
                                Search
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="portlet light bg-inverse">
                <div class="portlet-title">


                </div>
                <div class="portlet-body">
                    <div class="scroller" style="height:350px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd" >

                        <table class="table table-bordered customTable" ng-show="showTable"  >
                            <thead>
                                <tr>
                                    <th class="id-width">
                                        Employee Id
                                    </th>
                                    <th class="flatwidth">
                                        Employee Name
                                    </th>
                                    <th class="keyswidth" ng-repeat="keys in monthlyValuekeys" ng-bind="monthlyValuesI[keys]">

                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="row in tableDataCopy">
                                    <td ng-bind="row.EMPLOYEE_ID">

                                    </td>
                                    <td>
                                        <span ng-bind="row.FIRST_NAME"></span>
                                        <span ng-bind="row.MIDDLE_NAME"></span>
                                        <span ng-bind="row.LAST_NAME"></span>
                                    </td>
                                    <td ng-repeat="keys in monthlyValuekeys">
                                        <input class="form-control" type="number" ng-model="row[keys]">
                                    </td>
                                </tr>


                            </tbody>
                            <tfoot>
                                <tr>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td ng-repeat="keys in monthlyValuekeys">
                                        <input class="form-control" type="number" ng-model="colVal"
                                               ng-change="changeAllColVal(keys, colVal)">
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="row margin-top-5">
                        <div class="col-sm-12">
                            <button class="btn btn-success pull-right" ng-click="setMonthlyValue()">Assign Monthly Value</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>