<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/bootstrap-table/bootstrap-table.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-table/bootstrap-table.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/setup/recommend-approve/comBranchDeptDesignSearch.js'))
        ->appendFile($this->basePath('js/Payroll/MonthlyValue/detailController.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.getMonthlyValueDetailWS = '<?php echo $this->url("monthlyValue", ["action" => "getMonthlyValueDetail"]); ?>';
    document.postMonthlyValueDetailWS = '<?php echo $this->url("monthlyValue", ["action" => "postMonthlyValueDetail"]); ?>';
    document.monthlyValues =<?php echo json_encode($monthlyValues); ?>;
    document.fiscalYears =<?php echo json_encode($fiscalYears); ?>;
    document.months =<?php echo json_encode($months); ?>;
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\monthlyValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <label>Company</label>
                            <select multiple class="form-control" name="company" id="companyId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Branch</label>
                            <select multiple class="form-control" name="branchId" id="branchId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Department</label>
                            <select multiple class="form-control" name="department" id="departmentId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Designation</label>
                            <select multiple class="form-control" name="designation" id="designationId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Position</label>
                            <select multiple class="form-control" name="position" id="positionId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Service Type</label>
                            <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                            </select>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Service Event Type</label>
                            <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Employee Type</label>
                            <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Gender</label>
                            <select multiple class="form-control" name="gender" id="genderId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Functional Type</label>
                            <select multiple class="form-control" name="functionalType" id="functionalTypeId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Employee</label>
                            <select multiple class="form-control" name="employee" id="employeeId">
                            </select>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-sm-2">
                            <label>Monthly value</label>
                            <select class="form-control reset-field" id="monthlyValueId" >
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Fiscal Year</label>
                            <select class="form-control reset-field" id="fiscalYearId" >
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Month</label>
                            <select class="form-control" id="monthId" >
                            </select>
                        </div>
                        <div class="col-sm-2 col-sm-offset-4">
                            <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                                Reset
                                <i class="fa fa-refresh"></i>
                            </button>
                            <button  id="searchEmployeesBtn" class="btn btn-default btn-sm pull-right">
                                Search
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="tools">
                        <a href="" class="fullscreen" data-original-title="" title=""> </a>
                    </div>
                    
                    <div class="actions">
                        <div class="btn-group">
                            <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-copy"></i> Tools
                                <i class="fa fa-angle-down "></i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li >
                                    <a href="javascript:;" id="excelExport">
                                        <i class="fa fa-file-excel-o" ></i>
                                        Export to Excel
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
                <div class="portlet-body">
                    <div style="overflow-x:auto;">
                        <table class="table table-bordered table-striped customTable " id="monthlyValueDetailTable" >
                            <thead>
                                <tr id="monthlyValuesDetailHeader">

                                </tr>
                            </thead>
                            <tbody id="monthlyValueDetailGrid">


                            </tbody>
                            <tfoot id="monthlyValueDetailFooter">

                            </tfoot>
                        </table>
                    </div>
                    <div class="row margin-top-20">
                        <div class="col-sm-12">
                            <button id="assignMonthlyValueBtn" class="btn pull-right" >Assign Monthly Value</button>
                        </div>
                    </div>
                </div>
                
                
                <form enctype="multipart/form-data" action="<?= $this->url("monthlyValue", ["action" => "uploadMonthlyValueEmpWise"]); ?>" method="POST" >  

                        <div class="row margin-top-20">
                            <div class="col-sm-4">
                                <label>Select Monthly Excel Upload</label>  
                                <input required="required" type="file" name="excel_file" />  
                                <input type="submit" value="submit"> 
                            </div>
                        </div>
                    </form>  
                
            </div>
        </div>
    </div>
</div>