<?php
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/Payroll/MonthlyValue/index.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<script>
    document.menu =<?php $menu = ["id" => "menuPayroll", "subMenu" => ["id" => "subMenuMonthlyValue"], "subMenuChild" => ["id" => "subMenuChildMonthlyValSetup"]];echo json_encode($menu);?>;
    document.monthlyValues = <?= json_encode($monthlyValues); ?>;
</script>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\monthlyValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('monthlyValue', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="monthlyValueTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (MTH_CODE == null) ? '-' : MTH_CODE #
        </td>
        <td>
        #: (MTH_EDESC == null) ? '-' : MTH_EDESC #
        </td>
        <td>
        #: (MTH_LDESC == null) ? '-' : MTH_LDESC #
        </td>
        <td>
        #: (SHOW_AT_RULE == null) ? '-' : SHOW_AT_RULE #
        </td>
        <td>
        #: (SH_INDEX_NO == null) ? '-' : SH_INDEX_NO #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("monthlyValue", ["action" => "edit"]); ?>/#:MTH_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
         <a class="btn-delete confirmation"
        href="<?= $this->url("monthlyValue", ["action" => "delete"]); ?>/#:MTH_ID #" id="bs_#:MTH_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>
</div>