<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/cafeteria/cafeteria-setup/schedule.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('id', 'time-form');
 
$timeName = $form->get('timeName');

$remarks = $form->get('remarks');

$form->setAttribute('action', $this->url('cafeteriasetup', ['action' => 'edit']));
$form->prepare();

?>
<script>
    document.scheduleDetails = <?=json_encode($time)?>;
    document.editScheduleLink = '<?= $this->url("cafeteriasetup", ["action" => "schedule"]) ?>';
    document.deleteScheduleLink = '<?= $this->url("cafeteriasetup", ["action" => "deleteSchedule"]) ?>';
</script>
<style>
    .table-wrapper {
        font-size: 150%;
        max-height: 300px;
        overflow: auto;
        display:inline-block;
      }
</style>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\loanApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Time Master Setup</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <a id="add" class="btn default btn-sm">
                <i class="fa fa-plus-square icon-black"></i> New </a>
<!--            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF
                        </a>
                    </li>
                </ul>
            </div>-->
        </div>
    </div>
    

<!--        <div class="row margin-top-10">
            <div class=" col-sm-offset-8 col-sm-4">
                <button class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>-->


<div class="row">
    <div id="timeTable" class="table-wrapper col-sm-4">
    <table>
        <?php foreach($time as $item){ if($item['STATUS'] == 'E'){ ?>
        <tr id="tr-<?=$item['TIME_ID']?>"><td><button type="button" value="<?=$item['TIME_ID']?>" class="btn btn-link time" style="border: none;"><?=$item['TIME_NAME']?></button></td></tr>
        <?php }} ?> 
    </table>
    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-4">
        <?php
                print $this->form()->openTag($form);
                ?>
                <div class=" row">

                <div class="form-group">
                    <?php print $this->formLabel($timeName); ?>
                    <span class="required" aria-required="true">*</span>
                    <?php print $this->formElement($timeName); ?>
                    <?php print $this->formElementErrors()->render($timeName, ['class' => 'help-block']); ?>
                </div>
                </div>

                <div class=" row">
                    <input type="hidden" name="timeId" id="timeId" value="">
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                </div>
         <div class="row">
             <button type="button" id="submit" class="btn btn-success submit">Submit</button>
             <button type="button" class="btn btn-success edit-cancel">Edit</button>
             <?php
                print $this->form()->closeTag();
                ?>
             <form method="post" action="<?= $this->url("cafeteriasetup", ["action" => "deleteSchedule"]) ?>">
             <input type="hidden" name="timeId" id="deleteTimeId" value="">
             <button type="submit" class="btn btn-success delete">Delete</button>
             </form>
         </div>
        
    </div>
    </div>
         
    </div>
