<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/advance-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'advanceApprove-form');

$advanceId = $form->get('advanceId');
$advanceId->setValueOptions($advances);
$advanceId->setAttributes(["disabled"=>"disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled"=>"disabled"]);
$advanceDate = $form->get('advanceDate');
$advanceDate->setAttributes(["disabled"=>"disabled"]);
$reason = $form->get('reason');
$reason->setAttributes(["disabled"=>"disabled"]);
$terms = $form->get('terms');
$terms->setAttributes(["disabled"=>"disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['required'=>'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required'=>'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('advanceApprove', ['action' => 'view', 'id' => $id, 'role' => $role]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuManagerService","subMenu"=>["id"=>"subMenuAdvancetoApprove"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advanceApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20" ng-app="hris" ng-controller="advanceDetailController">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Advance Request Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="border-bottom">
                <div class="form-group">
                    <div class="row div-font-11">
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Employee Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $employeeName; ?>
                                    </td>
                                </tr>
                                
                                <tr height="30">
                                    <td>
                                        Your Role
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php if ($role == 3) {
                                                echo 'Approver';
                                            } else if ($role == 2) {
                                                echo 'Recommender';
                                            }else if($role==4){
                                                echo 'Recommender\Approver';
                                            } ?>
                                    </td>
                                </tr>                               
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>  
                                <tr height="30">
                                    <td>
                                        Requested Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $requestedDate; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Status
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        if ($status == 'RQ') {
                                            echo "Pending";
                                        } else if ($status == 'RC') {
                                            echo "Recommended";
                                        } else if ($status == 'AP') {
                                            echo "Approved";
                                        } else if ($status == "R") {
                                            echo "Rejected";
                                        } else if ($status == "C") {
                                            echo "Cancelled";
                                        } ?>
                                    </td>
                                </tr>
                                <?php if($role!=4){?>
                                <tr height="30">
                                    <td>
                                        <?= ($role==3)? "Recommender":"Approver"; ?>
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= ($role==3)? $recommender:$approver; ?>
                                    </td>
                                </tr> 
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="form-employeeId" value="<?php echo $requestedEmployeeId; ?>"/>
                <div class="form-group">
                    <?php print $this->formLabel($advanceId); ?>
                    <?php print $this->formElement($advanceId); ?>
                    <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                    <span ng-bind="allowAmt" style="font-size:11px; font-weight: bold;"></span>
                    <span ng-bind="allowTerms" style="font-size:11px; font-weight: bold;"></span>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($terms); ?>
                    <?php print $this->formElement($terms); ?>
                    <?php print $this->formElementErrors()->render($terms, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($advanceDate); ?>
                    <div class="input-group date" id="startDate">
                        <?php print $this->formElement($advanceDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($advanceDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($reason); ?>
                    <?php print $this->formElement($reason); ?>
                    <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                </div>
                </div>     
                <?php if ($role == 2) { ?>
                    <div
                        class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($recommendedRemarks); ?>
                        <?php print $this->formElement($recommendedRemarks); ?>
                    </div>
                <?php } ?>
                <?php  if($role==2 && ($status=='AP' || ($status=='R' && $approvedDT!=null))){ ?>
                    <div
                        class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                        <label>Reason for action [From Approver]</label>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php }  ?>

                <?php if ($role == 3 || $role==4) {
                        $recommendedRemarks->setAttributes(['disabled'=>'disabled']);
                        ?>
                    <?php if($role!=4){ ?>
                        <div
                            class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                            <label>Reason for action [From Recommender]</label>
                            <?php print $this->formElement($recommendedRemarks); ?>
                        </div>
                    <?php } ?>
                    <div
                        class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($approvedRemarks); ?>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php } ?>

                <?php
                if ($status == 'RQ' || ($status == 'RC' && $employeeId != $recommendedBy)) {
                    print $this->formSubmit($submit);
                    ?>
                    <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                <?php } ?>

            </div>

        </div>
    </div>
</div>

<?php

print $this->form()->closeTag();

?>