<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js">
<![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js">
<![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <!--<meta http-equiv="content-type" content="text/html;charset=ISO-8859-1"/>-->
    <head>
        <meta charset="utf-8"/>
        <title>Neo::HRIS</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="Preview page of Metronic Admin Theme #1 for statistics, charts, recent events and reports"
              name="description"/>
        <meta content="" name="author"/>
        <!-- BEGIN GLOBAL MANDATORY STYLES -->

        <link rel="shortcut icon" href="<?= $this->basePath('favicon.ico') ?>"/>
        <link href="<?= $this->basePath('css/fonts.css') ?>" rel="stylesheet"
              type="text/css"/>
        <link href="<?= $this->basePath('assets/font-awesome/font-awesome.css') ?>" rel="stylesheet"
              type="text/css"/>
        <link href="<?= $this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css') ?>"
              rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/global/plugins/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet"
              type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<?= $this->basePath('assets/layouts/layout/css/layout.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/layouts/layout/css/themes/light2.min.css') ?>" rel="stylesheet"
              type="text/css"/>
        <!-- END THEME LAYOUT STYLES -->

        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<?= $this->basePath('assets/global/css/components-md.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php print $this->basePath('assets/global/css/plugins.css'); ?>" rel="stylesheet" type="text/css"/>
        <!-- END THEME GLOBAL STYLES -->

        <!--mandatory plugins -->
        <link href="<?= $this->basePath('assets/global/plugins/select2/css/select2.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/global/plugins/select2/css/select2-bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>

        <link href="<?= $this->basePath('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css') ?>"
              rel="stylesheet" type="text/css"/>

        <link href="<?= $this->basePath('assets/global/plugins/bootstrap-toastr/toastr.min.css') ?>"
              rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/global/plugins/jquery-ui/jquery-ui.min.css') ?>" rel="stylesheet" type="text/css"/>
        <!--End of mandatory plugins-->
        <?php
        print $this->headLink();
        ?>

        <link href="<?= $this->basePath('css/listpage.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('css/custom.css') ?>" rel="stylesheet" type="text/css"/>

    </head>


    <body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white page-md page-sidebar-fixed">
        <script>
            document.restfulUrl = '<?= $this->url("restful", ["action" => "index"]) ?>';
            document.basePath = '<?= $this->basePath() ?>';
            document.settingUrl = '<?= $this->url("user-setting", ["action" => "index"]) ?>';
            document.updateSettingUrl = '<?= $this->url("user-setting", ["action" => "update"]) ?>';
<?php if ($displayGlobalSearch) { ?>
                document.globalSearchemployeeList = <?php echo json_encode($employeeList); ?>;
<?php } ?>
            document.globalSearchEmployeeProfileUrl = '<?= $this->url("employee", ["action" => "view"]) ?>';
        </script>
        <div class="page-wrapper" id="hris-page-content">
            <?php
            print $this->partial('partials/header.phtml');
            ?>
            <div class="clearfix"></div>
            <div class="page-container">
                <?php
                $this->navigation('navigation-menu')->menu()->setPartial('partials/sidebar');
                echo $this->navigation('navigation-menu')->menu()->render();
                ?>
                <div class="page-content-wrapper">
                    <div  class="page-content">
                        <?php
                        print $this->content;
                        ?>
                    </div>
                </div>
                <?php
                print $this->partial('partials/quick-sidebar.phtml');
                ?>
            </div>
            <?php
            print $this->partial('partials/footer.phtml');
            ?>
            <?php
            print $this->partial('partials/profile.phtml');
            ?>

        </div>

        <!--[if lt IE 9]>
        <script src="<?= $this->basePath('assets/global/plugins/respond.min.js') ?>"></script>
        <script src="<?= $this->basePath('assets/global/plugins/excanvas.min.js') ?>"></script>
        <script src="<?= $this->basePath('assets/global/plugins/ie8.fix.min.js') ?>"></script>
        <![endif]-->

        <?php
        if ($displayGlobalSearch) {
            $this->headScript()
                    ->prependFile($this->basePath('js/application/globalSearch.js'));
        }
        $this->headScript()
                ->prependFile($this->basePath('js/user-setting.js'));
        $this->headScript()
                ->prependFile($this->basePath('js/custom.js'));
        ?>
        <?php
        $this->headScript()->prependFile($this->basePath('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'));
        $this->headScript()->prependFile($this->basePath('assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js'));
        ?>

        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <?php
        $this->headScript()
                ->prependFile($this->basePath('assets/layouts/global/scripts/quick-nav.min.js'))
                ->prependFile($this->basePath('assets/layouts/global/scripts/quick-sidebar.min.js'))
                ->prependFile($this->basePath('assets/layouts/layout/scripts/demo.min.js'))
                ->prependFile($this->basePath('assets/layouts/layout/scripts/layout.min.js'));
        ?>
        <!-- END THEME LAYOUT SCRIPTS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <?php
        $this->headScript()
                ->prependFile($this->basePath('assets/global/scripts/app.min.js'));
        ?>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BLOCK UI -->
        <?php
        $this->headScript()->prependFile($this->basePath('assets/global/plugins/jquery.blockui.min.js'));
        ?>
        <!-- BLOCK UI -->
        <!--Select 2-->
        <?php
        $this->headScript()
                ->prependFile($this->basePath('assets/global/plugins/select2/js/select2.full.min.js'));
        ?>
        <!--End Select 2-->
        <!-- BEGIN CORE PLUGINS -->
        <?php
        print $this->headScript()
                        ->prependFile($this->basePath('assets/global/plugins/jquery-ui/jquery-ui.min.js'))
                        ->prependFile($this->basePath('assets/global/plugins/bootstrap-toastr/toastr.min.js'))
                        ->prependFile($this->basePath('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js'))
                        ->prependFile($this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js'))
                        ->prependFile($this->basePath('assets/global/plugins/js.cookie.min.js'))
                        ->prependFile($this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js'))
                        ->prependFile($this->basePath('assets/global/plugins/jquery.min.js'))
                        ->appendFile($this->basePath('js/application/changePassword/index.js'));
        ?>
        <!-- END CORE PLUGINS -->
        <!-- End -->
        
            <?php
            print $this->partial('partials/change-password.phtml');
            ?>
        
        <div id='pdfExportTable'></div>


    </body>
</html>