<?php
/**
 * Created by PhpStorm.
 * User: himal
 * Date: 7/22/16
 * Time: 4:04 PM
 */
?>

<?php print $this->doctype() ?>

<html lang="en">

<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta charset="utf-8"/>
    <title>Neo::HRIS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description"/>
    <meta content="" name="author"/>

    <?php print $this->headLink(['rel'=>'shortcut icon', 'type'=>'image/vnd.microsoft.icon', 'href'=>$this->basePath('ico/favicon.png')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('datatables-responsive/css/datatables.responsive.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('plugins/jquery-datatable/media/css/dataTables.bootstrap.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('css/custom.css')])

        ->prependStylesheet(['rel'=>'apple-touch-icon-precomposed', 'sizes'=>'152x152', 'href'=>$this->basePath('ico/152.png')])
        ->prependStylesheet(['rel'=>'apple-touch-icon-precomposed', 'sizes'=>'120x120', 'href'=>$this->basePath('ico/120.png')])
        ->prependStylesheet(['rel'=>'apple-touch-icon-precomposed', 'sizes'=>'76x76', 'href'=>$this->basePath('ico/76.png')])
        ->prependStylesheet(['rel'=>'apple-touch-icon-precomposed', 'sizes'=>'60x60', 'href'=>$this->basePath('ico/60.png')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'class'=>'main-stylesheet', 'href'=>$this->basePath('pages/css/pages.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'href'=>$this->basePath('pages/css/pages-icons.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/jquery-metrojs/MetroJs.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/bootstrap-datepicker/css/datepicker3.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/bootstrap-timepicker/bootstrap-timepicker.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'href'=>$this->basePath('plugins/rickshaw/rickshaw.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'href'=>$this->basePath('plugins/mapplic/css/mapplic.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/nvd3/nv.d3.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/switchery/css/switchery.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/bootstrap-select2/select2.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css', 'media'=>'screen', 'href'=>$this->basePath('plugins/jquery-scrollbar/jquery.scrollbar.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('plugins/font-awesome/css/font-awesome.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('plugins/bootstrap-v3.3.6/css/bootstrap.min.css')])
        ->prependStylesheet(['rel'=>'stylesheet', 'type'=>'text/css','href'=>$this->basePath('plugins/pace/pace-theme-flash.css')]);

       
    ?>
    <!--[if lte IE 9]>
    <link href="<?php print $this->basePath('plugins/codrops-dialogFx/dialog.ie.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
    <![endif]-->

    <?php $this->headScript()->captureStart(); ?>
    site = {
    basePath: "<?php print $this->basePath(); ?>"
    };
    <?php $this->headScript()->captureEnd(); ?>

</head>
<body class="fixed-header pace-done sidebar-visible">
<?php

/**
 * SIDEBAR
 */
print $this->partial("partials/sidebar.phtml");
?>
<div class="page-container ">
    <?php
    /**
     * HEADER
     */
    print $this->partial("partials/header.phtml");
    ?>

    <div class="page-content-wrapper ">
        <div class="content sm-gutter">
            <div class="container-fluid padding-25 sm-padding-10 bg-master-light">
                <?php print $this->content; ?>
            </div>
        </div>

        <?php
        /**
         * FOOTER
         */
        print $this->partial("partials/footer.phtml");
        ?>
    </div>
</div>


<?php print $this->headScript()

    ->prependFile($this->basePath('js/menu.js'))
    ->prependFile($this->basePath('js/custom.js'))

    //for form tab<<
    ->prependFile($this->basePath('js/form/form_wizard.js'))
    //>>


    //for form tab<<
    ->prependFile($this->basePath('js/form/boostrap-form-wizard/js/jquery.bootstrap.wizard.min.js'))
    //>>

    ->prependFile($this->basePath('js/demo.js'))
    ->prependFile($this->basePath('js/scripts.js'))
//    ->prependFile($this->basePath('js/dashboard.js'))
    ->prependFile($this->basePath('pages/js/pages.min.js'))
    ->prependFile($this->basePath('plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'))

    ->prependFile($this->basePath('plugins/skycons/skycons.js'))
    ->prependFile($this->basePath('plugins/jquery-sparkline/jquery.sparkline.min.js'))
    ->prependFile($this->basePath('plugins/jquery-metrojs/MetroJs.min.js'))
//    ->prependFile($this->basePath('plugins/rickshaw/rickshaw.min.js'))
    ->prependFile($this->basePath('plugins/mapplic/js/mapplic.js'))
    ->prependFile($this->basePath('plugins/mapplic/js/jquery.mousewheel.js'))
    ->prependFile($this->basePath('plugins/mapplic/js/hammer.js'))
    ->prependFile($this->basePath('plugins/nvd3/src/models/lineWithFocusChart.js'))
    ->prependFile($this->basePath('plugins/nvd3/src/models/line.js'))
    ->prependFile($this->basePath('plugins/nvd3/src/models/axis.js'))
    ->prependFile($this->basePath('plugins/nvd3/src/interactiveLayer.js'))
    ->prependFile($this->basePath('plugins/nvd3/src/tooltip.js'))
    ->prependFile($this->basePath('plugins/nvd3/src/utils.js'))
    ->prependFile($this->basePath('plugins/nvd3/nv.d3.min.js'))
    ->prependFile($this->basePath('plugins/nvd3/lib/d3.v3.js'))
    ->prependFile($this->basePath('plugins/switchery/js/switchery.min.js'))
    ->prependFile($this->basePath('plugins/classie/classie.js'))
    ->prependFile($this->basePath('plugins/bootstrap-select2/select2.min.js'))
    ->prependFile($this->basePath('plugins/jquery-scrollbar/jquery.scrollbar.min.js'))
    ->prependFile($this->basePath('plugins/jquery-actual/jquery.actual.min.js'))
    ->prependFile($this->basePath('plugins/jquery-ios-list/jquery.ioslist.min.js'))
    ->prependFile($this->basePath('plugins/jquery-bez/jquery.bez.min.js'))
    ->prependFile($this->basePath('plugins/jquery-unveil/jquery.unveil.min.js'))
    ->prependFile($this->basePath('plugins/jquery/jquery-easy.js'))
    ->prependFile($this->basePath('plugins/bootstrap-v3.3.6/js/bootstrap.min.js'))
    ->prependFile($this->basePath('plugins/jquery-ui/jquery-ui.min.js'))
    ->prependFile($this->basePath('plugins/modernizr.custom.js'))
    ->prependFile($this->basePath('plugins/jquery/jquery-2.2.4.min.js'))
    ->prependFile($this->basePath('plugins/pace/pace.min.js'));




?>

</body>

</html>

