<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/Notification/news/add.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('id', 'newsForm');
$form->setAttribute('action', $this->url('news', ['action' => 'add']));



$newsDate = $form->get('newsDate');

$newsType = $form->get('newsType');
$newsType->setValueOptions($newsTypeValue);

$newsTitle = $form->get('newsTitle');

$newsEdesc = $form->get('newsEdesc');

$newsLdesc = $form->get('newsLdesc');

$remarks = $form->get('remarks');


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->prepare();
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues) ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\news')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($newsDate); ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($newsDate); ?>
                                    <?php print $this->formElementErrors()->render($newsDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDate" id="nepaliDate"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>  

                    </div>


                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($newsType); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($newsType); ?>
                            <?php print $this->formElementErrors()->render($newsType, ['class' => 'help-block']); ?>
                        </div>
                    </div>


                    <div class="col-sm-4">

                        <div class="form-group">
                            <?php print $this->formLabel($newsTitle); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($newsTitle); ?>
                            <?php print $this->formElementErrors()->render($newsTitle, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($newsEdesc); ?>
                    <span class="required" aria-required="true">*</span>
                    <?php print $this->formElement($newsEdesc); ?>
                    <?php print $this->formElementErrors()->render($newsEdesc, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($newsLdesc); ?>
                    <?php print $this->formElement($newsLdesc); ?>
                    <?php print $this->formElementErrors()->render($newsLdesc, ['class' => 'help-block']); ?>
                </div>



                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>


                <div class="row form-group">
                    <div class="col-sm-2">
                        <label>Company</label>
                        <select  class="form-control" name="companyId" id="companyId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Branch</label>
                        <select  class="form-control" name="branchId" id="branchId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Department</label>
                        <select  class="form-control" name="departmentId" id="departmentId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Designation</label>
                        <select  class="form-control" name="designationId" id="designationId">
                        </select>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-sm-2">
                        <label>Position</label>
                        <select multiple class="form-control" name="position" id="positionId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>service Type</label>
                        <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Service Event Type</label>
                        <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee Type</label>
                        <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee</label>
                        <select multiple class="form-control" name="employee[]" id="employeeId">
                        </select>
                    </div>
                </div>



                <div>
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>

            </div>
        </div>
    </div>
</div>