<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/Notification/news/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php }
?>

<script>
    document.news =<?= json_encode($news) ?>;
</script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\news')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('news', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New <i class="fa fa-plus"></i>
<!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">                      
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <?php
//                echo'<pre>';
//        print_r($news);
    ?>

    <div id="newsTable">

    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>                              
        #: (NEWS_DATE == null) ? '-' : NEWS_DATE #
        </td>
        <td>    
        #: (NEWS_TYPE == null) ? '-' : NEWS_TYPE #
        </td>
        <td>                 
        #: (NEWS_TITLE == null) ? '-' : NEWS_TITLE #
        </td>
        <td>                 
        #: (NEWS_EDESC == null) ? '-' : NEWS_EDESC #
        </td>
        <td>
        <a class="btn-edit" href="<?= $this->url("news", ["action" => "edit"]); ?>/#:NEWS_ID#" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="btn-delete confirmation"
        href="<?= $this->url("news", ["action" => "delete"]); ?>/#:NEWS_ID#" id="bs_#:NEWS_ID #" style="height:17px;"> 
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>






</div>