<?php
$this->headScript()->appendFile($this->basePath('js/customer/contract-absent-details/edit.js'));
?>

<?php
$employeeId = $form->get('employeeId');
$subEmployeeId = $form->get('subEmployeeId');
$postingType = $form->get('postingType');

$employeeIdVal = $employeeId->getValue();
$subEmployeeIdVal = $subEmployeeId->getValue();



//die();
//$employeeCode = $form->get('employeeCode');
//$firstName = $form->get('firstName');
//$middleName = $form->get('middleName');
//$lastName = $form->get('lastName');
//$genderId = $form->get('genderId');
//$bloodGroupId = $form->get('bloodGroupId');
//$telephoneNo = $form->get('telephoneNo');
//$mobileNo = $form->get('mobileNo');
//$email = $form->get('email');
//$idCitizenshipNo = $form->get('citizenshipNo');
//$idCitizenshipIssueDate = $form->get('citizenshipIssueDate');
//$idCitizenshipIssuePlace = $form->get('citizenshipIssuePlace');
//$addrPermZoneId = $form->get('permanentZoneId');
//$addrPermDistrictId = $form->get('permanentDistrictId');
//$addrTempZoneId = $form->get('temporaryZoneId');
//$addrTempDistrictId = $form->get('temporaryDistrictId');
//$employeeType = $form->get('employeeType');
//$branchId = $form->get('branchId');
//$departmentId = $form->get('departmentId');
//$designationId = $form->get('designationId');
//$positionId = $form->get('positionId');
//$accountNo = $form->get('accountNo');
//
//
//$genderId->setOptions(["value_options" => $genders]);
//$bloodGroupId->setOptions(["value_options" => $bloodGroups]);
//$addrPermZoneId->setOptions(["value_options" => $zones]);
//$addrTempZoneId->setOptions(["value_options" => $zones]);
//$branchId->setValueOptions($branches);
//$departmentId->setValueOptions($departments);
//$designationId->setValueOptions($designations);
//$positionId->setValueOptions($positions);



$submit = $form->get('submit');

$form->setAttribute('action', $this->url('contract-absent-details', ['action' => 'edit', "id" => $id]));
$form->prepare();
?>

<script>
    document.employeeList =<?= json_encode($employeeList); ?>;
    document.employeeIdVal =<?= $employeeIdVal; ?>;
    document.subEmployeeIdVal =<?= $subEmployeeIdVal ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advance-setup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">

                    
                    <div class="col-sm-12 col-md-6 col-lg-3" >
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <?php print $this->formElement($employeeId); ?>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-3" >
                        <div class="form-group">
                            <?php print $this->formLabel($subEmployeeId); ?>
                            <?php print $this->formElement($subEmployeeId); ?>
                            <?php print $this->formElementErrors()->render($subEmployeeId, ['class' => 'help-block']); ?>
                        </div>
                    </div>


                    <div class="col-sm-12 col-md-6 col-lg-3" >
                        <div class="form-group">
                            <?php print $this->formLabel($postingType); ?>
                            <?php print $this->formElement($postingType); ?>
                            <?php print $this->formElementErrors()->render($postingType, ['class' => 'help-block']); ?>
                        </div>
                    </div>




                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>

