<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
//        ->appendFile($this->basePath('js/appraisal/heading/index.js'))
?>

<?php if ($this->messages) { ?>
    <script>
        $("#grid").kendoGrid({
                height: 550,
                sortable: true
            });

        
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } 

?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\experience')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('heading', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New <i class="fa fa-plus"></i>
<!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">                      
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="example">
            <table id="grid">
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Company</th>
                        <th>Designation</th>
                        <th>Position</th>
                        <th>Service Type</th>
                        <th>From Date</th>
                        <th>To Date</th>
                        <th>Total Working Yrs</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Rama Kumari Thapa</td>
                        <td>IT Nepal Pvt.Ltd.</td>
                        <td>Developer</td>
                        <td>Junior</td>
                        <td>Probation</td>
                        <td>2015-03-01</td>
                        <td>2016-03-31</td>
                        <td>1 Yr</td>
                        <td>
        <a class="btn-edit" href="/neo-hris/public/index.php/appraisal/detailSetup/edit/2" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="btn-delete confirmation" href="/neo-hris/public/index.php/appraisal/detailSetup/delete/2" id="bs_2" style="height:17px;"> 
        <i class="fa fa-trash-o"></i></a>
        
        </td>
                    </tr>
                    <tr>
                        <td>Rama Kumari Thapa</td>
                        <td>Softnep Pvt.Ltd.</td>
                        <td>QC</td>
                        <td>Senior</td>
                        <td>Permanent</td>
                        <td>2017-01-01</td>
                        <td>2017-03-31</td>
                        <td>.25 Yr</td>
                        <td>
        <a class="btn-edit" href="/neo-hris/public/index.php/appraisal/detailSetup/edit/2" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="btn-delete confirmation" href="/neo-hris/public/index.php/appraisal/detailSetup/delete/2" id="bs_2" style="height:17px;"> 
        <i class="fa fa-trash-o"></i></a>
        
        </td>
                    </tr>
                    
                </tbody>
            </table>
</div>
