<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/setup/service-event-type/index.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuServiceEventType"]];
echo json_encode($menu);
?>;
    document.serviceEventTypes =<?php echo json_encode($serviceEventTypes) ?>;
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\serviceEventType')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('serviceEventType', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="serviceEventTypeTable">
    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (SERVICE_EVENT_TYPE_CODE == null) ? '-' : SERVICE_EVENT_TYPE_CODE #
        </td>
        <td>
        #: (SERVICE_EVENT_TYPE_NAME == null) ? '-' : SERVICE_EVENT_TYPE_NAME #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("serviceEventType", ["action" => "edit"]) ?>/#:SERVICE_EVENT_TYPE_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
        <a class="btn-delete confirmation"
        href="<?= $this->url("serviceEventType", ["action" => "delete"]); ?>/#:SERVICE_EVENT_TYPE_ID #" id="bs_#:SERVICE_EVENT_TYPE_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>
</div>