<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuAppraisal", "subMenu" => ["id" => "subMenuSetup"]];
echo json_encode($menu); ?>;
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\appraisal-setup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="row">
    <div class="col-lg-12">



        <div class="panel-heading">
            <h4>Appraisal Setup</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <form class="well form" action="appraisal/appraisal_submit.php" method="post">
                        <div class="form-group" style="width:100%;">	
                            <table class="table table-hover">

                                <tbody><tr>
                                        <td><label>Appraisal Name</label></td><td>:</td>
                                        <td colspan="12"><input type="text" required="" name="appraisal_name" id="appraisal_name" onclick="HandleBrowseClick1()" class="form-control"></td>
                                    </tr>
                                    <tr>
                                        <td><label>Appraisal Type</label></td><td>:</td>
                                        <td colspan="12">
                                            <select name="appraisal_type" class="form-control" required="">
                                                <option value="1">Monthly</option>
                                                <option value="3">Quarterly</option>
                                                <option value="6">Half-Yearly</option>
                                                <option value="12">Annually</option>
                                            </select>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td><label>Appraisal Status</label></td><td>:</td>
                                        <td colspan="12">
                                            <select name="appraisal_status" class="form-control" required=""> 
                                                <option value="1">Begining Mode</option>
                                                <option value="L">Locked</option>
                                                <option value="3">Key Achievements </option>
                                                <option value="0">Completed</option>
                                            </select>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td><label>From Date</label></td><td>:</td>
                                        <td colspan="12"><input type="text" required="" name="start_date" id="from_date" class="form-control hasDatepicker"></td>
                                    </tr>
                                    <tr>
                                        <td><label>To Date</label></td><td>:</td>
                                        <td colspan="12"><input type="text" required="" name="end_date" id="to_date" class="form-control hasDatepicker"></td>
                                    </tr>


                                    <tr>
                                        <td><label>Remarks</label></td><td>:</td>
                                        <td><textarea name="remarks" id="remarks" required="" class="form-control" style="height:80px"></textarea></td>
                                    </tr>

                                </tbody></table>	
                            <button type="submit" value="submit " class="btn btn-primary" style="width:100px">&nbsp;SUBMIT</button>

                        </div></form>
                </div>
            </div>
        </div>
    </div>
</div>
