
<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\appraisal-setup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>



<div class="row margin-top-10">
    <div class="col-sm-12">
        <table id="dataTable">
            <thead>
                <tr>
                    <th>
                        Appraisal
                    </th>
                    <th>
                        Start Date
                    </th>
                    <th>
                        End Date
                    </th>
                    <th>
                        Appraisee
                    </th>
                    <th>
                        Appraiser
                    </th>
                    <th>
                        Reviewer
                    </th>
                    <th>
                        Approved?
                    </th>
                    <th>
                        Rating
                    </th>
                    <th>
                        Objective Set?
                    </th>
                    <th>
                        Appraiser Evaluation?
                    </th>
                    <th>
                        Reviewer View?
                    </th>
                    <th>
                        Final Rating?
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        &nbsp;
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>
