<?php // in module/Application/view/partial/breadcrumb.phtml: ?>
<ul class="page-breadcrumb">
    <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            // if this isn't the last page, add a link and the separator:
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
                <i class="fa fa-circle"></i>

                <?php
            // otherwise, output the name only:
            else:
                ?>
                <?= $page->getLabel() ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>