<div class="modal fade" id="changePasswordModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Change Password</h4>
            </div>
            <div class="modal-body">

                <div class="row">

                    <form action="" id="changePasswordForm" method="post">

                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label class="passwordLabel">Enter Old Password</label>
                                    <input required="required" type="password" class="form-control" name="oldPassword" id="oldPassword"/>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label class="passwordLabel">Enter New Password</label>
                                    <input required="required" type="password" class="form-control" name="newPassword" id="newPassword"/>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label class="passwordLabel">Confirm New Password</label>
                                    <input required="required" type="password" class="form-control" name="reNewPassword" id="reNewPassword"/>
                                    
                                </div>
                            </div>
                        </div>
                    </form>


                </div>




            </div>
            <div class="modal-footer">
                <button id="changePwdBtn" type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

