
<script>
document.getoldPassword="<?=$this->url('changePwd', ['action' => 'getoldPassword']);?>";
</script>

<div class="modal fade" id="changePasswordModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Change Pasword</h4>
            </div>
            <div class="modal-body">

                <div class="row">

                    <!--<form action="<?= $this->url('changePwd', ['action' => 'updatePassword']); ?>" id="changePassword" method="post">-->
                    <form action="" id="changePasswordForm" method="post">

                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label class="passwordLabel">Enter Old Password</label>
                                    <input required="required" type="password" class="form-control" name="oldPassword" id="oldPassword"/>
                                    <span id="oldPwdErr" class="errorMsg"></span>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label class="passwordLabel">Enter New Password</label>
                                    <input required="required" type="password" class="form-control" name="newPassword" id="newPassword"/>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group">
                                    <label class="passwordLabel">Confirm New Password</label>
                                    <input required="required" type="password" class="form-control" name="reNewPassword" id="reNewPassword"/>
                                    <span id="pwdMisMatchErr" class="errorMsg"></span>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4 col-sm-offset-4" >
                                <div class="form-group pull-left">
                                    <input value="submit" type="button" id="changePwdBtn">
                                    <!--<input type="submit" id="changePwdBtn" name="submit" class="btn btn-primary btn-block uppercase loginbtn codeSubmit" value="Submit">-->
                                </div>
                            </div>
                        </div>

                    </form>


                </div>




            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

