<div class="page-header navbar navbar-fixed-top" style="z-index: 1000;">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="#">
                <img src="<?= $this->basePath('img/neo-hris.png') ?>" alt="logo" class="logo-default" /> </a>

            <div class="menu-toggler sidebar-toggler">
                <span></span>
            </div>
        </div>
        <!-- END LOGO -->
        <?php if ($displayGlobalSearch) { ?>
            <form id="globalSearchForm" class="search-form search-form-expanded margin-right-10" action="" method="GET">
                <div class="input-group">
                    <input style="height: 50px !important;" id="globalSearch" type="text" class="form-control" placeholder="Search..." name="query">
                    <span class="input-group-btn">
                        <a href="javascript:;" class="btn submit">
                            <i class="icon-magnifier"></i>
                        </a>
                    </span>
                </div>
            </form>

        <?php } ?>
        <div class="company-logo company-logo-box margin-right-10">
            <?php if (isset($companyLogoUrl) && $companyLogoUrl != "NO") { ?>
                <img src="<?= $this->basePath("uploads/" . $companyLogoUrl) ?>" alt="logo" class="logo-default1 companylogo">
            <?php } ?>
            <?php // print_r($profilePictureUrl);  ?>
            <span>
                <?= strtoupper($companyName) ?>
                <br>
                <address>
                    <?= $companyAddress ?>
                </address>
            </span>
        </div>




        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="page-top">
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <!-- NOTIFICATION DROPDOWN -->
                    <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="icon-bell"></i>
                            <!--<span class="badge badge-default"> 7 </span>-->
                            <?php if (sizeof($notifications) > 0): ?>
                                <span class="badge badge-default"> <?php print sizeof($notifications); ?> </span>
                            <?php endif; ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="external">
                                <h3>
                                    <span class="bold"><?php print sizeof($notifications); ?> pending</span> notifications</h3>
                                <a href="<?php print $this->url('notification', ['action' => 'index']); ?>">view all</a>
                            </li>
                            <li>
                                <ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                                    <?php foreach ($notifications as $notification): ?>

                                        <li>
                                            <a href="<?php print $this->url('notification', ['action' => 'view', 'id' => $notification['MESSAGE_ID']]); ?>">
                                                <!--<span class="time">just now</span>-->
                                                <span class="time"><?php echo $dateCompare($notification['MESSAGE_DATETIME']) ?> days</span>
                                                <span class="details">
                                                    <span class="label label-sm label-icon label-success">
                                                        <i class="fa fa-bell-o"></i>
                                                    </span> <?php print $notification['MESSAGE_DESC']; ?> </span>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <!-- END NOTIFICATION DROPDOWN -->

                    <li class="dropdown dropdown-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <img alt="Profile Picture" class="img-polaroid" src="<?= $this->basePath("uploads/" . $profilePictureUrl) ?>" />
                            <span class="username username-hide-on-mobile"> <?= $employeeName ?> </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="<?= $this->url('profile', ['action' => 'index', 'tab' => 1]) ?>">
                                    <i class="icon-user"></i> My Profile </a>
                            </li>

                            <li>
                                <a class=""  href="#" id="passwordChangeMenu">
                                    <i class="icon-lock"></i> Change Password </a>
                            </li>
                            <?php if ($showAddressBook): ?>
                                <li>
                                    <a href="<?php echo $this->url('employee', ['action' => 'contact']); ?>">
                                        <i class="icon-magnifier"></i>Address Book </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($allowRegisterAttendance) { ?>
                                <li>
                                    <a href="<?php echo $this->url('registerAttendance', ['action' => 'checkout']); ?>">
                                        <i class="icon-login"></i>Check <?= ($registerAttendance == 'OUT') ? 'Out' : 'In' ?> </a>
                                </li>
                            <?php } ?>
                            <li>
                                <a href="<?php echo $this->url('logout', ['action' => 'logout']); ?>">
                                    <i class="icon-key"></i> Log Out </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                    <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-quick-sidebar-toggler">
                        <a href="javascript:;" class="dropdown-toggle">
                            <i class="icon-logout"></i>
                        </a>
                    </li>
                    <!-- END QUICK SIDEBAR TOGGLER -->
                </ul>
            </div>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>