<div class="floating-profile" id="floating-profile">
    <div class="profile-header" id="profile-header">
        <label>
            User profile
        </label>
        <i class="pull-right fa fa-minus" id="min-max-btn">
        </i>
    </div>
    <div class="profile-body" id="profile-body">
        <div>
            <img height="50" width="70" class="profile-image" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image" />
        </div>
        <div>
            <label id="name">Ukesh</label>
        </div>
        <div>
            Contact No.:
            <label id="mobileNo">

            </label>
        </div>
        <div>
            Appointment Date:
            <label id="appDate">
            </label>
        </div>
        <div>
            App. Branch:
            <label id="appBranch">
            </label>
        </div>
        <div>
            App. Department:
            <label id="appDepartment">
            </label>
        </div>
        <div>
            App. Designation:
            <label id="appDesignation">
            </label>
        </div>
        <div>
            App. Position:
            <label id="appPosition">
            </label>
        </div>
        <div>
            App. Service Type:
            <label id="appServiceType">
            </label>
        </div>
        <div>
            App. Service Event Type:
            <label id="appServiceEventType">
            </label>
        </div>
        <div>
            Cur. Branch:
            <label id="branch">
            </label>
        </div>
        <div>
            Cur. Department:
            <label id="department">
            </label>
        </div>
        <div>
            Cur. Designation:
            <label id="designation">
            </label>
        </div>
        <div>
            Cur. Position:
            <label id="position">
            </label>
        </div>
        <div>
            Cur. Service Type:
            <label id="serviceType">
            </label>
        </div>
        <div>
            Cur. Service Event Type:
            <label id="serviceEventType">
            </label>
        </div>
    </div>
</div>
