<div class="floating-profile" id="floating-profile">
    <div class="profile-header" id="profile-header">
        <label>
            User profile
        </label>
        <i class="pull-right fa fa-minus" id="min-max-btn">
        </i>
    </div>
    <div class="profile-body" id="profile-body">
        <div>
            <img class="profile-image" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image" />
        </div>
        <div>
            <label id="name">Ukesh</label>
        </div>
        <div>
            <label id="gender">

            </label>   
        </div>
        <div>
            <label id="birthDate">

            </label>   
        </div>
        <div>
            <label id="mobileNo">

            </label>   
        </div>

    </div>
</div>
