<a href="javascript:;" class="page-quick-sidebar-toggler">
    <i class="icon-login"></i>
</a>
<div class="page-quick-sidebar-wrapper" data-close-on-body-click="false">
    <div class="page-quick-sidebar">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="javascript:;" data-target="#setting_tab" data-toggle="tab"> 
                    Settings
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane page-quick-sidebar-settings active" id="setting_tab">
                <div class="page-quick-sidebar-settings-list">
                    <h3 class="list-heading">General Settings</h3>
                    <ul class="list-items borderless">
                        <li> Enable Notifications
                            <input id="enableNotification" type="checkbox"   data-size="small" data-on-color="success" data-on-text="ON" data-off-color="default" data-off-text="OFF"> 
                        </li>
                        <li> Enable SMS Alerts
                            <input id="enableEmail" type="checkbox"   data-size="small" data-on-color="success" data-on-text="ON" data-off-color="default" data-off-text="OFF"> 
                        </li>
                        <li> Allow Tracking
                            <input type="checkbox" class="make-switch" data-size="small" data-on-color="info" data-on-text="ON" data-off-color="default" data-off-text="OFF"> 
                        </li>
                        <li> Log Errors
                            <input type="checkbox" class="make-switch" checked data-size="small" data-on-color="danger" data-on-text="ON" data-off-color="default" data-off-text="OFF"> </li>
                        <li> Auto Sumbit Issues
                            <input type="checkbox" class="make-switch" data-size="small" data-on-color="warning" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>