<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'branch-form');

$branchCode = $form->get('branchCode');
$branchName = $form->get('branchName');
$streetAddress = $form->get('streetAddress');
$telephone = $form->get('telephone');
$fax = $form->get('fax');
$email = $form->get('email');
$remarks = $form->get('remarks');
$countryId = $form->get('countryId');
$countryId->setValueOptions($countries);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('branch', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuBranch"]];echo json_encode($menu);?>;
</script>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-default customShadow">
            <div class="panel-heading bg-master-lighter">
                <div class="panel-title">
                    <h3 class="panel-title">Branch</h3>
                </div>
            </div>
            <div class="panel-body p-t-5">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group form-group-sm <?= empty($branchCode->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($branchCode); ?>
                    <?php print $this->formElement($branchCode); ?>
                </div>
                <?php print $this->formElementErrors()->render($branchCode, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($branchName->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($branchName); ?>
                    <?php print $this->formElement($branchName); ?>
                </div>
                <?php print $this->formElementErrors()->render($branchName, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm  <?= empty($streetAddress->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($streetAddress); ?>
                    <?php print $this->formElement($streetAddress); ?>
                </div>
                <?php print $this->formElementErrors()->render($streetAddress, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm form-group-default-select2">
                    <?php print $this->formLabel($countryId); ?>
                    <?php print $this->formElement($countryId); ?>
                </div>
                <?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($telephone->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($telephone); ?>
                    <?php print $this->formElement($telephone); ?>
                </div>
                <?php print $this->formElementErrors()->render($telephone, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($fax->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($fax); ?>
                    <?php print $this->formElement($fax); ?>
                </div>
                <?php print $this->formElementErrors()->render($fax, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm <?= empty($email->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($email); ?>
                    <?php print $this->formElement($email); ?>
                </div>
                <?php print $this->formElementErrors()->render($email, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-sm">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                </div>
                <?php print $this->formSubmit($submit); ?>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>