<?php
$this->headScript()->appendFile($this->basePath('js/setup/branch/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'branch-form');

$branchCode = $form->get('branchCode');
$branchName = $form->get('branchName');
$streetAddress = $form->get('streetAddress');
$telephone = $form->get('telephone');
$fax = $form->get('fax');
$email = $form->get('email');
$remarks = $form->get('remarks');
$countryId = $form->get('countryId');
$countryId->setValueOptions($countries);

//custom validatin message
if (key($telephone->getMessages()) == "regexNotMatch") {
    $telephone->setMessages(["regexNotMatch" => "Invalid Phone Number"]);
}
if (key($email->getMessages()) == "regexNotMatch") {
    $email->setMessages(["regexNotMatch" => "Invalid Email Address"]);
}


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('branch', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php
$menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuBranch"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Branch')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($branchCode->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($branchCode); ?>
                            <?php print $this->formElement($branchCode); ?>
                            <?php print $this->formElementErrors()->render($branchCode, ['class' => 'help-block error']); ?>
                        </div>
                    </div>


                    <div class="col-sm-4">
                        <div class="form-group <?= empty($branchName->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($branchName); ?>
                            <?php print $this->formElement($branchName); ?>
                            <?php print $this->formElementErrors()->render($branchName, ['class' => 'help-block error']); ?>
                        </div>
                    </div>


                    <div class="col-sm-4">
                        <div class="form-group <?= empty($streetAddress->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($streetAddress); ?>
                            <?php print $this->formElement($streetAddress); ?>
                            <?php print $this->formElementErrors()->render($streetAddress, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>


                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($countryId); ?>
                            <?php print $this->formElement($countryId); ?>
                            <?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block error']); ?>
                        </div>  
                    </div>


                    <div class="col-sm-4">
                        <div class="form-group <?= empty($telephone->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($telephone); ?>
                            <?php print $this->formElement($telephone); ?>
                            <?php print $this->formElementErrors()->render($telephone, ['class' => 'help-block error']); ?>
                        </div>       
                    </div>


                    <div class="col-sm-4">
                        <div class="form-group <?= empty($fax->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($fax); ?>
                            <?php print $this->formElement($fax); ?>
                            <?php print $this->formElementErrors()->render($fax, ['class' => 'help-block error']); ?>
                        </div>  
                    </div>
                </div>
                
                
                <div class=" row">
                    <div class="col-sm-4">
                <div class="form-group <?= empty($email->getMessages()) ? "" : "has-error" ?>">
                    <?php print $this->formLabel($email); ?>
                    <?php print $this->formElement($email); ?>
                    <?php print $this->formElementErrors()->render($email, ['class' => 'help-block error']); ?>
                </div>
                    </div>


                    <div class="col-sm-4">
                <div class="form-group <?= empty($remarks->getMessages()) ? "" : "has-error" ?>">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                </div>
                    </div>


                    <div class="col-sm-4">
                    </div>
                </div>


                <?php print $this->formSubmit($submit); ?>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>