<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'branch-form');

$branchCode = $form->get('branchCode');
$branchName = $form->get('branchName');
$streetAddress = $form->get('streetAddress');
$telephone = $form->get('telephone');
$fax = $form->get('fax');
$email = $form->get('email');
$remarks = $form->get('remarks');

$countryId=$form->get('countryId');
$countryId->setValueOptions($countries);

$submit = $form->get('submit');
$submit->setAttribute('value','UPDATE');

$form->setAttribute('action', $this->url('branch', ['action' => 'edit','id'=>$id]));

if ($this->messages) {
	print '<ul class="help-block bg-danger" style="background:#f3e250;">';
	foreach ($this->messages as $message) {
		print '<li>' . $message . '</li>';
	}
	print '</ul>';
}

$form->prepare();
?>
	<script>
		document.menu=<?php $menu = ["id" => "menuSetup","subMenu"=>["id"=>"subMenuBranch"]];echo json_encode($menu);?>;
	</script>

	<div class="row">
		<div class="col-sm-8 bg-light-color padding-30">
			<div class="row panel-title-head" style="margin-bottom: 2%">
				<div class="col-xs-9 col-sm-9 col-md-9">
					<div class="panel-heading padding-5">
						<h4>Edit Branch</h4>
					</div>
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 pull-right">
					<div class="pull-right m-b-10">
						<a href="<?= $this->url("branch",["action","index"])?>" style="margin-left:16%;">
							<button class="btn btn-default btn-cons"><i class="fa fa-arrow-left"></i>
								<span>Back </span></button>
						</a>
					</div>
				</div>
			</div>
			<div class="panel-body padding-0" >
				<?php
				print $this->form()->openTag($form);
				?>
				<div class="form-group form-group-default <?= empty($branchCode->getMessages()) ? "" : "error" ?>">
					<?php print $this->formLabel($branchCode); ?>
					<?php print $this->formElement($branchCode); ?>
				</div>
				<?php print $this->formElementErrors()->render($branchCode, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default <?= empty($branchName->getMessages()) ? "" : "error" ?>">
					<?php print $this->formLabel($branchName); ?>
					<?php print $this->formElement($branchName); ?>
				</div>
				<?php print $this->formElementErrors()->render($branchName, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default  <?= empty($streetAddress->getMessages()) ? "" : "error" ?>">
					<?php print $this->formLabel($streetAddress); ?>
					<?php print $this->formElement($streetAddress); ?>
				</div>
				<?php print $this->formElementErrors()->render($streetAddress, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default form-group-default-select2">
					<?php print $this->formLabel($countryId); ?>
					<?php print $this->formElement($countryId); ?>
				</div>
				<?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default <?= empty($telephone->getMessages()) ? "" : "error" ?>">
					<?php print $this->formLabel($telephone); ?>
					<?php print $this->formElement($telephone); ?>
				</div>
				<?php print $this->formElementErrors()->render($telephone, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default <?= empty($fax->getMessages()) ? "" : "error" ?>">
					<?php print $this->formLabel($fax); ?>
					<?php print $this->formElement($fax); ?>
				</div>
				<?php print $this->formElementErrors()->render($fax, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default <?= empty($email->getMessages()) ? "" : "error" ?>">
					<?php print $this->formLabel($email); ?>
					<?php print $this->formElement($email); ?>
				</div>
				<?php print $this->formElementErrors()->render($email, ['class' => 'help-block error']); ?>

				<div class="form-group form-group-default" >
					<?php print $this->formLabel($remarks); ?>
					<?php print $this->formElement($remarks); ?>
					<?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
				</div>


				<div class="">
					<?php print $this->formSubmit($submit); ?>
				</div>

				<?php
					print $this->form()->closeTag();
				?>
			</div>
			<div class="col-sm-2">
			</div>

		</div>
	</div>
