<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('js/setup/branch/index.js'));
?>


<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.branches =<?= json_encode($branches) ?>;
    document.menu =<?php
$menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuBranch"]];
echo json_encode($menu);
?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Branch')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('branch', ['action' => 'add']) ?>" id="sample_editable_1_new" class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a id="saveAsPdfBtn" href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="branchTable">
    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
    <tr>
        <td>    
            #: BRANCH_CODE #
            </td>
        <td>
            #: BRANCH_NAME #  
        </td>
        <td>
            #: STREET_ADDRESS #
        </td>
        <td>
            #: TELEPHONE #
        </td>
        <td>
        #: EMAIL #
        </td>
        <td>
            <a class            =""
               href="<?= $this->url("branch", ["action" => "edit"]) ?>/#:BRANCH_ID #">
                Edit
            </a> /
            <a class=""
               href="<?= $this->url("branch", ["action" => "delete"]); ?>/#:BRANCH_ID #">
                Delete
            </a>
        </td>

    </tr>
    </script>
    <script type="text/x-kendo-template" id="toolbar-template">
        <div class="k-header k-grid-toolbar">

        <a class="k-button k-button-icontext k-grid-excel" href="javascript">
        <i class="fa fa-file-excel-o"></i>
        </a>

        <a class="k-button k-button-icontext k-grid-pdf" href="javas        cript">
        <i class="fa fa-file-pdf-o"></i>
        </a>
        </div>
    </script>
</div>

