<?php
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

?>
<a href="<?= $this->url('branch',['action'=>'add'])?>">Add New</a>

<table role="grid" class="table table-hover dataTable no-footer" id="employeelist">

    <thead>
    <tr role="row">
        <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1" rowspan="1"
            aria-controls="basicTable" tabindex="0" class="sorting_desc" style="width: 218px;">
            Branch Name
        </th>
     
        <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="basicTable"
            tabindex="0" class="sorting" style="width: 219px;">Telephone
        </th>
        <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="basicTable"
            tabindex="0" class="sorting" style="width: 219px;">Fax
        </th>
        <th aria-label="Places: activate to sort column ascending" colspan="1" rowspan="1" aria-controls="basicTable"
            tabindex="0" class="sorting" style="width: 219px;">Email
        </th>
   
        <th aria-label="Last Update: activate to sort column ascending" colspan="1" rowspan="1"
            aria-controls="basicTable" tabindex="0" class="sorting" style="width: 155px;">
            Action
        </th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($branches as $branch): ?>
        <tr role="row">
            <td class="v-align-middle sorting_1">
                <p>
                    <?php print $this->escapeHtml($branch->getBranchName()) ?>
                </p>
            </td>
            <td class="v-align-middle sorting_1">
                <p>
                    <?php print $this->escapeHtml($branch->getTelephone()) ?>
                </p>
            </td>
            <td class="v-align-middle sorting_1">
                <p>
                    <?php print $this->escapeHtml($branch->getFax()) ?>
                </p>
            </td>
            <td class="v-align-middle sorting_1">
                <p>
                    <?php print $this->escapeHtml($branch->getEmail()) ?>
                </p>
            </td>
            
            <td class="v-align-middle sorting_1">
                <a href="<?= $this->url("branch", ["action" => "edit", "id" => $branch->getBranchId()]) ?>">Edit</a>
                <a href="<?= $this->url("branch",["action"=>"delete","id"=>$branch->getBranchId()]); ?>" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
            </td>
        </tr>

    <?php endforeach; ?>

    </tbody>
</table>
