<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'))
        ->appendFile($this->basePath('js/setup/branch/index.js'));
?>


<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.branches =<?= json_encode($branches) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Branch')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">

    <div class="portlet light bg-inverse">

        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('branch', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id ="export" class="hris-export-to-excel" hris-export-to-excel-target="branchTable">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="branchTable">
        </div>
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td> 
        #: (BRANCH_NAME == null) ? '-' : BRANCH_NAME #
        </td>
        <td>
        #: (STREET_ADDRESS == null) ? '-' : STREET_ADDRESS #
        </td>
        <td>
        #: (TELEPHONE == null) ? '-' : TELEPHONE #
        </td>
        <td>
        #: (EMAIL == null) ? '-' : EMAIL #
        </td>
        <td>
        #: (COMPANY_NAME == null) ? '-' : COMPANY_NAME#
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("branch", ["action" => "edit"]) ?>/#:BRANCH_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="confirmation btn-delete"
        href="<?= $this->url("branch", ["action" => "delete"]); ?>/#:BRANCH_ID #" id="bs_#:BRANCH_ID #" style="height:17px;"> 
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>

        </tr>
    </script>
</div>

