CREATE TABLE HR_APPRAISAL_TYPE
(
	APPRAISAL_TYPE_CODE	         		NUMBER  NOT NULL,	
	SERVICE_TYPE_ID						NUMBER,
	APPRAISAL_TYPE_EDESC           		VARCHAR2(100 BYTE)      NOT NULL,
	APPRAISAL_TYPE_NDESC           		VARCHAR2(400 BYTE)      DEFAULT NULL, 
	COMPANY_CODE          				VARCHAR2(30 BYTE),	
	BRANCH_CODE           				VARCHAR2(30 BYTE),
	CREATED_BY            				VARCHAR2(30 BYTE),
	CREATED_DATE          				DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_TYPE PRIMARY KEY (APPRAISAL_TYPE_CODE),
	CONSTRAINT FK_APPRAISAL_TYPE FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES HR_SERVICE_TYPES(SERVICE_TYPE_ID),
);


CREATE TABLE HR_APPRAISAL_STAGE
(
	STAGE_CODE            NUMBER                  NOT NULL,
	STAGE_EDESC           VARCHAR2(100 BYTE)      NOT NULL,
	STAGE_NDESC           VARCHAR2(400 BYTE)      DEFAULT NULL,
	START_DATE          	VARCHAR2(200 BYTE)      DEFAULT NULL,
	END_DATE		        VARCHAR2(30 BYTE)       DEFAULT NULL,
	ORDER_NO				NUMBER,
	COMPANY_CODE          VARCHAR2(30 BYTE),	
	BRANCH_CODE           VARCHAR2(30 BYTE),
	CREATED_BY            VARCHAR2(30 BYTE),
	CREATED_DATE          DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_STAGE PRIMARY KEY (STAGE_CODE)
);


CREATE TABLE HR_APPRAISAL_HEADING
(
	HEADING_CODE            NUMBER                  NOT NULL,
	APPRAISAL_TYPE_CODE		NUMBER NOT NULL,
	PERCENTAGE				NUMBER(5,2) DEFAULT 0,
	HEADING_EDESC           VARCHAR2(400 BYTE)      NOT NULL,
	HEADING_NDESC           VARCHAR2(800 BYTE)      DEFAULT NULL, 
	COMPANY_CODE          VARCHAR2(30 BYTE),	
	BRANCH_CODE           VARCHAR2(30 BYTE),
	CREATED_BY            VARCHAR2(30 BYTE),
	CREATED_DATE          DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_HEADING PRIMARY KEY (HEADING_CODE),
	CONSTRAINT FK_APPRAISAL_HEADING FOREIGN KEY (APPRAISAL_TYPE_CODE) REFERENCES HR_APPRAISAL_TYPE(APPRAISAL_TYPE_CODE),
);



CREATE TABLE HR_APPRAISAL_SETUP
(
	APPRAISAL_CODE        NUMBER                  NOT NULL,
	APPRAISAL_EDESC       VARCHAR2(400 BYTE)      NOT NULL,
	APPRAISAL_NDESC       VARCHAR2(800 BYTE)      DEFAULT NULL, 
	APPRAISAL_TYPE_CODE	NUMBER,
	START_DATE			DATE,
	END_DATE				DATE,
	CURRENT_STAGE_CODE	NUMBER,
	REMARKS				VARCHAR2(200 BYTE),
	COMPANY_CODE          VARCHAR2(30 BYTE),	
	BRANCH_CODE           VARCHAR2(30 BYTE),
	CREATED_BY            VARCHAR2(30 BYTE),
	CREATED_DATE          DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_SETUP PRIMARY KEY (APPRAISAL_CODE),	
	CONSTRAINT FK_APPRAISAL_SETUP1 FOREIGN KEY (CURRENT_STAGE_CODE) REFERENCES HR_APPRAISAL_STAGE(STAGE_CODE),
	CONSTRAINT FK_APPRAISAL_SETUP2 FOREIGN KEY (APPRAISAL_TYPE_CODE) REFERENCES HR_APPRAISAL_TYPE(APPRAISAL_TYPE_CODE)
);


CREATE TABLE HR_APPRAISAL_QUESTION
(
	QUESTION_CODE       NUMBER                  NOT NULL,
	HEADING_CODE		NUMBER NOT NULL,
	QUESTION_EDESC      VARCHAR2(400 BYTE)      NOT NULL,
	QUESTION_NDESC      VARCHAR2(800 BYTE)      DEFAULT NULL, 
	ANSWER_TYPE			VARCHAR2(30 BYTE) CHECK( ANSWER_TYPE IN ('TEXT','NUMBER','PERCENTAGE','CHECKBOX','RADIO')), 
	APPRAISEE_FLAG      VARCHAR2(1 BYTE),	
	APPRAISER_FLAG      VARCHAR2(1 BYTE),
	REVIEWER_FLAG 		VARCHAR2(1 BYTE),
	APPRAISEE_RATING	VARCHAR2(1 BYTE),
	APPRAISER_RATING	VARCHAR2(1 BYTE),
	REVIEWER_RATING		VARCHAR2(1 BYTE),
	MAX_VALUE			VARCHAR2(3 BYTE),
	MIN_VALUE			VARCHAR2(3 BYTE),
	NEXT_QUESTION_CODE	NUMBER DEFAULT NULL,
	CREATED_BY          VARCHAR2(30 BYTE),
	CREATED_DATE        DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_QUESTION PRIMARY KEY (QUESTION_CODE),
	CONSTRAINT FK_APPRAISAL_QUESTION FOREIGN KEY (HEADING_CODE) REFERENCES HR_APPRAISAL_HEADING(HEADING_CODE)
);


CREATE TABLE HR_APPRAISAL_STAGE_QUESTIONS
(
	QUESTION_CODE       NUMBER    NOT NULL,
	STAGE_CODE			NUMBER NOT NULL
	CONSTRAINT FK_APP_STAGE_QUE FOREIGN KEY (STAGE_CODE) REFERENCES HR_APPRAISAL_STAGE(STAGE_CODE),
	CONSTRAINT FK_APP_STAGE_QUE1 FOREIGN KEY (QUESTION_CODE) REFERENCES HR_APPRAISAL_QUESTION(QUESTION_CODE)
);

CREATE TABLE HR_APPRAISAL_QUESTION_OPTIONS
(
	OPTION_CODE			NUMBER NOT NULL,
	QUESTION_CODE       NUMBER                  NOT NULL,
	OPTION_EDESC        VARCHAR2(400 BYTE)      NOT NULL,
	OPTION_NDESC        VARCHAR2(800 BYTE)      DEFAULT NULL,   
	CREATED_BY          VARCHAR2(30 BYTE),
	CREATED_DATE        DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_HEADING PRIMARY KEY (HEADING_CODE)
);


CREATE TABLE HR_EMPLOYEE_APPRAISAL
(
	APPRAISAL_CODE		NUMBER NOT NULL,
	EMPLOYEE_ID         NUMBER  NOT NULL,
	STAGE_CODE        	NUMBER(6) NOT NULL,  
	USER_ID				NUMBER(6),
	STATUS				VARCHAR2(30 BYTE)  CHECK( STATUS IN ('AGREEED','DISAGREED')),  
	REMARKS				VARCHAR2(100 BYTE) DEFAULT NULL,
	CREATED_BY          VARCHAR2(30 BYTE),
	CREATED_DATE        DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_HEADING PRIMARY KEY (HEADING_CODE)
);


CREATE TABLE HR_APPRAISAL_ORDER
(
  APPRAISAL_CODE		NUMBER NOT NULL,
  EMPLOYEE_ID         	NUMBER  NOT NULL, 
  REPORT_TO				NUMBER(6),
  APP_INDEX				NUMBER(1), /* 1: FOR APPRAISER AND 2 FOR REVIEWER IN DEFAULT */
  CREATED_BY            VARCHAR2(30 BYTE),
  CREATED_DATE          DATE,
  LAST_MODIFIED_BY	 	VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE	DATE,
  CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
  APPROVED_BY			VARCHAR2(30 BYTE),
  APPROVED_DATE			DATE,
  APPROVED				VARCHAR2(1 BYTE) DEFAULT 'N',
  DELETED_FLAG        	CHAR(1 BYTE),
  CONSTRAINT PK_APPRAISAL_HEADING PRIMARY KEY (HEADING_CODE)
);



CREATE TABLE HR_APPRAISAL_ANSWER
(
	APPRAISAL_CODE		NUMBER NOT NULL,
	QUESTION_CODE       NUMBER  NOT NULL,
	EMPLOYEE_ID        	NUMBER(6) NOT NULL,
	USER_ID				NUMBER(6) NOT NULL,
	ANSWER				VARCHAR(2000 BYTE) 		NOT NULL,   
	RATING				NUMBER(5,2),
	STAGE_CODE			NUMBER,
	REMARKS				VARCHAR2(100 BYTE) DEFAULT NULL,
	STATUS				VARCHAR2(30 BYTE)  CHECK( STATUS IN ('FORWARDED','APPROVED')),  
	CREATED_BY          VARCHAR2(30 BYTE),
	CREATED_DATE        DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_HEADING PRIMARY KEY (HEADING_CODE)
);


CREATE TABLE HR_APPRAISAL_ASSIGN
(
	APPRAISAL_CODE		NUMBER NOT NULL,
	EMPLOYEE_CODE       NUMBER  NOT NULL,
	APPRAISER_CODE      NUMBER,
	REVIEWER_CODE		NUMBER
	REMARKS				VARCHAR2(100 BYTE) DEFAULT NULL,
	STATUS				VARCHAR2(30 BYTE)  CHECK( STATUS IN ('FORWARDED','APPROVED')),  
	CREATED_BY          VARCHAR2(30 BYTE),
	CREATED_DATE        DATE,
	LAST_MODIFIED_BY	VARIANCE(30 BYTE),
	LAST_MODIFIED_DATE	DATE,
	CHECKED				VARCHAR2(1 BYTE) DEFAULT 'N',
	APPROVED_BY			VARCHAR2(30 BYTE),
	APPROVED_DATE		DATE,
	APPROVED			VARCHAR2(1 BYTE) DEFAULT 'N',
	DELETED_FLAG        CHAR(1 BYTE),
	CONSTRAINT PK_APPRAISAL_HEADING PRIMARY KEY (HEADING_CODE)
);



CREATE TABLE AUD_HR_APPRAISAL_ANSWER
(
  SNO		        	NUMBER(3) NOT NULL,
  APPRAISAL_CODE		NUMBER NOT NULL,
  QUESTION_CODE         NUMBER  NOT NULL,
  EMPLOYEE_ID        	NUMBER(6) NOT NULL,
  USER_ID				NUMBER(6) NOT NULL,
  ANSWER				VARCHAR(2000 BYTE) 		NOT NULL,   
  RATING				NUMBER(5,2),
  REMARKS				VARCHAR2(100 BYTE) DEFAULT NULL,
  CREATED_BY            VARCHAR2(30 BYTE),
  CREATED_DATE          DATE,
  LAST_MODIFIED_BY		VARIANCE(30 BYTE),
  LAST_MODIFIED_DATE	DATE,
  APPROVED_BY			VARCHAR2(30 BYTE),
  APPROVED_DATE			DATE,
  DELETED_FLAG          CHAR(1 BYTE)
);

ALTER TABLE AUD_HR_APPRAISAL_ANSWER ADD CONSTRAINT PK_AUD_HR_APP_ANS PRIMARY KEY
        (SNO, APPRAISAL_CODE);


/*TRIGGER TO MAINTAION ANSWER CHANGE HISTORY */
CREATE OR REPLACE TRIGGER TRG_HR_APPRAISAL_ANSWER
BEFORE INSERT OR DELETE OR UPDATE ON HR_APPRAISAL_ANSWER
FOR EACH ROW
DECLARE

    V_ROW HR_APPRAISAL_ANSWER%ROWTYPE;
    V_AUDIT AUD_HR_APPRAISAL_ANSWER%ROWTYPE;

BEGIN

    SELECT MAX(NVL(SNO,0))+1  INTO V_AUDIT.SNO FROM HR_APPRAISAL_ANSWER WHERE APPRAISAL_CODE = :NEW.APPRAISAL_CODE;

    IF NOT DELETING THEN

        :NEW.CREATED_DATE := SYSDATE;
		:NEW.LAST_MODIFIED_DATE := SYSDATE;		
		:NEW.APPROVED_DATE := SYSDATE;

    END IF;

    IF INSERTING OR UPDATING THEN
				
     	V_AUDIT.SNO := :NEW.SNO;
        V_AUDIT.APPRAISAL_CODE	:= :NEW.APPRAISAL_CODE;
		V_AUDIT.QUESTION_CODE	:= :NEW.QUESTION_CODE;
		V_AUDIT.EMPLOYEE_ID := :NEW.EMPLOYEE_ID;
		V_AUDIT.USER_ID	:= :NEW.USER_ID;
		V_AUDIT.ANSWER	 := :NEW.ANSWER;
		V_AUDIT.RATING	:= :NEW.RATING;
		V_AUDIT.REMARKS := :NEW.REMARKS;
		V_AUDIT.COMPANY_CODE := :NEW.COMPANY_CODE;
		V_AUDIT.BRANCH_CODE := :NEW.BRANCH_CODE;
		V_AUDIT.CREATED_DATE :=  SYSDATE;
		V_AUDIT.LAST_MODIFIED_BY := :NEW.LAST_MODIFIED_BY;
		V_AUDIT.LAST_MODIFIED_DATE :=  SYSDATE;
		V_AUDIT.APPROVED_BY := :NEW.APPROVED_BY;
		V_AUDIT.APPROVED_DATE :=  SYSDATE;	
        V_AUDIT.DELETED_FLAG := :NEW.DELETED_FLAG;

    ELSIF DELETING THEN

       V_AUDIT.SNO := :OLD.SNO;
        V_AUDIT.APPRAISAL_CODE	:= :OLD.APPRAISAL_CODE;
		V_AUDIT.QUESTION_CODE	:= :OLD.QUESTION_CODE;
		V_AUDIT.EMPLOYEE_ID := :OLD.EMPLOYEE_ID;
		V_AUDIT.USER_ID	:= :OLD.USER_ID;
		V_AUDIT.ANSWER	 := :OLD.ANSWER;
		V_AUDIT.RATING	:= :OLD.RATING;
		V_AUDIT.REMARKS := :OLD.REMARKS;
		V_AUDIT.COMPANY_CODE := :OLD.COMPANY_CODE;
		V_AUDIT.BRANCH_CODE := :OLD.BRANCH_CODE;
		V_AUDIT.CREATED_DATE :=  SYSDATE;
		V_AUDIT.LAST_MODIFIED_BY := :OLD.LAST_MODIFIED_BY;
		V_AUDIT.LAST_MODIFIED_DATE :=  SYSDATE;
		V_AUDIT.APPROVED_BY := :OLD.APPROVED_BY;
		V_AUDIT.APPROVED_DATE :=  SYSDATE;	
        V_AUDIT.DELETED_FLAG := :OLD.DELETED_FLAG;
		
    END IF;

    INSERT INTO AUD_HR_APPRAISAL_ANSWER VALUES V_AUDIT;

END TRG_HR_APPRAISAL_ANSWER;
/
		