<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuAcademicProgram"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\academicProgram')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('academicProgram', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <!--                        <i class="fa fa-plus"></i>-->
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <table class="table" id="dataTable">
        <thead>
        <tr role="row">
            <th>
                Academic Program Code
            </th>
            <th>
                Academic Program Name
            </th>
            <th>
                Action
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($programs as $list): ?>
            <tr role="row">
                <td>
                    <?php print $this->escapeHtml($list->ACADEMIC_PROGRAM_CODE); ?>
                </td>
                <td>
                    <?php print $this->escapeHtml($list->ACADEMIC_PROGRAM_NAME); ?>
                </td>
                <td>
                    <a
                        href="<?= $this->url("academicProgram", ["action" => "edit", "id" => $list->ACADEMIC_PROGRAM_ID]); ?>">
                        Edit
                    </a> /
                    <a
                        href="<?= $this->url("academicProgram", ["action" => "delete", "id" => $list->ACADEMIC_PROGRAM_ID]); ?>">
                        Delete
                    </a>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>