
<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/search.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/ShiftAssign/add.js'));

?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.shiftList =<?php echo json_encode($shiftList); ?>;
    document.employeeListWS = '<?= $this->url("shiftassign", ["action" => "employeeListWS"]) ?>';
    document.addWs = '<?= $this->url("shiftassign", ["action" => "addWs"]) ?>';
    document.employeeShiftsWS = '<?= $this->url("shiftassign", ["action" => "employeeShiftsWS"]) ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
</script>sear
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\shiftassign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Search</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Company</label>
                    <select multiple class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Branch</label>
                    <select multiple class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select multiple class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Position</label>
                    <select multiple class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <label>Service Type</label>
                    <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Service Event Type</label>
                    <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee Type</label>
                    <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select multiple class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button  ng-click="view()" id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="shiftAssignTable">
    </div>
    <div class="portlet light margin-top-10" id="bulkActionDiv" style="display: none;">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Action </span>
            </div>
        </div>
        <div class="portlet-body">
            <div  class="row"  >
                <div class="col-sm-2">
                    <select class="form-control" id="shiftId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="fromDate" class="form-control" placeholder="From Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="toDate" class="form-control" placeholder="To Date"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliToDate"  class="form-control" placeholder="To Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <button id="bulkAdd" class="btn btn-sm btn-danger pull-right">Add</button>
                </div>
            </div>
        </div>
    </div>

</div>