<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));


$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/spin.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/ladda.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/ShiftAssign/shiftController.js'));
?>

<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>sear
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\shiftassign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="" ng-app="hris" ng-controller="shiftAssignController">
    <div class="margin-top-20  formbg mgap">
        <div class="row">
            <div class="col-sm-4 marginspace">
                <?php print $this->formLabel($branches); ?>
                <?php print $this->formElement($branches); ?>
            </div>
            <div class="col-sm-4 marginspace">
                <?php print $this->formLabel($departments); ?>
                <?php print $this->formElement($departments); ?>

            </div>
            <div class="col-sm-4 marginspace">
                <?php print $this->formLabel($designations); ?>
                <?php print $this->formElement($designations); ?>
            </div>
            <div class="col-sm-4 marginspace">
                <?php print $this->formLabel($positions); ?>
                <?php print $this->formElement($positions); ?>
            </div>
            <div class="col-sm-4 marginspace">
                <?php print $this->formLabel($serviceTypes); ?>
                <?php print $this->formElement($serviceTypes); ?>
            </div>


            <div class="col-sm-2">

                <button ng-click="view()" id="viewEmployees" class=" btn btn-default  i-search form-control" style="margin-top:21px !important">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div> 
    <div class="margin-top-20">
        <table class="table table-striped table-bordered table-hover no-footer custometbletwo">
            <thead>
                <tr>
                    <th>
                        Employee
                    </th>
                    <th>
                        Branch
                    </th>
                    <th>
                        Department
                    </th>
                    <th>
                        Designation
                    </th>
                    <th>
                        Position
                    </th>
                    <th>
                        Service Type
                    </th>
                    <th>
                        Shift Assigned
                    </th>
                    <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                        <div class="th-inner ">
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                <span></span>
                            </label>
                        </div>
                        <div class="fht-cell" style="width: 46px;"></div>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="employeeShift in employeeShiftList">
                    <td>
                        <span ng-bind="employeeShift.FIRST_NAME"></span>
                        <span ng-bind="employeeShift.MIDDLE_NAME"></span>
                        <span ng-bind="employeeShift.LAST_NAME"></span>
                    </td>
                    <td ng-bind="employeeShift.BRANCH_NAME">
                    </td>
                    <td ng-bind="employeeShift.DEPARTMENT_NAME">

                    </td>
                    <td ng-bind="employeeShift.DESIGNATION_TITLE">
                    </td>
                    <td ng-bind="employeeShift.POSITION_NAME">
                    </td>
                    <td ng-bind="employeeShift.SERVICE_TYPE_NAME">
                    </td>
                    <td ng-bind="employeeShift.SHIFT_ENAME || 'Default'">

                    </td>
                    <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                        <div class="th-inner ">
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input class="" ng-model="employeeShift.checked" type="checkbox"
                                       ng-change="checkUnit(item.checked)"/>
                                <span></span>
                            </label>
                        </div>
                        <div class="fht-cell" style="width: 46px;"></div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="row" ng-show="assignShowHide">
        <div class="col-sm-offset-8 col-sm-2">
            <?php print $this->formElement($shiftFormElement); ?>
        </div>
        <div class="col-sm-2 ">
            <button class="pull-right btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="assignBtn" ng-click="assign()">
                Assign
                <i class="fa fa-edit"></i>
            </button>
        </div>
    </div>
</div>