
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/other/grade-change/index.js'));
?>


<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.gradeChangeList = [
        {
            EMPLOYEE_NAME: "Ukesh Gaiju",
            APPOINTMENT_DATE: "01-Jan-2016",
            CURRENT_SERVICE: "Developer",
            EFFECTIVE_DATE: "3-Mar-2017",
            LAST_GRADE: "Mid",
            NEW_GRADE: "Senior",
            GRADE_EFFECTIVE_DATE: "4-Jul-2017",
        },
        {
            EMPLOYEE_NAME: "Subin Manandhar",
            APPOINTMENT_DATE: "01-Jan-2015",
            CURRENT_SERVICE: "Developer",
            EFFECTIVE_DATE: "3-Apr-2017",
            LAST_GRADE: "Mid",
            NEW_GRADE: "Senior",
            GRADE_EFFECTIVE_DATE: "4-Jul-2017",
        }
    ];
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\grade-change')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="#" id="sample_editable_1_new" class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="gradeChangeTable">
    </div>
    <div class="table-toolbar margin-top-20">
        <div class="row">
            <div class="col-md-12">
                <div class="btn-group pull-right">
                    <a href="#" id="sample_editable_1_new" class="btn green"> Save
                        <i class="fa fa-save"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (EMPLOYEE_NAME == null) ? '-' : EMPLOYEE_NAME #
        </td>
        <td> 
        #: (APPOINTMENT_DATE == null) ? '-' : APPOINTMENT_DATE #
        </td>
        <td>
        #: (CURRENT_SERVICE== null) ? '-' : CURRENT_SERVICE #
        </td>
        <td>
        #: (EFFECTIVE_DATE== null) ? '-' : EFFECTIVE_DATE #
        </td>
        <td>
        #: (LAST_GRADE== null) ? '-' : LAST_GRADE #
        </td>
        <td>
        #: (NEW_GRADE== null) ? '-' : LAST_GRADE #
        </td>
        <td>
        #: (GRADE_EFFECTIVE_DATE== null) ? '-' : GRADE_EFFECTIVE_DATE #
        </td>
        <td>
        <input type="checkbox">
        </td>

        </tr>
    </script>
</div>

