<?php
$this->headScript()->appendFile($this->basePath('js/system/attendance-device/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceDeviceForm');


$deviceName=$form->get('deviceName');
$deviceIp=$form->get('deviceIp');
$deviceLocation=$form->get('deviceLocation');
$companyId=$form->get('companyId');
$companyId->setValueOptions($company);
$branchId=$form->get('branchId');






$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('AttendanceDevice', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
        document.branches =<?php echo json_encode($branch); ?>;
    </script>


<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\AttendanceDevice')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


 <div class="row margin-top-20">
        <div class="col-sm-12">
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>New Entry
                    </div>
                </div>
                <div class="portlet-body">
                    <?php print $this->form()->openTag($form); ?>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($deviceName); ?>
                                <?php print $this->formElement($deviceName); ?>
                                <?php print $this->formElementErrors()->render($deviceName, ['class' => 'help-block']); ?>
                                <span class="errorMsg" style="font-size:11px; color:red;"></span>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($deviceIp); ?>
                                <?php print $this->formElement($deviceIp); ?>
                                <?php print $this->formElementErrors()->render($deviceIp, ['class' => 'help-block']); ?>
                                <span class="errorMsg" style="font-size:11px; color:red;"></span>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($deviceLocation); ?>
                                <?php print $this->formElement($deviceLocation); ?>
                                <?php print $this->formElementErrors()->render($deviceLocation, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>


                    <div class=" row">

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($companyId); ?>
                                <?php print $this->formElement($companyId); ?>
                                <?php print $this->formElementErrors()->render($companyId, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($branchId); ?>
                                <?php print $this->formElement($branchId); ?>
                                <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            
                        </div>
                    </div>

                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
