<?php
$this->headScript()->appendFile($this->basePath('js/system/attendance-device/add.js'));

$deviceIp = $form->get('deviceIp');
$deviceCompany = $form->get('deviceCompany');
$deviceName = $form->get('deviceName');
$companyId = $form->get('companyId');
$branchId = $form->get('branchId');
$deviceLocation = $form->get('deviceLocation');
$isActive = $form->get('isActive');
$purpose = $form->get('purpose');
$submit = $form->get('submit');
$branchManager= $form->get('branchManager');
$form->setAttribute('action', $this->url('AttendanceDevice', ['action' => 'edit', 'id' => $id]));
$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\AttendanceDevice')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($deviceIp); ?>
                            <?php print $this->formElement($deviceIp); ?>
                            <?php print $this->formElementErrors()->render($deviceIp, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4 ">
                        <div class="form-group">
                            <?php print $this->formLabel($deviceCompany); ?>
                            <?php print $this->formElement($deviceCompany); ?>
                            <?php print $this->formElementErrors()->render($deviceCompany, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($deviceName); ?>
                            <?php print $this->formElement($deviceName); ?>
                            <?php print $this->formElementErrors()->render($deviceName, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>


                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($companyId); ?>
                            <?php print $this->formElement($companyId); ?>
                            <?php print $this->formElementErrors()->render($companyId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($branchId); ?>
                            <?php print $this->formElement($branchId); ?>
                            <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($deviceLocation); ?>
                            <?php print $this->formElement($deviceLocation); ?>
                            <?php print $this->formElementErrors()->render($deviceLocation, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($isActive); ?>
                            <?php print $this->formElement($isActive); ?>
                            <?php print $this->formElementErrors()->render($isActive, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($purpose); ?>
                            <?php print $this->formElement($purpose); ?>
                            <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($branchManager); ?>
                            <?php print $this->formElement($branchManager); ?>
                            <?php print $this->formElementErrors()->render($branchManager, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
