<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/system/attendance-device/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));

//echo '<pre>';
//print_r($attendanceDevice);
//die();
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
    
    <script>
    document.attendanceDevice=<?= json_encode($attendanceDevice); ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\AttendanceDevice')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('AttendanceDevice', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="attendanceDevice">
    </div>
	</div>
    


    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (DEVICE_NAME == null) ? ' ' : DEVICE_NAME #
        </td>
        <td>
        #: (DEVICE_IP == null) ? ' ' : DEVICE_IP #
        </td>
        <td>
        #: (PING_STATUS == null) ? '-' : PING_STATUS #
        </td>
        <td>
        #: (DEVICE_LOCATION == null) ? ' ' : DEVICE_LOCATION #
        </td>
        <td>
        #: (ISACTIVE == null) ? '-' : ISACTIVE #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("AttendanceDevice", ["action" => "edit"]); ?>/#:DEVICE_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
         <a class="btn-delete confirmation"
        href="<?= $this->url("AttendanceDevice", ["action" => "delete"]); ?>/#:DEVICE_ID #" id="bs_#:DEVICE_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>
    
  
</div>