<div class="tab-pane" id="tab9">
    <div class="col-md-offset-2 col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-8 margin gapspaceing">
        <div class="identification-infomation">  
            <p>
                <i class="fa fa-plus-circle ticon" aria-hidden="true"></i>
                Additional Infomation
            </p>
            <div class="row clearfix e-setup">
                <div class="col-md-12">
                    <div id="rolePanel">
                        <ul id="roleList">
                            <li>
                                Leave Assign
                                <a href="<?php echo $this->url("leaveassign", ["action" => "assign", "eid" => $id]) ?>">
                                    <i class="fa fa-arrow-circle-right pull-right" aria-hidden="true" style="font-size:20px; line-height:20px!important;"></i>
                                </a>
                            </li>
                            <li>
                                Training Assign
                                <a href="<?php echo $this->url("trainingAssign", ["action" => "assign", "employeeId" => $id]) ?>">
                                    <i class="fa fa-arrow-circle-right pull-right" aria-hidden="true" style="font-size:20px; line-height:20px!important;"></i>
                                </a>
                            </li>
                            <li>
                                Appraisal Assign
                                <a href="<?php echo $this->url("appraisalAssign", ["action" => "index", "id" => $id]) ?>">
                                    <i class="fa fa-arrow-circle-right pull-right" aria-hidden="true" style="font-size:20px; line-height:20px!important;"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="row bottomgap">
                            <div class="form-group">
                                <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                    <label> Shift </label>
                                </div>
                                <div class="col-xs-6 col-sm-6 cgap-4">
                                    <select required="required" name="shift">
                                        <?php
                                        foreach ($shifts as $shiftKey => $shiftValue) {
                                            $shiftSelected = ($shiftId == $shiftKey) ? "selected" : "";
                                            ?>
                                            <option  value="<?php echo $shiftKey; ?>" <?php echo $shiftSelected; ?>><?php echo $shiftValue; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>