<?php
$formOne->setAttribute('role', 'form');
$formOne->setAttribute('id', 'form1');

/**
 * Personal Information
 */
$companyId = $formOne->get('companyId');
$employeeCode = $formOne->get("employeeCode");
$firstName = $formOne->get("firstName");
$middleName = $formOne->get("middleName");
$lastName = $formOne->get("lastName");
$nameNepali = $formOne->get("nameNepali");
$birthDate = $formOne->get('birthDate');
$genderId = $formOne->get('genderId');
$bloodGroupId = $formOne->get('bloodGroupId');
$religionId = $formOne->get('religionId');
$socialActivity = $formOne->get('socialActivity');
$telephoneNo = $formOne->get('telephoneNo');
$mobileNo = $formOne->get('mobileNo');
$extensionNo = $formOne->get('extensionNo');
$emailOfficial = $formOne->get('emailOfficial');
$emailPersonal = $formOne->get('emailPersonal');
$socialNetwork = $formOne->get('socialNetwork');
$countryId = $formOne->get('countryId');
$abroadAddress = $formOne->get('abroadAddress');

/**
 * Emergency Contact Information
 */
$emergContactName = $formOne->get('emergContactName');
$emergContactNo = $formOne->get('emergContactNo');
$emergContactAddress = $formOne->get('emergContactAddress');
$emergContactRelationship = $formOne->get('emergContactRelationship');


/*
 * Address Information
 */
$addrPermHouseNo = $formOne->get('addrPermHouseNo');
$addrPermWardNo = $formOne->get('addrPermWardNo');
$addrPermStreetAddress = $formOne->get('addrPermStreetAddress');
$addrPermVdcMunicipalityId = $formOne->get('addrPermVdcMunicipalityId');
$addrPermDistrictId = $formOne->get('addrPermDistrictId');
$addrPermZoneId = $formOne->get('addrPermZoneId');
$addrPermProvinceId = $formOne->get('addrPermProvinceId');

$addrTempHouseNo = $formOne->get('addrTempHouseNo');
$addrTempWardNo = $formOne->get('addrTempWardNo');
$addrTempStreetAddress = $formOne->get('addrTempStreetAddress');
$addrTempVdcMunicipalityId = $formOne->get('addrTempVdcMunicipalityId');
$addrTempDistrictId = $formOne->get('addrTempDistrictId');
$addrTempZoneId = $formOne->get('addrTempZoneId');
$addrTempProvinceId = $formOne->get('addrTempProvinceId');

//Custom validation
if (key($mobileNo->getMessages()) == "regexNotMatch") {
    $mobileNo->setMessages(["regexNotMatch" => "Invalid Mobile Number"]);
}
if (key($emailOfficial->getMessages()) == "regexNotMatch") {
    $emailOfficial->setMessages(["regexNotMatch" => "Invalid Email Address"]);
}
if (key($emailPersonal->getMessages()) == "regexNotMatch") {
    $emailPersonal->setMessages(["regexNotMatch" => "Invalid Email Address"]);
}
if (key($telephoneNo->getMessages()) == "regexNotMatch") {
    $telephoneNo->setMessages(["regexNotMatch" => "Invalid Telephone Number"]);
}
$formOne->setAttribute('action', $this->url('employee', ['action' => 'edit', 'id' => $id, 'tab' => 1]));
$formOne->setAttribute("name", "employeeForm");
$formOne->prepare();
?>

<div class="tab-pane active" id="tab1" style="min-height: 400px;">
    <?php print $this->form()->openTag($formOne); ?>
    <div class="personal-info">
        <p><i class="fa fa-user ticon" aria-hidden="true"></i>
            Personal Information</p>
        <div class="row clearfix e-setup">

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($employeeCode->getMessages()) ? '' : 'hasError' ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign"> 
                            <?php print $this->formLabel($employeeCode) ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($employeeCode) ?>
                            <?php print $this->formElementErrors()->render($employeeCode, ['class' => 'error']) ?>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($firstName->getMessages()) ? '' : 'hasError' ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign"> 
                            <?php print $this->formLabel($firstName) ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($firstName) ?>
                            <?php print $this->formElementErrors()->render($firstName, ['class' => 'error']) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($middleName->getMessages()) ? "" : "hasError" ?>">
                        <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                            <?php print $this->formLabel($middleName) ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($middleName) ?>
                            <?php print $this->formElementErrors()->render($middleName, ['class' => 'error']) ?>
                        </div>
                    </div>
                </div> 
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($lastName->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                            <?php print $this->formLabel($lastName) ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($lastName) ?>
                            <?php print $this->formElementErrors()->render($lastName, ['class' => 'error']) ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($nameNepali->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                            <?php print $this->formLabel($nameNepali); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($nameNepali); ?>
                            <?php print $this->formElementErrors()->render($nameNepali, ['class' => ' error']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($genderId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                            <?php print $this->formLabel($genderId); ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($genderId); ?>
                            <?php print $this->formElementErrors()->render($genderId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($birthDate->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                            <?php print $this->formLabel($birthDate) ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <div class="input-group date" id="employeeBirthDate">
                                <?php print $this->formElement($birthDate) ?>
                            </div>
                            <?php print $this->formElementErrors()->render($birthDate, ['class' => 'help-block error']) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <label for="nepaliStartDate">Birth Date(Nepali)</label>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <div class="input-group date">
                                <input type="text"   id="nepaliBirthDate" class="form-control " value="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($countryId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($countryId); ?>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($countryId); ?>
                            <?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>




            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group ">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($religionId) ?>
                           
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($religionId) ?>
                        </div>
                        <?php print $this->formElementErrors()->render($religionId, ['class' => 'help-block error']) ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($companyId->getMessages()) ? '' : 'hasError' ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($companyId); ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($companyId); ?>
                            <?php print $this->formElementErrors()->render($companyId, ['class' => 'error']) ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($bloodGroupId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($bloodGroupId); ?>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($bloodGroupId); ?>
                            <?php print $this->formElementErrors()->render($bloodGroupId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($mobileNo); ?>
                            <span class="required" aria-required="true">*</span>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($mobileNo); ?>
                            <?php print $this->formElementErrors()->render($mobileNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($telephoneNo->getMessages()) ? "" : "hasError" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($telephoneNo); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($telephoneNo); ?>
                            <?php print $this->formElementErrors()->render($telephoneNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($socialActivity->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                            <?php print $this->formLabel($socialActivity) ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($socialActivity) ?></div>
                        <?php print $this->formElementErrors()->render($socialActivity, ['class' => 'help-block error']) ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($extensionNo->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($extensionNo); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($extensionNo); ?>
                            <?php print $this->formElementErrors()->render($extensionNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($emailOfficial->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($emailOfficial); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($emailOfficial); ?>
                            <?php print $this->formElementErrors()->render($emailOfficial, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div> 

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($emailPersonal->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($emailPersonal); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($emailPersonal); ?>
                            <?php print $this->formElementErrors()->render($emailPersonal, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($socialNetwork->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($socialNetwork); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($socialNetwork); ?>
                            <?php print $this->formElementErrors()->render($socialNetwork, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="permanent-info" id="abroadAddressDiv">
        <p> <i class="fa fa-ad ticon" aria-hidden="true"></i>Abroad Address</p>
                    <?php // print $this->formLabel($abroadAddress); ?>
        
        <div class="row clearfix e-setup">
            <div class="col-md-12 colsm-12 col-xs-12">
                    <?php print $this->formElement($abroadAddress); ?>
                    <?php print $this->formElementErrors()->render($abroadAddress, ['class' => 'help-block error']); ?>

            </div>
            
        </div>
        
    </div>


    <div class="permanent-info" id="permanentAddressDiv">

        <p> <i class="fa fa-address-book ticon" aria-hidden="true"></i>Permanent Address</p>

        <div class="row clearfix e-setup">
            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($addrPermHouseNo->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermHouseNo); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermHouseNo); ?>
                            <?php print $this->formElementErrors()->render($addrPermHouseNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group <?= empty($addrPermWardNo->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermWardNo); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermWardNo); ?>
                            <?php print $this->formElementErrors()->render($addrPermWardNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($addrPermStreetAddress->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermStreetAddress); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermStreetAddress); ?>
                            <?php print $this->formElementErrors()->render($addrPermStreetAddress, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($addrPermZoneId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermZoneId); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermZoneId); ?>
                            <?php print $this->formElementErrors()->render($addrPermZoneId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">

                    <div class="form-group  <?= empty($addrPermDistrictId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermDistrictId); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermDistrictId); ?></div>
                        <?php print $this->formElementErrors()->render($addrPermDistrictId, ['class' => 'help-block error']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">

                    <div class="form-group  <?= empty($addrPermVdcMunicipalityId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermVdcMunicipalityId); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermVdcMunicipalityId); ?></div>
                        <?php print $this->formElementErrors()->render($addrPermVdcMunicipalityId, ['class' => 'help-block error']); ?>
                    </div>
                </div>

            </div>
            
            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">

                    <div class="form-group  <?= empty($addrPermProvinceId->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($addrPermProvinceId); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($addrPermProvinceId); ?></div>
                        <?php print $this->formElementErrors()->render($addrPermProvinceId, ['class' => 'help-block error']); ?>
                    </div>
                </div>

            </div>

        </div>
        <div class="Temporary-info">
            <p><i class="fa fa-address-card ticon" aria-hidden="true"></i>
                Temporary Address</p>

            <div class="row clearfix e-setup">
                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">

                        <div class="form-group  <?= empty($addrTempHouseNo->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempHouseNo); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempHouseNo); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempHouseNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>



                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">
                        <div class="form-group  <?= empty($addrTempWardNo->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempWardNo); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempWardNo); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempWardNo, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">
                        <div class="form-group  <?= empty($addrTempStreetAddress->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempStreetAddress); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempStreetAddress); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempStreetAddress, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">

                        <div class="form-group  <?= empty($addrTempZoneId->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempZoneId); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempZoneId); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempZoneId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">
                        <div class="form-group  <?= empty($addrTempDistrictId->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempDistrictId); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempDistrictId); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempDistrictId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">
                        <div class="form-group  <?= empty($addrTempVdcMunicipalityId->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempVdcMunicipalityId); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempVdcMunicipalityId); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempVdcMunicipalityId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <?php print $this->formElementErrors()->render($addrTempVdcMunicipalityId, ['class' => 'help-block error']); ?>

                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                    <div class="row bottomgap">
                        <div class="form-group  <?= empty($addrTempProvinceId->getMessages()) ? "" : "error" ?>">
                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                <?php print $this->formLabel($addrTempProvinceId); ?></div>
                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                <?php print $this->formElement($addrTempProvinceId); ?></div>
                            <?php print $this->formElementErrors()->render($addrTempProvinceId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <?php print $this->formElementErrors()->render($addrTempProvinceId, ['class' => 'help-block error']); ?>

                </div>
            </div>
        </div>


    </div>

    <div class="Emergency-info">
        <p><i class="fa fa-map-marker ticon" aria-hidden="true"></i>
            Emergency Contact Details</p>
        <div class="row clearfix e-setup">

            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">


                    <div class="form-group  <?= empty($emergContactName->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($emergContactName); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($emergContactName); ?></div>
                        <?php print $this->formElementErrors()->render($emergContactName, ['class' => 'help-block error']); ?>

                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($emergContactRelationship->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($emergContactRelationship); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($emergContactRelationship); ?></div>
                        <?php print $this->formElementErrors()->render($emergContactRelationship, ['class' => 'help-block error']); ?>
                    </div>
                </div>
            </div>




            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">
                    <div class="form-group  <?= empty($emergContactAddress->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($emergContactAddress); ?></div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($emergContactAddress); ?></div>
                        <?php print $this->formElementErrors()->render($emergContactAddress, ['class' => 'help-block error']); ?>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                <div class="row bottomgap">

                    <div class="form-group  <?= empty($emergContactNo->getMessages()) ? "" : "error" ?>">
                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                            <?php print $this->formLabel($emergContactNo); ?>
                      
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                            <?php print $this->formElement($emergContactNo); ?></div>
                        <?php print $this->formElementErrors()->render($emergContactNo, ['class' => 'help-block error']); ?>
                    </div>
                </div>



            </div>
        </div>
        <input type="submit" class="hidden" id="btnform1" value="submit">
        <?php
        print $this->form()->closeTag();
        ?>
    </div>
</div>
