<?php
$formSeven->setAttribute('id', 'form7');

$expOrgName = $formSeven->get('organizationName');
$orgType = [
    'Financial' => 'Financial',
    'Non-Financial' => 'Non-Financial'
];
$expOrgType = $formSeven->get('organizationType');
$expOrgType->setValueOptions($orgType);
$expPosition = $formSeven->get('position');
$expFromDate = $formSeven->get('fromDate');
$expToDate = $formSeven->get('toDate');
?>

<div class="tab-pane aditional" id="tab7">
    <div class="row esetup">
        <div class="col-md-12">
            <form name="employeeExperienceForm" ng-submit="submitExperience()" id="form7" novalidate>
                <input type="hidden" name="employeeId" id="employeeId" value="<?php echo $id; ?>">
                <table class="table table-striped table-bordered table-hover no-footer customtbl" id="qualificationTbl">
                    <tr>
                        <td><?php print $this->formLabel($expOrgType); ?></td>
                        <td><?php print $this->formLabel($expOrgName); ?></td>
                        <td><?php print $this->formLabel($expPosition); ?></td>
                        <td><?php print $this->formLabel($expFromDate); ?></td>
                        <td><?php print $this->formLabel($expToDate); ?></td>

                        <td width="1%"></td>
                    </tr>
                    <tr ng-repeat="experience in experienceFormList">
                        <td>
                            <select select2 name="organizationType" ng-model="experience.organizationTypeId" ng-options="organizationTypeList.name for organizationTypeList in organizationType track by organizationTypeList.id" required="required" id="organizationType" class="form-control">
                            </select>
                        </td>
                        <td>
                            <input type="text" ng-model="experience.organizationName" name="organizationName_{{experience.checkbox}}" required="required" id="organizationName" class="form-control" value="">
                            <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.organizationName_{{experience.checkbox}}.$touched">
                                <ul ng-show="employeeExperienceForm.organizationName_{{experience.checkbox}}.$error.required" class="help-block error">
                                    <li>Organization Name is required.</li>
                                </ul>
                            </div>
                        </td>
                        <td>
                            <input type="text" ng-model="experience.position" name="position_{{experience.checkbox}}" required="required" id="position" class="form-control" value="">
                            <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.position_{{experience.checkbox}}.$touched">
                                <ul ng-show="employeeExperienceForm.position_{{experience.checkbox}}.$error.required" class="help-block error">
                                    <li>Position is required.</li>
                                </ul>
                            </div>
                        </td>
                        <td>
                            <input dvalue="{{experience.fromDate}}" datepicker type="text" ng-model="experience.fromDate" name="fromDate_{{experience.checkbox}}" required="required" class="form-control" id="expfromDate_{{experience.checkbox}}" value="">
                            <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.fromDate_{{experience.checkbox}}.$touched">
                                <ul ng-show="employeeExperienceForm.fromDate_{{experience.checkbox}}.$error.required" class="help-block error">
                                    <li>From Date is required.</li>
                                </ul>
                            </div>
                        </td>
                        <td>
                            <input dvalue="{{experience.toDate}}" datepicker type="text" ng-model="experience.toDate" name="toDate_{{experience.checkbox}}" required="required" class="form-control" id="exptoDate_{{experience.checkbox}}" value="">
                            <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.toDate_{{experience.checkbox}}.$touched">
                                <ul ng-show="employeeExperienceForm.toDate_{{experience.checkbox}}.$error.required" class="help-block error">
                                    <li>To Date is required.</li>
                                </ul>
                            </div>
                        </td>
                        <td width="1%" style="padding:15px;" class="checkboxgap">
                            <div class="md-checkbox">
                                <input type="checkbox" id="{{experience.checkbox}}" class="md-check"
                                       ng-model="experience.checked">
                                <label for="{{experience.checkbox}}">
                                    <span class="inc"></span>
                                    <span class="check"></span>
                                    <span class="box"></span>
                                </label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <a href="javascript:;" class="btn btn-icon-only default pull-right"
                               ng-click="addExperience()">
                                <i class="fa fa-plus"></i>
                            </a>
                        </td>
                        <td>
                            <a href="javascript:;" class="btn btn-icon-only default" ng-click="deleteExperience()">
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                </table>
                <input type="submit" class="hidden" id="btnform7" value="submit">
            </form>
        </div>
    </div>      
</div>