<?php
/**
 * Load Javascript files here
 */
$this->headScript()
     ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
     ->appendFile($this->basePath('js/angular.min.js'))
     ->appendFile($this->basePath('js/AttendanceManagement/attendance-status/index.js'));
?>

<script>
    document.menu =<?php
$menu = ["id" => "menuAttendance", "subMenu" => ["id" => "subMenuAttendanceStatus"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\attendancestatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="attendanceStatusListController">
    <div class="row margin-top-20">
        <div class="row">
            <div class="col-sm-2">
                <?php print $this->formLabel($employees); ?>
                <?php print $this->formElement($employees); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($branches); ?>
                <?php print $this->formElement($branches); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($departments); ?>
                <?php print $this->formElement($departments); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($designations); ?>
                <?php print $this->formElement($designations); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($positions); ?>
                <?php print $this->formElement($positions); ?>
            </div>
            <div class="col-sm-2">
                <?php print $this->formLabel($serviceTypes); ?>
                <?php print $this->formElement($serviceTypes); ?>
            </div>
        </div>
        <div class="row margin-top-10">            
            <div class="col-sm-2">
                <?php print $this->formLabel($attendanceStatus); ?>
                <?php print $this->formElement($attendanceStatus); ?>
            </div>    
            <div class="col-sm-2">
                <label for="fromDate">From Date</label>
                <div class="input-group date" id="fromDate">
                    <input type="text" placeholder="From Date" id="fromDate1" name="fromDate" ng-model="fromDate" class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label for="toDate">To Date</label>
                <div class="input-group date" id="toDate">
                    <input type="text" placeholder="To Date" id="toDate1" name="toDate" ng-model="toDate" class="form-control"/>
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
            <div class="col-sm-2">
                <label height="45"></label>
                <button ng-click="view()" id="viewAttendanceRequestStatus" class="btn btn-sm yellow form-control">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="margin-top-20">   
        <div id="attendanceRequestStatusTable">
        </div>
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: FIRST_NAME #  #: MIDDLE_NAME #  #: LAST_NAME #
        </td>
        <td>
        #: ATTENDANCE_DT #
        </td>
        <td>
        #: IN_TIME #
        </td>        
        <td>
        #: OUT_TIME #
        </td>
        <td>
        #: IN_REMARKS #
        </td>
        <td>
        #: OUT_REMARKS #
        </td>
        <td>
        #: FIRST_NAME1 # #: MIDDLE_NAME1 # #: LAST_NAME1 #
        </td>
        <td>
        #: STATUS #
        </td>
        <td>
        <a class=""
        href="<?= $this->url("attendancestatus", ["action" => "view"]) ?>/#: ID #">
        View
        </a>
        </td>
        </tr>
    </script>
</div>

<div class="col-md-12">
    <div class="portlet box">
        <div class="portlet-title">
            <div class="border-bottom">
                <div class="caption" style="padding-bottom:1.5%; color:rgba(102, 102, 102, 0.92) !important;">
                    <i class="icon-layers"></i>
                    <span class="caption-subject sbold uppercase">Pending Request</span>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <table class="table" id="dataTable">
                <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Attendance Date
                        </th>
                        <th>
                            Check In
                        </th>
                        <th>
                            Check Out
                        </th>
                        <th>
                            Late In Reason
                        </th>
                        <th>
                            Late Out Reason
                        </th>
                        <th>
                            Approver
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                </thead>
                <tbody>

                    <?php foreach ($pendingList as $attendanceList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['FIRST_NAME']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME']) . " " . $this->escapeHtml($attendanceList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['FIRST_NAME1']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME1']) . " " . $this->escapeHtml($attendanceList['LAST_NAME1']);
                                ?>
                            </td>

                            <td>
                                <a class=""
                                   href="<?= $this->url("attendancestatus", ["action" => "view", "id" => $attendanceList['ID']]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

<?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-green icon-layers"></i>
                        <span class="font-green caption-subject sbold uppercase">Approved Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable1">
                    <thead>
                        <tr role="row">
                            <th>
                                Employee Name
                            </th>
                            <th>
                                Attendance Date
                            </th>
                            <th>
                                Check In
                            </th>
                            <th>
                                Check Out
                            </th>
                            <th>
                                Late In Reason
                            </th>
                            <th>
                                Late Out Reason
                            </th>
                            <th>
                                Approver
                            </th>
                            <th>
                                Approved Date
                            </th>
                            <th>
                                Operation
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($approvedList as $attendanceList):
                            ?>
                            <tr role="row">
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['FIRST_NAME']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME']) . " " . $this->escapeHtml($attendanceList['LAST_NAME']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['IN_TIME']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['OUT_TIME']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['IN_REMARKS']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['FIRST_NAME1']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME1']) . " " . $this->escapeHtml($attendanceList['LAST_NAME1']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    echo $this->escapeHtml(trim($attendanceList['APPROVED_DT']));
                                    ?>
                                </td>
                                <td>
                                    <a class=""
                                       href="<?= $this->url("attendancestatus", ["action" => "view", "id" => $attendanceList['ID']]); ?>">
                                        View
                                    </a>
                                </td>
                            </tr>

<?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-red icon-layers"></i>
                        <span class="font-red caption-subject sbold uppercase">Rejected Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable2">
                    <thead>
                        <tr role="row">
                            <th>
                                Employee Name
                            </th>
                            <th>
                                Attendance Date
                            </th>
                            <th>
                                Check In
                            </th>
                            <th>
                                Check Out
                            </th>
                            <th>
                                Late In Reason
                            </th>
                            <th>
                                Late Out Reason
                            </th>
                            <th>
                                Approver
                            </th>
                            <th>
                                Rejected Date
                            </th>
                            <th>
                                Operation
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($rejectedList as $attendanceList):
                            ?>
                            <tr role="row">
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['FIRST_NAME']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME']) . " " . $this->escapeHtml($attendanceList['LAST_NAME']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['IN_TIME']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['OUT_TIME']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['IN_REMARKS']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    print $this->escapeHtml($attendanceList['FIRST_NAME1']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME1']) . " " . $this->escapeHtml($attendanceList['LAST_NAME1']);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    echo $this->escapeHtml(trim($attendanceList['APPROVED_DT']));
                                    ?>
                                </td>
                                <td>
                                    <a class=""
                                       href="<?= $this->url("attendancestatus", ["action" => "view", "id" => $attendanceList['ID']]); ?>">
                                        View
                                    </a>
                                </td>
                            </tr>

<?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
