<?php

$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
 
$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('js/AttendanceManagement/attendance/view.js'))
                    ->appendFile($this->basePath('js/manager-service/attendance-approve/view.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceByHr-form');

$attendanceDt = $form->get('attendanceDt');
$attendanceDt->setAttributes(['disabled' => "disabled"]);
$inTime = $form->get('inTime');
$inTime->setAttributes(['disabled' => "disabled"]);
$outTime = $form->get('outTime');
$outTime->setAttributes(['disabled' => "disabled"]);
$inRemarks = $form->get('inRemarks');
$inRemarks->setAttributes(['disabled' => "disabled"]);
$outRemarks = $form->get('outRemarks');
$outRemarks->setAttributes(['disabled' => "disabled"]);
$totalHour = $form->get('totalHour');
$totalHour->setAttributes(['disabled' => "disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required' => 'true']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');
$submit->setAttribute('id','approve');

$form->setAttribute('action', $this->url('attendancestatus', ['action' => 'view', 'id' => $id]));

$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attendancestatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Attendance Request
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                    print $this->form()->openTag($form);
                    ?>
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == "RQ") {
                                                echo "Pending";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "RC") {
                                                echo "Recommended";
                                            } else if ($status == "AP") {
                                                echo "Approved";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Employee Name
                                            <input type="hidden" id="employeeId"value="<?php echo $employeeId; ?>"/>
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $employeeName; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDt; ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                        </div>
                    </div>

                    <div class=" row">
                        <div class="col-sm-4">

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group <?= empty($attendanceDt->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($attendanceDt); ?>
                                            <?php print $this->formElement($attendanceDt); ?>
                                    </div>
                                    <?php print $this->formElementErrors()->render($attendanceDt, ['class' => 'help-block error']); ?>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliDate" id="nepaliDate"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>   

                        </div>
                    </div>
                    <div class="row">

                        <div class="col-sm-4">
                            <div class="form-group <?= empty($inTime->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($inTime) ?>
                                <div class="input-group dropdown-select">
                                    <?php print $this->formElement($inTime) ?>
                                </div>
                                <?php print $this->formElementErrors()->render($inTime, ['class' => 'help-block error']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-8">
                                    <div class="form-group <?= empty($outTime->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($outTime) ?>
                                        <span class="required" aria-required="true">*</span>
                                        <div class="input-group dropdown-select">
                                            <?php print $this->formElement($outTime) ?>
                                        </div>
                                    </div>
                                    <?php print $this->formElementErrors()->render($outTime, ['class' => 'help-block error']); ?>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group <?= empty($totalHour->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($totalHour); ?>
                                        <?php print $this->formElement($totalHour); ?>
                                    </div>
                                    <?php print $this->formElementErrors()->render($totalHour, ['class' => 'help-block error']); ?>
                                </div>
                            </div>
                        </div>
                    </div>




                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group <?= empty($inRemarks->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($inRemarks); ?>
                                <?php print $this->formElement($inRemarks); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($inRemarks, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group <?= empty($outRemarks->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($outRemarks); ?>
                                <?php print $this->formElement($outRemarks); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($outRemarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>



                </div>
                <div class="form-group margin-top-10 <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($approvedRemarks); ?>
                    <?php print $this->formElement($approvedRemarks); ?>
                </div>
                <?php print $this->formElementErrors()->render($approvedRemarks, ['class' => 'help-block error']); ?>

                <div class="">
                    <?php if ($status == 'RQ' || $status == 'RC') { ?>
                    <?php  if($acl['HR_APPROVE']=='Y'){  ?>
                        <?php print $this->formSubmit($submit); ?>
                     <?php }      ?>
                        <input type="submit" name="submit" class="btn btn-danger pull-right" value="Reject">
                        <?php
                        print $this->form()->closeTag();
                    }
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>
