<?php
$this->headScript()->appendFile($this->basePath('js/setup/functionalTypes/add.js'));
?>
<?php
$functionalTypesEdesc = $form->get("functionalTypesEdesc");
$functionalTypesLdesc = $form->get("functionalTypesLdesc");
$functionalTypesCode = $form->get("functionalTypesCode");
$submit = $form->get("submit");
$form->setAttribute('action', $this->url('functionalTypes', ['action' => 'edit', 'id' => $id]));
$form->prepare();
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\functionalTypes')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?= $this->formLabel($functionalTypesCode) ?>
                            <?= $this->formElement($functionalTypesCode); ?>
                            <?= $this->formElementErrors()->render($functionalTypesCode, ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?= $this->formLabel($functionalTypesEdesc) ?>
                            <span class="required" aria-required="true">*</span>
                            <?= $this->formElement($functionalTypesEdesc); ?>
                            <?= $this->formElementErrors()->render($functionalTypesEdesc, ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?= $this->formLabel($functionalTypesLdesc) ?>
                            <?= $this->formElement($functionalTypesLdesc); ?>
                            <?= $this->formElementErrors()->render($functionalTypesLdesc, ['class' => 'help-block']) ?>
                        </div>
                    </div>

                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>


