<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/loan-request/add.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/loan-request/loanController.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'loanAdvance-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$loanId = $form->get('loanId');
$loanId->setValueOptions($loans);
$requestedAmount = $form->get('requestedAmount');
$loanDate = $form->get('loanDate');
$reason = $form->get('reason');

$submit = $form->get('submit');
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('loanApply', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuLoan","subMenu"=>["id"=>"subMenuApply"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\loanApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20" ng-app="hris" ng-controller="loanController">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <select name="employeeId" id="employeeId" required="required"  ng-model="employeeId" ng-change="employeeChange()" class="form-control">
                            <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                            <?php foreach($employees as $key=>$value){ ?>
                            <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                        <?php } ?>
                    </select>
                    <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                </div>  
                <div class="form-group">
                    <?php print $this->formLabel($loanId); ?>
                    <select name="loanId" required="required" ng-options="value for (key,value) in loanList track by key" ng-model="loanId" id="loanId" class="form-control">
                        <option style="display:none" value="" disabled="" selected>select a type</option>
                    </select>
                    <?php print $this->formElementErrors()->render($loanId, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($loanDate); ?>
                    <div class="input-group date" id="startDate">
                        <?php print $this->formElement($loanDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($loanDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($reason); ?>
                    <?php print $this->formElement($reason); ?>
                    <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                </div>

                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
