<?php
$this->headScript()->appendFile($this->basePath('js/SelfService/payroll/payslip.js'));

?>
<script>
    document.getFiscalYearMonthLink = '<?php echo $this->url('payroll', ['action' => 'getFiscalYearMonth']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\payroll')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-money"></i>Payslip
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li >
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li >
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF 
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="portlet-body">
        <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>" />
        <div class="row">
            <div class="col-sm-2">
                <select id="fiscalYearId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="monthId">
                </select>
            </div>
            <div class="col-sm-2 col-sm-offset-6">
                <button id="printBtn" class="btn btn-outline pull-right">Print</button>
                <button id="viewBtn" class="btn btn-info pull-right">View</button>
            </div>
        </div>
        <div id="paySlipView" class="margin-top-10">
            <table class="table table-bordered" id="employee-detail">
                <tr><td colspan="4"><h3><b><span id="yearMonthDetails"></span></b></h3>  </td> </tr>
                <tr>
                    <td>Employee Id</td>
                    <td key="EMPLOYEE_ID"></td>
                    <td>Employee Name</td>
                    <td key="FULL_NAME"></td>
                </tr>
                <tr>
                    <td>Marital Status</td>
                    <td key="MARITAL_STATUS_DESC"></td>
                    <td>Department</td>
                    <td key="DEPARTMENT_NAME"></td>
                </tr>
                <tr>
                    <td>Present Days</td>
                    <td key="PRESENT"></td>
                    <td>Absent Days</td>
                    <td key="ABSENT"></td>
                </tr>
                <tr>
                    <td>Salary</td>
                    <td key="SALARY"></td>
                </tr>
            </table>
            <table class="table table-bordered">
                <thead>
                <th colspan="2">Addition</th>
                <th colspan="2">Deduction</th>
                </thead>
                <tbody id="paySlipBody">
                </tbody>
            </table>
        </div>
    </div>
</div>