<?php
$this->headScript()
        ->appendFile($this->basePath('assets/global/scripts/app.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-toastr/toastr.min.js'))
        ->appendFile($this->basePath('js/custom.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/application/forgot-password/checkCode.js'))
?>
<?php
if ($this->messages) {
    foreach ($this->messages as $message) {
        print '<div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Warning!</strong> ';
        print $message;
        print '</div>';
    }
} 
?>
<div class="form-title codeTitle">
    <span class="form-title">Please Enter Security Code</span>
</div>
<script>
    document.employeeId ='<?= $employeeId ?>';
    document.url = '<?= $this->url("recover", ["action" => "index"]) ?>';
</script>
<form action="<?= $this->url("recover",["action"=>"code","employeeId"=>$employeeId])?>" id="codeForm" method="post">
    <div class="form-group">
        <label class="codeLabel">Please check your email for a message with code.</label>
        <input type="text" placeholder="Enter Code" size="10" id="code" class="codeInput" name="code"/>
        <div class="codeList">
            <ul>
                <li class="bold">We sent your code to</li>
                <li>Your Registered Email</li>
            </ul>
        </div>
        <span id="errorMsg" class="errorMsg"></span>

    </div>
    <div class="form-actions codeBottom">
        <div class="pull-left">
            <input type="submit" name="submit" class="btn btn-primary btn-block uppercase loginbtn codeSubmit" value="Submit">
            <a href="<?= $this->url("login"); ?>" class="btn default btn-block uppercase loginbtn codeCancel" style="color:#000 !important">Cancel</a>
        </div>
        <div class="pull-right forget-password-block">
            <label class="checkIn check">
                <a id="forget-password" class="forget-password">Didn't get code?</a>
            </label>
        </div>
    </div>
</form>