<?php
$this->headScript()
        ->appendFile($this->basePath('assets/global/scripts/app.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-toastr/toastr.min.js'))
        ->appendFile($this->basePath('js/custom.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/application/forgot-password/checkUsername.js'))
?>
<script>
    document.userList ='';
</script>
<?php
if ($this->messages) {
    foreach ($this->messages as $message) {
        print '<div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Warning!</strong> ';
        print $message;
        print '</div>';
    }
} 
?>
<div class="form-title codeTitle">
    <span class="form-title">Forgot Your Password?</span>
</div>
<form action="<?= $this->url("recover",["action"=>"email"])?>" id="usernameForm" method="post">
    <div class="form-group">
        <label class="codeLabel">Please enter the username you used to login. We will then send you a recovery code.</label>
        <input type="text" placeholder="Enter Username" class="codeInput form-control" name="username" id="username"/>
        <span id="errorMsg" class="errorMsg"></span>
    </div>
    <div class="form-actions codeBottom">
        <div class="pull-left">
            <input type="submit" name="submit" class="btn btn-primary btn-block uppercase loginbtn codeSubmit" value="Submit">
            <a href="<?= $this->url("login"); ?>" class="btn default btn-block uppercase loginbtn codeCancel" style="color:#000 !important">Cancel</a>
        </div>
    </div>
</form>