<?php
$this->headScript()
        ->appendFile($this->basePath('assets/global/scripts/app.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-toastr/toastr.min.js'))
        ->appendFile($this->basePath('js/custom.js'))
?>
<?php
if ($this->messages) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages;
    print '</div>';
}
?>
<div class="form-title codeTitle">
    <span class="form-title">Choose a new password.</span>
    <?php
    if ($this->messages) {
        foreach ($this->messages as $message) {
            print '<span class="form-subtitle error-message">' . $message . '</span>';
        }
    } else {
        ?>
        <?php
    }
    ?>
</div>
<form action="<?= $this->url("recover",["action"=>"password",'employeeId'=>$employeeId])?>" id="usernameForm" method="post">
    <div class="form-group">
        <label class="codeLabel">Please Enter New Password</label>
        <input type="password" class="codeInput form-control" name="password" id="password"/>
    </div>
    <div class="form-actions codeBottom">
        <div class="pull-left">
            <input type="submit" name="submit" class="btn btn-primary btn-block uppercase loginbtn codeSubmit" value="Submit">
            <a href="<?= $this->url("login"); ?>" class="btn default btn-block uppercase loginbtn codeCancel" style="color:#000 !important">Cancel</a>
        </div>
    </div>
</form>