<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuManagerService", "subMenu" => ["id" => "subMenuAttendanceApprove"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attedanceapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if($this->messages) { ?>
    <script>
        document.messages=<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;"> Print </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Save as PDF </a>
                        </li>
                        <li>
                            <a href="javascript:;"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <table class="table" id="dataTable">
        <thead>
        <tr role="row">
            <th>
                Employee Name
            </th>
            <th>
                Attendance Date
            </th>
            <th>
                Check In
            </th>
            <th>
                Check Out
            </th>
            <th>
                Late In Reason
            </th>
            <th>
                Late Out Reason
            </th>
            <th>
                Your Role
            </th>
            <th>
                Operation
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($list as $attendanceList):
            ?>
            <tr role="row">
                <td>
                    <?php
                    print $this->escapeHtml($attendanceList['FIRST_NAME'])." ".$this->escapeHtml($attendanceList['MIDDLE_NAME'])." ".$this->escapeHtml($attendanceList['LAST_NAME']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($attendanceList['IN_TIME']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($attendanceList['OUT_TIME']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($attendanceList['IN_REMARKS']);
                    ?>
                </td>
                <td>
                    <?php
                    print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                    ?>
                </td>
                <td>
                    <?php
                        echo "APPROVER";
                    ?>
                </td>
                <td>
                    <a class=""
                       href="<?= $this->url("attedanceapprove", ["action" => "view", "id" =>$attendanceList['ID']]); ?>">
                        View
                    </a>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>


</div>