<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('js/kendoDataTable.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuManagerService", "subMenu" => ["id" => "subMenuAttendanceStatus"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attedanceapprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%; color:rgba(102, 102, 102, 0.92) !important;">
                        <i class="icon-layers"></i>
                        <span class="caption-subject sbold uppercase">Pending Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Attendance Date
                        </th>
                        <th>
                            Check In
                        </th>
                        <th>
                            Check Out
                        </th>
                        <th>
                            Late In Reason
                        </th>
                        <th>
                            Late Out Reason
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($pendingList as $attendanceList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['FIRST_NAME']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME']) . " " . $this->escapeHtml($attendanceList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                echo "APPROVER";
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("attedanceapprove", ["action" => "view", "id" => $attendanceList['ID']]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-green icon-layers"></i>
                        <span class="font-green caption-subject sbold uppercase">Approved Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable1">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Attendance Date
                        </th>
                        <th>
                            Check In
                        </th>
                        <th>
                            Check Out
                        </th>
                        <th>
                            Late In Reason
                        </th>
                        <th>
                            Late Out Reason
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($approvedList as $attendanceList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['FIRST_NAME']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME']) . " " . $this->escapeHtml($attendanceList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                echo "APPROVER";
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("attedanceapprove", ["action" => "view", "id" => $attendanceList['ID']]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet box">
            <div class="portlet-title">
                <div class="border-bottom">
                    <div class="caption" style="padding-bottom:1.5%;">
                        <i class="font-red icon-layers"></i>
                        <span class="font-red caption-subject sbold uppercase">Rejected Request</span>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="dataTable2">
                    <thead>
                    <tr role="row">
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Attendance Date
                        </th>
                        <th>
                            Check In
                        </th>
                        <th>
                            Check Out
                        </th>
                        <th>
                            Late In Reason
                        </th>
                        <th>
                            Late Out Reason
                        </th>
                        <th>
                            Your Role
                        </th>
                        <th>
                            Operation
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($rejectedList as $attendanceList):
                        ?>
                        <tr role="row">
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['FIRST_NAME']) . " " . $this->escapeHtml($attendanceList['MIDDLE_NAME']) . " " . $this->escapeHtml($attendanceList['LAST_NAME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['ATTENDANCE_DT']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_TIME']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['IN_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                print $this->escapeHtml($attendanceList['OUT_REMARKS']);
                                ?>
                            </td>
                            <td>
                                <?php
                                echo "APPROVER";
                                ?>
                            </td>
                            <td>
                                <a class=""
                                   href="<?= $this->url("attedanceapprove", ["action" => "view", "id" => $attendanceList['ID']]); ?>">
                                    View
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>