<?php
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'company-form');

$companyCode = $form->get('companyCode');
$companyName = $form->get('companyName');
$address = $form->get('address');
$telephone = $form->get('telephone');
$fax = $form->get('fax');
$swift = $form->get('swift');


$submit = $form->get('submit');
$submit->setAttribute('value','Add Company');

$form->setAttribute('action', $this->url('company', ['action' => 'add']));


if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}


$form->prepare();
print $this->form()->openTag($form);

?>
    <script>
        document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuCompany"]];echo json_encode($menu);?>;
    </script>


    <div class="row">
        <div class="col-sm-2">

        </div>
        <div class="col-sm-8 bg-light-color padding-30">
            <div class="panel-heading panel-title-head">
                <h4>Company Profile</h4>
            </div>
            <div class="panel-body">
            <div class="form-group form-group-default required ">
                <?php print $this->formLabel($companyCode); ?>
                <?php print $this->formElement($companyCode); ?>
                <?php print $this->formElementErrors()->render($companyCode, ['class' => 'help-block']); ?>
            </div>
            <div class="form-group form-group-default required ">
                <?php print $this->formLabel($companyName); ?>
                <?php print $this->formElement($companyName); ?>
                <?php print $this->formElementErrors()->render($companyName, ['class' => 'help-block']); ?>
            </div>
            <div class="form-group form-group-default required ">
                <?php print $this->formLabel($address); ?>
                <?php print $this->formElement($address); ?>
                <?php print $this->formElementErrors()->render($address, ['class' => 'help-block']); ?>
            </div>
            <div class="form-group form-group-default ">
                <?php print $this->formLabel($telephone); ?>
                <?php print $this->formElement($telephone); ?>
                <?php print $this->formElementErrors()->render($telephone, ['class' => 'help-block']); ?>
            </div>

            <div class="form-group form-group-default ">
                <?php print $this->formLabel($fax); ?>
                <?php print $this->formElement($fax); ?>
                <?php print $this->formElementErrors()->render($fax, ['class' => 'help-block']); ?>
            </div>
            <div class="form-group form-group-default ">
                <?php print $this->formLabel($swift); ?>
                <?php print $this->formElement($swift); ?>
                <?php print $this->formElementErrors()->render($swift, ['class' => 'help-block']); ?>
            </div>
            <?php print $this->formSubmit($submit); ?>
            </div>
        </div>

    </div>

    </div>


<?php

print $this->form()->closeTag($form);

?>