<?php 
$form->setAttribute('role','form');
$form->setAttribute('class','company-form');

$companyCode = $form->get('companyCode');
$companyName = $form->get('companyName');
$inNepali = $form->get('inNepali');
$addressFirst = $form->get('addressFirst');
$addressSecond = $form->get('addressSecond');

$telephone = $form->get('telephone');
$email = $form->get('email');
$fax = $form->get('fax');
$web = $form->get('web');



$form->setAttribute('action',$this->url('company',['action'=>'add']));
$form->prepare();

print $this->form()->openTag($form);

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

?>

<div class="panel panel-default">
	<div class="panel-heading panel-title-head">
		<!--<div class="panel-title"> -->
			<h4>Company Profile Setup</h4>		
	</div>
	<div class="panel-body padding-10">
		<div class="row">
			<div class="col-sm-6">
			<fieldset class="scheduler-border" style="height:auto;">
                <legend class="scheduler-border" style="font-size:15px;">Company Profile</legend>
                       
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($companyCode); ?>
					<?php print $this->formElement($companyCode); ?>
					<?php print $this->formElementErrors()->render($companyCode,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($companyName); ?>
					<?php print $this->formElement($companyName); ?>
					<?php print $this->formElementErrors()->render($companyName,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($inNepali); ?>
					<?php print $this->formElement($inNepali); ?>
					<?php print $this->formElementErrors()->render($inNepali,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($addressFirst); ?>
					<?php print $this->formElement($addressFirst); ?>
					<?php print $this->formElementErrors()->render($addressFirst,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($addressSecond); ?>
					<?php print $this->formElement($addressSecond); ?>
					<?php print $this->formElementErrors()->render($addressSecond,['class'=>'help-block']);?>
				</div>
				
				</fieldset>
			</div>

			<div class="col-sm-6">
			<fieldset class="scheduler-border" style="height:auto;">
                <legend class="scheduler-border" style="font-size:15px;">Contact Address</legend>
                       
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($telephone); ?>
					<?php print $this->formElement($telephone); ?>
					<?php print $this->formElementErrors()->render($telephone,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($email); ?>
					<?php print $this->formElement($email); ?>
					<?php print $this->formElementErrors()->render($email,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($fax); ?>
					<?php print $this->formElement($fax); ?>
					<?php print $this->formElementErrors()->render($fax,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($web); ?>
					<?php print $this->formElement($web); ?>
					<?php print $this->formElementErrors()->render($web,['class'=>'help-block']);?>
				</div>
				
				
				</fieldset>
			</div>
		</div>			
					
	</div>
</div>





<?php

print $this->form()->closeTag($form);

?>