
<?php 
$form->setAttribute('role','form');
$form->setAttribute('class','company-form');

$companyId = $form->get('companyId');
$companyCode = $form->get('companyCode');
$companyName = $form->get('companyName');
$address= $form->get('address');
$telephone = $form->get('telephone');
$fax = $form->get('fax');
$swift = $form->get('swift');


$submit = $form->get('submit');
$submit->setAttribute('value','Edit Company');

$form->setAttribute('action',$this->url('company',['action'=>'edit','id'=>$id]));



if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}


$form->prepare();
print $this->form()->openTag($form);

?>

<div class="panel panel-default">
	<div class="panel-heading panel-title-head">
		<!--<div class="panel-title"> -->
			<h4>Company Profile Setup</h4>		
	</div>
	<div class="panel-body padding-10">
		<div class="row">
			<div class="col-sm-6">
				<fieldset class="scheduler-border" style="height:auto;">
                <legend class="scheduler-border" style="font-size:15px;">Company Profile</legend>
                 <div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($companyId); ?>
					<?php print $this->formElement($companyId); ?>
					<?php print $this->formElementErrors()->render($companyId,['class'=>'help-block']);?>
				</div>      
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($companyCode); ?>
					<?php print $this->formElement($companyCode); ?>
					<?php print $this->formElementErrors()->render($companyCode,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($companyName); ?>
					<?php print $this->formElement($companyName); ?>
					<?php print $this->formElementErrors()->render($companyName,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default required emp-form-group">
					<?php print $this->formLabel($address); ?>
					<?php print $this->formElement($address); ?>
					<?php print $this->formElementErrors()->render($address,['class'=>'help-block']);?>
				</div>
				
				
				</fieldset>
			</div>

			<div class="col-sm-6">
				<fieldset class="scheduler-border" style="height:auto;">
                <legend class="scheduler-border" style="font-size:15px;">Contact Address</legend>
                       
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($telephone); ?>
					<?php print $this->formElement($telephone); ?>
					<?php print $this->formElementErrors()->render($telephone,['class'=>'help-block']);?>
				</div>

				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($fax); ?>
					<?php print $this->formElement($fax); ?>
					<?php print $this->formElementErrors()->render($fax,['class'=>'help-block']);?>
				</div>
				<div class="form-group form-group-default emp-form-group">
					<?php print $this->formLabel($swift); ?>
					<?php print $this->formElement($swift); ?>
					<?php print $this->formElementErrors()->render($swift,['class'=>'help-block']);?>
				</div>
				</fieldset>
			</div>
		</div>
		
		</div>	

		<div class="panel-footer panel-footer-default">
			<?php  print $this->formSubmit($submit); ?>		
		</div>
					
	</div>

	
</div>

<?php

print $this->form()->closeTag($form);

?>