<?php
/**
 * Load Javascript files here
 */
$this->headScript()
    ->appendFile($this->basePath('plugins/datatables/media/js/jquery.dataTables.min.js'))
    ->appendFile($this->basePath('plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js'))
    ->appendFile($this->basePath('js/datatables.js'));
?>

<?php
if ($this->messages) {
    print '<div class="alert alert-success" role="alert"><button class="close" data-dismiss="alert"></button>';
    foreach ($this->messages as $message) {
        print '<strong>Success: </strong>' . $message;
    }
    print '</div>';
}
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuCompany"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Company')->breadcrumbs()->setMinDepth(0) ?>
</div>
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-user"></i>Table
        </div>
        <div class="actions">
            <a href="<?= $this->url('company', ['action' => 'add']) ?>" class="btn btn-default btn-sm">
                <i class="fa fa-pencil"></i> Add </a>
            <div class="btn-group">
                <a class="btn btn-default btn-sm" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-cogs"></i> Tools <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-pencil"></i> Edit </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-trash-o"></i> Delete </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-ban"></i> Ban </a>
                    </li>
                    <li class="divider">
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="i"></i> Make admin </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-bordered" id="tableWithSearch">
            <thead>
            <tr role="row">
                <th>Company
                    Code
                </th>
                <th>Company Name
                </th>
                <th>
                    Action
                </th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($companyList as $company): ?>
                <tr role="row">
                    <td>
                        <?php print $this->escapeHtml($company->COMPANY_CODE) ?>
                    </td>
                    <td>
                        <?php print $this->escapeHtml($company->COMPANY_NAME) ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default">
                                <a class="fa fa-edit btn-link"
                                   href="<?= $this->url("company", ["action" => "edit", "id" => $company->COMPANY_ID]); ?>">
                                </a>
                            </button>
                            <button type="button" class="btn btn-default">
                                <a class="fa fa-trash-o btn-link"
                                   href="<?= $this->url("company", ["action" => "delete", "id" => $company->COMPANY_ID]); ?>"></a>
                            </button>
                        </div>
                    </td>
                </tr>

            <?php endforeach; ?>

            </tbody>
        </table>

    </div>
</div>