<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/manager-service/dayoff-work-approve/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuManagerService", "subMenu" => ["id" => "subMenuDayoffWorktoApprove"]];
echo json_encode($menu); ?>;
    document.deleteURL ='<?= $this->url("restful", ["action" => "index"]) ?>';
    document.dayoffWorkRequest=<?php echo json_encode($dayoffWorkRequest);?>
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\dayoffWorkApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="dayoffWorkApproveTable">
    </div>
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (FIRST_NAME == null) ? ' ' : FIRST_NAME #
        #: (MIDDLE_NAME == null) ? ' ' : MIDDLE_NAME #
        #: (LAST_NAME == null) ? ' ' : LAST_NAME #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (FROM_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (DURATION == null) ? '-' : DURATION #
        </td>
        <td>
        #: (YOUR_ROLE == null) ? '-' : YOUR_ROLE #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("dayoffWorkApprove", ["action" => "view"]); ?>/#:ID #/#:ROLE #" style="height:17px;" title="view">
        <i class="fa fa-search-plus"></i></a>
        </a>
        </td>
        </tr>
    </script>
</div>