<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/training/training-assign/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuTrainingList"]];
echo json_encode($menu); ?>;
    document.deleteURL ='<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingList')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">   
    <div id="loanAdvanceTable">
        <table id="grid">
            <thead>
            <tr>
                <th>Training Name</th>
                <th>Start Date</th>
                <th>To Date</th>
                <th>Location</th>
                <th>Instructor Name</th>
                <th>Training Institute Name</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Organizational</td>
                    <td>02-Jan-2016</td>
                    <td>07-Jan-2016</td>
                    <td>Jawalakhel</td>
                    <td>Ramesh Chhetri</td>
                    <td>Alpha Beta</td>
                </tr>             
            </tbody>
        </table>
    </div>
 

</div>