
<script>
    document.menu =<?php
$menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuTrainingList"]];
echo json_encode($menu);
?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingList')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Training Detail
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group">
                    <div class="row div-font-11">
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Training Code
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['TRAINING_CODE']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Training Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['TRAINING_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Start Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['START_DATE']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        End Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['END_DATE'] ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Institute Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['INSTITUTE_NAME'] ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Location
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['LOCATION'] ?>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Duration(in hour)
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['DURATION']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Training Type
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $type = ($detail['TRAINING_TYPE'] == 'CP') ? "Company Personal" : "Company Contribution"; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Instructor Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['INSTRUCTOR_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Telephone Detail (for institute)
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['TELEPHONE']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Email Address (for institute)
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['EMAIL']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Remarks (for training)
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['REMARKS']; ?>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
