<?php
$this->headScript()->appendFile($this->basePath('js/asset/issue/add.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/asset/issue/assetIssueController'));

//echo '<pre>';
//print_r($editVal->employeeId);
//print_r($employee);
//die();

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'assetIssue-form');
$form->setAttribute('action', $this->url('assetIssue', ['action' => 'edit', 'id' => $id]));


$issueDate = $form->get('issueDate');

$assetId = $form->get('assetId');
$assetId->setValueOptions($asset);

//    echo '<pre>';
//    print_r($editVal->assetId);
//    die();

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employee);

$quantity = $form->get('quantity');

$requestDate = $form->get('requestDate');

$returnable = $form->get('returnable');

$returnDate = $form->get('returnDate');

$purpose = $form->get('purpose');

$remarks = $form->get('remarks');


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');
$form->prepare();

//    echo '<pre>';
//    print_r($issueDate);
//    print_r($this->formElement($returnable));
//    echo '</pre>';
//    die();
?>

<script>
    document.editVal =<?= json_encode($editVal) ?>;
    document.assetList =<?= json_encode($asset) ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\assetIssue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div ng-app="hris" ng-controller="assetIssuecontroller">
    <div class="row margin-top-20">
        <div class="col-sm-12">
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>Edit
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php print $this->form()->openTag($form); ?>
                    <input type="hidden" name="balance" ng-model="bal" value="{{bal}}">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($issueDate); ?>
                                <?php print $this->formElement($issueDate); ?>
                                <?php print $this->formElementErrors()->render($issueDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="assetId">Asset Name</label>
                                <select ng-options="key as value for (key , value) in assetList" ng-model="asset" ng-change="astChange()" name="assetId" required="required" id="assetId" class="form-control">
                                   

                                </select>

                                <span ng-model="rQ" ng-bind="rQ"></span>

                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="employeeId">Employee</label>                    
                                <select ng-model="employee" name="employeeId" required="required" id="employeeId" class="form-control">
                                    <option value="" disabled="" selected="" class="ng-binding">Please select</option>   
                                    <?php foreach ($employee as $key => $value) { ?>
                                        <?php if ($editVal->employeeId == $key) { ?>
                                            <option selected="selected" value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                        <?php } else { ?>
                                            <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>                                    
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($quantity); ?>
                                <?php print $this->formElement($quantity); ?>
                                <?php print $this->formElementErrors()->render($quantity, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($requestDate); ?>
                                <?php print $this->formElement($requestDate); ?>
                                <?php print $this->formElementErrors()->render($requestDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($purpose); ?>
                                <?php print $this->formElement($purpose); ?>
                                <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>


                    <div class=" row">
                        <div class="col-sm-1">
                            <div class="form-group">
                                <label for="returnable">Returnable</label>                    
                                <input type="hidden" name="returnable" value="N">
                                <input ng-model="rdChk" ng-click="rdClk()" type="checkbox" name="returnable"  id="returnable" class="form-control" value="Y">
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label for="returnDate">Return Date</label>
                                <input ng-model="rdTxt" ng-disabled="!rdChk" type="text" name="returnDate" id="returnDate" class="form-control" disabled="disabled" value="">
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>





                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>



