<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advance-request')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'));
$this->headScript()->appendFile($this->basePath('js/advance/advance-request/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'advance-form');

$advanceId = $form->get('advanceId');
$advanceId->setValueOptions($advances);
$advanceId->setAttributes(["disabled" => "disabled"]);

$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);

$dateOfadvance = $form->get('dateOfadvance');
$dateOfadvance->setAttributes(["disabled" => "disabled"]);

$reason = $form->get('reason');
$reason->setAttributes(["disabled" => "disabled"]);

$deductionRate = $form->get('deductionRate');
$deductionRate->setAttributes(["disabled" => "disabled"]);

$deductionIn = $form->get('deductionIn');
$deductionIn->setAttributes(["disabled" => "disabled"]);

$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);

$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('advance-request', ['action' => 'add']));
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.advanceRequestData =<?php echo json_encode($advanceRequestData); ?>;
</script>

<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Advance Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>

            </div>
            <div class="portlet-body">
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDate; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            echo $statusDetail;
                                            ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>                               
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" id="form-employeeId" value="<?php echo $employeeId; ?>"/>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($advanceId); ?>
                                <?php print $this->formElement($advanceId); ?>
                                <?php print $this->formElementErrors()->render($advanceId, ['class' => 'help-block']); ?>
                            </div>               
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($requestedAmount); ?>
                                <?php print $this->formElement($requestedAmount); ?>
                                <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($dateOfadvance); ?>
                                        <?php print $this->formElement($dateOfadvance); ?>
                                        <?php print $this->formElementErrors()->render($dateOfadvance, ['class' => 'help-block']); ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliDate" id="nepalidateOfadvance"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div> 

                        </div>

                    </div>

                    <div class=" row">
                        <?php
                        if ($advanceRequestData['DEDUCTION_TYPE'] == 'S') {
                            ?>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <?php print $this->formLabel($deductionRate); ?>
                                    <?php print $this->formElement($deductionRate); ?>
                                    <?php print $this->formElementErrors()->render($deductionRate, ['class' => 'help-block']); ?>
                                    <span ><?php
                                        $monthlyDeductAmt = ($advanceRequestData['DEDUCTION_RATE'] / 100) * $advanceRequestData['SALARY'];
                                        echo 'RS.' . $monthlyDeductAmt;
                                        ?></span>

                                </div>
                            </div>
                            <?php
                        }
                        ?>

                        <?php
                        if ($advanceRequestData['DEDUCTION_TYPE'] == 'M') {
                            ?>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <?php print $this->formLabel($deductionIn); ?>
                                    <?php print $this->formElement($deductionIn); ?>
                                    <?php print $this->formElementErrors()->render($deductionIn, ['class' => 'help-block']); ?>
                                </div>
                            </div>

                            <?php
                        }
                        ?>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($reason); ?>
                                <?php print $this->formElement($reason); ?>
                                <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                    </div>


                </div>
                <div
                    class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Recommender]</label>
                    <?php print $this->formElement($recommendedRemarks); ?>
                </div>
                <div
                    class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                    <label>Reason for action [From Approver]</label>
                    <?php print $this->formElement($approvedRemarks); ?>
                </div>
            </div>

        </div>
    </div>
</div>
