<?php $disabledKPICOM = "disabled"; 
if($assignedAppraisalDetail['COMPETENCIES_SETTING']=='Y'){
?>
<div class="tab-pane" id="portlet_tab2_COM" ng-controller="competenciesController">
    <h6 class="appHeading">
        COMPETENCIES AND COMMENT
    </h6>
    <form name="competenciesForm" id="competenciesForm" ng-submit="submitCompetenciesForm()" novalidate>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width:5%;">S.N.</th>
                    <th>Competencies</th>
                    <?php if ($appCompetenciesRatingDtlNum > 0) { ?>
                        <th>Rating</th>
                        <th>Appraiser's Comments</th>
                    <?php } ?>
                </tr>
            </thead>
            <tr ng-repeat="competencies in competenciesList">
                <td><span ng-bind="competencies.counter"></span></td>
                <td>
                    <div>
                    <textarea cols="25" rows="20" class="form-control" style="height:25px!important" name="title_{{competencies.checkbox}}" ng-model="competencies.title" required="required" <?= $disabledKPICOM; ?>></textarea>
                    <div ng-show="competenciesForm.$submitted || competenciesForm.title_{{competencies.checkbox}}.$touched">
                        <ul ng-show="competenciesForm.title_{{competencies.checkbox}}.$error.required" class="help-block error">
                            <li>Competencies Detail is required.</li>
                        </ul>
                    </div>
                    </div>
                </td>
                <?php if ($appCompetenciesRatingDtlNum > 0) { ?>
                    <td width='10%'>
                        <div>
                        <select name="rating_{{competencies.checkbox}}" ng-model="competencies.rating" ng-options="item for item in ratingNames" required="required" disabled='disabled'>
                        </select>
                        <div ng-show="competenciesForm.$submitted || competenciesForm.rating_{{competencies.checkbox}}.$touched">
                            <ul ng-show="competenciesForm.rating_{{competencies.checkbox}}.$error.required" class="help-block error">
                                <li>Appraiser Rating is required.</li>
                            </ul>
                        </div> 
                        </div>
                    </td>
                    <td>
                        <div>
                        <textarea cols="25" rows="20" class="form-control" style="height:150px!important" name="comments_{{competencies.checkbox}}" ng-model="competencies.comments" required="required" disabled='disabled'></textarea>
                        <div ng-show="competenciesForm.$submitted || competenciesForm.comments_{{competencies.checkbox}}.$touched">
                            <ul ng-show="competenciesForm.comments_{{competencies.checkbox}}.$error.required" class="help-block error">
                                <li>Appraiser's Comment is required.</li>
                            </ul>
                        </div>
                        </div>
                    </td>
                <?php } ?>
            </tr>
            <?php if ($appCompetenciesRatingDtlNum > 0) {
                ?>
                <tr>
                    <td colspan="2">
                        ANNUAL RATING ON COMPETENCIES:
                    </td>
                    <td>
                        <div>
                        <select name="annualRatingCompetency" id="annualRatingCompetency" required="required" disabled='disabled'>
                            <option <?= ($assignedAppraisalDetail['ANNUAL_RATING_COMPETENCY'] == "A") ? "selected" : "" ?>>A</option>
                            <option <?= ($assignedAppraisalDetail['ANNUAL_RATING_COMPETENCY'] == "B") ? "selected" : "" ?>>B</option>
                            <option <?= ($assignedAppraisalDetail['ANNUAL_RATING_COMPETENCY'] == "C") ? "selected" : "" ?>>C</option>
                        </select>
                        </div>
                    </td>
                    <td></td>
                </tr>
            <?php } ?>
        </table>
    </form>
    <?php
    print $this->partial('appraisal/layout/competency-remarks.phtml');
    ?>
</div>
<?php } ?>