 <div class="tab-pane <?= ($tab==6)?"active":""; ?>" id="portlet_tab2_6">
    <form method="post" action="<?= $this->url("appraisalReport",['action'=>'view','appraisalId'=>$appraisalId,'employeeId'=>$employeeId]) ?>" name="performanceAppraisalForm" id="hrAppraisalReview">
    <div class="row">
        <?php
        $disabledHrComment = ($assignedAppraisalDetail['STAGE_ID']!=9)?'disabled':'';?>
        <div class="col-md-12 margin-bottom-10">
            <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;">For Use Of HR</h6>
                <div class="row">
                    <div  class="col-md-12 margin-bottom-10"> 
                        <div class="row">
                            <div class="col-sm-8">
                                <label> <h7 style="font-size:12px;">Overall Comment</h7>  </label> 
                                <textarea name="hrComment" id="hrComment" class="form-control" style="height:50px!important" required="required" <?= $disabledHrComment; ?>><?= $assignedAppraisalDetail['HR_FEEDBACK']; ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <?php if ($assignedAppraisalDetail['STAGE_ID']==9){?>
    <div class="row margin-top-10">
        <div class="col-sm-12">
            <div class="form-group">
                <button type="submit" id="submit" class="btn btn-success pull-right">
                    SUBMIT
                </button>
            </div>
        </div>
    </div>
    <?php } ?>
    </form>
</div>
