 <div class="tab-pane <?= ($tab==6)?"active":""; ?>" id="portlet_tab2_6">
    <form method="post" action="<?= $this->url("appraisalReport",['action'=>'view','appraisalId'=>$appraisalId,'employeeId'=>$employeeId,'tab'=>6]) ?>" name="performanceAppraisalForm" id="hrAppraisalReview">
    <div class="row">
        <?php
        $disabled = ($questionForCurStage==0)?'disabled':'';
        foreach ($hrQuestionTemplate as $hrQuestionList) { ?>
            <div class="col-md-12 margin-bottom-10">
                <div style="border: 1px solid #ddd; padding: 0px 10px 10px 10px;">
                    <h6 style="border-bottom: 1px solid #ddd; padding-bottom: 1%; color: black; font-weight: 400;"><?php echo $hrQuestionList['HEADING_EDESC']; ?></h6>
                    <div class="row">
                        <?php foreach ($hrQuestionList['QUESTIONS'] as $hrQuestionRow) { ?>
                            <div  class="col-md-12 margin-bottom-10">  
                                <div class="row">
                                    <div class="col-sm-8">
                                        <label><h7 style="font-size:12px;"><?php echo $hrQuestionRow['QUESTION_EDESC']; ?></h7> </label> 
                                        <?php 
                                        $keyForHRQuestion = ($hrQuestionRow['ANSWER']==null || count($hrQuestionRow['ANSWER'])==0)?$hrQuestionRow['QUESTION_ID']:array_keys($hrQuestionRow['ANSWER'])[0];
                                        if($hrQuestionRow['HR_FLAG']=='Y'){
                                            if($hrQuestionRow['ANSWER_TYPE']=="RADIO"){ ?>
                                            <div class="md-radio-inline">
                                                <?php $customRenderer($performanceAppraisalObj("answer[".$keyForHRQuestion."]", $hrQuestionRow['ANSWER_TYPE'],(count($hrQuestionRow['QUESTION_OPTIONS'])>0)?$hrQuestionRow['QUESTION_OPTIONS']:null,($hrQuestionRow['ANSWER']!=null && count($hrQuestionRow['ANSWER'])>0)?array_values($hrQuestionRow['ANSWER'])[0]['ANSWER']:null,$disabled)); ?>
                                            </div>
                                            <?php } else if($hrQuestionRow['ANSWER_TYPE']=="CHECKBOX"){?>
                                                <div class="md-checkbox-inline">
                                                    <?php $customRendererForCheckbox($performanceAppraisalObj("answer[".$keyForHRQuestion."][]", $hrQuestionRow['ANSWER_TYPE'],(count($hrQuestionRow['QUESTION_OPTIONS'])>0)?$hrQuestionRow['QUESTION_OPTIONS']:null,($hrQuestionRow['ANSWER']!=null && count($hrQuestionRow['ANSWER'])>0)?array_values($hrQuestionRow['ANSWER'])[0]['ANSWER']:null,$disabled)); ?>
                                                </div>
                                            <?php } else{
                                                print_r($this->formElement($performanceAppraisalObj("answer[".$keyForHRQuestion."]", $hrQuestionRow['ANSWER_TYPE'],(count($hrQuestionRow['QUESTION_OPTIONS'])>0)?$hrQuestionRow['QUESTION_OPTIONS']:null,($hrQuestionRow['ANSWER']!=null && count($hrQuestionRow['ANSWER'])>0)?array_values($hrQuestionRow['ANSWER'])[0]['ANSWER']:null,$disabled)));
                                            }
                                        }
                                        ?>
                                    </div>
                                    <?php if($hrQuestionRow['HR_RATING']=='Y'){ 
                                        if($questionRow['HR_FLAG']=='N'){?>
                                            <input type="hidden" value="<?= (count($questionRow['ANSWER'])>0)?array_keys($questionRow['ANSWER'])[0]:0; ?>" name="answerId[]"/>
                                            <input type="hidden" value="" name="<?= "answer[".$keyForHRQuestion."]"; ?>"/>
                                        <?php }?>
                                        <div class="col-sm-1">
                                            <label>Self Rating:</label><input class="form-control" type="number" name="<?= "answer[".$keyForHRQuestion.".hr]"?>" value="<?= ($hrQuestionRow['ANSWER']!=null||count($hrQuestionRow['ANSWER'])>0)?array_values($hrQuestionRow['ANSWER'])[0]['RATING']:null ?>" <?= $disabled ?> min="<?= $hrQuestionRow['MIN_VALUE'] ?>" max="<?= $hrQuestionRow['MAX_VALUE'] ?>"/>
                                        </div>
                                    <?php }?>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php if ($questionForCurStage>0){?>
    <div class="row margin-top-10">
        <div class="col-sm-12">
            <div class="form-group">
                <button type="submit" id="submit" class="btn btn-success pull-right">
                    SUBMIT
                </button>
            </div>
        </div>
    </div>
    <?php } ?>
    </form>
</div>
