<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/overtime-request/add.js'))
        ->appendFile($this->basePath('js/SelfService/overtime-request/detailController.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('class', 'overtimeRequest-form');
$form->setAttribute('id', 'overtimeRequest-form');

$overtimeDate = $form->get('overtimeDate');
$startTime = $form->get('startTime');
$startTime->setValue("10:00 AM");
$startTime->setAttributes(['readonly' => "readonly"]);
$endTime = $form->get('endTime');
$endTime->setValue("5:00 PM");
$endTime->setAttributes(['readonly' => "readonly"]);
$description = $form->get('description');
$remarks = $form->get('remarks');
$totalHour = $form->get('totalHour');
$totalHour->setValue("7.0");
$totalHour->setAttributes(['readonly' => "readonly"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('overtimeRequest', ['action' => 'add']));


$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\overtimeRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<script>
    document.urlOvertime = '<?= $this->url("overtimeRequest", ["action" => "index"]) ?>';
</script>
    <div class="row margin-top-20" ng-app="hris" ng-controller="detailController">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Overtime Request
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <input type="hidden" id="overtimeId" value="0"/>
                <div class=" row">
                    <div class="col-sm-4">

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group <?= empty($overtimeDate->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($overtimeDate); ?>
                                    <span class="required" aria-required="true">*</span>
                                        <?php print $this->formElement($overtimeDate); ?>
                                </div>
                                <?php print $this->formElementErrors()->render($overtimeDate, ['class' => 'help-block error']); ?>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDate" id="nepaliDate"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>     

                    </div>
                    <div class="col-sm-6">
                    <table width='100%'>
                        <tr ng-repeat="overtimeDetail in overtimeDetailList" height="30"> 
                            <td width="45%" style="padding:5px;">
                                <input timepicker type="text" size="3" class="form-control" name="startTime_{{overtimeDetail.checkbox}}" ng-model="overtimeDetail.startTime" value="" required="required" readonly="readonly"/>
                            </td>
                            <td width="45%" style="padding:5px;">
                                <input timepicker type="text" size="3"  class="form-control" name="endTime_{{overtimeDetail.checkbox}}" ng-model="overtimeDetail.endTime" value="" required="required" readonly="readonly"/>
                            </td>
                            <td width="45%" style="padding:5px;">
                                <input type="text" size="3" class="form-control" name="totalHour_{{overtimeDetail.checkbox}}" ng-model="overtimeDetail.totalHour"  required="required" readonly="readonly"/>
                            </td>
                            <td width="47">
                                <div class="md-checkbox">
                                    <input type="checkbox" id="{{overtimeDetail.checkbox}}" class="md-check"
                                           ng-model="overtimeDetail.checked">
                                    <label for="{{overtimeDetail.checkbox}}">
                                        <span class="inc"></span>
                                        <span class="check"></span>
                                        <span class="box"></span>
                                    </label>
                                </div>
                            </td>
                        </tr>
                        <tr height="30">
                            <td></td>
                            <td></td>
                            <td>
                                <a href="javascript:;" class="btn btn-icon-only default pull-right" style="margin-left:17%;" ng-click="addOvertimeDetail()" id="plushIcon">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </td>
                            <td>
                                <a href="javascript:;" class="btn btn-icon-only default" ng-click="delete()" id="plushIcon">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                        </tr>
                    </table>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($startTime->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($startTime) ?>
                            <span class="required" aria-required="true">*</span>
                            <div class="input-group dropdown-select">
                                <?php print $this->formElement($startTime) ?>
                            </div>
                            <?php print $this->formElementErrors()->render($startTime, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($endTime->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($endTime) ?>
                            <span class="required" aria-required="true">*</span>
                            <div class="input-group dropdown-select">
                                <?php print $this->formElement($endTime) ?>
                            </div>
                        </div>
                        <?php print $this->formElementErrors()->render($endTime, ['class' => 'help-block error']); ?>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($description->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($description); ?>
                            <?php print $this->formElement($description); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($description, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($remarks->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($totalHour->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($totalHour); ?>
                            <?php print $this->formElement($totalHour); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($totalHour, ['class' => 'help-block error']); ?>
                    </div>
                </div>

                <div class="">
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>
