<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuPerformanceAppraisal"]];
echo json_encode($menu); ?>;
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\performance-appraisal')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

