<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/asset/setup/index.js'));


$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()->appendFile($this->basePath('js/asset/setup/setupController.js'));
$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));


?>

<?php

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'assetIssue-form');
$form->setAttribute('action', $this->url('assetIssue', ['action' => 'add']));


$issueDate = $form->get('issueDate');

$assetId = $form->get('assetId');
$assetId->setValueOptions($asset);


$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employee);

$quantity = $form->get('quantity');

$requestDate = $form->get('requestDate');

$returnable = $form->get('returnable');

$returnDate = $form->get('returnDate');

$purpose = $form->get('purpose');

$remarks = $form->get('remarks');


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');
$form->prepare();

?>




<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.setup =<?= json_encode($setup) ?>;
    document.pullAssetBalanceLink = '<?= $this->url("assetSetup", ["action" => "pullAssetBalance"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\assetSetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20"   ng-app="hris" ng-controller="setupController">
    
    <div class="portlet light bg-inverse">
        
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('assetSetup', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <div id="assetSetupTable">

    </div>
	</div>
    
    
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>    
        #: (ASSET_EDESC == null) ? '-' : ASSET_EDESC #
        </td>
        <td>    
        #: (ASSET_GROUP_EDESC == null) ? '-' : ASSET_GROUP_EDESC #
        </td>
        <td>    
        #: (BRAND_NAME == null) ? '-' : BRAND_NAME #
        </td>
        <td>    
        #: (MODEL_NO == null) ? '-' : MODEL_NO #
        </td>
        <td>    
        #: (QUANTITY == null) ? '-' : QUANTITY #
        </td>
        <td>    
        #: (QUANTITY_BALANCE == null) ? '-' : QUANTITY_BALANCE #
        </td>
        <td>
        # if(QUANTITY==QUANTITY_BALANCE){#
        <a class="btn-edit"
        href="<?= $this->url("assetSetup", ["action" => "edit"]); ?>/#:ASSET_ID#" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a>
        <a class="btn-delete confirmation"
        href="<?= $this->url("assetSetup", ["action" => "delete"]); ?>/#:ASSET_ID#" id="bs_#:ASSET_ID #" style="height:17px;"> 
        <i class="fa fa-trash-o"></i>
        </a>
        # } #
        <a class="btn-edit" id="btnIssue" data-asset="#:ASSET_EDESC#" data-assetid="#:ASSET_ID#"
        href="\\#"   > 
        <i class="fa fa-send-o"></i>
        </a>
        
        <a class="btn-edit"
        href="<?= $this->url("assetIssue", ["action" => "view"]); ?>/#:ASSET_ID#" > 
        <i class="fa fa-eye"></i>
        </a>
        </td>
        </tr>
    </script>


                    
                   
       
     
<script type="text/ng-template" id="myModalContent.html">
     <div class="modal-header">
            <h3 class="modal-title" id="modal-title">ASSET ISSUE</h3>
        </div>
        <div class="modal-body" id="modal-body">
        
        <div class="row">
                    <div class="col-sm-12">
                    <?php print $this->form()->openTag($form); ?>
                    <input type="hidden" name="balance" ng-model="bal" value="{{bal}}">
                    <input type="hidden" name="assetId" ng-model="asset" value="{{asset}}">
                    
                    
                    <div class="row">
                        <div class="col-sm-2">
                            <label>Asset : </label>
                        </div>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" readonly="readonly" name='assetName'ng-model="assetNameView">    
                        </div>
                        <div class="col-sm-5">
                            <span ng-model="rQ" ng-bind="rQ"></span>    
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-6"> 
                            <div class="form-group">
                                <?php print $this->formLabel($requestDate); ?>
                                <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                <?php print $this->formElement($requestDate); ?>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <input type="text"   id="requestDateNepali" class="form-control " value="">
                                </div>
                            </div>
                                <?php print $this->formElementErrors()->render($requestDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        
                        <div class="col-sm-6"> 
                            <div class="form-group">
                                <?php print $this->formLabel($issueDate); ?>
                                <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                <?php print $this->formElement($issueDate); ?>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <input type="text"   id="issueDateNepali" class="form-control " value="">
                                </div>
                            </div>
                                <?php print $this->formElementErrors()->render($issueDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>
                    
                    
                    
                    
                    <div class="row">
                        <div class="col-sm-6"> 
                            <div class="form-group">
                                <?php print $this->formLabel($quantity); ?>
                                <?php print $this->formElement($quantity); ?>
                                <?php print $this->formElementErrors()->render($quantity, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        
                        <div class="col-sm-6"> 
                            <div class="form-group">
                                <label for="employeeId">Employee</label>                    
                                <select name="employeeId" required="required" id="employeeId" class="form-control">
                                    <option value="" disabled="" selected="" class="ng-binding">Please select</option>   
                                    <?php foreach ($employee as $key => $value) { ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                    <?php } ?>
                                </select>                                    
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="returnable">Returnable</label>                    
                                <input type="hidden" name="returnable" value="N">
                                <input ng-model="rdChk" ng-click="rdClk()" type="checkbox" name="returnable"  id="returnable" class="form-control" value="Y">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="returnDate">Return Date</label>
                                
                                <div class="row">
                                    <div class="col-xs-6 col-sm-6 col-md-6 nopaddinggap">
                                        <input ng-model="rdTxt" ng-disabled="!rdChk" type="text" name="returnDate" id="returnDate" class="form-control" disabled="disabled" value="">
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 minpaddingleft">
                                        <input type="text" ng-model="rdTxtNepali"  ng-disabled="!rdChk"   id="returnDateNepali" class="form-control " value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-sm-6"> 
                            <div class="form-group">
                                <?php print $this->formLabel($purpose); ?>
                                <?php print $this->formElement($purpose); ?>
                                <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>
                       

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>


                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
            </div>
        </div>
        
        
        
        </div>
        <div class="modal-footer">
            <button class="btn btn-defualt" type="button" ng-click="assetIssuecancel()">Cancel</button>
        </div>
  </script>
                        </div>

