<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\news-type')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

?>


<?php
$form->setAttribute('role', 'form');

$newsTypeDesc = $form->get('newsTypeDesc');
$uploadFlag = $form->get('uploadFlag');
$downloadFlag = $form->get('downloadFlag');



$submit = $form->get('submit');
$submit->setAttribute('value', 'Submit');
//
$form->setAttribute('action', $this->url('news-type', ['action' => 'edit', "id" => $id]));


$form->prepare();
print $this->form()->openTag($form);
?>


<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    Add News Type 
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($newsTypeDesc); ?>
                            <?php print $this->formElement($newsTypeDesc); ?>
                            <?php print $this->formElementErrors()->render($newsTypeDesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($uploadFlag); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($uploadFlag); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($downloadFlag); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($downloadFlag); ?>
                            </div>
                        </div>
                    </div>

                </div>

                <span id="beforeSubmitVal" class="errorMsg"></span></br>

                <?php print $this->formSubmit($submit); ?>

            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>
