<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/manager-service/appraisal-final-review/index.js'));
?>


<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.viewLink = '<?php echo $this->url("appraisal-final-review", ["action" => "view"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\appraisal-final-review')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    <input type="hidden" value="<?= $userId; ?>" id="userId" />
    <input type="hidden" value="appraisalFinalReview" id="reportType" />
    <input type="hidden" value="A" id="durationType" />
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i> 
                                Export to Excel 
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Company</label>
                    <select class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Branch</label>
                    <select class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Holiday</label>
                    <select class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <label>Service Type</label>
                    <select class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Service Event</label>
                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Appraisals</label>
                    <?php print $this->formElement($appraisals); ?>
                </div>
                <div class="col-sm-2">
                    <label>Appraisal Stages</label>
                    <?php print $this->formElement($appraisalStages); ?>
                </div> 
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <div class="input-group date" id="fromDate">
                        <input type="text" placeholder="From Date" id="fromDate" name="fromDate"  class="form-control reset-field"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="input-group date" id="nepaliFromDate">
                        <input type="text" placeholder="From Date Nepali" id="nepaliFromDate" name="fromDate" class="form-control reset-field"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="input-group date" id="toDate">
                        <input type="text" placeholder="To Date" id="toDate" name="toDate"  class="form-control reset-field"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="input-group date" id="nepaliToDate">
                        <input type="text" placeholder="To Date Nepali" id="nepaliToDate" name="toDate"  class="form-control reset-field"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button  id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div id="table">

    </div>
</div>