<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));

$this->headScript()->appendFile($this->basePath('js/travel/travel-itnary-request/add.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelItnaryForm');

$fromDate = $form->get('fromDt');
$toDate = $form->get('toDt');
$requestedAmount = $form->get('floatMoney');
$transportType = $form->get('transportType');
//$transportType->setValueOptions($transportTypes);
$purpose = $form->get('purpose');
$remarks = $form->get('remarks');
$noOfDays = $form->get('noOfDays');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('travelItnary', ['action' => 'add']));


$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.employeeList = <?= json_encode($employeeList); ?>;
    document.transportTypes = <?= json_encode($transportTypes); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>New Entry
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
            </div>
            <?php
            print $this->form()->openTag($form);
            ?>

            <div class=" row">

                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <?php print $this->formLabel($fromDate); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($fromDate); ?>
                                <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>     
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nepaliStartDate">&nbsp;</label>
                                <div class="input-group">
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                           class="form-control" value="">
                                </div>
                            </div>
                        </div>     
                    </div>  

                </div>

                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <?php print $this->formLabel($toDate); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($toDate); ?>
                                <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>     
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nepaliEndDate">&nbsp;</label>
                                <div class="input-group">
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                           class="form-control" value="">
                                </div>
                            </div>
                        </div>     
                    </div>  

                </div>

                <div class="col-sm-4">
                    <div
                        class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($noOfDays); ?>
                        <span class="required" aria-required="true">*</span>
                        <?php print $this->formElement($noOfDays); ?>
                        <span id="errorMsg" style="font-size:11px; color:red;"></span>
                    </div>
                    <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                </div>

            </div>


            <div class=" row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <?php print $this->formLabel($purpose); ?>
                        <?php print $this->formElement($purpose); ?>
                        <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <?php print $this->formLabel($requestedAmount); ?>
                        <?php print $this->formElement($requestedAmount); ?>
                        <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                    </div>
                </div>


            </div>

            <div class=" row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <?php print $this->formLabel($transportType); ?>
                        <?php print $this->formElement($transportType); ?>
                        <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                    </div> 
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <?php print $this->formLabel($remarks); ?>
                        <?php print $this->formElement($remarks); ?>
                        <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                    </div>
                </div>
            </div>

            <!--member addition-->
            <div class="row">
                <div class="col-sm-6">
                    <table id="memberDetails" class="table">
                        <thead>
                            <tr>
                                <th>Member</th>       
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <select class="memberSelect" name="employeeId[] required="required">
                                        <option value="<?= $selfId ?>"><?php echo $selfName; ?></option>
                                    </select>
                                </td>
                            </tr>
                        </tbody>
                        <!--<tfoot></tfoot>-->
                    </table>

                </div>
                <div class="col-sm-1">
                    <input class="memberAddBtn btn btn-default" type="button" value="Add +">
                </div>

            </div>


            <!--itnary details addition-->

            <div class="row" >
                <div class="col-md-11" >
                    <table id="itnaryDetails" class="table table-bordered">
                        <thead>
                            <tr>
                                <th colspan="2">Departure</th>       
                                <th colspan="2">Location</th>       
                                <th rowspan="2">Means of TPT</th>       
                                <th colspan="2">Arrives</th>       
                                <th rowspan="2">Remarks</th>       
                                <th rowspan="2">Action</th>       
                            </tr>
                            <tr>
                                <th>Date</th>       
                                <th>Time</th>       
                                <th>From</th>       
                                <th>To</th>       
                                <th>Date</th>       
                                <th>Time</th>       
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div style="overflow:hidden">
                                        <input style="width:100%" type="text" name="depDate[]" required="required"  class="depDate">
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <input style="width:100%" type="text" name="depTime[]"   class="depTime"  data-format="HH:mm" data-template="HH:mm">       
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <input style="width:100%" type="text" name="locFrom[]" required="required"  class="locFrom">       
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <input style="width:100%" type="text" name="locto[]" required="required"  class="locto">       
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <select class='mot' name='mot[]' required="required">
                                        </select>
                                    </div>
                                </td>       
                                <td>
                                    <div style="overflow:hidden">
                                        <input style="width:100%" type="text" name="arrDate[]" required="required"  class="arrDate">       
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <input style="width:100%" type="text" name="arrTime[]"  class="arrTime"  data-format="HH:mm" data-template="HH:mm">
                                    </div>
                                </td>       
                                <td>
                                    <div style="overflow:hidden">
                                        <textarea style="width:100%" rows="4" cols="50" name="detRemarks[]"  class="detRemarks"></textarea>
                                    </div>
                                </td>

                                <td></td>

                            </tr>
<!--                                <tr>
                            <td>
                                <select class="memberSelect" name="employeeId[]">
                                </select>
                            </td>
                        </tr>-->
                        </tbody>
                        <!--<tfoot></tfoot>-->
                    </table>

                </div>
                <div class="col-md-1">
                    <input class="deatilAddBtn btn btn-default" type="button" value="Add +">
                </div>

            </div>

            <?php
            print $this->formSubmit($submit);
            ?>

            <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>

            <?php
            print $this->form()->closeTag();
            ?>



        </div>

    </div>
</div>

