<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/appraisal/setup/add.js'));
//print_r($form); die();
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'appraisalSetup-form');

$appraisalEdesc = $form->get('appraisalEdesc');
$appraisalNdesc = $form->get('appraisalNdesc');
$remarks = $form->get('remarks');
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$appraisalTypeId = $form->get('appraisalTypeId');
$appraisalTypeId->setValueOptions($appraisalTypes);
$currentStageId = $form->get('currentStageId');
$currentStageId->setValueOptions($appraisalStages);
$kpiSetting = $form->get('kpiSetting');
$competenciesSetting = $form->get('competenciesSetting');
$hrFeedbackEnable = $form->get('hrFeedbackEnable');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('detailSetup', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\DetailSetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraisalEdesc); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($appraisalEdesc); ?>
                            <?php print $this->formElementErrors()->render($appraisalEdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraisalNdesc); ?>
                            <?php print $this->formElement($appraisalNdesc); ?>
                            <?php print $this->formElementErrors()->render($appraisalNdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($appraisalTypeId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($appraisalTypeId); ?>
                            <?php print $this->formElementErrors()->render($appraisalTypeId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($startDate); ?>
                                    <?php print $this->formElement($startDate); ?>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>     
                    </div>

                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($endDate); ?>
                                    <?php print $this->formElement($endDate); ?>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>     
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($currentStageId); ?>
                            <?php print $this->formElement($currentStageId); ?>
                            <?php print $this->formElementErrors()->render($currentStageId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($kpiSetting); ?>
                            <div class="md-radio-inline">
                                <?php $customRender($kpiSetting); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($kpiSetting, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($competenciesSetting); ?>
                            <div class="md-radio-inline">
                                <?php $customRender($competenciesSetting); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($competenciesSetting, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($hrFeedbackEnable); ?>
                            <div class="md-radio-inline">
                                <?php $customRender($hrFeedbackEnable); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($hrFeedbackEnable, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>