<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/loan/loan-status/index.js'));
?>

<script>
    document.ids =<?php echo json_encode(["loanId" => -1, "loanRequestStatusId" => -1, "fromDate1" => "", "nepaliFromDate" => "", "toDate1" => "", "nepaliToDate" => ""]) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.rectifyLink = '<?= $this->url("loanApply", ["action" => "rectify"]) ?>';
    document.viewLink = '<?= $this->url("loanStatus", ["action" => "view"]) ?>';
    document.editLink = '<?= $this->url("loanStatus", ["action" => "edit"]) ?>';
    document.loanClosing = '<?= $this->url("loanApply", ["action" => "loanClosing"]) ?>';
    document.pullLoanRequestStatusListLink = '<?= $this->url("loanStatus", ["action" => "pullLoanRequestStatusList"]) ?>';
    document.preference =<?php echo json_encode($preference) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\loanStatus')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title"> 
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Search</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <label>Company</label>
                <select class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Branch</label>
                <select class="form-control" name="branchId" id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Department</label>
                <select class="form-control" name="department" id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Designation</label>
                <select class="form-control" name="designation" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Position</label>
                <select class="form-control" name="position" id="positionId">
                </select>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Service Type</label>
                <select class="form-control" name="serviceType" id="serviceTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Service Event Type</label>
                <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee Type</label>
                <select class="form-control" name="employeeType" id="employeeTypeId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Employee</label>
                <select class="form-control" name="employee" id="employeeId">
                </select>
            </div>
            <div class="col-sm-2 ">
                <label>Loan Type</label>
                <?php print $this->formElement($loans); ?>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2 ">
                <label>Status</label>
                <?php print $this->formElement($loanStatus); ?>
            </div>
            <div class="col-sm-2">
                <label>From Date Nepali</label>
                <input type="text" id="fromDate" name="fromDate" class="form-control reset-field" placeholder="From Date"/>
            </div>
            <div class="col-sm-2">
                <label>From Date Nepali</label>
                <input type="text" id="nepaliFromDate" name="nepaliFromDate"  class="form-control reset-field" placeholder="From Date Nepali"/>

            </div>
            <div class="col-sm-2">
                <label>To Date</label>
                <input type="text"  id="toDate" name="toDate"  class="form-control reset-field" placeholder="To Date"/>
            </div>
            <div class="col-sm-2">
                <label>To Date Nepali</label>
                <input type="text"  id="nepaliToDate" name="nepaliToDate" class="form-control reset-field" placeholder="To Date Nepali"/>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-sm-2">
                <label>Loan Status</label>
                <select class="form-control reset-field" name="loanStatus" id="loanStatus">
                    <option value="BOTH">Both</option>
                    <option value="OPEN">Open</option>
                    <option value="CLOSED">Closed</option>
                </select>
            </div>
            <div class=" col-sm-offset-8 col-sm-4">
                <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <button  id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div>

<div class="margin-top-20">  
    <div id="loanRequestStatusTable">
    </div>
</div>