<?php
/**
 * Created by PhpStorm.
 * User: himal
 * Date: 7/17/16
 * Time: 12:17 PM
 */

$title = 'Delete album';
$url   = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>

<h1><?php print $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?php print $this->escapeHtml($album->title) ?>" by
    "<?php print $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?php print $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php print (int) $album->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>
