<?php
/**
 * Created by PhpStorm.
 * User: himal
 * Date: 7/17/16
 * Time: 12:17 PM
 */

$title = 'Edit album';
$this->headTitle($title);
?>

<h1><?php print $this->escapeHtml($title) ?></h1>
<?php
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php print $this->formLabel($album) ?>
    <?php print $this->formElement($album) ?>
    <?php print $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?php print $this->formLabel($artist) ?>
    <?php print $this->formElement($artist) ?>
    <?php print $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();