<?php
/**
 * Created by PhpStorm.
 * User: himal
 * Date: 7/17/16
 * Time: 12:17 PM
 */

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php print $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?php print $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php print $this->escapeHtml($album->title) ?></td>
            <td><?php print $this->escapeHtml($album->artist) ?></td>
            <td>
                <a href="<?php print $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                <a href="<?php print $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>