<?php
$form->setAttribute('role', 'form');

$leaveCode = $form->get('leaveCode');
$leaveEname = $form->get('leaveEname');
$leaveLname = $form->get('leaveLname');
$allowHalfday = $form->get('allowHalfday');
$defaultDays = $form->get('defaultDays');
$fiscalYear = $form->get('fiscalYear');
$carryForward = $form->get('carryForward');
$cashable = $form->get('cashable');

$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'Add Leave');

$form->setAttribute('action', $this->url('leavesetup', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveSetup"]];echo json_encode($menu);?>;
    </script>

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 padding-30 bg-light-color">
            <div class="panel-heading panel-title-head">
                <h4>Position</h4>
            </div>
            <div class="panel-body">
                <div class="form-group form-group-default <?= empty($leaveCode->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($leaveCode); ?>
                    <?php print $this->formElement($leaveCode); ?>
                </div>
                <?php print $this->formElementErrors()->render($leaveCode, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($leaveEname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($leaveEname); ?>
                    <?php print $this->formElement($leaveEname); ?>
                </div>
                <?php print $this->formElementErrors()->render($leaveEname, ['class' => 'help-block error']); ?>

                <div class="form-group form-group-default <?= empty($leaveLname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($leaveLname); ?>
                    <?php print $this->formElement($leaveLname); ?>
                </div>
                <?php print $this->formElementErrors()->render($leaveLname, ['class' => 'help-block error']); ?>

                <div class="padding-5">
                    <div class="row  bg-master-lightest">
                        <div class=" col-sm-6 ">
                            <div class="form-group padding-15">
                                <?php print $this->formLabel($allowHalfday); ?>
                                <div class="radio radio-success">
                                    <?php $customRenderer($allowHalfday); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($allowHalfday, ['class' => 'help-block error']); ?>
                            <div class="form-group padding-15">
                                <?php print $this->formLabel($defaultDays); ?>
                                <div class="radio radio-success">
                                    <?php $customRenderer($defaultDays); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($defaultDays, ['class' => 'help-block error']); ?>
                            <div class="form-group padding-15">
                                <?php print $this->formLabel($cashable); ?>
                                <div class="radio radio-success">
                                    <?php $customRenderer($cashable); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($cashable, ['class' => 'help-block error']); ?>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group padding-15">
                                <?php print $this->formLabel($fiscalYear); ?>
                                <div class="radio radio-success">
                                    <?php $customRenderer($fiscalYear); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($fiscalYear, ['class' => 'help-block error']); ?>

                            <div class="form-group padding-15">
                                <?php print $this->formLabel($carryForward); ?>
                                <div class="radio radio-success">
                                    <?php $customRenderer($carryForward); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($carryForward, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>


                <div class="form-group form-group-default">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>

                <?php print $this->formSubmit($submit); ?>

            </div>

        </div>
    </div>
<?php

print $this->form()->closeTag();

?>