<?php
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveSetup/addForm.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'leaveSetup-form');

$leaveCode = $form->get('leaveCode');
$leaveEname = $form->get('leaveEname');
$leaveLname = $form->get('leaveLname');
$allowHalfday = $form->get('allowHalfday');
$defaultDays = $form->get('defaultDays');
$fiscalYear = $form->get('fiscalYear');
$carryForward = $form->get('carryForward');
$paid = $form->get('paid');
$cashable = $form->get('cashable');

$companyId = $form->get('companyId');
$companyId->setValueOptions($companies);

$remarks = $form->get('remarks');

$fiscalYear->setValueOptions($fiscalYears);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('leavesetup', ['action' => 'add']));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leavesetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>

            </div>
            <div class="portlet-body">

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($leaveCode->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($leaveCode); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($leaveCode); ?>
                            <span class="errorMsg" style="font-size:11px; color:red;"></span>
                            <?php print $this->formElementErrors()->render($leaveCode, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($leaveEname->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($leaveEname); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($leaveEname); ?>
                            <span class="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($leaveEname, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($leaveLname->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($leaveLname); ?>
                            <?php print $this->formElement($leaveLname); ?>
                            <span class="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($leaveLname, ['class' => 'help-block error']); ?>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($companyId->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($companyId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($companyId); ?>
                            <span class="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($companyId, ['class' => 'help-block error']); ?>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($fiscalYear->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($fiscalYear); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($fiscalYear); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($fiscalYear, ['class' => 'help-block error']); ?>
                    </div>


                </div>


                <div class="padding-5">
                    <div class="row  bg-master-lightest">
                        <div class=" col-sm-4 ">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($allowHalfday); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($allowHalfday); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($allowHalfday, ['class' => 'help-block error']); ?>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($defaultDays); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($defaultDays); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($defaultDays, ['class' => 'help-block error']); ?>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($paid); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($paid); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($paid, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="row bg-master-lightest">
                        <div class="col-sm-4">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($cashable); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($cashable); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($cashable, ['class' => 'help-block error']); ?>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($carryForward); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($carryForward); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($carryForward, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>


                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                </div>

                <?php print $this->formSubmit($submit); ?>
                <?php print $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>