<?php
$form->setAttribute('role', 'form');

$leaveCode = $form->get('leaveCode');
$leaveEname = $form->get('leaveEname');
$leaveLname = $form->get('leaveLname');
$allowHalfday = $form->get('allowHalfday');
$defaultDays = $form->get('defaultDays');
$fiscalYear = $form->get('fiscalYear');
$carryForward = $form->get('carryForward');
$cashable = $form->get('cashable');

$remarks = $form->get('remarks');

$fiscalYear->setValueOptions($fiscalYears);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('leavesetup', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveSetup"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leavesetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>UPDATE
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group <?= empty($leaveCode->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($leaveCode); ?>
                    <?php print $this->formElement($leaveCode); ?>
                </div>
                <?php print $this->formElementErrors()->render($leaveCode, ['class' => 'help-block error']); ?>

                <div class="form-group  <?= empty($leaveEname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($leaveEname); ?>
                    <?php print $this->formElement($leaveEname); ?>
                </div>
                <?php print $this->formElementErrors()->render($leaveEname, ['class' => 'help-block error']); ?>

                <div class="form-group <?= empty($leaveLname->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($leaveLname); ?>
                    <?php print $this->formElement($leaveLname); ?>
                </div>
                <?php print $this->formElementErrors()->render($leaveLname, ['class' => 'help-block error']); ?>

                <div
                    class="form-group <?= empty($fiscalYear->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($fiscalYear); ?>
                    <?php print $this->formElement($fiscalYear); ?>
                </div>
                <?php print $this->formElementErrors()->render($fiscalYear, ['class' => 'help-block error']); ?>


                <div class="padding-5">
                    <div class="row  bg-master-lightest">
                        <div class=" col-sm-6 ">
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($allowHalfday); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($allowHalfday); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($allowHalfday, ['class' => 'help-block error']); ?>
                            <div class="form-group padding-0">
                                <?php print $this->formLabel($defaultDays); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($defaultDays); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($defaultDays, ['class' => 'help-block error']); ?>
                        </div>
                        <div class="col-sm-6">

                            <div class="form-group padding-0">
                                <?php print $this->formLabel($cashable); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($cashable); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($cashable, ['class' => 'help-block error']); ?>


                            <div class="form-group padding-0">
                                <?php print $this->formLabel($carryForward); ?>
                                <div class="md-radio-inline">
                                    <?php $customRenderer($carryForward); ?>
                                </div>
                            </div>
                            <?php print $this->formElementErrors()->render($carryForward, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>

                <?php print $this->formSubmit($submit); ?>
                <?PHP print $this->form()->closeTag(); ?>

            </div>
        </div>

    </div>
</div>
