<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/media/js/dataTables.bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/datatables.responsive.js'));
$this->headScript()->appendFile($this->basePath('plugins/datatables-responsive/js/lodash.min.js'));
$this->headScript()->appendFile($this->basePath('js/datatables.js'));

$this->headScript()->appendFile($this->basePath('js/leave-setup/index.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuLeaveManagement", "subMenu" => ["id" => "subMenuLeaveSetup"]];echo json_encode($menu);?>;
</script>

<?php
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>

<div class="panel bg-white customShadow">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a class="btn btn-success" href="<?= $this->url('leavesetup', ['action' => 'add']) ?>">
                Add new
            </a>
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings</a>
                </li>
                <li><a href="#">Help</a>
                </li>
            </ul>
        </div>
        <div class="pull-left">
            <div class="">
                <input type="text" id="search-table" class="form-control pull-left" placeholder="Search">
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body panel-info">
        <div class="table-responsive">
            <table class="table table-bordered bg-master-lighter table-striped small-table" id="tableWithSearch">
                <thead>
                <tr role="row">
                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                        Leave Code
                    </th>

                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                        Leave Name
                    </th>
                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                        Allow Halfday
                    </th>
                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                        Default Days
                    </th>

                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                        Carry Forward
                    </th>
                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                        Cashable
                    </th>
                    <th aria-label="Title: activate to sort column ascending" aria-sort="descending" colspan="1"
                        rowspan="1"
                        aria-controls="basicTable" tabindex="0" class="sorting_desc">
                       Action
                    </th>

                </tr>
                </thead>
                <tbody>

                <?php foreach ($leaveList as $leave):
                    ?>
                    <tr role="row">
                        <td class="">
                            <p>
                                <?php print $this->escapeHtml($leave['LEAVE_CODE']); ?>
                            </p>
                        </td>
                        <td class="">
                            <p>
                                <?php print $this->escapeHtml($leave['LEAVE_ENAME']); ?>
                            </p>
                        </td>
                        <td class="">
                            <p>
                                <?php print $this->escapeHtml($getValue($leave['ALLOW_HALFDAY'])); ?>
                            </p>
                        </td>
                        <td class="">
                            <p>
                                <?php print $this->escapeHtml($getValue($leave['DEFAULT_DAYS'])); ?>
                            </p>
                        </td>
                        <td class="">
                            <p>
                                <?php print $this->escapeHtml($getValue($leave['CARRY_FORWARD'])); ?>
                            </p>
                        </td>
                        <td class="">
                            <p>
                                <?php print $this->escapeHtml($getValue($leave['CASHABLE'])); ?>
                            </p>
                        </td>
                        <td class="">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">
                                    <a class="fa fa-edit btn-link"
                                       href="<?= $this->url("leavesetup", ["action" => "edit", "id" => $leave['LEAVE_ID']]); ?>">
                                    </a>
                                </button>
                                <button type="button" class="btn btn-default">
                                    <a class="fa fa-trash-o btn-link"
                                       href="<?= $this->url("leavesetup", ["action" => "delete", "id" => $leave['LEAVE_ID']]); ?>"></a>
                                </button>
                            </div>
                        </td>
                    </tr>

                <?php endforeach; ?>

                </tbody>
            </table>
        </div>

    </div>
</div>