<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/LeaveManagement/LeaveSetup/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>


<script>
    document.leaves =<?= json_encode($leaves); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leavesetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('leavesetup', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="leaveTable">
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (LEAVE_ENAME == null) ? '-' : LEAVE_ENAME #
        </td>
        <td>
        #: (COMPANY_NAME == null) ? '-' : COMPANY_NAME #
        </td>
        <td>
        #: (ALLOW_HALFDAY == null) ? '-' : ALLOW_HALFDAY #
        </td>
        <td>
        #: (DEFAULT_DAYS == null) ? '-' : DEFAULT_DAYS #
        </td>
        <td>
        #: (CARRY_FORWARD == null) ? '-' : CARRY_FORWARD #
        </td>
        <td>
        #: (CASHABLE == null) ? '-' : CASHABLE #
        </td>
        <td>
        #: (PAID == null) ? '-' : PAID #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("leavesetup", ["action" => "edit"]); ?>/#:LEAVE_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
        # if(IS_SUBSTITUTE=='N') { #
        <a class="btn-delete confirmation"
        href="<?= $this->url("leavesetup", ["action" => "delete"]); ?>/#:LEAVE_ID #"  id="bs_#:LEAVE_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        # } #
        </td>
        </tr>
    </script>
</div>