<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>

              <h4 class="modal-title">Filter For Employees</h4>
            </div>
        
          
            <div class="modal-body"> 
                <div class="row">
                    <div class="col-sm-4">
                        <label for="companyId">Company</label>
                        <select class="form-control" name="company" id="companyId">
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <label for="branchId">Branch</label>
                        <select class="form-control" name="branchId" id="branchId">
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <label for="departmentId">Department</label>
                        <select class="form-control" name="department" id="departmentId">
                        </select>
                    </div>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div class="col-sm-4">
                        <label for="designationId">Designation</label>
                        <select class="form-control" name="designation" id="designationId">
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <label for="positionId">Position</label>
                        <select class="form-control" name="position" id="positionId">
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <label for="employeeTypeId">Employee Type</label>
                        <select class="form-control" name="employeeType" id="employeeTypeId">
                            <option value="-1">All Employee Type</option>
                            <option value="R">Employee</option>
                            <option value="C">Worker</option>
                        </select>
                    </div>
                </div>
                
                <div class="row" style="margin-top:10px;">
                    <div class="col-sm-4">
                        <label for="serviceTypeId">Service Type</label>
                        <select class="form-control" name="serviceType" id="serviceTypeId">
                        </select>
                    </div>

                    <div class="col-sm-4">
                        <label for="serviceEventTypeId">Working</label>
                        <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                        </select>
                    </div>

                    <div class="col-sm-4">
                        <label for="genderId">Gender</label>
                        <select class="form-control" name="gender" id="genderId">
                        </select>
                    </div>
                </div>
                <div class="row">                   
                    <div class="col-sm-3">
                        <label height="45"></label>
                        <button id="filterForRole" class="btn btn-default form-control i-search">
                        Search
                        <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>  
        </div> 
    </div>
</div>