<?php
//Load JS files here
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
        

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/system/system-utility/query.js'));

?>    


<script> 
    document.executeQueryLink = '<?= $this->url("system-utility", ["action" => "query"]) ?>';
    document.acl =<?php echo json_encode($acl); ?>;
</script> 

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Employee')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong>';
    print $this->messages[1];
    print '</div>';
}
?> 
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div id="employeeList" >
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
        <div class="row">
        
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-gre
                      en-haze uppercase"> Enter Query Here</span>
                
                <div class="actions" style="float: right; display: inline-block ">
                    <div class="btn-group">
                        <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-copy"></i> Tools
                            <i class="fa fa-angle-down "></i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li >
                                <a id="excelExport" href="javascript:;" class="hris-export-to-excel" hris-export-to-excel-target="queryReportTable">
                                    <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                            </li>
                            <li >
                                <a id="pdfExport" href="javascript:;" class="hris-export-to-pdf" hris-export-to-pdf-target="queryReportTable">
                                <i class="fa fa-file-pdf-o" ></i> Export to PDF </a>
                            </li>
                        </ul>
                        </div>
                    </div>
            </div>
            <div class="col-sm-4 ">
                    <textarea style="resize:none;" name="query_input" id="query_input" cols="130" rows="10"></textarea>  
                </div>
        </div>
            
        <div class="col-sm-4 col-sm-offset-8">
            <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                Reset
                <i class="fa fa-refresh"></i>
            </button>
            <button id="search" class="btn btn-default btn-sm pull-right">
                Run Query
                <i class="fa fa-search"></i>
            </button>
        </div>
            </div>
            </div>
    

    <div id="table">
    </div>
</div>