<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/system/system-utility/re-attendance.js'));

?>
<?php if ($this->messages): ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php endif; ?>
<?php
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

?>
<script>
    document.employeeList =<?= json_encode($employeeList); ?>;
    document.searchValues =<?= json_encode($searchValues); ?>;
    document.employeeFilter = '<?= $this->url('system-utility', ['action' => 'pullEmployeeFilter']); ?>';
    document.regenAttendanceLink = '<?php echo $this->url('system-utility', ['action' => 'regen-attendance']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\system-utility')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="row margin-top-30">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-edit"></i>
                    Reattendance
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>

            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group required  ">
                                    <label for="fromDate">From</label>                                    
                                    <span class="required" aria-required="true">*</span>
                                    <input type="text" name="fromDate" required="required" id="fromDate" class="form-control" vstartDatealue="">                                
                                </div>

                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepalifromDate">&nbsp;</label>
                                    <input type="text" name="nepalifromDate" id="nepaliFromDate" class="form-control " value="" >
                                </div>
                            </div>     
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group required  ">
                                    <label for="toDate">To</label>                                    
                                    <span class="required" aria-required="true">*</span>
                                    <input type="text" name="toDate" required="required" id="toDate" class="form-control" vstartDatealue="">                                
                                </div>

                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepalitoDate">&nbsp;</label>
                                    <input type="text" name="nepalitoDate" id="nepaliToDate" class="form-control " value="" >
                                </div>
                            </div>     
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="employeeId">Employees</label>
                            <span class="required" aria-required="true">*</span>
                            <select multiple name="employeeId" required="required" id="employeeId" class="form-control">
                            </select>
                        </div>

                    </div>
                    <div class="col-sm-2">
                        <div class="col-sm-6">

                            <a id="btn-filter" class="btn-edit" style="margin-top: 24px; height:28px; padding: 2px 7px !important;">
                                <i class="fa fa-filter" style="height:17px;"></i>      
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <input type="button" name="submit" class="btn btn-success pull-right" style="margin-top: 24px; height:28px !important;" id="btn-reAttendnace" value="Submit">
                        </div>
                    </div>


                </div>

            </div>

        </div>
    </div>
</div>

<?php print $this->partial('partials/re-attendance-modal.phtml'); ?>