<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/jquery-validation/js/jquery.validate.min.js'));
$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
        ->appendFile($this->basePath('js/search.js'));

$this->headScript()->appendFile($this->basePath('js/overtime/automation/wizard.js'));
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.handleWizardUrl = '<?php echo $this->url('overtimeAutomation', ['action' => 'handleWizard']); ?>';
    document.editData =<?php echo json_encode($editData); ?>;
    document.overtimeAutomationPage = '<?php echo $this->url('overtimeAutomation', ['action' => 'index']); ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\overtimeAutomation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="portlet light bordered" id="wizard">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Compulsory Overtime - <span class="step-title">
                Step 1 of 3 </span>
        </div>
        <div class="tools hidden-xs">
            <a class="fullscreen" href="javascript:;" ></a>
        </div>
    </div>
    <div class="portlet-body form">
        <div class="form-wizard">
            <div class="form-body">
                <ul class="nav nav-pills nav-justified steps">
                    <li>
                        <a href="#tab1" data-toggle="tab" class="step">
                            <span class="number">
                                1 </span>
                            <span class="desc">
                                <i class="fa fa-check"></i> Setup </span>
                        </a>
                    </li>
                    <li>
                        <a href="#tab2" data-toggle="tab" class="step">
                            <span class="number">
                                2 </span>
                            <span class="desc">
                                <i class="fa fa-check"></i> Assign </span>
                        </a>
                    </li>
                    <li>
                        <a href="#tab3" data-toggle="tab" class="step active">
                            <span class="number">
                                3 </span>
                            <span class="desc">
                                <i class="fa fa-check"></i> Finalize </span>
                        </a>
                    </li>
                </ul>
                <div id="bar" class="progress progress-striped" role="progressbar">
                    <div class="progress-bar progress-bar-success">
                    </div>
                </div>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                        <!--Start of tab1-->
                        <form id="setup-form">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group  required  ">
                                        <label for="compulsoryOtDesc">Description</label>                                        
                                        <input type="text" name="compulsoryOtDesc" required="required" id="compulsoryOtDesc" class="form-control" > 
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group  required  ">
                                                <label for="startDate">StartDate</label>                                        
                                                <input type="text" name="startDate" required="required" id="startDate" class="form-control" > 
                                            </div>
                                        </div>    

                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliStartDate">&nbsp;</label>
                                                <input type="text" name="nepaliStartDate" id="nepaliStartDate" class="form-control" >
                                            </div>    
                                        </div> 
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group required  ">
                                                <label for="endDate">End Date</label>                                                    
                                                <input type="text" name="endDate" id="endDate" class="form-control" value="">                                    
                                            </div>
                                        </div>     
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="nepaliEndDate">&nbsp;</label>
                                                <input type="text" name="nepaliEndDate" id="nepaliEndDate" class="form-control" >
                                            </div>
                                        </div>     
                                    </div>   

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="earlyOvertimeHour">Early Overtime Hour</label>                         
                                        <div class="input-group dropdown-select">
                                            <input  data-format="h:mm" data-template="hh : mm" class="form-control" type="text" name="earlyOvertimeHour" id="earlyOvertimeHour"/>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group ">
                                        <label for="lateOvertimeHour">Late Overtime Hour</label>                            
                                        <div class="input-group dropdown-select">
                                            <input  data-format="h:mm" data-template="hh : mm" class="form-control" type="text" name="lateOvertimeHour" id="lateOvertimeHour" />
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </form>
                        <!--end of tab1-->
                    </div>
                    <div class="tab-pane" id="tab2">

                        <!--adjustment shift assign start-->
                        <div class="row">
                            <div class="col-sm-2">
                                <select class="form-control" name="company" id="companyId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="branchId" id="branchId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="department" id="departmentId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="designation" id="designationId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="position" id="positionId">
                                </select>
                            </div>
                        </div>
                        <div class="row margin-top-10 margin-bottom-20">
                            <div class="col-sm-2">
                                <select class="form-control" name="serviceType" id="serviceTypeId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="gender" id="genderId">
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <select class="form-control" name="employee" id="employeeId">
                                </select>
                            </div>
                            <div class="col-sm-4 ">
                                <button type="button" id="searchBtn" class="btn btn-default btn-sm pull-right">
                                    Search
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>


                        <div class="scroller"  style="min-height:300px;height: 400px;" id="loadingDiv">
                            <table id="employeeTable" class="table table-striped table-bordered table-hover no-footer custometbletwo">
                                <thead>
                                    <tr>
                                        <th>
                                            Employee
                                        </th>
                                        <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                                            <div class="th-inner ">
                                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                    <input class="" type="checkbox" id="checkAll"/>
                                                    <span></span>
                                                </label>
                                            </div>
                                            <div class="fht-cell" style="width: 46px;"></div>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>   
                    </div>
                    <div class="tab-pane" id="tab3">
                        <h3 class="form-section">Setup</h3>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3">Description</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static" id="compulsoryOtDescLabel"></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3">Start Date</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static" id="startDateLabel"></p>
                                    </div>
                                </div>
                            </div>
                            <!--/span-->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3">End Date</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static" id="endDateLabel"></p>
                                    </div>
                                </div>
                            </div>
                            <!--/span-->
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3">Start Time</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static" id="earlyOvertimeHourLabel"></p>
                                    </div>
                                </div>
                            </div>
                            <!--/span-->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3">End Time</label>
                                    <div class="col-md-9">
                                        <p class="form-control-static" id="lateOvertimeHourLabel"></p>
                                    </div>
                                </div>
                            </div>
                            <!--/span-->
                        </div>
                        <h3 class="form-section">Employees Assigned</h3>
                        <div  class="scroller row" style="height:250px" id="assignedEmployeeList">

                        </div>
                    </div>

                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class=" col-md-12">
                        <a href="javascript:;" class="btn default button-previous pull-left">
                            <i class="m-icon-swapleft"></i> Back </a>
                        <a href="javascript:;" class="btn blue button-next pull-right">
                            Continue <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                        <a href="javascript:;" class="btn green button-submit pull-right">
                            Submit <i class="m-icon-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

