<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/SelfService/travel-notification/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.list =<?php echo json_encode($list); ?>
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelNotification')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">      
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>      
        </div>
    </div>    
    <div id="travelNotificationTable">
    </div>
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (FIRST_NAME == null) ? ' ' : FIRST_NAME #
        #: (MIDDLE_NAME == null) ? ' ' : MIDDLE_NAME #
        #: (LAST_NAME == null) ? ' ' : LAST_NAME #
        </td>
        <td>
        #: (TRAVEL_CODE == null) ? '-' : TRAVEL_CODE #
        </td>
        <td>
        #: (FROM_DATE == null) ? '-' : FROM_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
        </td>
        <td>
        #: (DESTINATION == null) ? '-' : DESTINATION #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>
        #: (SUB_APPROVED_FLAG == null) ? '-' : SUB_APPROVED_FLAG #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("travelNotification", ["action" => "view"]) ?>/#: TRAVEL_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i>
        </a>
        </td>
        </tr>
    </script>
</div>