<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/SelfService/travel-notification/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled" => "disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled" => "disabled"]);
$destination = $form->get('destination');
$destination->setAttributes(["disabled" => "disabled"]);
$purpose = $form->get('purpose');
$purpose->setAttributes(["disabled" => "disabled"]);
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
$requestedType->setAttributes(["disabled" => "disabled"]);
$transportType = $form->get('transportType');
$transportType->setValueOptions($transportTypes);
$transportType->setAttributes(['disabled' => "disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled" => "disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');
$submit->setAttribute('id', 'approve');

$form->setAttribute('action', $this->url('travelNotification', ['action' => 'view', 'id' => $id]));
$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelNotification')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php print $this->form()->openTag($form); ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Substitute Work Request
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div>
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Employee Name
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $employeeName; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>
                                    <?php if ($advanceAmt > 0) { ?>
                                        <tr height="30">
                                            <td>
                                                Advance Amount
                                            </td>
                                            <td width="15">:</td>
                                            <td>
                                                Rs.<?php echo $advanceAmt; ?>
                                            </td>
                                        </tr>
                                    <?php } ?>

                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDate; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>                               
                                </table>
                            </div>
                            
                            <div class="col-sm-4">
                                <table>  
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == 'RQ') {
                                                echo "Pending";
                                            } else if ($status == 'RC') {
                                                echo "Recommended";
                                            } else if ($status == 'AP') {
                                                echo "Approved";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($fromDate); ?>
                                        <?php print $this->formElement($fromDate); ?>
                                        <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliStartDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>        

                        </div>

                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <?php print $this->formLabel($toDate); ?>
                                        <?php print $this->formElement($toDate); ?>
                                        <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                                    </div>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliEndDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>        

                        </div>
                    </div>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($destination); ?>
                                <?php print $this->formElement($destination); ?>
                                <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                            </div>               
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($purpose); ?>
                                <?php print $this->formElement($purpose); ?>
                                <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($requestedType); ?>
                                <?php print $this->formElement($requestedType); ?>
                                <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                            </div>   
                        </div>
                    </div>

                    <div class=" row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($transportType); ?>
                                <?php print $this->formElement($transportType); ?>
                                <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                            </div> 
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($requestedAmount); ?>
                                <?php print $this->formElement($requestedAmount); ?>
                                <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <?php print $this->formLabel($remarks); ?>
                                <?php print $this->formElement($remarks); ?>
                                <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>


                    <?php
                    if ($subEmployeeId != null) {
                        $disabled = ($subApprovedFlag != null) ? "disabled" : "";
                        if ($subApprovedFlag == 'Y') {
                            $note = "[Approved]";
                        } else if ($subApprovedFlag == 'N') {
                            $note = "[Rejected]";
                        } else {
                            $note = "[Pending]";
                        }
                        ?>
                        <div class="form-group padding-0">
                            <label for="noOfDays">
                                Substitute Employee 
                            </label>
                            <div>
                                <select disabled="disabled" class="form-control" name="travelSubstitute">
                                    <?php
                                    foreach ($employeeList as $key => $value) {
                                        $selected = ($key == $subEmployeeId) ? "selected" : "";
                                        ?>
                                        <option style="cursor: pointer;" value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div
                            class="form-group margin-top-10 required">
                            <label>Reason for action [From Sub. Employee] <?php echo $note; ?></label>
                            <textarea <?php echo $disabled; ?> name="subRemarks" id="form-subRemarks" class="form-subRemarks form-control" style="height: 50px; font-size:12px" required="required"><?php echo $subRemarks; ?></textarea>
                        </div>
                    <?php } ?>
                </div>
                <?php if ($subApprovedFlag == null) { ?>
                    <div class="form-group">
                        <?php
                        print $this->formSubmit($submit);
                        ?>
                        <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<?php
print $this->form()->closeTag();
?>
   