<?php
$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/SelfService/travel-request/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled"=>"disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled"=>"disabled"]);
$travelCode = $form->get('travelCode');
$travelCode->setAttributes(["disabled"=>"disabled"]);
$destination = $form->get('destination');
$destination->setAttributes(["disabled"=>"disabled"]);
$purpose = $form->get('purpose');
$purpose->setAttributes(["disabled"=>"disabled"]);
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
$requestedType->setAttributes(["disabled"=>"disabled"]);
$transportType = $form->get('transportType');
$transportType->setValueOptions($transportTypes);
$transportType->setAttributes(['disabled'=>"disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled"=>"disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled"=>"disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled"=>"disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled"=>"disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('travelNotification', ['action' => 'view','id'=>$id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuSelfService","subMenu"=>["id"=>"subMenuTravelRequest"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
        document.urlCss='<?= $this->basePath('css/custom.css') ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelNotification')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20" ng-app="hris" ng-controller="advanceRequestController">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Substitute Work Request
                </div>
            </div>
            <div class="portlet-body">
                <div>
                <div class="form-group">
                    <div class="row div-font-11">
                        <div class="col-md-6">
                            <table>
                                <tr height="30">
                                    <td>
                                        Requested Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $requestedDate; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Recommender
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $recommender; ?>
                                    </td>
                                </tr>
                                <?php if($advanceAmt>0){ ?>
                                    <tr height="30">
                                        <td>
                                            Advance Amount
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            Rs.<?php echo $advanceAmt; ?>
                                        </td>
                                    </tr>
                                <?php } ?>
                                
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>  
                                <tr height="30">
                                    <td>
                                        Status
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php
                                        if ($status == 'RQ') {
                                            echo "Pending";
                                        } else if ($status == 'RC') {
                                            echo "Recommended";
                                        } else if ($status == 'AP') {
                                            echo "Approved";
                                        } else if ($status == "R") {
                                            echo "Rejected";
                                        } else if ($status == "C") {
                                            echo "Cancelled";
                                        } ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Approver
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $approver; ?>
                                    </td>
                                </tr>                               
                            </table>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($travelCode); ?>
                    <?php print $this->formElement($travelCode); ?>
                    <?php print $this->formElementErrors()->render($travelCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($fromDate); ?>
                    <div class="input-group date" id="fromDate">
                        <?php print $this->formElement($fromDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($toDate); ?>
                    <div class="input-group date" id="toDate">
                        <?php print $this->formElement($toDate); ?>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    </div>
                    <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($destination); ?>
                    <?php print $this->formElement($destination); ?>
                    <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                </div>               
                <div class="form-group">
                    <?php print $this->formLabel($purpose); ?>
                    <?php print $this->formElement($purpose); ?>
                    <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($requestedType); ?>
                    <?php print $this->formElement($requestedType); ?>
                    <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                </div>   
                <div class="form-group">
                    <?php print $this->formLabel($transportType); ?>
                    <?php print $this->formElement($transportType); ?>
                    <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                </div> 
                <div class="form-group">
                    <?php print $this->formLabel($requestedAmount); ?>
                    <?php print $this->formElement($requestedAmount); ?>
                    <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                if($subEmployeeId!=null){
                        $disabled = ($subApprovedFlag!=null) ? "disabled" : "";
                        if($subApprovedFlag=='Y'){
                            $note = "[Approved]";
                        }else if($subApprovedFlag=='N'){
                            $note = "[Rejected]";
                        }else{
                            $note = "[Pending]";
                        }
                    ?>
                    <div class="form-group padding-0">
                        <label for="noOfDays">
                                Substitute Employee 
                        </label>
                        <div>
                            <select disabled="disabled" class="form-control" name="travelSubstitute">
                            <?php foreach($employeeList as $key=>$value){ 
                                $selected = ($key==$subEmployeeId) ? "selected" : "";
                                ?>
                                <option style="cursor: pointer;" value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
                            <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div
                        class="form-group margin-top-10 required">
                        <label>Reason for action [From Sub. Employee] <?php echo $note; ?></label>
                        <textarea <?php echo $disabled; ?> name="subRemarks" id="form-subRemarks" required="required" class="form-subRemarks form-control" style="height: 50px; font-size:12px"><?php echo $subRemarks;  ?></textarea>
                    </div>
                    <?php } ?>
                </div>
                <?php if($subApprovedFlag==null){ ?>
                <div class="form-group">
                <?php
                    print $this->formSubmit($submit);
                    ?>
                    <input type="submit" name="submit" class="btn btn-success pull-right" value="Reject">
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<?php

print $this->form()->closeTag();

?>
   