<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/manager-service/training-approve/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.deleteURL = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.trainingApprove =<?php echo json_encode($trainingApprove) ?>;
    document.viewLink = '<?= $this->url("trainingApprove", ["action" => "view"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.approveRejectUrl = '<?php echo $this->url('trainingApprove', ['action' => 'batchApproveReject']); ?>';
</script>    


<div class="margin-top-20">

    <div class="portlet light bg-inverse">

        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>



        <div id="trainingApproveTable">
        </div>

        <div style="display: none;" class="row margin-top-20" id="acceptRejectDiv" >
            <div class="col-sm-2 ">
                <button id="btnReject" class="btn btn-danger btnApproveReject">Reject</button>
            </div>
            <div class="col-sm-2 col-sm-offset-8">
                <button id="btnApprove" class="btn btn-info btnApproveReject pull-right">Approve</button>
            </div>
        </div>
    </div>
<!--    <script id="rowTemplate" type="text/x-kendo-tmpl">
    <tr>
    <td>
    <input type='checkbox' id='#:REQUEST_ID#' role-id='#:ROLE#'  class='k-checkbox row-checkbox'><label class='k-checkbox-label' for='#:REQUEST_ID#'></label>    
    </td>
    <td>
    #: (FULL_NAME == null) ? ' ' : FULL_NAME #
    </td>
    <td>
    #: (TITLE == null) ? '-' : TITLE #
    </td>
    <td>
    #: (REQUESTED_DATE == null) ? '-' : REQUESTED_DATE #
    </td>
    <td>
    #: (START_DATE == null) ? '-' : START_DATE #
    </td>
    <td>
    #: (END_DATE == null) ? '-' : END_DATE #
    </td>
    <td>
    #: (DURATION == null) ? '-' : DURATION #
    </td>
    <td>
    #: (TRAINING_TYPE == null) ? '-' : TRAINING_TYPE #
    </td>
    <td>
    #: (YOUR_ROLE == null) ? '-' : YOUR_ROLE #
    </td>
    <td>
    <a class="btn-edit"
    href=" `+ document.viewLink +` /#:REQUEST_ID #/#:ROLE #" style="height:17px;" title="view">
    <i class="fa fa-search-plus"></i></a>
    </a>
    </td>
    </tr>
</script>-->
</div>