<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/attendance-request/checkOut.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('class', 'attendanceByHr-form');

$attendanceDt = $form->get('attendanceDt');
$outTime = $form->get('outTime');
$outRemarks = $form->get('outRemarks');
$outRemarks->setAttributes(['required' => 'true']);
$totalHour = $form->get('totalHour');
$totalHour->setAttributes(['readonly' => "readonly"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('attendancerequest', ['action' => 'checkOut']));


$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attendancerequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Attendance Request
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;"
                       data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group">
                    <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
                </div>

                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group <?= empty($attendanceDt->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($attendanceDt); ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($attendanceDt); ?>
                                </div>
                                <?php print $this->formElementErrors()->render($attendanceDt, ['class' => 'help-block error']); ?>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDate" id="nepaliDate"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group <?= empty($outTime->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($outTime) ?>
                                    <span class="required" aria-required="true">*</span>
                                    <div class="input-group dropdown-select">
                                        <?php print $this->formElement($outTime) ?>
                                    </div>
                                </div>
                                <?php print $this->formElementErrors()->render($outTime, ['class' => 'help-block error']); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($outRemarks->getMessages()) ? "" : "error" ?>">
                            <?php print $this->formLabel($outRemarks); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($outRemarks); ?>
                        </div>
                        <?php print $this->formElementErrors()->render($outRemarks, ['class' => 'help-block error']); ?>
                        <label><input type="checkbox" value="Y" name='nextDay'>Next Day</label>
                    </div>
                </div>

                <div class="">
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>
