<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/SelfService/attendance-request/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.ids=<?php echo json_encode(["attendanceRequestStatusId"=>-1,"fromDate"=>"","nepaliFromDate"=>"","toDate"=>"","nepaliToDate"=>""]) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\attendancerequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="attendanceRequestListController">
    <div id="hris-page-content">
        
        <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('attendancerequest', ['action' => 'add']) ?>" id="sample_editable_1_new" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;">
                                <i class="fa fa-pencil" id="export"></i> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
    <div class="row margin-top-20">
        <div class="col-sm-3">
            <?php print $this->formLabel($attendanceStatus); ?>
            <?php print $this->formElement($attendanceStatus); ?>
        </div>              
        <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="fromDate">From Date</label>
                        <input type="text" id="fromDate" name="fromDate" ng-model="fromDate" class="form-control"/>
                    </div>

                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="nepaliFromDate">&nbsp;</label>
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate"  class="form-control"/>
                    </div>

                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="toDate">To Date</label>
                        <input type="text"  id="toDate" name="toDate" ng-model="toDate" class="form-control"/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="nepaliToDate">&nbsp;</label>
                        <input type="text"  id="nepaliToDate" name="nepaliToDate" class="form-control"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <label height="45"></label>
            <button id="reset" class="btn default btn-sm pull-right">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
            <button ng-click="view()" id="viewAttendanceRequestStatus" class="btn btn-default btn-sm pull-right">
                Search
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
    </div>

    <div class="margin-top-20">
        
        
        <div id="attendanceRequestTable">
        </div>

        <script id="rowTemplate" type="text/x-kendo-tmpl">
            <tr>
            <td>
            #: (REQUESTED_DT == null) ? '-' : REQUESTED_DT #
            </td>
            <td>
            #: (ATTENDANCE_DT == null) ? '-' : ATTENDANCE_DT #
            </td>
            <td>
            #: (IN_TIME == null) ? '-' : IN_TIME #
            </td>
            <td>
            #: (OUT_TIME == null) ? '-' : OUT_TIME #
            </td>
            <td>
            #: (A_STATUS == null) ? '-' : A_STATUS #
            </td>
            <td>
            <a class="btn-edit"
            href="<?= $this->url("attendancerequest", ["action" => "view"]) ?>/#: ID #" style="height:17px;" title="view detail">
            <i class="fa fa-search-plus"></i></a>
            </a>
            #if(ALLOW_TO_EDIT == 1){#       
            <a class="confirmation btn-delete"
            href="<?= $this->url("attendancerequest", ["action" => "delete"]) ?>/#: ID #" id="bs_#:ID #" style="height:17px;">
            <i class="fa fa-trash-o"></i></a>
            </a>
            #}#
            </td>
            </tr>
        </script>

    </div>
</div>
</div>