<?php
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/add.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/leaveRequestController.js'));
?>


<?php

$form->setAttribute('role', 'form');

$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$noOfDays = $form->get('noOfDays');
$halfDay = $form->get('halfDay');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'Apply Leave');
$submit->setAttribute('id', 'request');

$form->setAttribute('action', $this->url('leaverequest', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
print $this->form()->openTag($form);
?>
    <script>
        document.menu =<?php $menu =["id" => "menuSelfService", "subMenu" => ["id" => "subMenuLeaveApply"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("webService", ["action" => "index"]) ?>';
    </script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaverequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div ng-app="hris" ng-controller="leaveRequestController">
    <div class="row margin-top-20" >
        <div class="col-sm-8 col-sm-offset-2">
            <div class="portlet box custom-box">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>Apply For Leave
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-group">
                        <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
                    </div>

                    <div class="form-group">
                        <label for="leaveId">Leave Type</label>
                        <select name="leaveId" required="required" ng-model="leaveId" ng-change="change()" id="leaveId" class="form-control">
                            <option value="" disabled="" selected="" class="ng-binding">Please select</option>
                            <?php foreach($leave as $key => $value){ ?>
                                <option value="<?php echo $key?>"><?php echo $value?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div
                        class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($startDate) ?>
                        <?php print $this->formElement($startDate) ?>
                    </div>
                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>

                    <div
                        class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($endDate) ?>
                        <?php print $this->formElement($endDate) ?>
                        <span id="errorMsgDate" style="font-size:11px; color:red;"></span>
                    </div>
                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>

                    <div class="form-group disabled">
                        <label for="leaveId">Available Days</label>
                        <input type="text" READONLY name="availableDays" ng-model="availableDays" required="required" id="availableDays"  class="form-control"  value="">
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                    </div>
                    <div
                        class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                        <?php print $this->formLabel($noOfDays); ?>
                        <?php print $this->formElement($noOfDays); ?>
                        <span id="errorMsg" style="font-size:11px; color:red;"></span>
                    </div>
                    <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>

                    <div class="form-group padding-0" id="halfDay">
                        <?php print $this->formLabel($halfDay); ?>
                        <div class="md-radio-inline">
                            <?php $customRenderer($halfDay); ?>
                        </div>
                    </div>
                    <?php print $this->formElementErrors()->render($halfDay, ['class' => 'help-block error']); ?>
                    <div class="form-group padding-0" id="remarks">
                        <?php print $this->formLabel($remarks); ?>
                        <?php print $this->formElement($remarks); ?>
                    </div>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                    <?php print $this->formSubmit($submit); ?>

                </div>
            </div>
        </div>
    </div>
</div>
<?php

print $this->form()->closeTag();

?>