<?php
/**
 * Load Javascript files here
 */
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/SelfService/leave-request/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<script>
    document.menu =<?php
$menu = ["id" => "menuSelfService", "subMenu" => ["id" => "subMenuLeaveApply"]];
echo json_encode($menu);
?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaverequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div ng-app="hris" ng-controller="leaveRequestListController" class="formbg">
    <div class="row margin-top-20">
        <div class="col-sm-2">
            <?php print $this->formLabel($leaves); ?>
            <?php print $this->formElement($leaves); ?>
        </div>
        <div class="col-sm-2">
            <?php print $this->formLabel($leaveStatus); ?>
            <?php print $this->formElement($leaveStatus); ?>
        </div>  
        <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="fromDate">From Date</label>
                        <input type="text" id="fromDate" name="fromDate" ng-model="fromDate" class="form-control"/>
                    </div>

                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="nepaliFromDate">&nbsp;</label>
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate"  class="form-control"/>
                    </div>

                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="toDate">To Date</label>
                        <input type="text"  id="toDate" name="toDate" ng-model="toDate" class="form-control"/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="nepaliToDate">&nbsp;</label>
                        <input type="text"  id="nepaliToDate" name="nepaliToDate" class="form-control"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <label height="45"></label>
            <button ng-click="view()" id="viewLeaveRequestStatus" class="btn btn-default form-control i-search form-control">
                Search
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
    <div class="margin-top-20">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a href="<?= $this->url('leaverequest', ['action' => 'add']) ?>" id="sample_editable_1_new"
                           class="btn green">Apply For Leave
                            <!--                        <i class="fa fa-plus"></i>-->
                        </a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="btn-group pull-right">
                        <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;" id="export"> Export to Excel </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div id="leaveRequestTable">
        </div>
    </div> 
    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (LEAVE_CODE == null) ? '-' : LEAVE_CODE #
        </td>
        <td>
        #: (LEAVE_ENAME == null) ? '-' : LEAVE_ENAME #
        </td>
        <td>
        #: (REQUESTED_DT == null) ? '-' : REQUESTED_DT #
        </td>
        <td>
        #: (FROM_DATE == null) ? '-' : FROM_DATE #
        </td>
        <td>
        #: (TO_DATE == null) ? '-' : TO_DATE #
        </td>
        <td>
        #: (NO_OF_DAYS == null) ? '-' : NO_OF_DAYS #
        </td>
        <td>
        #: (STATUS == null) ? '-' : STATUS #
        </td>
        <td>        
        <a class="btn-edit"
        href="<?= $this->url("leaverequest", ["action" => "view"]) ?>/#: ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i></a>
        </a>
        #if(ALLOW_TO_EDIT == 1){#       
        <a class="confirmation btn-delete"
        href="<?= $this->url("leaverequest", ["action" => "delete"]) ?>/#: ID #" id="bs_#:ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        #}#
        </td>
        </tr>
    </script>

</div>