<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
/**
 * Load Javascript files here
 */
$this->headScript()->appendFile($this->basePath('js/LeaveManagement/LeaveRequest/add.js'));
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leaverequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<?php
$form->setAttribute('role', 'form');

$leaveId = $form->get('leaveId');
$leaveId->setValueOptions($leave);
$leaveId->setAttributes(['disabled' => "disabled"]);
$startDate = $form->get('startDate');
$startDate->setAttributes(['disabled' => "disabled"]);
$endDate = $form->get('endDate');
$endDate->setAttributes(['disabled' => "disabled"]);
$noOfDays = $form->get('noOfDays');
$noOfDays->setAttributes(['disabled' => "disabled"]);
$halfDay = $form->get('halfDay');
$halfDay->setAttributes(['disabled' => "disabled"]);

$gracePeriod = $form->get('gracePeriod');
$gracePeriod->setAttributes(['disabled' => "disabled"]);
$gracePeriod->setValue($gp);

$remarks = $form->get('remarks');
$remarks->setAttributes(['disabled' => 'disabled']);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['disabled' => 'disabled']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['disabled' => 'disabled']);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');

$form->setAttribute('action', $this->url('leaveapprove', ['action' => 'view', 'id' => $id]));


$form->prepare();
print $this->form()->openTag($form);
?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Leave Request Detail
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="border-bottom">
                    <div class="form-group">
                        <div class="row div-font-11">
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Employee Name
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $employeeName; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Recommender
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $recommender; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Status
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php
                                            if ($status == 'RQ') {
                                                echo "Pending";
                                            } else if ($status == 'RC') {
                                                echo "Recommended";
                                            } else if ($status == 'AP') {
                                                echo "Approved";
                                            } else if ($status == "R") {
                                                echo "Rejected";
                                            } else if ($status == "C") {
                                                echo "Cancelled";
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Requested Date
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $requestedDt; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Approver
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $approver; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Leave Type
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $halfdayDetail; ?> 
                                        </td>
                                    </tr>
                                </table> 
                            </div>
                            <div class="col-sm-4">
                                <table>
                                    <tr height="30">
                                        <td>
                                            Total Assigned Days
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $totalDays; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Available Days
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $availableDays; ?>
                                        </td>
                                    </tr>
                                    <tr height="30">
                                        <td>
                                            Actual Deduction Days
                                        </td>
                                        <td width="15">:</td>
                                        <td>
                                            <?php echo $actualDays; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>


                    <div class=" row">
                        <div class="col-sm-4">
                            <div
                                class="form-group required <?= empty($leaveId->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($leaveId); ?>
                                    <?php print $this->formElement($leaveId); ?>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group required  <?= empty($startDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($startDate) ?>
                                        <?php print $this->formElement($startDate) ?>
                                    </div>
                                    <?php print $this->formElementErrors()->render($startDate, ['class' => 'help-block error']) ?>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliStartDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>  
                        </div>

                        <div class="col-sm-4">  
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group required <?= empty($endDate->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($endDate) ?>
                                        <?php print $this->formElement($endDate) ?>
                                    </div>
                                    <?php print $this->formElementErrors()->render($endDate, ['class' => 'help-block error']) ?>
                                </div>     
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nepaliEndDate">&nbsp;</label>
                                        <div class="input-group">
                                            <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                                   class="form-control" value="" disabled="disabled">
                                        </div>
                                    </div>
                                </div>     
                            </div>    
                        </div>
                    </div>


                    <div class=" row">
                        <div class="col-sm-4">
                            <div
                                class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                    <?php print $this->formLabel($noOfDays); ?>
                                    <?php print $this->formElement($noOfDays); ?>
                                <span id="errorMsg" style="font-size:11px; color:red;"></span>
                            </div>
                            <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                        </div>

                        <?php
                        if ($gracePeriod->getValue() != ""):
                            ?>
                            <div class="col-sm-4">
                                <div
                                    class="form-group">
                                        <?php print $this->formLabel($gracePeriod); ?>
                                        <?php print $this->formElement($gracePeriod); ?>
                                </div>
                            </div>
                        <?php endif;
                        ?>

                        <div class="col-sm-4">
                            <?php if ($remarksDtl != null) { ?>
                                <div
                                    class="form-group required <?= empty($remarks->getMessages()) ? "" : "error" ?>">
                                        <?php print $this->formLabel($remarks); ?>
                                        <?php print $this->formElement($remarks); ?>
                                </div>
                            <?php }
                            ?>
                        </div>

                    </div>

                    <?php if(!empty($files)){ ?>
                        <div class="row">
                            <div class="col-sm-6"> 
                                <label>Attachments</label>
                                    <div style="overflow: scroll; height:100px;" >
                                        <ul> 
                                            <?php foreach($files as $file){ ?>
                                                <a target="_blank" href="<?='../../../uploads/leave_documents/'.$file['FILE_IN_DIR_NAME']?>">
                                                    <li><?=$file['FILE_NAME']?></li></a>
                                            <?php } ?>
                                        </ul>
                                    </div> 
                                </div>
                        </div>
                        <?php } ?>

                    <?php
                    if ($subEmployeeId != null) {
                        $disabled = ($subApprovedFlag != null) ? "disabled" : "";
                        if ($subApprovedFlag == 'Y') {
                            $note = "[Approved]";
                        } else if ($subApprovedFlag == 'N') {
                            $note = "[Rejected]";
                        } else {
                            $note = "[Pending]";
                        }
                        ?>
                        <div class="form-group padding-0">
                            <label for="noOfDays">
                                Substitute Employee 
                            </label> 
                            <div>
                                <select disabled="disabled" class="form-control" name="leaveSubstitute">
                                    <?php
                                    foreach ($employeeList as $key => $value) {
                                        $selected = ($key == $subEmployeeId) ? "selected" : "";
                                        ?>
                                        <option style="cursor: pointer;" value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>  

                        <div
                            class="form-group margin-top-10 required">
                            <label>Reason for action [From Sub. Employee] <?php echo $note; ?></label>
                            <textarea disabled="disabled" <?php echo $disabled; ?> name="subRemarks" id="form-subRemarks" required="required" class="form-subRemarks form-control" style="height: 50px; font-size:12px"><?php echo $subRemarks; ?></textarea>
                        </div>
                    <?php } ?>

                </div> 
                <?php if ($subApprovedFlag != 'N') { ?>
                    <div
                        class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                        <label>Reason for action [From Recommender]</label>
                        <?php print $this->formElement($recommendedRemarks); ?>
                    </div>
                    <div
                        class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                        <label>Reason for action [From Approver]</label>
                        <?php print $this->formElement($approvedRemarks); ?>
                    </div>
                <?php } else if ($subApprovedFlag == 'N') { ?>
                    <div class="form-group" style="font-size:11px;">[note:You have to re-send leave detail!!!!]</div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>