<?php
$this->headLink()
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()->appendFile($this->basePath('assets/pages/scripts/ui-modals.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/bootstrap-master/ui-bootstrap-tpls-2.2.0.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/boostrap-form-wizard/js/jquery.bootstrap.wizard.min.js'));
$this->headScript()->appendFile($this->basePath('js/setup/employee/form_wizard.js'));
$this->headScript()->appendFile($this->basePath('js/setup/employee/add.js'));
$this->headScript()->appendFile($this->basePath('js/setup/employee/employeeEditController.js'));
$this->headScript()->appendFile($this->basePath('dropzone/dropzone.min.js'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
?>

<?php
$formOne->setAttribute('role', 'form');
$formOne->setAttribute('id', 'form1');

/**
 * Personal Information
 */
$companyId = $formOne->get('companyId');
$employeeCode = $formOne->get("employeeCode");
$firstName = $formOne->get("firstName");
$middleName = $formOne->get("middleName");
$lastName = $formOne->get("lastName");
$nameNepali = $formOne->get("nameNepali");
$birthDate = $formOne->get('birthDate');
$genderId = $formOne->get('genderId');
$bloodGroupId = $formOne->get('bloodGroupId');
$religionId = $formOne->get('religionId');
$socialActivity = $formOne->get('socialActivity');
$telephoneNo = $formOne->get('telephoneNo');
$mobileNo = $formOne->get('mobileNo');
$extensionNo = $formOne->get('extensionNo');
$emailOfficial = $formOne->get('emailOfficial');
$emailPersonal = $formOne->get('emailPersonal');
$socialNetwork = $formOne->get('socialNetwork');
$countryId = $formOne->get('countryId');

/**
 * Emergency Contact Information
 */
$emergContactName = $formOne->get('emergContactName');
$emergContactNo = $formOne->get('emergContactNo');
$emergContactAddress = $formOne->get('emergContactAddress');
$emergContactRelationship = $formOne->get('emergContactRelationship');


/*
 * Address Information
 */
$addrPermHouseNo = $formOne->get('addrPermHouseNo');
$addrPermWardNo = $formOne->get('addrPermWardNo');
$addrPermStreetAddress = $formOne->get('addrPermStreetAddress');
$addrPermVdcMunicipalityId = $formOne->get('addrPermVdcMunicipalityId');
$addrPermDistrictId = $formOne->get('addrPermDistrictId');
$addrPermZoneId = $formOne->get('addrPermZoneId');
$addrTempHouseNo = $formOne->get('addrTempHouseNo');
$addrTempWardNo = $formOne->get('addrTempWardNo');
$addrTempStreetAddress = $formOne->get('addrTempStreetAddress');
$addrTempVdcMunicipalityId = $formOne->get('addrTempVdcMunicipalityId');
$addrTempDistrictId = $formOne->get('addrTempDistrictId');
$addrTempZoneId = $formOne->get('addrTempZoneId');

$genderId->setOptions(["value_options" => $genders]);
$bloodGroupId->setOptions(["value_options" => $bloodGroups]);
$religionId->setOptions(["value_options" => $religions]);
$addrPermZoneId->setOptions(["value_options" => $zones]);
$addrTempZoneId->setOptions(["value_options" => $zones]);
$companyId->setOptions(["value_options" => $companies]);
$countryId->setValueOptions($countries);

//Custom validation
if (key($mobileNo->getMessages()) == "regexNotMatch") {
    $mobileNo->setMessages(["regexNotMatch" => "Invalid Mobile Number"]);
}
if (key($emailOfficial->getMessages()) == "regexNotMatch") {
    $emailOfficial->setMessages(["regexNotMatch" => "Invalid Email Address"]);
}
if (key($emailPersonal->getMessages()) == "regexNotMatch") {
    $emailPersonal->setMessages(["regexNotMatch" => "Invalid Email Address"]);
}
if (key($telephoneNo->getMessages()) == "regexNotMatch") {
    $telephoneNo->setMessages(["regexNotMatch" => "Invalid Telephone Number"]);
}



$formTwo->setAttribute('id', 'form2');

$famFatherName = $formTwo->get('famFatherName');
$famFatherOccupation = $formTwo->get('famFatherOccupation');
$famMotherName = $formTwo->get('famMotherName');
$famMotherOccupation = $formTwo->get('famMotherOccupation');
$famGrandFatherName = $formTwo->get('famGrandFatherName');
$famGrandMotherName = $formTwo->get('famGrandMotherName');
$maritualStatus = $formTwo->get('maritualStatus');
$famSpouseName = $formTwo->get('famSpouseName');
$famSpouseOccupation = $formTwo->get('famSpouseOccupation');
$famSpouseBirthDate = $formTwo->get('famSpouseBirthDate');
$famSpouseWeddingAnniversary = $formTwo->get('famSpouseWeddingAnniversary');

$maritualStatus->setOptions(["value_options" => ["M" => "Married", "U" => "Unmarried"]]);


$formThree->setAttribute('id', 'form3');

$idCardNo = $formThree->get('idCardNo');
$idLbrf = $formThree->get('idLbrf');
$idBarCode = $formThree->get('idBarCode');
$idProvidentFundNo = $formThree->get('idProvidentFundNo');
$idDrivingLicenseNo = $formThree->get('idDrivingLicenseNo');
$idDrivingLicenseType = $formThree->get('idDrivingLicenseType');
$idDrivingLicenseExpiry = $formThree->get('idDrivingLicenseExpiry');
$idThumbId = $formThree->get('idThumbId');
$idPanNo = $formThree->get('idPanNo');
$idAccountId = $formThree->get('idAccountId');
$idRetirementNo = $formThree->get('idRetirementNo');
$idCitizenshipNo = $formThree->get('idCitizenshipNo');
$idCitizenshipIssueDate = $formThree->get('idCitizenshipIssueDate');
$idCitizenshipIssuePlace = $formThree->get('idCitizenshipIssuePlace');
$idPassportNo = $formThree->get('idPassportNo');
$idPassportExpiry = $formThree->get('idPassportExpiry');


$formFour->setAttribute('id', 'form4');
$joinDate = $formFour->get('joinDate');
$salary = $formFour->get('salary');
$salaryPf = $formFour->get('salaryPf');


$serviceTypeId = $formFour->get('serviceTypeId');
$serviceTypeId->setValueOptions($serviceTypes);

$positionId = $formFour->get('positionId');
$positionId->setValueOptions($positions);

$designationId = $formFour->get('designationId');
$designationId->setValueOptions($designations);

$departmentId = $formFour->get('departmentId');
$departmentId->setValueOptions($departments);


$branchId = $formFour->get('branchId');
$branchId->setValueOptions($branches);


$employeeType = $formFour->get('employeeType');
$employeeTypeValue = [
    'R' => 'Regular',
    'C' => 'Contract'
];
$employeeType->setValueOptions($employeeTypeValue);
$isHR = $formFour->get('isHR');



$formSix->setAttribute('id', 'form6');
$academicDegreeId = $formSix->get('academicDegreeId');
$academicDegreeId->setValueOptions($academicDegree);
$academicUniversityId = $formSix->get('academicUniversityId');
$academicUniversityId->setValueOptions($academicUniversity);
$academicProgramId = $formSix->get('academicProgramId');
$academicProgramId->setValueOptions($academicProgram);
$academicCourseId = $formSix->get('academicCourseId');
$academicCourseId->setValueOptions($academicCourse);
$rankType = $formSix->get('rankType');
$rankType->setValueOptions($rankTypes);
$rankValue = $formSix->get('rankValue');
$passedYr = $formSix->get('passedYr');



$formSeven->setAttribute('id', 'form7');

$expOrgName = $formSeven->get('organizationName');
$orgType = [
    'Financial' => 'Financial',
    'Non-Financial' => 'Non-Financial'
];
$expOrgType = $formSeven->get('organizationType');
$expOrgType->setValueOptions($orgType);
$expPosition = $formSeven->get('position');
$expFromDate = $formSeven->get('fromDate');
$expToDate = $formSeven->get('toDate');




$formEight->setAttribute('id', 'form8');

$traName = $formEight->get('trainingName');
$traDescription = $formEight->get('description');
$traFromDate = $formEight->get('fromDate');
$traToDate = $formEight->get('toDate');


$empId = isset($id) ? $id : -1;


if ($countryId->getValue() == 168) {
    $name = $idCitizenshipIssuePlace->getAttributes()['name'];
    $label = $idCitizenshipIssuePlace->getLabel();
    $value = $idCitizenshipIssuePlace->getValue();

    $idCitizenshipIssuePlace = clone($addrPermDistrictId);
    $idCitizenshipIssuePlace->setAttributes(['name' => $name]);
    $idCitizenshipIssuePlace->setLabel($label);
    $idCitizenshipIssuePlace->setValue($value);
} else if ($countryId->getValue() != null) {
    $idCitizenshipIssuePlace->setAttributes(['value' => $countries[$countryId->getValue()]]);
    $idCitizenshipIssuePlace->setAttributes(["disabled" => 'true']);
} else {
    $idCitizenshipIssuePlace->setAttributes(["disabled" => 'true']);
}
?>

<?php
if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.urlDistrict = '<?= $this->url("subordinate", ["action" => "district"]) ?>';
    document.urlSubmitExperience = '<?= $this->url('subordinate', ['action' => 'edit', 'id' => $id, 'tab' => 8]) ?>';
    document.urlSubmitTraining = '<?= $this->url('subordinate', ['action' => 'edit', 'id' => $id, 'tab' => 9]) ?>';
    document.urlMunicipality = '<?= $this->url("subordinate", ["action" => "municipality"]) ?>';
    document.urlEmployeeList = '<?= $this->url("employee", ["action" => "index"]) ?>';
    document.currentTab = '<?= $tab ?>';
    document.urlQualificationDtl = '<?= $this->url('restful', ["action" => 'index']); ?>';
    document.fileTypes = <?= json_encode($filetypes); ?>;
    document.profilePictureId =<?= ($profilePictureId == null) ? -1 : $profilePictureId ?>;
    document.employeeId =<?= $id ?>;
    document.address =<?php echo json_encode($address); ?>;
    document.urlSetupComplete = '<?php echo $this->url('subordinate', ['action' => 'edit', 'id' => $id, 'tab' => 10]); ?>';
    document.pullAcademicDetailLink = '<?php echo $this->url('subordinate', ['action' => 'pullAcademicDetail']); ?>';
    document.pullExperienceDetailLink = '<?php echo $this->url('subordinate', ['action' => 'pullExperienceDetail']); ?>';
    document.pullTrainingDetailLink = '<?php echo $this->url('subordinate', ['action' => 'pullTrainingDetail']); ?>';
    document.submitQualificationDtlLink = '<?php echo $this->url('subordinate', ['action' => 'submitQualificationDtl']); ?>';
    document.submitExperienceDtlLink = '<?php echo $this->url('subordinate', ['action' => 'submitExperienceDtl']); ?>';
    document.submitTrainingDtlLink = '<?php echo $this->url('subordinate', ['action' => 'submitTrainingDtl']); ?>';
    document.deleteQualificationDtlLink = '<?php echo $this->url('subordinate', ['action' => 'deleteQualificationDtl']); ?>';
    document.deleteExperienceDtlLink = '<?php echo $this->url('subordinate', ['action' => 'deleteExperienceDtl']); ?>';
    document.deleteTrainingDtlLink = '<?php echo $this->url('subordinate', ['action' => 'deleteTrainingDtl']); ?>';
    document.pullEmployeeFileLink = '<?php echo $this->url('subordinate', ['action' => 'pullEmployeeFile']); ?>';
    document.pushEmployeeProfileLink = '<?php echo $this->url('subordinate', ['action' => 'pushEmployeeProfile']); ?>';
    document.pushEmployeeDocumentLink = '<?php echo $this->url('subordinate', ['action' => 'pushEmployeeDocument']); ?>';
    document.pullEmployeeFileByEmpIdLink = '<?php echo $this->url('subordinate', ['action' => 'pullEmployeeFileByEmpId']); ?>';
    document.dropEmployeeFileLink = '<?php echo $this->url('subordinate', ['action' => 'dropEmployeeFile']); ?>';</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Employee')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div id="quaConId" ng-app="hris" ng-controller="qualificationController">
    <div id="rootwizard" class="tabbable-custom">
        <ul class="nav nav-tabs">
            <li class="active">
                <a data-toggle="tab" href="#tab1">
                    <i class="fa fa-book ticon" aria-hidden="true"></i>  General
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab2">
                    <i class="fa fa-users ticon" aria-hidden="true"></i>   Family
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab3">
                    <i class="fa fa-user-circle ticon" aria-hidden="true"></i>Identification
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab4">
                    <i class="fa fa-info-circle ticon"></i> Status & Integration
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab5">
                    <i class="fa fa-graduation-cap ticon" aria-hidden="true"></i> Qualification
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab6">
                    <i class="fa fa-picture-o ticon" aria-hidden="true"></i>Upload Image
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab7">
                    <i class="fa fa-plus-circle ticon" aria-hidden="true"></i>
                    Experience
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab8">
                    <i class="fa fa-plus-circle ticon" aria-hidden="true"></i>
                    Training
                </a>
            </li>
            <li class="">
                <a data-toggle="tab" href="#tab9">
                    <i class="fa fa-plus-circle ticon" aria-hidden="true"></i>
                    Add. Information
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1" style="min-height: 400px;">
                <?php
                $formOne->setAttribute('action', $this->url('subordinate', ['action' => 'edit', 'id' => $empId, 'tab' => 1]));
                $formOne->setAttribute("name", "employeeForm");
                $formOne->prepare();
                print $this->form()->openTag($formOne);
                ?>
                <div class="personal-info">
                    <p><i class="fa fa-user ticon" aria-hidden="true"></i>
                        Personal Information</p>
                    <div class="row clearfix e-setup">

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($employeeCode->getMessages()) ? '' : 'hasError' ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign"> 
                                        <?php print $this->formLabel($employeeCode) ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($employeeCode) ?>
                                        <?php print $this->formElementErrors()->render($employeeCode, ['class' => 'error']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($firstName->getMessages()) ? '' : 'hasError' ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign"> 
                                        <?php print $this->formLabel($firstName) ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($firstName) ?>
                                        <?php print $this->formElementErrors()->render($firstName, ['class' => 'error']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($middleName->getMessages()) ? "" : "hasError" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($middleName) ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($middleName) ?>
                                        <?php print $this->formElementErrors()->render($middleName, ['class' => 'error']) ?>
                                    </div>
                                </div>
                            </div> 
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($lastName->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($lastName) ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($lastName) ?>
                                        <?php print $this->formElementErrors()->render($lastName, ['class' => 'error']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($nameNepali->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($nameNepali); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($nameNepali); ?>
                                        <?php print $this->formElementErrors()->render($nameNepali, ['class' => ' error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($genderId->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($genderId); ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($genderId); ?>
                                        <?php print $this->formElementErrors()->render($genderId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($birthDate->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($birthDate) ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <div class="input-group date" id="employeeBirthDate">
                                            <?php print $this->formElement($birthDate) ?>
                                        </div>
                                        <?php print $this->formElementErrors()->render($birthDate, ['class' => 'help-block error']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="nepaliStartDate">Birth Date(Nepali)</label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <div class="input-group date">
                                            <input type="text"   id="nepaliBirthDate" class="form-control " value="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($countryId->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($countryId); ?>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($countryId); ?>
                                        <?php print $this->formElementErrors()->render($countryId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>




                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group ">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($religionId) ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($religionId) ?>
                                    </div>
                                    <?php print $this->formElementErrors()->render($religionId, ['class' => 'help-block error']) ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($companyId->getMessages()) ? '' : 'hasError' ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($companyId); ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($companyId); ?>
                                        <?php print $this->formElementErrors()->render($companyId, ['class' => 'error']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($bloodGroupId->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($bloodGroupId) ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($bloodGroupId) ?>
                                        <?php print $this->formElementErrors()->render($bloodGroupId, ['class' => 'help-block error']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($mobileNo); ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($mobileNo); ?>
                                        <?php print $this->formElementErrors()->render($mobileNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($telephoneNo->getMessages()) ? "" : "hasError" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($telephoneNo); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($telephoneNo); ?>
                                        <?php print $this->formElementErrors()->render($telephoneNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($socialActivity->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6  col-md-6 rightalign">
                                        <?php print $this->formLabel($socialActivity) ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($socialActivity) ?></div>
                                    <?php print $this->formElementErrors()->render($socialActivity, ['class' => 'help-block error']) ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($extensionNo->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($extensionNo); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($extensionNo); ?>
                                        <?php print $this->formElementErrors()->render($extensionNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($emailOfficial->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($emailOfficial); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($emailOfficial); ?>
                                        <?php print $this->formElementErrors()->render($emailOfficial, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div> 

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($emailPersonal->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($emailPersonal); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($emailPersonal); ?>
                                        <?php print $this->formElementErrors()->render($emailPersonal, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($socialNetwork->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($socialNetwork); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($socialNetwork); ?>
                                        <?php print $this->formElementErrors()->render($socialNetwork, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="permanent-info">

                    <p> <i class="fa fa-address-book ticon" aria-hidden="true"></i>Permanent Address</p>

                    <div class="row clearfix e-setup">
                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($addrPermHouseNo->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($addrPermHouseNo); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($addrPermHouseNo); ?>
                                        <?php print $this->formElementErrors()->render($addrPermHouseNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group <?= empty($addrPermWardNo->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($addrPermWardNo); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($addrPermWardNo); ?>
                                        <?php print $this->formElementErrors()->render($addrPermWardNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($addrPermStreetAddress->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($addrPermStreetAddress); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($addrPermStreetAddress); ?>
                                        <?php print $this->formElementErrors()->render($addrPermStreetAddress, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($addrPermZoneId->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($addrPermZoneId); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($addrPermZoneId); ?>
                                        <?php print $this->formElementErrors()->render($addrPermZoneId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">

                                <div class="form-group  <?= empty($addrPermDistrictId->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($addrPermDistrictId); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($addrPermDistrictId); ?></div>
                                    <?php print $this->formElementErrors()->render($addrPermDistrictId, ['class' => 'help-block error']); ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">

                                <div class="form-group  <?= empty($addrPermVdcMunicipalityId->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($addrPermVdcMunicipalityId); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($addrPermVdcMunicipalityId); ?></div>
                                    <?php print $this->formElementErrors()->render($addrPermVdcMunicipalityId, ['class' => 'help-block error']); ?>
                                </div>
                            </div>

                        </div>

                    </div>
                    <div class="Temporary-info">
                        <p><i class="fa fa-address-card ticon" aria-hidden="true"></i>
                            Temporary Address</p>

                        <div class="row clearfix e-setup">
                            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($addrTempHouseNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                            <?php print $this->formLabel($addrTempHouseNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                            <?php print $this->formElement($addrTempHouseNo); ?></div>
                                        <?php print $this->formElementErrors()->render($addrTempHouseNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($addrTempWardNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                            <?php print $this->formLabel($addrTempWardNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                            <?php print $this->formElement($addrTempWardNo); ?></div>
                                        <?php print $this->formElementErrors()->render($addrTempWardNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($addrTempStreetAddress->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                            <?php print $this->formLabel($addrTempStreetAddress); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                            <?php print $this->formElement($addrTempStreetAddress); ?></div>
                                        <?php print $this->formElementErrors()->render($addrTempStreetAddress, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($addrTempZoneId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                            <?php print $this->formLabel($addrTempZoneId); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                            <?php print $this->formElement($addrTempZoneId); ?></div>
                                        <?php print $this->formElementErrors()->render($addrTempZoneId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($addrTempDistrictId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                            <?php print $this->formLabel($addrTempDistrictId); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                            <?php print $this->formElement($addrTempDistrictId); ?></div>
                                        <?php print $this->formElementErrors()->render($addrTempDistrictId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($addrTempVdcMunicipalityId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                            <?php print $this->formLabel($addrTempVdcMunicipalityId); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                            <?php print $this->formElement($addrTempVdcMunicipalityId); ?></div>
                                        <?php print $this->formElementErrors()->render($addrTempVdcMunicipalityId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                                <?php print $this->formElementErrors()->render($addrTempVdcMunicipalityId, ['class' => 'help-block error']); ?>

                            </div>
                        </div>
                    </div>


                </div>

                <div class="Emergency-info">
                    <p><i class="fa fa-map-marker ticon" aria-hidden="true"></i>
                        Emergency Contact Details</p>
                    <div class="row clearfix e-setup">

                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">


                                <div class="form-group  <?= empty($emergContactName->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($emergContactName); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($emergContactName); ?></div>
                                    <?php print $this->formElementErrors()->render($emergContactName, ['class' => 'help-block error']); ?>

                                </div>
                            </div>
                        </div>


                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($emergContactRelationship->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($emergContactRelationship); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($emergContactRelationship); ?></div>
                                    <?php print $this->formElementErrors()->render($emergContactRelationship, ['class' => 'help-block error']); ?>
                                </div>
                            </div>
                        </div>




                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">
                                <div class="form-group  <?= empty($emergContactAddress->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($emergContactAddress); ?></div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($emergContactAddress); ?></div>
                                    <?php print $this->formElementErrors()->render($emergContactAddress, ['class' => 'help-block error']); ?>
                                </div>
                            </div>
                        </div>


                        <div class="col-xs-12 col-sm-6 col-md-3 col-box">
                            <div class="row bottomgap">

                                <div class="form-group  <?= empty($emergContactNo->getMessages()) ? "" : "error" ?>">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <?php print $this->formLabel($emergContactNo); ?>
                                        <span class="required" aria-required="true">*</span>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php print $this->formElement($emergContactNo); ?></div>
                                    <?php print $this->formElementErrors()->render($emergContactNo, ['class' => 'help-block error']); ?>
                                </div>
                            </div>



                        </div>
                    </div>
                    <input type="submit" class="hidden" id="btnform1" value="submit">
                    <?php
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>

            <div class="tab-pane" id="tab2">
                <?php
                $formTwo->setAttribute('action', $this->url('subordinate', ['action' => 'edit', 'id' => $empId, 'tab' => 2]));
                $formTwo->setAttribute("name", "employeeForm");
                $formTwo->prepare();
                print $this->form()->openTag($formTwo);
                ?>

                <div class="col-md-offset-2 col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-8 margin gapspaceing">
                    <div class="family-info">
                        <p><i class="fa fa-users ticon" aria-hidden="true"></i>
                            Family Information</p>
                        <div class="row clearfix e-setup">

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group <?= empty($famFatherName->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famFatherName); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famFatherName); ?></div>
                                        <?php print $this->formElementErrors()->render($famFatherName, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group <?= empty($famFatherOccupation->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famFatherOccupation); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famFatherOccupation); ?></div>
                                        <?php print $this->formElementErrors()->render($famFatherOccupation, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group <?= empty($famGrandFatherName->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famGrandFatherName); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famGrandFatherName); ?></div>
                                        <?php print $this->formElementErrors()->render($famGrandFatherName, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($maritualStatus->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($maritualStatus); ?>
                                            <span class="required" aria-required="true">*</span>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($maritualStatus); ?></div>
                                        <?php print $this->formElementErrors()->render($maritualStatus, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group <?= empty($famSpouseName->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famSpouseName); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famSpouseName); ?></div>
                                        <?php print $this->formElementErrors()->render($famSpouseName, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group <?= empty($famSpouseOccupation->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famSpouseOccupation); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famSpouseOccupation); ?></div>
                                        <?php print $this->formElementErrors()->render($famSpouseOccupation, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>


                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group <?= empty($famMotherName->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famMotherName); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famMotherName); ?></div>
                                        <?php print $this->formElementErrors()->render($famMotherName, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group <?= empty($famMotherOccupation->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famMotherOccupation); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famMotherOccupation); ?></div>
                                        <?php print $this->formElementErrors()->render($famMotherOccupation, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group <?= empty($famGrandMotherName->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famGrandMotherName); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <?php print $this->formElement($famGrandMotherName); ?></div>
                                        <?php print $this->formElementErrors()->render($famGrandMotherName, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group <?= empty($famSpouseBirthDate->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famSpouseBirthDate); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <div class="row">
                                                <div class="col-md-6 nopaddinggap">
                                                    <div class="input-group date">
                                                        <?php print $this->formElement($famSpouseBirthDate); ?>
                                                    </div>  
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text"   id="famSpouseBirthDateNepali" class="form-control " value="">
                                                </div>
                                            </div>
                                        </div>
                                        <?php print $this->formElementErrors()->render($famSpouseBirthDate, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group<?= empty($famSpouseWeddingAnniversary->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-2">
                                            <?php print $this->formLabel($famSpouseWeddingAnniversary); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-2">
                                            <div class="row">
                                                <div class="col-md-6 nopaddinggap">
                                                    <div class="input-group date">
                                                        <?php print $this->formElement($famSpouseWeddingAnniversary); ?>
                                                    </div>  
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text"   id="weddingAnniversaryDateNepali" class="form-control " value="">
                                                </div>
                                            </div>
                                        </div>
                                        <?php print $this->formElementErrors()->render($famSpouseWeddingAnniversary, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                        </div>
                    </div>

                    <input type="submit" class="hidden" id="btnform2" value="submit">
                    <?php
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>
            <div class="tab-pane" id="tab3">
                <?php
                $formThree->setAttribute('action', $this->url('subordinate', ['action' => 'edit', 'id' => $empId, 'tab' => 3]));
                $formThree->setAttribute("name", "employeeForm");
                $formThree->prepare();
                print $this->form()->openTag($formThree);
                ?>
                <div class="col-md-offset-2 col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-8 margin gapspaceing">
                    <div class="identification-infomation">  
                        <p><i class="fa fa-user-circle ticon" aria-hidden="true"></i>
                            Identification Infomation</p>
                        <div class="row clearfix e-setup">
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group <?= empty($idCardNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idCardNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idCardNo); ?></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idLbrf->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idLbrf); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idLbrf); ?></div>
                                        <?php print $this->formElementErrors()->render($idLbrf, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($idBarCode->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idBarCode); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idBarCode); ?></div>
                                        <?php print $this->formElementErrors()->render($idBarCode, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idProvidentFundNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idProvidentFundNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idProvidentFundNo); ?></div>
                                        <?php print $this->formElementErrors()->render($idProvidentFundNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idDrivingLicenseNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idDrivingLicenseNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idDrivingLicenseNo); ?></div>
                                        <?php print $this->formElementErrors()->render($idDrivingLicenseNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group   <?= empty($idDrivingLicenseExpiry->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idDrivingLicenseExpiry); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <div class="row">
                                                <div class="col-md-6 nopaddinggap">
                                                    <div class="input-group date">
                                                        <?php print $this->formElement($idDrivingLicenseExpiry); ?>
                                                    </div>  
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text"   id="drivingLicenseExpiaryNepali" class="form-control " value="">
                                                </div>
                                            </div>
                                        </div>
                                        <?php print $this->formElementErrors()->render($idDrivingLicenseExpiry, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($idDrivingLicenseType->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idDrivingLicenseType); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">  
                                            <?php print $this->formElement($idDrivingLicenseType); ?></div>
                                        <?php print $this->formElementErrors()->render($idDrivingLicenseType, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($idPassportNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idPassportNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3"> 
                                            <?php print $this->formElement($idPassportNo); ?></div>
                                        <?php print $this->formElementErrors()->render($idPassportNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>


                            </div>


                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idThumbId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idThumbId); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idThumbId); ?></div>
                                        <?php print $this->formElementErrors()->render($idThumbId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idPanNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idPanNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idPanNo); ?></div>
                                        <?php print $this->formElementErrors()->render($idPanNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idAccountId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idAccountId); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idAccountId); ?></div>
                                        <?php print $this->formElementErrors()->render($idAccountId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idRetirementNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idRetirementNo); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idRetirementNo); ?></div>
                                        <?php print $this->formElementErrors()->render($idRetirementNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idCitizenshipNo->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idCitizenshipNo); ?>
                                            <span class="required" aria-required="true">*</span>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idCitizenshipNo); ?></div>
                                        <?php print $this->formElementErrors()->render($idCitizenshipNo, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group   <?= empty($idCitizenshipIssueDate->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idCitizenshipIssueDate); ?>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <div class="row">
                                                <div class="col-md-6 nopaddinggap">
                                                    <div class="input-group date">
                                                        <?php print $this->formElement($idCitizenshipIssueDate); ?>
                                                    </div>  
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text"   id="citizenshipIssueDateNepali" class="form-control " value="">
                                                </div>
                                            </div>
                                        </div>
                                        <?php print $this->formElementErrors()->render($idCitizenshipIssueDate, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>




                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($idCitizenshipIssuePlace->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idCitizenshipIssuePlace); ?></div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <?php print $this->formElement($idCitizenshipIssuePlace); ?></div>
                                        <?php print $this->formElementErrors()->render($idCitizenshipIssuePlace, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group   <?= empty($idPassportExpiry->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-3">
                                            <?php print $this->formLabel($idPassportExpiry); ?>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-3">
                                            <div class="row">
                                                <div class="col-md-6 nopaddinggap">
                                                    <div class="input-group date">
                                                        <?php print $this->formElement($idPassportExpiry); ?>
                                                    </div>  
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text"   id="passportExpiryNepali" class="form-control " value="">
                                                </div>
                                            </div>
                                        </div>
                                        <?php print $this->formElementErrors()->render($idPassportExpiry, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <input type="submit" class="hidden" id="btnform3" value="submit">
                    <?php
                    print $this->form()->closeTag();
                    ?>
                </div>
            </div>
            <div class="tab-pane" id="tab4">
                <?php
                $formFour->setAttribute('action', $this->url('subordinate', ['action' => 'edit', 'id' => $empId, 'tab' => 4]));
                $formFour->setAttribute("name", "employeeForm");
                $formFour->prepare();
                print $this->form()->openTag($formFour);
                ?>
                <div class="col-md-offset-2 col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-8 margin gapspaceing">
                    <div class="status-info"> 
                        <p><i class="fa fa-info-circle ticon ticon"></i>Status Infomation</p>
                        <div class="row clearfix e-setup">



                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($joinDate); ?>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-4">
                                            <div class="row">
                                                <div class="col-md-6 nopaddinggap">
                                                    <div class="input-group date">
                                                        <?php print $this->formElement($joinDate); ?>
                                                    </div>  
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text"   id="nepalijoinDate" class="form-control " value="">
                                                </div>
                                            </div>
                                        </div>
                                        <?php print $this->formElementErrors()->render($joinDate, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group<?= empty($employeeType->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($employeeType); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($employeeType); ?></div>
                                        <?php print $this->formElementErrors()->render($employeeType, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group  <?= empty($salary->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($salary); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($salary); ?></div>
                                        <?php print $this->formElementErrors()->render($salary, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group  <?= empty($salaryPf->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($salaryPf); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($salaryPf); ?></div>
                                        <?php print $this->formElementErrors()->render($salaryPf, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group   <?= empty($serviceTypeId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($serviceTypeId); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($serviceTypeId); ?></div>
                                        <?php print $this->formElementErrors()->render($serviceTypeId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group<?= empty($branchId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($branchId); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($branchId); ?></div>
                                        <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group   <?= empty($departmentId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($departmentId); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($departmentId); ?></div>
                                        <?php print $this->formElementErrors()->render($departmentId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group   <?= empty($designationId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">

                                            <?php print $this->formLabel($designationId); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($designationId); ?></div>
                                        <?php print $this->formElementErrors()->render($designationId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">

                                    <div class="form-group   <?= empty($positionId->getMessages()) ? "" : "error" ?>">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <?php print $this->formLabel($positionId); ?></div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <?php print $this->formElement($positionId); ?></div>
                                        <?php print $this->formElementErrors()->render($positionId, ['class' => 'help-block error']); ?>
                                    </div>
                                </div>
                            </div>



                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <label> Recommender</label>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <select required="required" name="recommender">
                                                <?php
                                                foreach ($recommenders as $recommenderKey => $recommenderValue) {
                                                    $recommenderSelected = ($recommenderId == $recommenderKey) ? "selected" : "";
                                                    ?>
                                                    <option  value="<?php echo $recommenderKey; ?>" <?php echo $recommenderSelected; ?>><?php echo $recommenderValue; ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <label> Approver</label>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <select required="required" name="approver">
                                                <?php
                                                foreach ($approvers as $approverKey => $approverValue) {
                                                    $approverSelected = ($approverId == $approverKey) ? "selected" : "";
                                                    ?>
                                                    <option  value="<?php echo $approverKey; ?>" <?php echo $approverSelected; ?>><?php echo $approverValue; ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4">
                                            <label> Shift </label>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 cgap-4">
                                            <select required="required" name="shift">
                                                <?php
                                                foreach ($shifts as $shiftKey => $shiftValue) {
                                                    $shiftSelected = ($shiftId == $shiftKey) ? "selected" : "";
                                                    ?>
                                                    <option  value="<?php echo $shiftKey; ?>" <?php echo $shiftSelected; ?>><?php echo $shiftValue; ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="row bottomgap">
                                    <div class="form-group">
                                        <div class="col-xs-6 col-sm-6 col-md-6 rightalign-4" style="margin-top:2%;">
                                            <?= $this->formLabel($isHR) ?>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 cgap-4">
                                            <div class="md-radio-inline">
                                                <?php $customRender($isHR); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>



                        <input type="submit" class="hidden" id="btnform4" value="submit">
                        <?php
                        print $this->form()->closeTag();
                        ?>

                    </div>
                </div></div>


            <div class="tab-pane" id="tab5" style="min-height: 400px;">
                <div class="row esetup">
                    <input type="hidden" name="employeeId" id="employeeId" value="<?php echo $id; ?>">
                    <div class="col-sm-12">
                        <table class="table table-striped table-bordered table-hover no-footer customtbl" id="qualificationTbl">
                            <tr>
                                <td><?php print $this->formLabel($academicDegreeId); ?></td>
                                <td><?php print $this->formLabel($academicUniversityId); ?></td>
                                <td><?php print $this->formLabel($academicProgramId); ?></td>
                                <td><?php print $this->formLabel($academicCourseId); ?></td>
                                <td class="rankwidth"><?php print $this->formLabel($rankType); ?></td>
                                <td><?php print $this->formLabel($rankValue); ?></td>
                                <td class="passedyr"><?php print $this->formLabel($passedYr); ?></td>
                                <td width="1%">
                                </td>
                            </tr>
                            <tr ng-repeat="qualificationForm in qualificationFormList">
                                <td>
                                    <input type="hidden" ng-model="qualificationForm.id"/>
                                    <select select2 class="form-control academicSelect"
                                            ng-options="degree.name for degree in degreeList track by degree.id"
                                            ng-model="qualificationForm.academicDegreeId">
                                    </select>
                                </td>
                                <td>
                                    <select select2 class="form-control academicSelect"
                                            ng-options="university.name for university in universityList track by university.id"
                                            ng-model="qualificationForm.academicUniversityId">
                                    </select>
                                </td>
                                <td>
                                    <select select2 class="form-control academicSelect"
                                            ng-options="program.name for program in programList track by program.id"
                                            ng-model="qualificationForm.academicProgramId">
                                    </select>
                                </td>
                                <td>
                                    <select select2 class="form-control academicSelect"
                                            ng-options="course.name for course in courseList track by course.id"
                                            ng-model="qualificationForm.academicCourseId">
                                    </select>
                                </td>
                                <td>
                                    <select select2 class="form-control academicSelect"
                                            ng-options="rankTypes.name for rankTypes in rankType track by rankTypes.id"
                                            ng-model="qualificationForm.rankType">
                                    </select>
                                </td>


                                <td>
                                    <input ng-model="qualificationForm.rankValue" required="required"
                                           class="rankValue-weight form-control" size="1" type="text" value="">
                                </td>
                                <td>
                                    <input type="text" class="form-passedYr form-control" value=""
                                           ng-model="qualificationForm.passedYr" size="2">
                                </td>
                                <td width="1%" style="padding:15px;" class="checkboxgap">
                                    <div class="md-checkbox">
                                        <input type="checkbox" id="{{qualificationForm.checkbox}}" class="md-check"
                                               ng-model="qualificationForm.checked">
                                        <label for="{{qualificationForm.checkbox}}">
                                            <span class="inc"></span>
                                            <span class="check"></span>
                                            <span class="box"></span>
                                        </label>
                                    </div>

                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <a href="javascript:;" class="btn btn-icon-only default pull-right"
                                       ng-click="view()">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript:;" class="btn btn-icon-only default" ng-click="delete()">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--<button id="qualificationSubmitBtn" ng-click="addQualification()">Submit</button>-->
                </div>
            </div>

            <div class="tab-pane" id="tab6" style="min-height: 400px;">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <form ng-show="(file.fileCode == null || file.editMode)" action="<?= $this->url("restful", ["action" => "index"]) ?>"
                                      class="dropzone"
                                      id="my-awesome-dropzone">
                                </form>
                                <span ng-show="noImageSelected" class="errorMsg">Please Select an Image!</span>
                                <div ng-hide="(file.fileCode == null || file.editMode)" class="cbp-caption-defaultWrap">
                                    <image style="width:100%;height:144px;"   src="{{viewImage(file.filePath)}}"/>
                                </div>

                            </div>
                        </div>
                        <div class="row margin-top-10">
                            <div class="col-sm-3 col-sm-offset-3">
                                <select class="form-control" ng-model="file.fileTypeCode" ng-options="key as value for (key,value) in fileTypes">
                                </select>
                            </div>
                            <div class="col-sm-3">
                                <button class="btn btn-block btn-animated  post-btn" ng-show="(file.fileCode == null || file.editMode)" ng-click="post()">
                                    Post
                                </button>
                                <button class="btn btn-block btn-link" ng-hide="(file.fileCode == null || file.editMode)" ng-click="edit()">
                                    Edit
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Document Name
                                                </th>
                                                <th>
                                                    File Type
                                                </th>
                                                <th>
                                                    Action
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr ng-repeat="(key,empDoc) in employeeDocuments">
                                                <td>
                                                    <label ng-bind="empDoc.FILE_NAME">
                                                    </label>
                                                </td>
                                                <td>
                                                    <label ng-bind="empDoc.FILETYPE_CODE">
                                                    </label>

                                                </td>
                                                <td>
                                                    <button class="btn btn-danger" ng-click="drop(empDoc.FILE_CODE, key)">
                                                        Delete
                                                    </button>
                                                </td>
                                            </tr>
                                            <tr >
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    <button class="btn btn-link" ng-click="addDocument()">
                                                        Add
                                                    </button>
                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="tab-pane aditional" id="tab7">
                <div class="row esetup">
                    <div class="col-md-12">
                        <form name="employeeExperienceForm" ng-submit="submitExperience()" id="form7" novalidate>
                            <input type="hidden" name="employeeId" id="employeeId" value="<?php echo $id; ?>">
                            <table class="table table-striped table-bordered table-hover no-footer customtbl" id="qualificationTbl">
                                <tr>
                                    <td><?php print $this->formLabel($expOrgType); ?></td>
                                    <td><?php print $this->formLabel($expOrgName); ?></td>
                                    <td><?php print $this->formLabel($expPosition); ?></td>
                                    <td><?php print $this->formLabel($expFromDate); ?></td>
                                    <td><?php print $this->formLabel($expToDate); ?></td>

                                    <td width="1%"></td>
                                </tr>
                                <tr ng-repeat="experience in experienceFormList">
                                    <td>
                                        <select select2 name="organizationType" ng-model="experience.organizationTypeId" ng-options="organizationTypeList.name for organizationTypeList in organizationType track by organizationTypeList.id" required="required" id="organizationType" class="form-control">
                                        </select>
                                    </td>
                                    <td>
                                        <input type="text" ng-model="experience.organizationName" name="organizationName_{{experience.checkbox}}" required="required" id="organizationName" class="form-control" value="">
                                        <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.organizationName_{{experience.checkbox}}.$touched">
                                            <ul ng-show="employeeExperienceForm.organizationName_{{experience.checkbox}}.$error.required" class="help-block error">
                                                <li>Organization Name is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" ng-model="experience.position" name="position_{{experience.checkbox}}" required="required" id="position" class="form-control" value="">
                                        <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.position_{{experience.checkbox}}.$touched">
                                            <ul ng-show="employeeExperienceForm.position_{{experience.checkbox}}.$error.required" class="help-block error">
                                                <li>Position is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input dvalue="{{experience.fromDate}}" datepicker type="text" ng-model="experience.fromDate" name="fromDate_{{experience.checkbox}}" required="required" class="form-control" id="expfromDate_{{experience.checkbox}}" value="">
                                        <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.fromDate_{{experience.checkbox}}.$touched">
                                            <ul ng-show="employeeExperienceForm.fromDate_{{experience.checkbox}}.$error.required" class="help-block error">
                                                <li>From Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input dvalue="{{experience.toDate}}" datepicker type="text" ng-model="experience.toDate" name="toDate_{{experience.checkbox}}" required="required" class="form-control" id="exptoDate_{{experience.checkbox}}" value="">
                                        <div ng-show="employeeExperienceForm.$submitted || employeeExperienceForm.toDate_{{experience.checkbox}}.$touched">
                                            <ul ng-show="employeeExperienceForm.toDate_{{experience.checkbox}}.$error.required" class="help-block error">
                                                <li>To Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td width="1%" style="padding:15px;" class="checkboxgap">
                                        <div class="md-checkbox">
                                            <input type="checkbox" id="{{experience.checkbox}}" class="md-check"
                                                   ng-model="experience.checked">
                                            <label for="{{experience.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                            </label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <a href="javascript:;" class="btn btn-icon-only default pull-right"
                                           ng-click="addExperience()">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="deleteExperience()">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <input type="submit" class="hidden" id="btnform7" value="submit">
                        </form>
                    </div>
                </div>      
            </div>
            <div class="tab-pane aditional" id="tab8">
                <div class="row clearfix">
                    <div class="col-md-12">
                        <form name="employeeTrainingForm" ng-submit="submitTraining()" id="form8" novalidate>
                            <input type="hidden" name="employeeId" id="employeeId" value="<?php echo $id; ?>">
                            <table class="table table-striped table-bordered table-hover no-footer customtbl" id="qualificationTbl">
                                <tr>
                                    <td><?php print $this->formLabel($traName); ?></td>
                                    <td><?php print $this->formLabel($traDescription); ?></td>
                                    <td><?php print $this->formLabel($traFromDate); ?></td>
                                    <td><?php print $this->formLabel($traToDate); ?></td>

                                    <td width="1%"></td>
                                </tr>
                                <tr ng-repeat="training in trainingFormList">
                                    <td>
                                        <input type="text" ng-model="training.trainingName" name="trainingName_{{training.checkbox}}" required="required" id="trainingName" class="form-control" value="">
                                        <div ng-show="employeeTrainingForm.$submitted || employeeTrainingForm.trainingName_{{training.checkbox}}.$touched">
                                            <ul ng-show="employeeTrainingForm.trainingName_{{training.checkbox}}.$error.required" class="help-block error">
                                                <li>Training Name is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" ng-model="training.description" name="description_{{training.checkbox}}" required="required" id="description" class="form-control" value="">
                                        <div ng-show="employeeTrainingForm.$submitted || employeeTrainingForm.description_{{training.checkbox}}.$touched">
                                            <ul ng-show="employeeTrainingForm.description_{{training.checkbox}}.$error.required" class="help-block error">
                                                <li>Description is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input dvalue="{{training.fromDate}}" datepicker type="text" ng-model="training.fromDate" name="fromDate_{{training.checkbox}}" required="required" class="form-control" id="expfromDate_{{training.checkbox}}" value="">
                                        <div ng-show="employeeTrainingForm.$submitted || employeeTrainingForm.fromDate_{{training.checkbox}}.$touched">
                                            <ul ng-show="employeeTrainingForm.fromDate_{{training.checkbox}}.$error.required" class="help-block error">
                                                <li>From Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <input dvalue="{{training.toDate}}" datepicker type="text" ng-model="training.toDate" name="toDate_{{training.checkbox}}" required="required" class="form-control" id="exptoDate_{{training.checkbox}}" value="">
                                        <div ng-show="employeeTrainingForm.$submitted || employeeTrainingForm.toDate_{{training.checkbox}}.$touched">
                                            <ul ng-show="employeeTrainingForm.toDate_{{training.checkbox}}.$error.required" class="help-block error">
                                                <li>To Date is required.</li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td width="1%" style="padding:15px;" class="checkboxgap">
                                        <div class="md-checkbox">
                                            <input type="checkbox" id="{{training.checkbox}}" class="md-check"
                                                   ng-model="training.checked">
                                            <label for="{{training.checkbox}}">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                            </label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <a href="javascript:;" class="btn btn-icon-only default pull-right"
                                           ng-click="addTraining()">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="javascript:;" class="btn btn-icon-only default" ng-click="deleteTraining()">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <input type="submit" class="hidden"  id="btnform8" value="submit">
                        </form>
                    </div>
                </div>
            </div>
            <div class="tab-pane aditional" id="tab9">
                <div class="col-md-offset-2 col-xs-offset-0 col-xs-12 col-sm-offset-0 col-sm-12 col-md-8 margin gapspaceing">
                    <div class="identification-infomation">  
                        <p><i class="fa fa-plus-circle ticon" aria-hidden="true"></i>
                            Additional Infomation</p>
                        <div class="row clearfix e-setup">
                            <div class="col-md-12">
                                <div id="rolePanel">
                                    <ul id="roleList">
                                        <li>
                                            Leave Assign
                                            <a href="<?php echo $this->url("leaveassign", ["action" => "assign", "eid" => $id]) ?>">
                                                <i class="fa fa-arrow-circle-right pull-right" aria-hidden="true" style="font-size:20px; line-height:20px!important;"></i>
                                            </a>
                                        </li>
                                        <li>
                                            Training Assign
                                            <a href="<?php echo $this->url("trainingAssign", ["action" => "assign", "employeeId" => $id]) ?>">
                                                <i class="fa fa-arrow-circle-right pull-right" aria-hidden="true" style="font-size:20px; line-height:20px!important;"></i>
                                            </a>
                                        </li>
                                        <li>
                                            Appraisal Assign
                                            <a href="<?php echo $this->url("appraisalAssign", ["action" => "index", "id" => $id]) ?>">
                                                <i class="fa fa-arrow-circle-right pull-right" aria-hidden="true" style="font-size:20px; line-height:20px!important;"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="padding-20">
                <ul class="pager wizard">
                    <li class="next">
                        <button
                            class="btn btn-default pull-right">
                            <span>Save & Continue</span>
                            <i class="fa fa-arrow-right iconcolor" aria-hidden="true"></i>
                        </button>
                    </li>
                    <li class="next finish hidden">
                        <button id="finishBtn"
                                class="btn btn-default pull-right"
                                type="button">

                            <span>Finish</span>
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                        </button>
                    </li>
                    <li class="previous first hidden">
                        <button class="btn btn-default btn-cons btn-animated from-left fa fa-cog pull-right"
                                type="button">

                            <span>First</span>
                        </button>
                    </li>
                    <li class="previous">
                        <button class="btn btn-default pull-left" type="button">
                            <i class="fa fa-arrow-left iconcolor" aria-hidden="true"></i>
                            <span>Previous</span>
                        </button>
                    </li>
                </ul>
            </div>

        </div>

    </div>

    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header">
        <h3 class="modal-title" id="modal-title">Document Upload</h3>
        </div>
        <div class="modal-body" id="modal-body">
        <div class="row">
        <div class="col-sm-12">
        <div id="dropZoneContainer" class="dropzone">
        </div>
        <div class="error" ng-show="!valid">Please upload Image.</div>

        </div>
        </div>
        <div class="row margin-top-10">
        <div class="col-sm-4">
        <select class="form-control " ng-options="key as value for (key,value) in fileTypes" ng-model="fileTypeCode">
        <!--<option ng-repeat="(key,fileType) in fileTypes" value="{{key}}">{{fileType}}</option>-->
        </select>
        </div>

        </div>


        </div>
        </div>
        <div class="modal-footer">
        <button class="btn btn-primary" type="button" ng-click="ok()">OK</button>
        <button class="btn btn-warning" type="button" ng-click="cancel()">Cancel</button>
        </div>
    </script>
</div>




