<?php
$this->headScript()->appendFile($this->basePath('js/setup/academic-course/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'academicCourse-form');

$academicCourseName = $form->get('academicCourseName');

$remarks = $form->get('remarks');
$academicProgramName = $form->get('academicProgramId');
///print_r($programs); die();
$academicProgramName->setValueOptions($programs);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('academicCourse', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\academicCourse')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($academicCourseName); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($academicCourseName); ?>
                            <?php print $this->formElementErrors()->render($academicCourseName, ['class' => 'help-block']); ?>
                            <span class="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($academicProgramName); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($academicProgramName); ?>
                            <?php print $this->formElementErrors()->render($academicProgramName, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>



                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>