<?php
$this->headScript()->appendFile($this->basePath('js/setup/academic-course/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'academicCourse-form');

$academicCourseCode = $form->get('academicCourseCode');
$academicCourseName = $form->get('academicCourseName');

$remarks = $form->get('remarks');
$academicProgramName = $form->get('academicProgramId');
$academicProgramName->setValueOptions($programs);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('academicCourse', ['action' => 'edit','id'=>$id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}
$form->prepare();
?>
<script>
    document.menu =<?php $menu = ["id" => "menuSetup", "subMenu" => ["id" => "subMenuAcademicCourse"]];echo json_encode($menu);?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\academicCourse')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php print $this->formLabel($academicCourseCode); ?>
                    <?php print $this->formElement($academicCourseCode); ?>
                    <?php print $this->formElementErrors()->render($academicCourseCode, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($academicCourseName); ?>
                    <?php print $this->formElement($academicCourseName); ?>
                    <?php print $this->formElementErrors()->render($academicCourseName, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($academicProgramName); ?>
                    <?php print $this->formElement($academicProgramName); ?>
                    <?php print $this->formElementErrors()->render($academicProgramName, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>