<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/setup/academic-course/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.academicCourses = <?php echo json_encode($academicCourses); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\academicCourse')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>


<div class="margin-top-20">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="<?= $this->url('academicCourse', ['action' => 'add']) ?>" id="sample_editable_1_new"
                       class="btn green"> Add New
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export"> Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="academicCourseTable">
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (ACADEMIC_COURSE_CODE == null) ? '-' : ACADEMIC_COURSE_CODE #
        </td>
        <td>
        #: (ACADEMIC_COURSE_NAME == null) ? '-' : ACADEMIC_COURSE_NAME #
        </td>
        <td>
        #: (ACADEMIC_PROGRAM_NAME == null) ? '-' : ACADEMIC_PROGRAM_NAME #
        </td>
        <td>
        <a class="btn-edit"
        href="<?= $this->url("academicCourse", ["action" => "edit"]) ?>/#:ACADEMIC_COURSE_ID #" style="height:17px;">
        <i class="fa fa-edit"></i>
        </a> 
        <a class="btn-delete confirmation"
        href="<?= $this->url("academicCourse", ["action" => "delete"]); ?>/#:ACADEMIC_COURSE_ID #" id="bs_#:ACADEMIC_COURSE_ID #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        </td>
        </tr>
    </script>
</div>