<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/Notification/news/add.js'));


$form->setAttribute('role', 'form');
$form->setAttribute('id', 'newsForm');
$form->setAttribute('action', $this->url('news', ['action' => 'edit', 'id' => $id]));



$newsDate = $form->get('newsDate');

$newsType = $form->get('newsType');
$newsType->setValueOptions($newsTypeValue);

$newsTitle = $form->get('newsTitle');

$newsEdesc = $form->get('newsEdesc');

$newsLdesc = $form->get('newsLdesc');

$remarks = $form->get('remarks');

$companyId = $form->get('companyId');
$companyId->setValueOptions($company);

$branchId = $form->get('branchId');

$designationId = $form->get('designationId');

$departmentId = $form->get('departmentId');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->prepare();
?>

<script>
    document.branches =<?php echo json_encode($branch); ?>;
    document.designation =<?php echo json_encode($designation); ?>;
    document.department =<?php echo json_encode($department); ?>;

    document.selectedBranchId = '<?php echo $branchId->getValue(); ?>';
    document.selectedDepartmentId = '<?php echo $departmentId->getValue(); ?>';
    document.selectedDesignationId = '<?php echo $designationId->getValue(); ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\news')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Edit
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($newsDate); ?>
                                    <span class="required" aria-required="true">*</span>
                                    <?php print $this->formElement($newsDate); ?>
                                    <?php print $this->formElementErrors()->render($newsDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDate" id="nepaliDate"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>     
                        </div>  
                    </div>


                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($newsType); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($newsType); ?>
                            <?php print $this->formElementErrors()->render($newsType, ['class' => 'help-block']); ?>
                        </div>
                    </div>


                    <div class="col-sm-4">

                        <div class="form-group">
                            <?php print $this->formLabel($newsTitle); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($newsTitle); ?>
                            <?php print $this->formElementErrors()->render($newsTitle, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($newsEdesc); ?>
                    <span class="required" aria-required="true">*</span>
                    <?php print $this->formElement($newsEdesc); ?>
                    <?php print $this->formElementErrors()->render($newsEdesc, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($newsLdesc); ?>
                    <?php print $this->formElement($newsLdesc); ?>
                    <?php print $this->formElementErrors()->render($newsLdesc, ['class' => 'help-block']); ?>
                </div>


                <div class=" row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <?php print $this->formLabel($companyId); ?>
                            <?php print $this->formElement($companyId); ?>
                            <?php print $this->formElementErrors()->render($companyId, ['class' => 'help-block']); ?>
                        </div>
                    </div>


                    <div class="col-sm-3">
                        <div class="form-group">
                            <?php print $this->formLabel($branchId); ?>
                            <?php print $this->formElement($branchId); ?>
                            <?php print $this->formElementErrors()->render($branchId, ['class' => 'help-block']); ?>
                        </div>
                    </div>


                    <div class="col-sm-3">

                        <div class="form-group">
                            <?php print $this->formLabel($departmentId); ?>
                            <?php print $this->formElement($departmentId); ?>
                            <?php print $this->formElementErrors()->render($departmentId, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-3">

                        <div class="form-group">
                            <?php print $this->formLabel($designationId); ?>
                            <?php print $this->formElement($designationId); ?>
                            <?php print $this->formElementErrors()->render($designationId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>









                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>