<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/lobilist-master/lib/jquery/jquery-ui.min.css'))
//        ->appendStylesheet($this->basePath('assets/global/plugins/lobilist-master/lib/bootstrap/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/lobilist-master/dist/lobilist.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/lobilist-master/lib/jquery/jquery-ui.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/lobilist-master/lib/jquery/jquery.ui.touch-punch-improved.js'))
//        ->appendFile($this->basePath('assets/global/plugins/lobilist-master/lib/bootstrap/js/bootstrap.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/lobilist-master/dist/lobilist.min.js'))
        ->appendFile($this->basePath('js/Notification/news/test.js'));


?>

<?php
//echo'<pre>';
//print_r($list);
?>

<script>
    document.taskList = <?php echo json_encode($list); ?>
</script>

<div id="lobilist"></div>


