<?php
$this->headScript()->appendFile($this->basePath('js/training/training-assign/index.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'trainingAssign-form');

$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);
$trainingId = $form->get('trainingId');
$trainingId->setValueOptions($training);
$startDate = $form->get('startDate');
$endDate = $form->get('endDate');
$duration = $form->get('duration');
$cost = $form->get('cost');
$location = $form->get('location');
$instructorName = $form->get('instructorName');
$trainingInstitute = $form->get('trainingInstitute');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value','SUBMIT');

$form->setAttribute('action', $this->url('loanAdvance', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
    <script>
        document.menu=<?php $menu = ["id" => "menuTraining","subMenu"=>["id"=>"subMenuAssign"]];echo json_encode($menu);?>;
        document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    </script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingAssign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <?php print $this->formLabel($employeeId); ?>
                    <?php print $this->formElement($employeeId); ?>
                    <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($trainingId); ?>
                    <?php print $this->formElement($trainingId); ?>
                    <?php print $this->formElementErrors()->render($trainingId, ['class' => 'help-block']); ?>
                </div>
               
                <div class="form-group">
                    <?php print $this->formLabel($duration); ?>
                    <?php print $this->formElement($duration); ?>
                    <?php print $this->formElementErrors()->render($duration, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($location); ?>
                    <?php print $this->formElement($location); ?>
                    <?php print $this->formElementErrors()->render($location, ['class' => 'help-block']); ?>
                </div>
                <div class="form-group">
                    <?php print $this->formLabel($cost); ?>
                    <?php print $this->formElement($cost); ?>
                    <?php print $this->formElementErrors()->render($cost, ['class' => 'help-block']); ?>
                </div>
                
                <div class="form-group">
                    <?php print $this->formLabel($instructorName); ?>
                    <?php print $this->formElement($instructorName); ?>
                    <?php print $this->formElementErrors()->render($instructorName, ['class' => 'help-block']); ?>
                </div>
                
                <div class="form-group">
                    <?php print $this->formLabel($trainingInstitute); ?>
                    <?php print $this->formElement($trainingInstitute); ?>
                    <?php print $this->formElementErrors()->render($trainingInstitute, ['class' => 'help-block']); ?>
                </div>

                <div class="form-group" >
                    <?php print $this->formLabel($remarks); ?>
                    <?php print $this->formElement($remarks); ?>
                    <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                </div>
                <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
