<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/spin.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/ladda.min.js'));
$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/training/training-assign/index.js'));
?>

<script>
    document.menu =<?php $menu = ["id" => "menuTraining", "subMenu" => ["id" => "subMenuTrainingAssign"]];echo json_encode($menu);?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingAssign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="" ng-app="hris" ng-controller="trainingAssignController">
    <div class="row margin-top-20">
        <div class="col-sm-4">
            <?php print $this->formElement($trainings); ?>
        </div>
    </div>      
    <div class="margin-top-20  formbg mgap">
    <div class="row">
        <div class="col-sm-4 marginspace">
            <?php print $this->formLabel($employees); ?>
                 <?php print $this->formElement($employees); ?>
        </div>
        <div class="col-sm-4 marginspace">
            <?php print $this->formLabel($branches); ?>
                 <?php print $this->formElement($branches); ?>
        </div>
        <div class="col-sm-4 marginspace">
            <?php print $this->formLabel($departments); ?>
             <?php print $this->formElement($departments); ?>

        </div>
        <div class="col-sm-4 marginspace">
            <?php print $this->formLabel($designations); ?>
            <?php print $this->formElement($designations); ?>
        </div>
        <div class="col-sm-4 marginspace">
            <?php print $this->formLabel($positions); ?>
               <?php print $this->formElement($positions); ?>
        </div>
        <div class="col-sm-4 marginspace">
            <?php print $this->formLabel($serviceTypes); ?>
               <?php print $this->formElement($serviceTypes); ?>
        </div>                     
        <div class="col-sm-2">
            <button ng-click="view()" id="viewEmployees" class=" btn btn-default  i-search form-control" style="margin-top:21px !important">
                Search
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
    </div> 
    <div class="margin-top-30 scrollbar-vertical">
        <table class="table table-striped table-bordered table-hover no-footer custometbletwo">
            <thead>
            <tr>
                <th>
                    Employee Code
                </th>
                <th>
                    Employee Name
                </th>               
                <th>
                    Training Assigned
                </th>
                <th>
                    Start Date
                </th>
                <th>
                    End Date
                </th>
                <th>
                    Institute Name
                </th>
                <th>
                    Location Detail
                </th>
                <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                    <div class="th-inner ">
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                        <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                            <span></span>
                        </label>
                    </div>
                    <div class="fht-cell" style="width: 46px;"></div>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="employeeTraining in employeeList">
                <td ng-bind="employeeTraining.EMPLOYEE_CODE">
                </td>
                <td>
                    <span ng-bind="employeeTraining.FIRST_NAME"></span>
                    <span ng-bind="employeeTraining.MIDDLE_NAME"></span>
                    <span ng-bind="employeeTraining.LAST_NAME"></span>
                </td>
                <td ng-bind="employeeTraining.TRAINING_NAME">
                </td>
                <td ng-bind="employeeTraining.START_DATE">
                </td>
                <td ng-bind="employeeTraining.END_DATE">
                </td>
                <td ng-bind="employeeTraining.INSTITUTE_NAME">
                </td>
                <td ng-bind="employeeTraining.LOCATION">
                </td>
                <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                    <div class="th-inner ">
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                        <input class="" ng-model="employeeTraining.checked" type="checkbox"
                               ng-change="checkUnit(item.checked)"/>
                            <span></span>
                        </label>
                    </div>
                    <div class="fht-cell" style="width: 46px;"></div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="row" ng-show="assignShowHide">
        <div class="col-sm-6">
<!--            <button class="pull-left btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="cancelBtn" ng-click="cancel()">
                Cancel
                <i class="fa fa-trash"></i>
            </button>-->
        </div>
        <div class="col-sm-6">
            <button class="pull-right btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="assignBtn" ng-click="assign()">
                Assign
                <i class="fa fa-edit"></i>
            </button>           
        </div>
    </div>
</div>