<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headScript()->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('js/search.js'));
$this->headScript()->appendFile($this->basePath('js/training/training-assign/assign.js'));

?>

<script>
    document.assignEmployeeTrainingLink = '<?= $this->url("trainingAssign", ["action" => "assignEmployeeTraining"]) ?>';
    document.pullEmployeeForTrainingAssignLink = '<?= $this->url("trainingAssign", ["action" => "pullEmployeeForTrainingAssign"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\trainingAssign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="" ng-app="hris" ng-controller="trainingAssignController">
    <div id="hris-page-content">
        <div class="row margin-top-20">
            <div class="col-sm-4">
<?php print $this->formElement($trainings); ?>
            </div>
        </div>
        <div class="portlet light bg-inverse margin-top-10">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-paper-plane font-green-haze"></i>
                    <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                </div>
                <div class="tools">
                    <a href="" class="collapse" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-2">
                <label>Company</label>
                <select multiple class="form-control" name="company" id="companyId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Branch</label>
                <select multiple class="form-control" name="branchId" id="branchId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Department</label>
                <select multiple class="form-control" name="department" id="departmentId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Designation</label>
                <select multiple class="form-control" name="designation" id="designationId">
                </select>
            </div>
            <div class="col-sm-2">
                <label>Position</label>
                <select multiple class="form-control" name="position" id="positionId">
                </select>
            </div>
                </div>
                <div class="row margin-top-10">
                    <div class="col-sm-2">
                        <label>Service Type</label>
                        <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee Type</label>
                        <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <label>Employee</label>
                        <select multiple class="form-control" name="employee" id="employeeId">
                        </select>
                    </div>
                    <div class="col-sm-2 col-lg-offset-4">
                        <label height="45"></label>
                        <button  ng-click="view()" id="viewEmployees" class="btn btn-default btn-sm pull-right">
                            Search
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="margin-top-30 scrollbar-vertical" id="loadingTable">
            <table class="table table-striped table-bordered table-hover no-footer custometbletwo">
                <thead>
                    <tr>
                        <th>
                            Employee Code
                        </th>
                        <th>
                            Employee Name
                        </th>               
                        <th>
                            Training Assigned
                        </th>
                        <th>
                            Start Date
                        </th>
                        <th>
                            End Date
                        </th>
                        <th>
                            Institute Name
                        </th>
                        <th>
                            Location Detail
                        </th>
                        <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="employeeTraining in employeeList">
                        <td ng-bind="employeeTraining.EMPLOYEE_CODE">
                        </td>
                        <td>
                            <span ng-bind="employeeTraining.FIRST_NAME"></span>
                            <span ng-bind="employeeTraining.MIDDLE_NAME"></span>
                            <span ng-bind="employeeTraining.LAST_NAME"></span>
                        </td>
                        <td ng-bind="employeeTraining.TRAINING_NAME">
                        </td>
                        <td ng-bind="employeeTraining.START_DATE">
                        </td>
                        <td ng-bind="employeeTraining.END_DATE">
                        </td>
                        <td ng-bind="employeeTraining.INSTITUTE_NAME">
                        </td>
                        <td ng-bind="employeeTraining.LOCATION">
                        </td>
                        <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                            <div class="th-inner ">
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input class="" ng-model="employeeTraining.checked" type="checkbox"
                                           ng-change="checkUnit(item.checked)"/>
                                    <span></span>
                                </label>
                            </div>
                            <div class="fht-cell" style="width: 46px;"></div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="row" ng-show="assignShowHide">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <button class="pull-right btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="assignBtn" ng-click="assign()">
                    Assign
                    <i class="fa fa-edit"></i>
                </button>           
            </div>
        </div>
    </div>
</div>