<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/training/training-assign/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js'));
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\trainingAssign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="" ng-app="hris" ng-controller="trainingAssignController">
     <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <select class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <select class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <?php print $this->formElement($trainings); ?>
                </div> 
                <div class="col-sm-2 col-lg-offset-2">
                    <label height="45"></label>
                    <button  ng-click="viewTrainingAssignList()" id="viewEmployees" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="margin-top-10">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a href="<?= $this->url('trainingAssign', ['action' => 'assign']) ?>" id="sample_editable_1_new"
                           class="btn green"> Assign
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="btn-group pull-right">
                        <button class="btn green btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">      
                            <li>
                                <a href="javascript:;" id="export"> Export to Excel </a>
                            </li>
                        </ul>
                    </div>
                </div>      
            </div>
        </div> 
        <div id="trainingAssignListTable"></div>
    </div>  

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (FIRST_NAME == null) ? ' ' : FIRST_NAME #
        #: (MIDDLE_NAME == null) ? ' ' : MIDDLE_NAME #
        #: (LAST_NAME == null) ? ' ' : LAST_NAME #
        </td>
        <td>
        #: (TRAINING_NAME == null) ? '-' : TRAINING_NAME #
        </td>
        <td>
        #: (START_DATE == null) ? '-' : START_DATE #
        </td>
        <td>    
        #: (END_DATE == null) ? '-' : END_DATE #
        </td>
        <td>    
        #: (DURATION == null) ? '-' : DURATION #
        </td>
        <td>
        #: (INSTITUTE_NAME == null) ? '-' : INSTITUTE_NAME #
        </td>
        <td>
        #: (TRAINING_TYPE == null) ? '-' : TRAINING_TYPE #
        </td> 
        <td>
        <a class="btn-edit"
        href="<?= $this->url("trainingAssign", ["action" => "view"]) ?>/#: EMPLOYEE_ID #/#: TRAINING_ID #" style="height:17px;" title="view detail">
        <i class="fa fa-search-plus"></i></a>
        </a>
        #if(ALLOW_TO_EDIT == 1){#       
        <a class="confirmation btn-delete"
        href="<?= $this->url("trainingAssign", ["action" => "delete"]) ?>/#: EMPLOYEE_ID #/#: TRAINING_ID #" id="bs_#:SN #" style="height:17px;">
        <i class="fa fa-trash-o"></i></a>
        </a>
        #}#

        </td>
        </tr>
    </script>
</div>