<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/setup/travel-category/edit.js'));

?>

<script>
    document.viewTravelCategoryLink = '<?= $this->url("travelCategory", ["action" => "view",'id' => $id]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelCategory')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>View 
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                

                <div class=" row">
                <div class="col-sm-4">
                      <div class="form-group">
                        <label for="associateName">Category Name</label>
                        <input name="positionId"  id="positionId" class="form-control" type="text" value="<?php echo $detail[0]['CATEGORY_NAME']; ?>" disabled>
                      </div>              
                    </div>

                    <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Requested Type </label>
                        <select name="requestedType" class="form-control"  id="requestedType" disabled>
                            <option value=""   disabled>Select the Requested type</option>
                            <option value="ad" <?php if($detail[0]['REQUESTED_TYPE'] == 'ad'){echo 'selected';} ?> selected >Advance</option>
                            <option value="ep" <?php if($detail[0]['REQUESTED_TYPE'] == 'ep'){echo 'selected';} ?>>Expense</option>
                        </select>
                    </div>              
                    </div>
                    <div class="col-sm-4">
                     <div class="form-group">
                        <label for="associateName">Rate</label>
                        <input type="number" id="rate"  name="rate" class="form-control" value="<?php echo $detail[0]['RATE']; ?>" autocomplete="off" disabled>                                
                    </div>
                </div>

                <!-- <input type="submit" name="submit" id="submit" class="btn btn-success" value="Submit" autocomplete="off" style="margin-top:3rem ;">                 -->
                  
                </div>
          </div>
        </div>
    </div>
</div>
